### ISSUE TITLE
Yubikey support?

### ISSUE THREAD

**Issue by bmomjian** [OpenSC/OpenSC#1099]
Is Yubikey supported?  The release notes seem to indicate it is, but it isn't listed on your Hardware Support website:

   https://github.com/OpenSC/OpenSC/wiki/Supported-hardware-%28smart-cards-and-USB-tokens%29

If it is listed somewhere in your repository, a search of "Yubikey" doesn't find it except in release notes and source code.

**Comment by dengert** [comment]
Yubico provides a PIV applet for some of their devices. This is supported as best as possible by the OpenSC PIV driver. 
See: https://www.yubico.com/solutions/smart-card-piv/

**Comment by bmomjian** [comment]
OK, thanks, that helps.

**Comment by Jakuje** [comment]
For the records, the guides from Yubico [1] are using the OpenSC as a PKCS#11 provider. Their PKCS#11 module [2] has a lot of unresolved bugs and does not build with OpenSSL 1.1.0 anymore.

You should be able to use current yubikeys without any problems with current OpenSC. This does not apply for HSMs hardware or U2F, OAUTH and other mechanisms, which do not go through the PKCS#11 interface.

[1] https://developers.yubico.com/PIV/Guides/SSH_with_PIV_and_PKCS11.html
[2] https://github.com/Yubico/yubico-piv-tool

**Comment by mouse07410** [comment]
I'm not sure what the problem seems to be. I'm actively using Yubikey with the current master of OpenSC (and my fork of OpenSC.tokend) on MacOS Sierra without any problem. I use Yubikey PIV, and U2F. S/MIME email, Web browser authentication, use of applications that access smart cards via PKCS#11 - all that seems to work just fine.

With the current nightly build of GPGTools, I can also successfully use Yubikey OpenPGP applet.

I found that both OpenSSL-1.0.2 and OpenSSL-1.1.0 can work with Yubikey fine using the current master of `libp11` (PKCS#11 engine) and `opensc-pkcs11.dylib`.

While I only build `yubikey-piv-tool` with OpenSSL-1.0.2, it does not interfere at all with the ability to use Yubikey token itself with software that is based on OpenSSL-1.1.x.
