### ISSUE TITLE
what to do about launchpad opensc entries?

### ISSUE THREAD

**Issue by tolonuga** [OpenSC/OpenSC#1370]
We have a "team": https://launchpad.net/~opensc-team
We have a project: https://launchpad.net/opensc-project

I fixed the code URL pointing to the no-longer existing SVN server. But what else should be done?
Delete the whole thing? Or do we need to keep it, as ubuntu uses this to import OpenSC as package?

Who else has a launchpad.net / ubuntu One account and should be given owner access?

**Comment by frankmorgner** [comment]
Sorry, I don't think I have the capacity to manage any distribution package. Maybe @martinpaljak can pick this up again. @Jakuje would you be available for managing Ubuntu and/or other Linux-based platforms?

**Comment by Jakuje** [comment]
I have an account on Ubuntu One/launchpad, but I am not quite sure what is the purpose of the team there. To my understanding, OpenSC is available in the latest Ubuntu and Debian and already has assigned maintainers (even though the 0.18.0 is not there yet):

https://packages.ubuntu.com/cosmic/opensc

**Comment by dpward** [comment]
@Jakuje I don't believe there is anyone currently maintaining OpenSC for Ubuntu at all (whether in the distribution, or otherwise through the "Launchpad team"). Please see this instead: https://launchpad.net/ubuntu/+source/opensc

The only reason that 0.17.0 and 0.18.0 builds even appear for Ubuntu is that those are automatic imports directly from Debian, which occur for the development version of Ubuntu prior to the [Debian import freeze](https://wiki.ubuntu.com/DebianImportFreeze) date. Otherwise, no one seems to be touching the packages for Ubuntu at all, since 2015.

Most of the [open bug reports](https://bugs.launchpad.net/ubuntu/+source/opensc/+bugs?field.status%3Alist=NEW&field.status%3Alist=CONFIRMED&field.status%3Alist=TRIAGED&field.status%3Alist=INPROGRESS&field.status%3Alist=FIXCOMMITTED) in Ubuntu are basically requests for someone to backport either an upstream bug fix, or a new upstream release, to a currently supported release of Ubuntu.

**Comment by Jakuje** [comment]
Yes ... I see there some rotten bug reports, but I did not have any problem there (though I use only yubikey there).

I am just occasional user of Ubuntu so I am really not familiar with the way how the packaging, development and patching works at the moment, since it is not mine primary system.

But I believe I can keep an eye on that in some free time, if it would be some help and somebody will be able to point me to some resources how does it work and what needs to be done to do that.

**Comment by tolonuga** [comment]
Actually I have no idea what the purpose of these configuration objects on launchpad.net is these days.
Are those for creating PPAs? For managing the package inside ubuntu? Just as a software listing?

Any suggestion on what to do is very welcome. I didn't want to try deleting things, as I wouldn't be sure of the consequences, and wanted to involve the persons currently active on the project. Any direction you prefer is fine with me.

**Comment by dpward** [comment]
As I understand it, Launchpad is sort of like [Sourceforge](https://sourceforge.net/create/) — it's a service that is available for open-source projects to use to for release downloads, repository hosting, bug tracking, e-mail lists, etc.

* There is an [Ubuntu project](https://launchpad.net/ubuntu) on Launchpad. It contains all of the packages built for Ubuntu distributions (including the [opensc package](https://launchpad.net/ubuntu/+source/opensc)) which are available for download. The bugs in the Ubuntu package can be tracked there.

* As another example, there is an [Inkscape project](https://launchpad.net/inkscape). It is currently just used for bug tracking, but its source code repository used to be hosted there (it was moved to GitLab).

* There is also an [OpenSC project](https://launchpad.net/opensc) on Launchpad — which is actually part of an [OpenSC project group](https://launchpad.net/opensc-project) on Launchpad. Both of these are maintained by the [OpenSC team](https://launchpad.net/~opensc-team) on Launchpad (as opposed to a single user) — this team currently consists of @tolonuga and @martinpaljak. There's ... basically nothing there.

I'm not an OpenSC maintainer, but it seems like everything in the last bullet could just be deleted, unless anyone actually plans to do something with it. This will not affect the Ubuntu opensc package, which lives in the Ubuntu project. For someone to maintain the official opensc package in Ubuntu, they have to apply to become an [Ubuntu per-package uploader](https://wiki.ubuntu.com/UbuntuDevelopers#Per-package_Uploaders).

**Comment by tolonuga** [comment]
Thanks, I filled a support ticket with launchpad.net to get the launchpad project and team disabled / deleted:
https://answers.launchpad.net/launchpad/+question/669918
