### ISSUE TITLE
OpenPGP v3.3: Support multiple certificates

### ISSUE THREAD

**Issue by amaccuish** [OpenSC/OpenSC#1399]
With v3.3 of the OpenPGP spec, there are now 3 slots for certificates on the card, matching the three private keys you can store. It would be great if opensc could be updated to allow these to be read and loaded onto the card.
GnuPG does not have support for this so far as far as I'm aware.

**Comment by amaccuish** [comment]
This is the relevant bit of the spec (https://gnupg.org/ftp/specs/OpenPGP-smart-card-application-3.3.0.pdf):

> **Cardholder certificate (each for AUT, DEC and SIG)**
These DOs are designed to store a certificate (e. g. X.509) for the keys in the card. They can be used to identify the card in a client-server authentication, where specific non-OpenPGP-certificates are needed, for S-MIME and other x.509 related functions. The maximum length of the DOs is announced in Extended Capabilities. The content should be TLV-constructed, but is out of scope of this specification. The DOs are stored in the order AUT (1st occurrence), DEC (2nd occurrence) and 
SIG (3rd occurrence). Storing the AUT certificate at first occurrence is for downward compatibility with older versions of this specification.

**Comment by alex-nitrokey** [comment]
This is more difficult to implement then I thought. 

While I was able to make *storing* multiple certificates possible (see [this quick solution](https://github.com/OpenSC/OpenSC/compare/master...alex-nitrokey:OPC3-mult-cert)), it would need a lot of work to make *using* multiple certs possible withing the openpgp part of OpenSC because until now it is assumed that only one such certificate exists.

Do you have any good example how to implement multiple Cardholder certs within the OpenSC project which may help me to implement this function for OpenPGP Cards as well?

**Comment by dengert** [comment]
Look at `pkcs15-piv.c` and the `sc_debug` line "PIV-II adding certs..."
then the line `r = sc_pkcs15emu_add_x509_cert(p15card, &cert_obj, &cert_info);`

`pkcs15-openpgp.c` only adds `/* Check if certificate DO 7F21 holds data */`  and also uses 
`r = sc_pkcs15emu_add_x509_cert(p15card, &cert_obj, &cert_info);`
It could add other certs. Make sure the `cert_info.id.value`,  `prkey_info.id.value` and `prkey_info.id.value` all use the same `id.value` so PKCS\#11 can match them up.  (pin and data object id.value are unrelated.)

**Comment by daringer** [comment]
hey @dengert, trying to continue Alex' work, so did some initial stuff here: [commit](https://github.com/daringer/OpenSC/commit/fa38097c21e2500118797d8ef99d0e23b03cc043) 

what I did so far:
* inspired by `pkcs15-piv.c` I am using `sc_card_ctl` to switch the certificate slot using `SELECT DATA`, therefore I added a ctl `SC_CARDCTL_OPENPGP_SELECT_DATA` in `src/libopensc/cardctl.h`
* fixed the actual `SELECT DATA` call (complained about wrong apdu args before) inside `pgp_select_data` 
using `sc_format_apdu_ex` 
* added proper `sc_card_ctl` calls for storing (`src/pkcs15init/pkcs15-openpgp.c`) and init (`src/libopensc/pkcs15-openpgp.c`)
* setting the `cert_info->id` accordingly during store (and init)

So far so good, but it looks like I am missing something, as I can add certificates, but once I added a cert for ID 3 it looks like none of the others can be set anymore: `Failed to store certificate: Non unique object ID` ... on the other side erasing and adding id 1 first and the id 3 works, but `list-certificates` still shows me 2 identical certs.

It looks like I don't fully understand all the concepts (sorry!) here.  Could you maybe take a short look at what I've done so far, because it feels like too much trial and error from this point...

I also tried setting `path` during store, but which one to set? I tried `3f017f21` and `3f027f21`... for the other 2 instead of `3f007f21` but this is not working especially during init I get `path not found`. Inside `pkcs15-piv.c` I can see different paths being used, but is this applicable here and which paths can/should I use, did not find any documentation for `3f007f21`.

**Comment by daringer** [comment]
oops, forgot to update this issue - so long story short: there is a working state available, which is cleaned up and working. In fact this means (using `pksc15-tool` and a *openpgp*/*nitrokey-pro* device):
* adding certificates at any id between 1 .. 3 is possible 
* listing the certificates also (seems) to work properly
* example output can be found [here](https://github.com/daringer/OpenSC/commit/fa38097c21e2500118797d8ef99d0e23b03cc043#commitcomment-41530997) including the history

As the next step, I will simply create a branch on top the current master and open a PR so that more people will be confronted with the code. :rocket:

**Comment by frankmorgner** [comment]
does someone here want to do a test of https://github.com/OpenSC/OpenSC/pull/2103 ?

**Comment by alex-nitrokey** [comment]
> does someone here want to do a test of #2103 ?

Okay, this is late, but I did a test now, see PR.
