### ISSUE TITLE
Multiple PIN prompts when using card authentication in Firefox

### ISSUE THREAD

**Issue by thw0rted** [OpenSC/OpenSC#1436]
### Problem Description

I'm getting prompted for a PIN multiple times when using card authentication in Firefox.

### Proposed Resolution

Using the Windows 10 default drivers (for Identiv SCR3310), I'm able to open the same page in Edge or Chrome (via MSCAPI, I assume) with a single PIN prompt.

### Logs

I logged in to the site where I'm seeing the issue with PKCS Spy enabled.  [This is the result](https://gist.github.com/thw0rted/81de0beb3319f7f6f6556bfcf6d68d49).  I also went through the procedure again with debug logging turned on, but a single login action generated more than 600kb of logs (at level=3) and I'm not sure I'm sanitizing it correctly, so please let me know if it's needed and I can share it individually.

**Comment by thw0rted** [comment]
I swear I tried that before, but doing it now brings the prompts from 4 or 5 down to 2 or 3.  I can live with that, but do you know why even the onepin module might ask more than once?

**Comment by enckse** [comment]
I saw this issue and have always wondered if there was a reliable way to get less prompts - I changed over to onepin as well and also get 2-3 prompts (which is what I was getting before).

**Comment by dengert** [comment]
You card is a PIV or PIV like card. There are 4 certificates, one for User Authentication, one for digital Signatures, one foe key management (encryption) and one for the card to authenticate itself. 

The SPY trace shows that FireFox chose to to use the  "Certificate for Digital Signature" which is meant to be used for signing such things as e-mails, but not for web or login authentication. The NIST policy for the  "Certificate for Digital Signature" is to require the PIN for every use, and the card enforces it. 
Look at the trace for `CKA_ALWAYS_AUTHENTICATE  True` This tells the application (FireFox) to request the PIN for each use. And that is what it is doing. 

Why FireFox chose the "Certificate for Digital Signature" rather than the "Certificate for PIV Authentication" is not clear. It depends on the content of the certificates and the website. 

You choices are:
Look at the certificates and what the website is looking for in a certificate so it picks the Authentication certificate. 

You can also look at the opensc.conf file and make sure `use_pin_caching = true;` and 
`pin_cache_ignore_user_consent = true;` But Firefox is still enforcing the it, so this may not help.

The onepin module should give the same results.

**Comment by mouse07410** [comment]
This problem is caused by the (fairly recent) changes to the login handling in OpenSC. Now, regardless of whether the re-auth is or is not necessary, OpenSC asks for the PIN before the operation if the key has `CKA_ALWAYS_AUTHENTICATE` flag set to `TRUE` (as `Digital Signature` keys have). Thus, the OpenSC software took upon itself enforcing the key property that should be the token's responsibility.

As @dengert said, your only three options are:

- Use a different key, e.g., `PIV Authentication` key instead of `Digital Signature`. That should get rid of the extra (unnecessary) prompt.
- Set `use_pin_caching` and `pin_cache_ignore_user_consent` to `true`. This should help with most of the apps. Maybe not with Firefox - but there's always Google Chrome.
- Modify OpenSC source. *If I haven't done it myself on my fork, I probably will.*

**Comment by thw0rted** [comment]
Thanks for all the feedback!  Just to clarify a few things:

* The first option (using PIV Auth instead of DS) would be a change to the requesting site's configuration, right?  I think some users might not have PIV Auth, only DS and KE, so maybe that's why they request DS for authentication.  I can ask, though -- maybe they can request PIV first and fall back on DS?
* I just turned on `pin_cache_ignore_user_consent`, which was not configured previously.  It appears to make more prompts, not fewer.  Is this setting related to the recent changes you mention, that enforce `CKA_ALWAYS_AUTHENTICATE` at the OpenSC level where the requesting application used to be responsible for prompting?
* I'm unlikely to make the changes myself, as I don't think I'll have the free time to do enough of a deep dive in how this all works.  (It's interesting, but not really in my wheelhouse.)  If you do make changes, keep in mind that both coolkey on Linux/Firefox and MSCAPI (Edge, Chrome) with the built-in Windows drivers load this site with only one PIN prompt -- they might be breaking spec, but they do it consistently and the user experience is IMHO better.  Maybe put the compliant-but-inconvenient behavior behind a config flag?

About the recent changes you mention: does that mean that if I go back and install OpenSC 0.17 instead, it might only prompt once?  If there's not some serious vulnerability that 0.18 addresses, I could just do that.

**Comment by dengert** [comment]
Your card has 3 certificates. So not clear why it did not use the Auth certificate.  And since you say some people may have only DS and KE it sounds like you have a dual CAC and PIV card. 
Search for "dual cac and piv transition plans" to see what others are doing. Some of then talk about activating the Auth cert on the CAC card. 

[Nice picture showing Dual PIV and CAC cards](http://www.cac.mil/Portals/53/Documents/ref5-Technical_Bulletin_CAC_2_6_2b_Applet_Structure_June_2009.pdf) Its from 2009, but you can get the idea of what the card may actually have. 

The PIV applet forces the PIN ALWAYS feature, but accessing the same certificate and key using CAC applet may not enforce it. (I don't have CAC cards, only NIST PIV cards.)

You could also try using just the OpenSC CAC driver, or coolkey driver by changing opensc.conf.

**Comment by thw0rted** [comment]
I added

    force_card_driver = cac;

to the config file.  This resulted in the behavior that I wanted -- one PIN prompt, certificate selection, then successful login!  It might be nice to provide the option of behaving as in old versions (leaving enforcement of PIN ALWAYS to the application, I guess?) just from the user-experience perspective, but this addresses my immediate concern.  Thanks again!

**Comment by dengert** [comment]
The PIV driver was written to support the NIST 800-73-3 standards, not the CAC standards.  The PIV standards require (and the card enforces) a PIN verify before using the Signing key.  OpenSC has some capabilities to cache a PIN to avoid having to ask the user for the PIN. This in effect avoids the policy of the card issuer. 

Some sites may even want to go as far as requiring the user to use a PIN PAD reader so the middleware can **not** cache a PIN, in order to enforce the policy. The current OpenSC code can do this. 

Policies for the CAC card may be different, so use the CAC drivers when needed.  (I believe eventialy as the CAC is phased out this will become the  default.)

The PIV driver also supports additional objects and keys that are not supported on the CAC or the dual CAC PIV cards. These include fingerprints, iris scans and picture.

**Comment by mouse07410** [comment]
> It might be nice to provide the option of behaving as in old versions (leaving enforcement of PIN ALWAYS to the application, I guess?)

This should not be necessary. Either the hardware (the token, the card) enforces this policy, or it doesn't. In my opinion, if the card chose not to enforce the "PIN ALWAYS", the application has no business second-guessing it.

**Comment by thw0rted** [comment]
I meant the other way around -- as I understand it, the "new"(ish) behavior in OpenSC is that it enforces PIN ALWAYS at the driver level where it used to let the application decide.  For now, it doesn't matter, but at some point, years from now, people might stop shipping cards with a CAC applet, if I'm right in understanding the "phase out" mentioned above.  If that happens, if I'm stuck with a card that only runs in PIV mode, and I'm stuck using a site that requests a DS cert for identity, I'd like to still have *some* way of avoiding multiple prompts for that specific scenario.  I'm not too worried about it at the moment, though.

**Comment by dengert** [comment]
If "that happens", you will not be the only one stuck. In addition a properly issued PIV card will always have an Auth cert that should be used for WEB sites. The Web sites will be changing too. 
In the meantime you can use your CAC card with the OpenSC CAC driver.

**Comment by thw0rted** [comment]
You can try to get hold of the owners of such sites and let them know what they're doing -- I sent the folks from DI2E to this thread and they have since fixed it.

**Comment by Chas-P** [comment]
I FIXED IT!

Reinstall active client and make sure that you select ALL components.  I did a right click on each major one and said to install all sub components.

I have now gone into webmail several times in IE with entering my pin ONCE!

Hope this helps others

**Comment by thw0rted** [comment]
Wait, you "fixed" the problem by uninstalling OpenSC and installing a vendor-proprietary driver instead?

**Comment by mouse07410** [comment]
Leaving alone the suggested "fix", I noticed that when I have more than one card present (Yubikey fur internal needs, CAC fur the DOD sites), after I remove and re-insert CAC, I'm getting multiple PIN prompts for Yubikey, which ignores the parameters configured in `opensc.conf`.

**Comment by dengert** [comment]
To address @Chas-P comment:
As best I can tell Dual mode CAC/PIV cards use the same certificate and key for Sign but CAC does not enforce CKA_ALWAYS_AUTHENTICATE but PIV does on the card. So the "fix'' maybe "active client" is using CAC interface. So during ant transition period for Dual CAC/PIV  to PIV only, makes it hard to says what is the real policy for using the Sign cert/key. 

Since CAC does not have a PIV Auth certificate and key so  DOD web sites have had to use the Sign cert/key. If a DOD web site start to allow both, the choice of which one is chosen may depend on the order they are presented by the web server or the order read from the card by the web client that makes the choice. This would be hard to test. It is not clear if there is a way to force the use of the Auth cert/key over the Sign cert/key if both are acceptable.    

It could also be "active client" is caching the PIN, which is in violation of the PIV policies but you can do it with OpenSC if you want to violate the PIV policies. 

If you site provides or requires you to use "active client" are you violating some local policy by using OpenSC? The OpenSC PIV driver was written to allow the use of PIV cards on systems where no vendor provided code was supplied, while sticking to the PIV polices.  (OpenSC is not trying to make it easy to subvert your site's or government policies.) 

@mouse07410  Are you saying that the OpenSC CAC driver was being used, but what you remove and re-insert CAC it some how effects the Yubikey? Do you have any debug log to see what may be happening? are the two cards being used by the same process?

**Comment by mouse07410** [comment]
@dengert  I think I'm using the PIV driver for both, and yes those were my observations. As it's through Firefox - how to collect the log?

Re. ActivClient - I suspect it caches the PIN.

**Comment by dengert** [comment]
Ooh, and the Yubikey may lose the login state if a AID is sent the Yubikey which it does not understand.  I real PIV does not lose the login state. This may be what you are seeing when the CAC is reinserted. The process to use the CAC  via PKCS11 may look at all all readers and cards. 

Wireshark may show something about when seting up mutual autheticatin via SSL/TLS.

Mozilla NSS used by FireFox  has some logging capabilities. that may show how a choice of certificates is made.

**Comment by Chas-P** [comment]
I do think ActiveClient cashes the PIN (started doing that after I installed everything an thus stopped asking for the PIN every other time I hit enter).  It still asked me what cert from the CAC that I want to use.  My PIV is enabled on my CAC but I don't always see it a a choice.

**Comment by mouse07410** [comment]
> Ooh, and the Yubikey may lose the login state if a AID is sent the Yubikey which it does not understand. A real PIV does not lose the login state. This may be what you are seeing when the CAC is reinserted.

@dengert I hear you, but my symptoms are: after the CAC is re-inserted (once!) I'm getting 8 PIN prompts in the row for Yubikey. Losing the login state after (another) card is re-inserted could explain asking for a PIN *once*. What about the other seven times??? Especially since it doesn't get to asking me the CAC PIN until all the eight Yubikey prompts are answered?

**Comment by dengert** [comment]
Seven extra prompts! That is hard to explain. But here is a possible factors:
- Yubikey can lose the PIV login state if it is sent an AID that it does not understand, or even the one it does understand. 
- Real PIV and Yubikey should/will lose the login state if sent an AID for some other applet that is on the card, such CAC.  (PIV says it will loose the login state if an other AID on the card is selected.)
- You will need to enter the pin once for initial login. (See below  comments on `card-piv.c` 'CI_*' issues.) 
- Then enter again it use the PIV signing key. 
- If you have multiple processes each trying to use the card multiply by the number of processes.
- If you are using p11 kit and more then one module is accessing the card multiply by the number of modules. 
- When OpenSC searches for a driver, many of the drivers will send an AID to the card. So using the default list of drivers may cause more then one AID to be sent. 
- OpenSC and p11kit (best I can tell) do not have a way to force the use of a card to one driver for a specific p11 module within the same process. (When using OpenSC with pkcs11 all processes show up as "opensc_pkcs11" and not the process name such as "opensc-tool".
- Reinsertion of the CAC card can cause the selection of AID to be be initiated by every one of the modules times the number of processes. 

Possible long term solutions:
- Get Yubico to fix the AID loses state issue. See in 'card-piv.c' 'CI_OTHER_AID_LOSE_STATE', 'CI_PIV_AID_LOSE_STATE' and ` CI_VERIFY_LC0_FAIL`
- Fix PCSC to keep track of login state and cached passwords. (Does not solve policy to use pinpad readers.)
- Fix OpenSC pkcs11 to pass the application name in addition to `opensc-pkcs11` so `opensc.conf`  can be used to differentiate between multiple applications calling `opensc-pkcs11`.
- Fix p11kit (I have not looked at this closely) to pass something different to each module to allow modules to differentiate what they should be doing, so you could have one module only look for specific card or only look at selected readers. 
- Fix OpenSC to only use selected readers for selected cards. 
- Fix tokens with multiple applets to support each applet on an independent reader so they appear as independent cards each in its own reader. (I proposed this to Yubico years ago to no avail.)

As you can tell from the above iso7816 and PC/SC have a lot of issues with multiple applets on the same card.  Vendors tend to assume their card is the only card in the system and not to expect  different drivers poking at them and don't implement may of the things iso7816 provides. Using the ATR to define the applet does not work when one can use a Java card with multiple applets installed vendor by user.

**Comment by mouse07410** [comment]
> You will need to enter the pin once for initial login. (See below comments on `card-piv.c` 'CI_*' issues.) Then enter again it use the PIV signing key...

That would explain being prompted twice. But not seven (more) times.

> ...So using the default list of drivers may cause more then one AID to be sent.

Neither this nor the majority of the other explanations account for the fact that I'm prompted so many times. At best they explain why the prompt might repeat twice.

> ...Get Yubico to fix the AID loses state issue...

I'll talk to them. Could you please clarify what **exactly** the issue is - what commands/messages/APDUs should the card accept without change in its status, which it violates?

**Comment by dengert** [comment]
@mouse07410 I believe I have sent you this script before: 
[piv-check-state.sh.txt](https://github.com/OpenSC/OpenSC/files/3965547/piv-check-state.sh.txt)

Here is the output  [piv-check-state.sh.123456.basic.txt](https://github.com/OpenSC/OpenSC/files/3965572/piv-check-state.sh.123456.basic.txt) using a Yubikey 4 (The latest I have) with version 4.3.7 with pin 123456 using command:`./piv-check-state.sh 123456 basic` 

The basic test  uses `opensc-tool` with default driver (iso7816).  All tests are all done by sending selected APDUs and do not need the PIV driver. 
```
                opensc-tool $DEBUG -c default -s "$SELECTAID_PIV" -s "$VERIFY:08$PIN" -s "$VERIFY" \
                    -s "$SELECTAID_PIV" -s "$VERIFY" \
                    -s "$SELECTAID_ESTEID" -s "$VERIFY" \
                    -s "$SELECTAID_PIV" -s "$VERIFY
```

- SELECTAID_PIV,  works returns 90 00
- VERIFY:08$PIN, works  returns 90 00
- VERIFY works returns 63 C3 i.e. 3 tries left, but still logged in.
- SELECTAID_PIV works returns 90 00
- VERIFY works and returns 63 C3 i.e. 3 tries left, but still logged in.
 - SELECTAID_ESTEID  fails 6A 82 as expected. The AID for this applet not on the token. It is an AID for one of the cards OpenSC supports and if you don't modify `opensc.conf` of force a driver OpenSC will test for this card. 
-  VERIFY now fails 6D 00. **PIV Specs that when an AID for an applet is not on the card, the login state should not change and the PIV applet will remain the active applet**.  
- SELECTAID_PIV works 
- VERIFY works and show PIV login state is still valid, which is an improvement over older Yubico devices. (See comments about testing type of card for `"Yubikey5"` if you have one of these.

The current `card-piv.c` will read the Yubico version number `priv->yubico_version` but only tests  in 2 places for  version  4.3.2. It does not test for 4.3.7 or any other versions where fixes have been made.

Note that the 4.3.7 token, fixed one of the issues in a way that OpenSC might live with, as `card-piv.c`  can do a SELECT_AID at the start of every transaction.   The test for type of Yubico devices may need improvement. Look for `"Yubikey4"` in  `card-piv.c`. It may need a test for `"Yubikey5"` if there is such a thing.

Please try the script with different tokens you have to see what they do. Add `-a` to the `opensc-tool` command to print ATR. You could add `YUBICO_VER="00 FD 00 00"`  and  `-s "$YUBICO_VER"  to the script to read the version number. 

What Yubikey or NEO devices do you have, and what are the ATRs, and Yubikey  versions? 

If you have any clout with Yubico, ask them to submit PRs to `card-piv.c` and/or `card-openpgp.c` to address issues fixed in different versions of their devices.  Being retired, I don't use any smart cards on a regular basic and don't keep up with new Yubico products.

**Comment by Jakuje** [comment]
Is this behavior with master (after #1822) or without it? Does these changes that I introduced there affect this behavior, or they affect only the reader removal?
