### ISSUE TITLE
Support for VCI or Full Opacity

### ISSUE THREAD

**Issue by mgramigna** [OpenSC/OpenSC#1517]
### Problem Description

If I have a PIV card that tries to use [Virtual Contact Interface (VCI)](https://nvlpubs.nist.gov/nistpubs/specialpublications/nist.sp.800-73-4.pdf) (pages 21-22) or [Full Opacity](https://www.securetechalliance.org/resources/pdf/OPACITY_Protocol_3.7.pdf), will OpenSC support the protocol?

**Comment by dengert** [comment]
When will it support the optional VCI in [NIST-800-73-4](https://nvlpubs.nist.gov/nistpubs/specialpublications/nist.sp.800-73-4.pdf) you ask?

When I or other developer have a PIV card that supports this option. Last time I went looking there where none. So far you are the only one who has asked. 

Is it a US Gov issued card? 
Is it a PIV only or dual CAC/PIV card?
What type card is it and where did you get it? 
Do you know where to buy/free one of these?

Not having looked the VCI in NIST-800-4 closely I think the OpenSC Secure Messaging could be used. 

As for the Opacity, that looks like something that may be in CAC cards from Active Identity but not in NIST-800-73-4. (Correct me if I am wrong.)

**Comment by frankmorgner** [comment]
The PIV standard you've referenced is talking about Opacity ZKM, which is broken. It doesn't mention FS. Is Opacity used anywhere?

AFAIK, Opacity is patented, which needs to be checked if someone wants to implement this for SM key establishment in OpenSC.

**Comment by dengert** [comment]
You may want to look at: [Opacity-for-smartcard](https://github.com/shevelevsergey/opacity-for-smartcard) It was last updated 3 years ago and includes a smart card applet and client code for a web server. It also includes  links to a security analysis from a few years ago.

Since OpenSC implements a PKCS\#11 interface to smart cards, I would doubt that it would ever implement any code for Opacity. I have not looked closely at the site. You may  want to contact the author: @shevelevsergey
