### ISSUE TITLE
openSC: how session objects are destroyed?

### ISSUE THREAD

**Issue by llllily** [OpenSC/OpenSC#1523]
hi,
i'm reading code to learn how to implement pkcs#11 spec. i have a question about how the session objects are destoryed when session is closed. I have not find that in the code of opensc.    
in pkcs#11 spec , "whenever a session is closed by any means, all session objects created by that session are automatically destroyed" 
Does openSC support this or not?

**Comment by frankmorgner** [comment]
grep for `pkcs15_any_destroy` or `__pkcs15_delete_object`, which is called from `C_DestroyObject`. Currently we're not supporting pure session objects. This is added with #1393, maybe @hhonkanen has some input.

**Comment by dengert** [comment]
Good question. OpenSC does not use many session objects. The one I know of
is ECC C_Derive of a secret key.

On Oct 31, 2018 9:44 PM, "llllily" <notifications@github.com> wrote:

hi,
i'm reading code to learn how to implement pkcs#11 spec. i have a question
about how the session objects are destoryed when session is closed. I have
not find that in the code of opensc.
in pkcs#11 spec , "whenever a session is closed by any means, all session
objects created by that session are automatically destroyed"
Does openSC support this or not?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenSC/OpenSC/issues/1523>, or mute the thread

**Comment by hhonkanen** [comment]
In #1393 we are introducing hardware session objects. Only MyEID cards fully support these objects in OpenSC currently, and we do the cleanup this way: OpenSC cleans up its internal memory structures as part of normal memory cleanup when a session is closed. (or when a slot is freed?). MyEID card clears session objects from the card automatically, when it is reset next time. At the latest it occurs, when the card is inserted into a reader and powered up next time. I think any other card that supports session objects should have a similar mechanism as well. The card can be ejected at any time, so one shouldn't rely on software to delete them.

To fully comply with PKCS#11, we should make it possible to delete session objects in C_CloseSession, which would work also in case the card remains in reader. Inside C_CloseSession call, we should walk through PKCS#15 objects, check if they have session_object flag set and check if they are associated with a hardware object. If it's on card, we should call the driver to delete it. There's already @dengert's TODO comment about this in function pkcs15_logout() in framework-pkcs15.c 

Session objects are not written into card's PKCS#15 directory files, so no cleanup is needed for them. 

I could try implementing it into C_CloseSession. I think pkcs15_logout() is probably the right place, but I'm not 100% sure. In sc_pkcs11_close_session() there's a comment: /* If we're the last session using this slot, make sure we log out */. logout() is called when the last sesson of a slot is closed. But shouldn't we clean session objects every time C_CloseSession is called? 

Another, maybe easier approach would be to let cards and drivers implement their own way to delete  all session objects in card.logout(). At the simplest, this would mean just resetting the card.

@frankmorgner I'd prefer to work with this separately from #1393.

**Comment by frankmorgner** [comment]
@hhonkanen sure! I just wanted to take this as a reminder what else could be needed with the new functionality. Currently, I don't think we have session objects that need to be destroyed, because everything is written persistently to the card...

**Comment by dengert** [comment]
We have two types of session objects. One that has data stored on the card
and one that does not.  For example the PIV ECC derive operation returns
the secret key from the card. The card does not save secret key.   A PKCS11
secret key object is created in memory as a session object that is returned
to the calling application that can then access the object to to get the
secret.

Wrap and unwrap could also do both types. The intent of the caller may be
to unwrap a key so it can be used by software. It may depend on the
capabilities of the card. Can it unwrap and the use the unwraped key on the
card or only return the key.

On Nov 4, 2018 3:48 AM, "Frank Morgner" <notifications@github.com> wrote:

@hhonkanen <https://github.com/hhonkanen> sure! I just wanted to take this
as a reminder what else could be needed with the new functionality.
Currently, I don't think we have session objects that need to be destroyed,
because everything is written persistently to the card...

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/OpenSC/OpenSC/issues/1523#issuecomment-435662941>, or mute
the thread

**Comment by llllily** [comment]
Thank everyone for your comments! I learned more about session objects.
