### ISSUE TITLE
Failed to connect to card: Card is invalid or cannot be handled - Aventra MyEID

### ISSUE THREAD

**Issue by minfrin** [OpenSC/OpenSC#1563]
### Problem Description

A previously working MyEID smartcard suddenly returns the error "Card is invalid or cannot be handled".

### Proposed Resolution

Smartcard recognised successfully.

### Steps to reproduce

Most commands return the above error, including pkcs15-tool --dump.

The key line seems to be:

0x1124d55c0 02:14:30.828 [pkcs15-tool] card-myeid.c:171:myeid_init: Failed to get MyEID applet information.: -1210 (Card is invalid or cannot be handled)

This triggers opensc to keep looking for other drivers, even though this ATR matched.

### Logs

https://gist.github.com/minfrin/d16273b4772bc259d67799d2f7feb16a

**Comment by minfrin** [comment]
Downgrading to opensc v0.18.0 is also broken, but the error returned is different:

    0x1105775c0 13:15:40.324 [pkcs15-tool] card-myeid.c:173:myeid_init: Failed to get MyEID applet information.: -1400 (Internal error)
    0x1105775c0 13:15:40.324 [pkcs15-tool] card.c:288:sc_connect_card: driver 'MyEID cards with PKCS#15 applet' init() failed: Internal error

**Comment by dengert** [comment]
`card-myeid.c:1442:myeid_get_info: called`
sent APDU `00 CA 01 A0 14` returned `67 00` (Wrong length)
This command has been there since 2009. 

Your card or reader may be broken.

Try cleaning contacts, different reader, different computer. 

You can also play with it using `opensc-tool -c default -s <arg>`

"-s, --send-apdu <arg>         Sends an APDU in format AA:BB:CC:DD:EE:FF..."

**Comment by minfrin** [comment]
I've tried two different readers (ACS ACR38T-D1 and Gemalto CT710), and various MyEID smartcards, all display the same problem.

I've swapped out the MyEID card for a Feitian card and everything works again.

Can you confirm how the error code "Wrong length" becomes "Card is invalid or cannot be handled"?

**Comment by dengert** [comment]
It looks like it is here:
https://github.com/OpenSC/OpenSC/commit/439a95f2d26a0d924ca9cab27fbde43cd74d1522#diff-a079bc432b6908f2ceb746e401e3147e

**Comment by dengert** [comment]
Try running this command:
opensc-tool -c default -s  "00:CA:01:A0:00"

Are these new MyEID cards? 
Is this related to: https://github.com/OpenSC/OpenSC/issues/1560
Is this one you erased? 

Try running this command:
opensc-tool -c default -s  "00:CA:01:A0:00"

This will try and read 256 bytes of "info". Maybe newer cards return more then the "20" or don't support the  `myeid_get_info` as they have in the past.

**Comment by minfrin** [comment]
I tried sending the APDU as follows:

    Little-Net:~ minfrin$ opensc-tool -c default -s "00:CA:01:A0:00"
    Using reader with a card: Gemalto Ezio Shield
    Sending: 00 CA 01 A0 00 
    Received (SW1=0x6A, SW2=0x88)

Can you confirm what the SW1 and SW2 bytes refer to?

To confirm I'm not mixing cards up, the ATR is as follows:

    Little-Net:~ minfrin$ opensc-tool --atr
    Using reader with a card: Gemalto Ezio Shield
    3b:f5:18:00:00:81:31:fe:45:4d:79:45:49:44:9a

One of the cards is the one that was successfully erased and reformatted as per #1560. The other cards (such as the one above) are brand new cards, and have not yet been formatted.

**Comment by dengert** [comment]
You can "comfirm what the  SW1 and SW2 bytes refer to" yourself. Find or buy a copy of iso7816-4 online.  Or look at: 
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/iso7816.c#L54 which has a list of the most common ones.

I see that in #1560  Aventra support gave you some assistance. Do you have any documentation or can they assist you on how to initialize new cards?

I also see https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-myeid.c#L4 "Copyright (C) 2008-2009 Aventra Ltd."  They wrote the driver. The card is not considered a MyEID card unless the APDU `00 CA 01 A0 14` returns `9000`. 

Many cards these days can have different applets loaded on a card. So  "card drivers" are more like "applet drivers". It might be that a "new card" needs the applet loaded, or the applet turned on. 
for example I have a pre-production "MyEID card with a PIV applet.   

```
./opensc-tool -c default -s "00:CA:01:A0:00"
Using reader with a card: SCM Microsystems Inc. SCR 355 [CCID Interface] 00 00
Sending: 00 CA 01 A0 00 
Received (SW1=0x90, SW2=0x00):
4D 79 45 49 44 04 00 00 00 00 50 63 25 16 2E 4D MyEID.....Pc%..M
24 4C 00 51 
```
And selecting the PIV applet and then running `00 CA 01 A0 00` still works: (But the data returned from the select does not meet the PIV specs.) 

```
doug@XUbuntu-18:/opt/ossl-1.1/bin$ ./opensc-tool -c default  -s "00 A4 04 00 09 A0 00 00 03 08 00 00 10 00 00" -s "00:CA:01:A0:00"
Using reader with a card: SCM Microsystems Inc. SCR 355 [CCID Interface] 00 00
Sending: 00 A4 04 00 09 A0 00 00 03 08 00 00 10 00 00 
Received (SW1=0x90, SW2=0x00):
4F 06 00 00 10 00 01 00 79 08 4F 06 00 00 10 00 O.......y.O.....
01 00 50 18 4D 79 45 49 44 20 50 49 56 20 63 61 ..P.MyEID PIV ca
72 64 20 65 6D 75 6C 61 74 69 6F 6E             rd emulation
Sending: 00 CA 01 A0 00 
Received (SW1=0x90, SW2=0x00):
4D 79 45 49 44 04 00 00 00 00 50 63 25 16 2E 4D MyEID.....Pc%..M
24 4C 00 51                                     $L.Q
```

 So what I am saying, is it looks you you need to contact support and ask what is on your new cards,  and why does 00:CA:01:A0 fail.

**Comment by hhonkanen** [comment]
The GET DATA (applet information) command that is sent in myeid_get_info() should work on all versions of MyEID and in all states. It is not part of the PKCS#15 structure and not something that is erased, if the card is erased/reinitialized. This code has been working fine for years, so looks like something else is wrong, I just don't undestand what it could be yet.

Would sending 00:CA:01:A0:00 instead of 00:CA:01:A0:14 make difference? Sending some other APDUs from the refence manual directly would show if the card responds to them normally or is there something wrong with readers or drivers. For example SELECT FILE commands:
00:A4:00:00:02:3F:00 or 00:A4:00:08:02:50:15 and see if you get FCI structure in response.

**Comment by minfrin** [comment]
Spent more time narrowing this down.

On the MacOS Mojave machine that's causing all the trouble, I get the following:

    Little-Net:~ minfrin$ opensc-tool -c default  -s "00 A4 04 00 09 A0 00 00 03 08 00 00 10 00 00" -s "00:CA:01:A0:00"
    Using reader with a card: Gemalto Ezio Shield
    Sending: 00 A4 04 00 09 A0 00 00 03 08 00 00 10 00 00 
    Received (SW1=0x6A, SW2=0x82)
    Sending: 00 CA 01 A0 00 
    Received (SW1=0x6A, SW2=0x88)

On another machine running MacOS Yosemite with the same smartcard and the same reader, I get the following:

    Beast-of-Burden:~ minfrin$ opensc-tool -c default  -s "00 A4 04 00 09 A0 00 00 03 08 00 00 10 00 00" -s "00:CA:01:A0:00"
    Using reader with a card: Gemalto Ezio Shield
    Sending: 00 A4 04 00 09 A0 00 00 03 08 00 00 10 00 00 
    Received (SW1=0x6A, SW2=0x82)
    Sending: 00 CA 01 A0 00 
    Received (SW1=0x90, SW2=0x00):
    4D 79 45 49 44 03 03 03 00 00 01 06 00 40 43 95 MyEID........@C.
    22 28 00 19                                     "(..

So - something on the Mojave machine is unhappy.

Something else I have noticed - on the Mojave machine, the smartcard does not appear at all in Keychain. The following is logged in the console log:

    No token driver found for card <TKSmartCardATR: 0x7fb464508400 3b 180000 T=1:--- T=1:fe45-;4d79454944> ATR bytes: <3bf51800 008131fe 454d7945 49449a>

On the Yosemite machine, the smartcard does appear as normal in the Keychain.

Is there something specific about MacOS Mojave that doesn't like the MyEID card?

**Comment by dengert** [comment]
[MyEID_PKI_JavaCard_Applet_Reference_Manual_2-1-4.pdf](https://webservices.aventra.fi/wordpress/wp-content/downloads/MyEID_PKI_JavaCard_Applet_Reference_Manual_2-1-4.pdf) Table 4 Says "CA"  is a GET DATA command **supported by the applet**.   With "P1 = 01h" and "P2 = A0h: MyEID Applet information, see Table 10."  Table 10 describes the 20 bytes.  

The Applet AID appears to be `A000000063504B43532D3135`.  [211-emv-aid-rid-pix](https://www.eftlab.co.uk/index.php/site-map/knowledge-base/211-emv-aid-rid-pix) says this AID is: "RSA PKCS-15 PKI application (Predecessor to ISO7816-15) / ID-card in Finland"


Is it possible that on new or erased card, the current AID (or default AID on power up)  is not the  
above AID, and thus it is not retrieved?

@minfrin 
Can you try a simple test to select the above AID then get the info (and also try the above two SELECT FILE commands) :

```
opensc-tool -c default -s '00 A4 04 00 0C A0 00 00 00 63 50 4B 43 53 2D 31 35 00' \
 -s '00 CA 01 A0 00' \
 -s "00:A4:00:00:02:3F:00"  -s "00:A4:00:08:02:50:15"
```
(Try the above without the `-s 00 A4 04 00 ...`  too. after removing and reinserting the card.

On my pre-production MyEID card with PIV and ATR 3b:f5:96:00:00:81:31:fe:45:4d:79:45:49:44:14 I get:
```
opensc-tool -c default -s '00 A4 04 00 0C A0 00 00 00 63 50 4B 43 53 2D 31 35 00' \
>  -s '00 CA 01 A0 00' \
>  -s "00:A4:00:00:02:3F:00"  -s "00:A4:00:08:02:50:15"
Using reader with a card: SCM Microsystems Inc. SCR 355 [CCID Interface] 00 00
Sending: 00 A4 04 00 0C A0 00 00 00 63 50 4B 43 53 2D 31 35 00 
Received (SW1=0x90, SW2=0x00):
6F 25 81 02 7F FF 82 01 38 83 02 50 15 86 03 11 o%......8..P....
30 FF 85 02 00 E2 8A 01 07 84 0C A0 00 00 00 63 0..............c
50 4B 43 53 2D 31 35                            PKCS-15
Sending: 00 CA 01 A0 00 
Received (SW1=0x90, SW2=0x00):
4D 79 45 49 44 04 00 00 00 00 50 63 25 16 2E 4D MyEID.....Pc%..M
24 4C 00 51                                     $L.Q
Sending: 00 A4 00 00 02 3F 00 
Received (SW1=0x90, SW2=0x00):
6F 17 81 02 7F FF 82 01 38 83 02 3F 00 86 03 11 o.......8..?....
30 FF 85 02 00 E2 8A 01 07                      0........
Sending: 00 A4 00 08 02 50 15 
Received (SW1=0x6A, SW2=0x86)
```

**Comment by mouse07410** [comment]
> On the Yosemite machine, the smartcard does appear as normal in the Keychain

On Yosemite, most likely you're using `OpenSC.tokend`. Among other things, it makes the card visible in the Keychain Access as another keychain.

On Mojave, unless you have `OpenSC.tokend` installed, you're limited to Apple's native `pivtoken` that does **not** present the card to the Keychain Access any more (it was a deliberate decision). I don't know whether `pivtoken` could interfere with `OpenSC.tokend` and whether it needs to be disabled via, e.g.:
```
sudo security smartcard token -d com.apple.pivtoken
```

**Comment by minfrin** [comment]
On the Mojave machine causing the trouble, I take out the card and I reinsert it, and get this:

    Little-Net:~ minfrin$ pkcs15-tool --dump
    Using reader with a card: Gemalto Ezio Shield
    Failed to connect to card: Card is invalid or cannot be handled

I then run the APDUs you suggested above, and get a valid response:

    Little-Net:~ minfrin$ opensc-tool -c default -s '00 A4 04 00 0C A0 00 00 00 63 50 4B 43 53 2D 31 35 00'  -s '00 CA 01 A0 00'  -s "00:A4:00:00:02:3F:00"  -s "00:A4:00:08:02:50:15"
    Using reader with a card: Gemalto Ezio Shield
    Sending: 00 A4 04 00 0C A0 00 00 00 63 50 4B 43 53 2D 31 35 00 
    Received (SW1=0x90, SW2=0x00):
    6F 25 81 02 7F FF 82 01 38 83 02 50 15 86 03 11 o%......8..P....
    1F FF 85 02 00 02 8A 01 01 84 0C A0 00 00 00 63 ...............c
    50 4B 43 53 2D 31 35                            PKCS-15
    Sending: 00 CA 01 A0 00 
    Received (SW1=0x90, SW2=0x00):
    4D 79 45 49 44 03 03 03 00 00 01 06 00 40 43 95 MyEID........@C.
    22 28 00 19                                     "(..
    Sending: 00 A4 00 00 02 3F 00 
    Received (SW1=0x90, SW2=0x00):
    6F 17 81 02 7F FF 82 01 38 83 02 3F 00 86 03 11 o.......8..?....
    3F FF 85 02 00 02 8A 01 01                      ?........
    Sending: 00 A4 00 08 02 50 15 
    Received (SW1=0x6A, SW2=0x86)

Suddenly, the pkcs15-tool --dump works too:

    Little-Net:~ minfrin$ pkcs15-tool --dump
    Using reader with a card: Gemalto Ezio Shield
    PKCS#15 Card [Mercury]:
	Version        : 0
	Serial number  : 00000106004043952228
	Manufacturer ID: Aventra Ltd.
	Last update    : 20190101204503Z
	Flags          : PRN generation, EID compliant

    PIN [Security Officer PIN]
	Object Flags   : [0x3], private, modifiable
	ID             : ff
	Flags          : [0xB0], initialized, needs-padding, soPin
	Length         : min_len:4, max_len:8, stored_len:8
	Pad char       : 0xFF
	Reference      : 3 (0x03)
	Type           : ascii-numeric

    PIN [Basic PIN]
	Object Flags   : [0x3], private, modifiable
	ID             : 01
	Flags          : [0x30], initialized, needs-padding
	Length         : min_len:4, max_len:8, stored_len:8
	Pad char       : 0xFF
	Reference      : 1 (0x01)
	Type           : ascii-numeric

I take the card out:

    Little-Net:~ minfrin$ pkcs15-tool --dump
    Card not present.

I put the card back in:

    Little-Net:~ minfrin$ pkcs15-tool --dump
    Using reader with a card: Gemalto Ezio Shield
    Failed to connect to card: Card is invalid or cannot be handled

I run the same APDUs as above:

    Little-Net:~ minfrin$ opensc-tool -c default -s '00 A4 04 00 0C A0 00 00 00 63 50 4B 43 53 2D 31 35 00'  -s '00 CA 01 A0 00'  -s "00:A4:00:00:02:3F:00"  -s "00:A4:00:08:02:50:15"
    Using reader with a card: Gemalto Ezio Shield
    Sending: 00 A4 04 00 0C A0 00 00 00 63 50 4B 43 53 2D 31 35 00 
    Received (SW1=0x90, SW2=0x00):
    6F 25 81 02 7F FF 82 01 38 83 02 50 15 86 03 11 o%......8..P....
    1F FF 85 02 00 02 8A 01 01 84 0C A0 00 00 00 63 ...............c
    50 4B 43 53 2D 31 35                            PKCS-15
    Sending: 00 CA 01 A0 00 
    Received (SW1=0x90, SW2=0x00):
    4D 79 45 49 44 03 03 03 00 00 01 06 00 40 43 95 MyEID........@C.
    22 28 00 19                                     "(..
    Sending: 00 A4 00 00 02 3F 00 
    Received (SW1=0x90, SW2=0x00):
    6F 17 81 02 7F FF 82 01 38 83 02 3F 00 86 03 11 o.......8..?....
    3F FF 85 02 00 02 8A 01 01                      ?........
    Sending: 00 A4 00 08 02 50 15 
    Received (SW1=0x6A, SW2=0x86)

And suddenly pkcs15-tool --dump works again:

    Little-Net:~ minfrin$ pkcs15-tool --dump
    Using reader with a card: Gemalto Ezio Shield
    PKCS#15 Card [Mercury]:
	Version        : 0
	Serial number  : 00000106004043952228
	Manufacturer ID: Aventra Ltd.
	Last update    : 20190101204503Z
	Flags          : PRN generation, EID compliant

    PIN [Security Officer PIN]
	Object Flags   : [0x3], private, modifiable
	ID             : ff
	Flags          : [0xB0], initialized, needs-padding, soPin
	Length         : min_len:4, max_len:8, stored_len:8
	Pad char       : 0xFF
	Reference      : 3 (0x03)
	Type           : ascii-numeric

    PIN [Basic PIN]
	Object Flags   : [0x3], private, modifiable
	ID             : 01
	Flags          : [0x30], initialized, needs-padding
	Length         : min_len:4, max_len:8, stored_len:8
	Pad char       : 0xFF
	Reference      : 1 (0x01)
	Type           : ascii-numeric

**Comment by mouse07410** [comment]
Applet not selected by default...?

**Comment by minfrin** [comment]
Unplugging the card / plugging card back in, and unplugging the USB / plugging the USB back in have the same effect:

The smartcard returns "Card is invalid or cannot be handled" until the APDUs are sent, them the card responds.

**Comment by dengert** [comment]
Selecting the correct  AID for the applet is the first step. 

There are other considerations with the logged_in state (i.e.VERIFY of the PIN sets logged_in state)  . ISO standards do not say anything about what happens to the logged_in state when  an SELECT AID is done with an AID **not** supported  or supported by the card.  

NIST 800-73-4 has 3 paragraphs on this  "3.1.1 SELECT Card Command" . Paraphrasing this
 it says: If AID is for PIV applet or AID not supported by the card, the logged_in state of teh PIV applets does not change. If AID is not the PIV AID but the card supports an applet with the AID, the PIV logged_in state is reset and the new applet becomes the active applet. 

Unfortunately some PIV look a like implementations do not follow the above. 

A VERIFY command with Lc=0 can be used to test the login_state. But I have seen PIV look a like cards where this  does not work. The MyEID specs say it is supported. 

So a card with multiple applets running in an environment where the user may want to use one applet with one application and a different applet with another application (for example: Browser and e-mail) has to support this. The other applications may or may not be using OpenSC (for example:  com.apple.pivtoken) 
so the OpenSC code has to at least make sure its applet is selected at the start of ever transaction and test the logged_in state as needed.

**Comment by hhonkanen** [comment]
All MyEID cards that are in distribution have only the MyEID applet and it is always set as default applet, therefore we haven't thought it would be necessary to select the applet explicitly. We have changed the applet loader keys and loading another applet to the cards would require requesting the keys from us. We don't generally allow other applets on the same card, a special contract with us would be required for that.

The PIV emulation is not enabled by default, so it shouldn't be possible that the card goes into PIV emulation state just by selecting the PIV AID. 

I don't have any first hand experience on using MyEID cards with MacOS. Maybe some other process is interfering, I just don't undertand how. 

In any case, it's not a bad idea to ensure selection of MyEID applet by selecting the AID when connecting to the card. We should add the SELECT command with MyEID AID to myeid_init() function. If it solves this particular problem then that's great.

**Comment by dengert** [comment]
Does the MyEID have any other applets such as GP or Java applets that some other driver during OpenSC match phase might be trying?

A pcscd trace would show what SELECT AID commands were sent to the card. That is assuming all applications are using PCSC. Not sure that is true on MacOS.

**Comment by hhonkanen** [comment]
Did some testing and I think I understand what happens. The card contains the GP Card Manager applet which can be selected with command 00A4040008A000000003000000. After selecting Card Manager commands are routed to it instead of MyEID and I can reproduce the problem this way. Looks like some process on the MacOS machine selects card manager when the card is inserted. I think it must be something else than OpenSC itself, because we haven't encountered this problem earlier.

We have to add SELECT AID to myeid_init(). I'll make a PR soon.

**Comment by dengert** [comment]
Adding SELECT AID to  myeid_init() may not be enough. Once the OpenSC  myeid_init() completes  "process on the MacOS machine selects card manager"  can leave the card with the wrong applet selected and other MyEID commands will fail. Its a mater which application set the AID last. 

Have a look at #842 which introduced the `card_reader_lock_obtained` to notify the card driver at the start of every SCardBeginTransaction. The driver can then do what is needed to make sure the correct AID is selected.  (In PIV driver case, it may do a GET_DATA of "7E" which on PIV applet will return AID and/or do a SELECT AID. It depends on the card as some PIV look alike applets lose the logged_in state when a SELECT AID is done. ) 

Also look at #1243 and 07256eec7769053bac1df528b308b97dd74ab693 which uses the  `card_reader_lock_obtained` only if the card was reset but could do more if needed. 

Since some of your MyEID cards may also have a PIV applet, you have a multiple applet card much like cards with PIV+OpenPGP and PIV+CAC.  You may want  to do the SELECT AID from card-myeid.c  for every SCardBeginTransaction.

**Comment by hhonkanen** [comment]
We cannot do SELECT AID at start of each transcation, because re-selecting MyEID applet affects the card's state, for example by invalidating PINs. We could do a GET DATA with p2=A0 (applet information) to check if MyEID is selected, but in case some other process has unselected it, it usually wouldn't help to reselect it, becuase we would have lost the authentication state. This check would also add extra overhead for those who don't have this issue.

connect_exclusive = true setting in opensc.conf can be set to ensure that other processes cannot interfere when the card is connected. Not sure if this Works with MacOS. 

The PIV feature in MyEID is actually emulation that is done internally in the MyEID applet. PIV emulation can be turned on and off. If it's on, selecting PIV AID activates it and subsequent commands are handled as PIV commands. If PIV emulation is off, selecting PIV AID results into SW/SW2=6A82..

**Comment by dengert** [comment]
What command can be used on a MyEID card to test which applets it has? I could use that in the PIV driver, like it does for Yubico cards to get version. 

The lost of login state was/is a problem with most PIV look a like card. NIST 800-73-4  (and previous versions) has 3 paragraphs on this "3.1.1 SELECT Card Command" that I cited in https://github.com/OpenSC/OpenSC/issues/1563#issuecomment-450867574 The NIST approved card vendors (most of which are Java based) support it.

The OpenSC piv driver tries to get around some of these problems. If the other applet is selected, it will do a SELECT PIV AID.  Better to get the PIV applet reselected then fail. This will required using a PIN cached by OpenSC or let PKCS\#11 prompt user for the PIN. 

PIV does talk about the PIV application PIN vs the "Global" PIN in the 800-73-3 "Discovery Object". But NIST never talk about  GP or Java. Some CAC and vendor documentation do talk about PINs, but the docs I have are pre 800-73-3.  

I am trying to point out having multiple applets on the same card have a lot of hidden problems.  Your MyEID/PIV sounds very similar to CAC/PIV cards. 

connect_exclusive does not work well when a user is trying to use one applet from the long running browser and the other applet from some other application like e-mail. The OpenPGP (not OpenPGP driver in OpenSC)  was connecting in exclusive mode and causing problems with cards with multiple applets. 

PIV does talk about the PIV PIN vs the "Global" PIN, in the 800-73-3 "Discovery Object". But NIST never talk about  GP or Java. Some CAC and vendor documentation does talk PINs, but the ones I have are are pre 800-73-3. 

If the 'PIV emulation can be turned on and off, and is controlled by the MyEID applet, why does it have to loose the login state?  Would using common "Global PIN"  for both applets help?

**Comment by hhonkanen** [comment]
Could you check if the card is in PIV mode by sending a GET DATA command from PIV spec (00 CB 3F FF ...) and check if you get a valid response?   

Selecting MyEID AID deauthenticates PINs, but I think this does not happen when selecting PIV AID, if you have authenticated PINs via MyEID interface first. Unfortunately I cannot verify this 
this now, because I'm not in the office and don't have a PIV enabled card with me. 

The main intended purpose of the PIV emulation is to allow using MyEID cards for smart card logon on devices, for example thin clients, which have a built-in PIV driver and it is not 
possible to install MyEID driver (either OpenSC or a Windows minidriver). We haven't really put effort into making possible to use both interfaces (MyEID and PIV) in the same system,
because we haven't recognized a need for this kind of usage. Why would someone want to use the PIV interface if the system has driver for the MyEID native interface? We see that there can 
be hidden problems, and this is one reason to keep the PIV feature disabled by default and require explicit activation before using it.

There are currently not many users for MyEID's PIV emulation and we haven't developed it further lately. The emulation is read only and and implements only part of the PIV specification.
