### ISSUE TITLE
PIV unused offCardCertURL

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#1587]
### Problem Description

offCardCertURL allows certificates to be fetched from an URL (http!) instead of the card. The OpenSC implementation looks into the file cache instead, i.e. the OpenSC implementation is incomplete, to say the least. ~~The OpenSC implementation, which assumes to contain the file path, is probably wrong since it is defined to be~~ When the card's offCardCertURL points to
> "http://" \<DNS name\> "/" \<ASCII-HEX encoded SHA-256 hash of OffCardKeyHistoryFile\>

then OpenSC expects the certificates to be in `.eid/cache/<ASCII-HEX encoded SHA-256 hash of OffCardKeyHistoryFile>`

Propably nobody uses uses this feature of OpenSC.

### Proposed Resolution

~~Remove support for offCardCertURL from OpenSC to reduce the complexity of the PIV driver.~~
Document this feature and add an external script for fetching the certificates from the card's URLs

**Comment by dengert** [comment]
The History object was added in 800-73-3 and is still in 800-73-4. A number of the NIST demo cards do have the URL, but when I added the code to OpenSC in 2012, I did not go as far as having the driver try and fetch the file using the URL. The idea of the History object is for retired encryption keys with maybe one key added every 2 years to a user's card or replacement card. Back then it was not clear if card memory would increase fast enough so storing off card certs would not be needed.
(The lastest demo card I have has enough memory, and is populated with the 20 retired keys.)

If it ever got to that point it could be added to piv-tool for example. 
 
To test it, I have a script pivdump.sh that uses the piv-history program to parse the history object.
[card.tools-1.0.4.tar.gz](https://github.com/OpenSC/OpenSC/files/2783610/card.tools-1.0.4.tar.gz) has the source for both. I have not touched this since 2013 before I retired in 2014. The piv-history  (history.c) was a quick and dirty program.  

Here is an example of the History object from the NIST demo card 4:
```
00000000: 5361 c101 03c2 0102 f357 6874 7470 3a2f  Sa.......Whttp:/
00000010: 2f73 6d69 6d65 322e 6e69 7374 2e67 6f76  /smime2.nist.gov
00000020: 2f37 3543 3442 3938 4446 4137 3241 3141  /75C4B98DFA72A1A
00000030: 3544 3236 3642 3038 3336 3537 4645 4632  5D266B083657FEF2
00000040: 3337 3339 3532 3643 4136 4541 3344 3236  3739526CA6EA3D26
00000050: 3635 3444 3945 3642 3834 3132 3046 4133  654D9E6B84120FA3
00000060: 35fe 00   
```
The URL can also be obtained using something like this too:
`strings history.object | sed 's/.*\(http.*\)/\1/'`

(Unfortunately some of the NIST web servers are down because of the government shutdown.
and smime2.nist.gov appears to be one of them.)
https://csrc.nist.gov/csrc/media/projects/piv/documents/test-piv-card-data-specifications.pdf
shws what is on each of the test cards.

I  would be against removing the code for the driver, because it is in the NIST specs, and would be harder to add back in then to leave it alone. 

(Last week I said I would be unavailable starting 1/29/19. It is actually starting tomorrow 1/23/19. I would like to postpone till I am back.)

**Comment by dengert** [comment]
1. You never said bug. 

I explained the missing piece was to get the URL out of the history object. The URL contains a file name (sha256 hash) , download the file pointed at be the URL and store it as a file in the user's OpenSC cache.  The driver does not do this but user can  pre-stage the file using  the something like pivdump.sh does i.e. 
`pkcs11-tool  -r -y data --application-id "2.16.840.1.101.3.7.2.96.96" > history.object`
the extract the URL and use a browser or wget to download the file.  See the pivdump.sh as an example. 

If your concern is a hacker trying to pass in a bogus pre-staged file, the file has to be a DER encoded sequence of certificates. These have to be parsed and be valid ASN1 before being used.  Right now the user would have to pre-stage it. (Along this line, are there other security concerns about what is in the OpenSC cache and how it could be misused?)  

2. a. I have always wrote OpenSC code to meet the standards of the card. Using demo cards issued by the standards writers, NIST in my case, is a way to have code ready before cards are issued to real users. 
( I now have a "demo" card that include 800-73-4 Secure Messaging and key derivation. I have started to look at implementing that part of teh standard. It looks like the OpenSC SM can be used, but the Key Derivation looks different. Expect more complexity 😊. )

2. b. We really don't know if it is used or not. I have distributed within DOE the tools to do the pre-staging.  Yubico PIV users are using the history object even with cards with limited memory. Don't know if anyone has needed to use the URL or not. All the code and comments on how to pre-stage the file are in the driver and in the NIST standards.  

2. c. The "fun" part is I enjoyed working on this code before retiring and no one (other then @mouse07410) with real PIV cards issued by US gov agencies has shown interest in maintaining the PIV driver. There was some interest in the past. Look at the copyright lines in the file.  So the "fun" part also include a loyalty to my former employer.  I have recently asked them to do a survey in DOE of who is using OpenSC with PIV cards and if there is anyone willing to get involved as an OpenSC  developer.  

DOE is not the only user.  Google for: mil.gov OpenSC   Also try Google for : "NATO" "OpenSC"
The military uses mostly dual CAC and PIV cards. Other gov agencies use pure PIV cards.  

We can carry on this discussion at a later date.

**Comment by frankmorgner** [comment]
>The OpenSC implementation, which assumes to contain the file path, is probably wrong since it is defined to be
>>    "http://" \<DNS name\> "/" \<ASCII-HEX encoded SHA-256 hash of OffCardKeyHistoryFile\>

OpenSC assumes that the URL contains a file path, but by specification it only contains a hash. That's a bug and it exactly starts here https://github.com/OpenSC/OpenSC/blob/4916d07ff2a370b10446fa5c4986a5de3c068caf/src/libopensc/card-piv.c#L2939-L2940.

What I've suggested is to remove support for offCardCertURL, not the entire PIV driver. I still do. I know that it is not used with OpenSC, because nobody complained about the bogus implementation.

**Comment by dengert** [comment]
I agree it is probably not used, because when it was introduced years ago, there was concern for not enough memory on a smart cards to hold 24 certificates.  But today cards have enough memory. 

You can turn it off or remove the code if you want but I disagree. Yubico users have jumped on using the extra keys and may have read the code. An option to piv-tool could be added to fetch the URL and
save as a file. 

If kept in the code could use some more hardening. 

-  The "filename part of the URL should be the length of a SHA-256 hash and only use the  characters
found in the encoded hash. i.e. no "/" or other that would make it look like a path. 

- After reading the file compute SHA-256 hash and compare to the file name.   

I don't believe it is a "bogus implementation" It was tested at the time it was written (and today) using the NIST demo card 4 and NIST web site. 

The URL from the above example of the history object for NIST card 4 says: 3 on card certs and 2 off card certs with a URL:
http://smime2.nist.gov/75C4B98DFA72A1A5D266B083657FEF23739526CA6EA3D26654D9E6B84120FA35

I used FireFox to download the file then copied  to what `sc_get_cache_dir`  would return, in my system that is `~.eid/cache/`
```
doug@XUbuntu-18:~/.eid/cache$ ls -la
total 16
drwx------ 2 doug doug 4096 Jan 30 10:22 .
drwxr-xr-x 3 doug doug 4096 Feb 13  2015 ..
-rw-r--r-- 1 doug doug 7288 Jan 30 10:22 75C4B98DFA72A1A5D266B083657FEF23739526CA6EA3D26654D9E6B84120FA35
```
pkcs11-tool -O shows:
```
Using slot 0 with a present token (0x0)
Public Key Object; RSA 2048 bits
  label:      Retired KEY MAN 3
  ID:         07
  Usage:      encrypt, wrap
Certificate Object; type = X.509 cert
  label:      Retired Certificate for Key Management 3
  subject:    DN: C=US, O=Test Government, OU=Test Department, OU=Test Agency, CN=Test E. Cardholder IV
  ID:         07
Public Key Object; RSA 2048 bits
  label:      Retired KEY MAN 19
  ID:         23
  Usage:      encrypt, wrap
Certificate Object; type = X.509 cert
  label:      Retired Certificate for Key Management 19
  subject:    DN: C=US, O=Test Government, OU=Test Department, OU=Test Agency, CN=Test E. Cardholder IV
  ID:         23
Public Key Object; RSA 2048 bits
  label:      Retired KEY MAN 20
  ID:         24
  Usage:      encrypt, wrap
Certificate Object; type = X.509 cert
  label:      Retired Certificate for Key Management 20
  subject:    DN: C=US, O=Test Government, OU=Test Department, OU=Test Agency, CN=Test E. Cardholder IV
  ID:         24
Public Key Object; EC  EC_POINT 256 bits
  EC_POINT:   0441049dbd6702660f3e3902adc3af070a85eaf0e7478b8d880c1c07a25068a8a4ea2e592807b3b98fe2a77ac172ab448be7d897fb0d5e9c14b5f37810870c1fb058cc
  EC_PARAMS:  06082a8648ce3d030107
  label:      PIV AUTH pubkey
  ID:         01
  Usage:      verify
Certificate Object; type = X.509 cert
  label:      Certificate for PIV Authentication
  subject:    DN: C=US, O=Test Government, OU=Test Department, OU=Test Agency, CN=Test E. Cardholder IV
  ID:         01
Public Key Object; EC  EC_POINT 256 bits
  EC_POINT:   044104d9eab706d1ef73c100e2217c2d419942ec589774a4461a4b983a1fb06649759e8a14aebe7cda5dabe1e2309a212ad2efdb4ede351758a176dd14ba7d1a0f0b34
  EC_PARAMS:  06082a8648ce3d030107
  label:      SIGN pubkey
  ID:         02
  Usage:      verify
Certificate Object; type = X.509 cert
  label:      Certificate for Digital Signature
  subject:    DN: C=US, O=Test Government, OU=Test Department, OU=Test Agency, CN=Test E. Cardholder IV
  ID:         02
Public Key Object; EC  EC_POINT 256 bits
  EC_POINT:   0441044a49f1fa00a0af37778cd07a266282e13a74fbbecb19da80e44c80a78daecc66b7d1a768f54599e3bc7aa735f4e19d316cba1668a3dc42b2159e4b887f546b3e
  EC_PARAMS:  06082a8648ce3d030107
  label:      KEY MAN pubkey
  ID:         03
  Usage:      derive
Certificate Object; type = X.509 cert
  label:      Certificate for Key Management
  subject:    DN: C=US, O=Test Government, OU=Test Department, OU=Test Agency, CN=Test E. Cardholder IV
  ID:         03
Public Key Object; EC  EC_POINT 256 bits
  EC_POINT:   0441042061ff8ccb53e82320158b4e579ba53244cb2c9728c250f1de92bc64ecbb003d2b42d681a1d2b770fa33b9f6338566e13d3b9ae1814946cb07a36b51f7b30533
  EC_PARAMS:  06082a8648ce3d030107
  label:      Retired KEY MAN 1
  ID:         05
  Usage:      derive
Certificate Object; type = X.509 cert
  label:      Retired Certificate for Key Management 1
  subject:    DN: C=US, O=Test Government, OU=Test Department, OU=Test Agency, CN=Test E. Cardholder IV
  ID:         05
Public Key Object; EC  EC_POINT 256 bits
  EC_POINT:   04410436f79d4e0bfd5ffe163a73337501dba638cd2e0af554ec1ab26c15a5e69b9599e638e98f57ab1678ce07f06f321b3fce6395394f430921e6cfefaa3a3398b792
  EC_PARAMS:  06082a8648ce3d030107
  label:      Retired KEY MAN 2
  ID:         06
  Usage:      derive
Certificate Object; type = X.509 cert
  label:      Retired Certificate for Key Management 2
  subject:    DN: C=US, O=Test Government, OU=Test Department, OU=Test Agency, CN=Test E. Cardholder IV
  ID:         06
Private Key Object; EC
  label:      CARD AUTH key
  ID:         04
  Usage:      sign
Public Key Object; EC  EC_POINT 256 bits
  EC_POINT:   044104e8b24c013f4b018176180b910b212a70042cb3686bcfa89a7456c4da48cdc6f41a08578ae13c4d219513a1e712b60bf157260bb9401cda5353c4c57a43e00eaf
  EC_PARAMS:  06082a8648ce3d030107
  label:      CARD AUTH pubkey
  ID:         04
  Usage:      verify
Certificate Object; type = X.509 cert
  label:      Certificate for Card Authentication
  subject:    DN: C=US, O=Test Government, OU=Test Department, OU=Test Agency/serialNumber=D650185B3CCE6D9C9053CDA16CDA10AA09C4378486501843EB
  ID:         04
Data object 2914290080
  label:          'Card Capability Container'
  application:    'Card Capability Container'
  app_id:         2.16.840.1.101.3.7.1.219.0
  flags:          <empty>
Data object 2914290176
  label:          'Card Holder Unique Identifier'
  application:    'Card Holder Unique Identifier'
  app_id:         2.16.840.1.101.3.7.2.48.0
  flags:          <empty>
Data object 2914290272
  label:          'Unsigned Card Holder Unique Identifier'
  application:    'Unsigned Card Holder Unique Identifier'
  app_id:         2.16.840.1.101.3.7.2.48.2
  flags:          <empty>
Data object 2914290368
  label:          'X.509 Certificate for PIV Authentication'
  application:    'X.509 Certificate for PIV Authentication'
  app_id:         2.16.840.1.101.3.7.2.1.1
  flags:          <empty>
Data object 2914290752
  label:          'X.509 Certificate for Digital Signature'
  application:    'X.509 Certificate for Digital Signature'
  app_id:         2.16.840.1.101.3.7.2.1.0
  flags:          <empty>
Data object 2914290848
  label:          'X.509 Certificate for Key Management'
  application:    'X.509 Certificate for Key Management'
  app_id:         2.16.840.1.101.3.7.2.1.2
  flags:          <empty>
Data object 2914290944
  label:          'X.509 Certificate for Card Authentication'
  application:    'X.509 Certificate for Card Authentication'
  app_id:         2.16.840.1.101.3.7.2.5.0
  flags:          <empty>
Data object 2914291040
  label:          'Security Object'
  application:    'Security Object'
  app_id:         2.16.840.1.101.3.7.2.144.0
  flags:          <empty>
Data object 2914291136
  label:          'Discovery Object'
  application:    'Discovery Object'
  app_id:         2.16.840.1.101.3.7.2.96.80
  flags:          <empty>
Data object 2914291232
  label:          'Key History Object'
  application:    'Key History Object'
  app_id:         2.16.840.1.101.3.7.2.96.96
  flags:          <empty>
Data object 2914291424
  label:          'Retired X.509 Certificate for Key Management 1'
  application:    'Retired X.509 Certificate for Key Management 1'
  app_id:         2.16.840.1.101.3.7.2.16.1
  flags:          <empty>
Data object 2914291520
  label:          'Retired X.509 Certificate for Key Management 2'
  application:    'Retired X.509 Certificate for Key Management 2'
  app_id:         2.16.840.1.101.3.7.2.16.2
  flags:          <empty>
Data object 2914299344
  label:          'Retired X.509 Certificate for Key Management 3'
  application:    'Retired X.509 Certificate for Key Management 3'
  app_id:         2.16.840.1.101.3.7.2.16.3
  flags:          <empty>
Data object 2914299440
  label:          'Retired X.509 Certificate for Key Management 19'
  application:    'Retired X.509 Certificate for Key Management 19'
  app_id:         2.16.840.1.101.3.7.2.16.19
  flags:          <empty>
Data object 2914299536
  label:          'Retired X.509 Certificate for Key Management 20'
  application:    'Retired X.509 Certificate for Key Management 20'
  app_id:         2.16.840.1.101.3.7.2.16.20
  flags:          <empty>
```
note the 5 "Retired X.509 Certificate for Key Management" keys and certs:1,2,3 are on the card and 
the keys for 19 and 20 are on the card, but the certs where found in file 
~.eid/cache/75C4B98DFA72A1A5D266B083657FEF23739526CA6EA3D26654D9E6B84120FA35

I can send a complete opensc-debug.txt  of the above or pkcs11-tool --test --login if that would help.
