### ISSUE TITLE
print label in hex format

### ISSUE THREAD

**Issue by mrangana** [OpenSC/OpenSC#1614]
### Problem Description
pkcs11-tool prints the label in non-hex format and may lose some null bytes at the end.  Some other interface may fail to find the key using provided label.

### Proposed Resolution
print the label in hex encoding similar to id 
### Steps to reproduce
- generate keys using other interfaces like crypto11 (crypto11.GenerateRSAKeyPair)
- List the keys using pkcs11-tool
          pkcs11-tool --module /usr/lib/softhsm/libsofthsm2.so -L -p <user pin> -O

### Logs
Public Key Object; RSA 2048 bits
  label:      **PjeoBI6H3mcjcHzYoHGkXU00sHFr3JAwQN63UR0sCkg=**
  ID:         44706658696d7a716279655244376559755a7938493833524b642d6374794b5867736e484e41654f37756b3d0000000000000000000000000000000000000000
  Usage:      encrypt, verify, wrap
Private Key Object; RSA
  label:      **PjeoBI6H3mcjcHzYoHGkXU00sHFr3JAwQN63UR0sCkg=**
  ID:         44706658696d7a716279655244376559755a7938493833524b642d6374794b5867736e484e41654f37756b3d0000000000000000000000000000000000000000
  Usage:      decrypt, sign, unwrap
 ---> e3a4a73df68d

**Comment by dengert** [comment]
PKCS\#11-2.4.0 says in Section: "4.4 Storage Objects" CKA_LABEL RFC2279 | string | Description of the object (default empty)."  

RFC2279 defines a string. i.e. UTF-8.  pkcs11-tool.c treats the CKA_LABEL as ASCII using printf to print it. 

PKCS\#11-2.40 also defines CK_CHAR as ASCII and  CK_UTF8CHAR as UTF-8.  then says "RFC2279 string an unpadded string of CK_UTF8CHARs with no null-termination."

pkcs11-tool.c treats the CKA_LABEL as ASCII using printf to print it.

This issue is more of an internationalization of pkcs11-tool.

**Comment by frankmorgner** [comment]
p11_utf8_to_local in pkcs11-tool.c adds the terminating Nul character

**Comment by frankmorgner** [comment]
Maybe you need to clearify your problem, I don't see an issue with your log either.
