### ISSUE TITLE
Mac OS Catalina : Token not visible in KeyChain Access

### ISSUE THREAD

**Issue by cjn** [OpenSC/OpenSC#1767]
### Problem Description
Hi,

In MacOS Catalina beta versions OpenSC 0.19.0 was installed.
After inserting smartcard keychain access app is not listing the smart card in this Mac OS beta version. 
In the command line it is possible to view the certificates under Apple's built in PIV module.
But the same is not visible in KeyChainAccess. 
Please let me know if OpenSC works on Mac OS Catalina or are we seeing a new issue and what logs should I look into to debug the issue?

**Comment by frankmorgner** [comment]
You are seeing the result of Apple's refactoring the token handling. Apple's built in module isn't visible in KeyChain.

If you want to use OpenSC with your token, you need to disable Apple's built-in driver.

**Comment by cjn** [comment]
I have already tried disabling Apple's built in driver. Even after that certificates are not visible in the Keychain access.

**Comment by mouse07410** [comment]
AFAIK, to present the token as a keychain so that is visible in Keychain Access App, you need OpenSC.tokend. 

To compile OpenSC.tokend you need Xcode-9.4.1 (or older). That's what I'm doing on Mojave. 

I don't know if Xcode-9.4.1 would run on Catalina. The hope is that eventually all the apps would either convert from CDSA to CTK (like Google Chrome), or support PKCS#11 API (like Firefox or Adobe Acrobat), making tokend unnecessary. I've no idea how wide in time that gap would be.

**Comment by cjn** [comment]
Yes. I tried installing the openSC.tokend on Catalina to be able to see the token in Keychain Access App. But despite of disabling the default built in driver it is not appearing in the Keychain access.

**Comment by mouse07410** [comment]
What do you mean by "built in driver"? `com.apple.pivtoken`?

If so, you shouldn't need to disable it, as it doesn't prevent `OpenSC.tokend` from running.

First, where is your tokend coming from? Second - can you see if tokend is running when the token is inserted? Is there any crash report visible in Console app?

**Comment by cjn** [comment]
Yes. com.apple.pivtoken  for built in driver.

OpenSC.tokend is running and Open SC notification comes that Smart card is inserted and removed.
However keychain access does not list the certificates. There are no crash reports for tokend but for ctk in the system.

**Comment by avvRobertoAlma** [comment]
I'm experiencing same issue on Mac OS Catalina official release. I have installed both opensctokenapp and opensc 0.19.0 (in order to have OPENSC.tokend active). The smartcard results as output of `security list-smartcards` and if i execute `security export-smartcard` apparently no errors are shown. But still the smartcard does not appear in the keychain.

The same smartcard currently runs perfectly on Mac OS 10.14.6 without any problems.

What do you suggest ?

**Comment by kitsushadow** [comment]
Same issue with Catalina 10.15 (19A583)

I personally think its a OS side issue.

**Comment by drazenzubovic** [comment]
Just raising awareness that other Mac Users are experiencing t**he same mishap** with Catalina.

**Comment by bolkedebruin** [comment]
No sure if relevant:

 tokend
A tokend is a piece of software used to bridge a cryptographic device (like a smart card) and the CDSA (Common Data Security Architecture) architecture.

Since macOS Lion (10.7 in 2011) the CDSA/tokend technology is deprecated. See "Mac OS X Lion and tokend".

Tokend are now disabled by default in macOS Catalina. See the Apple page "Prepare for smart card changes in macOS Catalina":

    macOS includes a modern architecture that supports smart cards. This architecture is based on the CryptoTokenKit framework, which supports authentication, encryption, and signing functions, plus MDM controls for managing smart cards within Enterprise environments. Starting with macOS Catalina, legacy smart card support that uses TokenD will be disabled by default.


It is still possible to enable support of tokend. See SmartCardServices-legacy(7) manpage:

sudo defaults write /Library/Preferences/com.apple.security.smartcard Legacy -bool true

**Comment by hflocken** [comment]
I'm facing the same issue as described above. I installed the latest opensc version and enabled support of tokend as described above. But I still do not see any certificates from the samrtcard in my keychain. Any other hints on how to fix this isssue?

**Comment by mouse07410** [comment]
If tokend is installed and successfully running on your system (easy to verify by {{{ps -ef | grep OpenSC}}}), then the certs should show up in the Keychain. 

However, as this method is about to disappear for good - better go to App Store and find {{{Smartcard Utility}}} (don’t recall the exact name, but you can find it there).
