### ISSUE TITLE
openpgp: test results for 0.20 rc3

### ISSUE THREAD

**Issue by alex-nitrokey** [OpenSC/OpenSC#1835]
I tested the openpgp part of rc3 with various real hardware token to make sure everything is fine (though it gets theoritically tested by the CI automatically anyway).

### Tested devices
* gnuk devices (Nitrokey Start)
* OpenPGP Card v2.1 (Nitrokey Pro)
* OpenPGP Card v3.3 (Nitrokey Pro 2)

### Things that got tested
I've done the following steps of the release testing page:
* pkcs-tool tests:
 * gnuk with rsa2048 ~~(fails, see below)~~ succeeds if key is imported like it is necessary for decryption on this models
 * OpenPGP Card v2.1 with rsa2048 ~~(fails, see below)~~ succeeds if key is imported like it is necessary for decryption on this models
 * OpenPGP Card v3.3 with rsa2048 (succeeds), brainpoolP256r1 (succeeds, but most tests are skipped, see below)
* pkcs11 module in Firefox and log-in with all three devices

In general I would call theses tests a success, as the fails I got are expected to happen considering the limitation of the hardware (see below)

### Next steps
I would like to adapt the pkcs11-tool tests and the tests done automatically by the CI and make a pull request afterwards. **Could you please tell me, where these are written** as I couldn't find them easily -.- I am sorry. A small hint should be enough.

Examples I would like to (get) fix in future:
* pkcs11-tool tests decryption via authentication key slot (slot 3) on gnuk and OpenPGP card v2 devices which can not work there (only on OpenPGP v3.?). Therefore, the tests fail.
* ECC key testing in pkcs11-tool

**Comment by Jakuje** [comment]
The tests in pkcs11-tool are implemented here (p11_test function):

https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L5984

Using the authentication key for decryption is usually error of the driver, setting unreasonable usage flags for keys that are internally restricted to specific operation (signature). This needs to be set up on the pkcs15-level, when the key/certificate structures are created. If the driver knows how to detect this earlier than it tries to do the operation, it should do that. Example is piv driver, which has fixed list of usage per slot

https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/pkcs15-piv.c#L389

or cac, driver, which reads the usage from the certificate associated to the keys:

https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/pkcs15-cac.c#L139

The OpenPGP defines this very similarly as PIV driver:

https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/pkcs15-openpgp.c#L95

For the ECC keys, I can recommend you to try with the p11test under the src/tests/p11test. It supports also the ECC keys and does a bit more extensive testing than the pkcs11-tool, but the results usually need to be manually reviewed since it is less strict about the bad usage flags.

**Comment by dengert** [comment]
Comment on: "Example is piv driver, which has fixed list of usage per slot"

 For government agency issued cards the fixed list is used. For others the certificate keyUsage bits are used. 

NIST standards have a policy that call for fixed key usages. But for cards I have seen, this is not enforced on the card. PIV cards support  RAW RSA , ECDSA and ECDH.  In particular, the piv-tool can create an RSA or EC key. The key is then used to sign a certificate request to get a certificate. This sign operations works for the all the keys even ones intended for RSA encryption or ECDH key derivation.   In the future, cards could enforce the NIST policy on the card. For RSA, the data could be examined  for PKCS1 or PSS padding indicating this is a sign operation, and EC keys operations are either ECDSA or ECDH. 

NIST standards also requires a signed "Card Holder Unique Identifier" (CHUI) object which contains a "Federal Agency Smart Credential Number" (FASC-N) which contains an agency number.  Agency numbers starting with 9999 are non government agencies, i.e. which opens up the PIV standards to non government agencies. 
 
See:
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/pkcs15-piv.c#L796

At request of Yubikey users, if a card (any vendor's card) does not have a CHUI or the agency number starts with 9999 the restrictions are relaxed and the certificate keyUsage bits are used to set the key usage of the private key.  i.e. not a "fixed list".
