### ISSUE TITLE
"X509 certificate doesn't have CA chain available on it"

### ISSUE THREAD

**Issue by cvcrckt** [OpenSC/OpenSC#1893]
We have a web app that requires smartcard auth. When we enable CRL checks via CDP on the web app, it stops working in Firefox with OpenSC 0.19.0. It works fine in Chrome and Edge. In the app's logs, we see:

> Not possible to verify signature on CRL. X509 certificate doesn't have CA chain available on it

Is there a configuration change we need to make to OpenSC? When OpenSC debugging is turned on, is there a particular section of the debug log I should be focused on?

**Comment by dengert** [comment]
This does not sound like an OpenSC issue. CA certificate needs to be in the local machine store and not trusted from the smart card.  

It may work on Chrome and Edge because they each have the CA and intermediate certificates in their respective stores.  

On FireFox, look at  Tools->options->Privacy& Security->Certificates->View Certificates->Authorities
Also look at "Your Certificates".

It is also not clear if error is from checking  the server of the user certificate.

**Comment by cvcrckt** [comment]
@dengert - You are spot on. FF has its own store, whereas the other browsers use the Windows-native user store. Adding the CA chain to the FF store fixed the issue.

Thanks!

**Comment by Tche333** [comment]
FF can be configured to use Windows certificate store (not by default).
See [Configuring Firefox to use the Windows Certificate Store](https://support.umbrella.com/hc/en-us/articles/115000669728-Configuring-Firefox-to-use-the-Windows-Certificate-Store).

**Comment by m-vt** [comment]
@cvcrckt @Tche333
Hello,
I have the same issue and I cannot solve it. 
I added my .p12 (client certificate) to the personal windows certificate and the .crt (server certificate) to the Intermediate Certification Authorities. None of Chrome, Firefox and Edge works for me and keep showing the error :"X509 certificate doesn't have CA chain available on it".
Do have any solutions that can help me with this?

**Comment by m-vt** [comment]
@dengert I did the steps you've suggested. In Firefox I added the .p12 of the client to "Your Certificates" part and also the .crt of CA to the "Authorities". Still it's not working although the client-chain.pem which can be given from the Firefox shows both client and CA cert in it.

Plus followed the same procedure in Chrome (.p12 -> Personal and the CA .crt ->Trusted Root Certification Authorities and  Intermediate Certification Authorities). So in the path you've mentioned( control panel->internet Options->...) I can see them. But It keeps showing "NET::ERR_CERT_COMMON_NAME_INVALID" while the CN of the CA cert is the same as the IP given to the server.

Note that certificates are self-signed and in postman it works properly by getting the client .p12 and also the client-chain.pem.

I don't have any idea what would be the problem.

**Comment by m-vt** [comment]
@dengert I also check with WireShark. Postman had 2 certificates in "Certificate, Client Key Exchange, Certificate Verify, Change Cipher Spec, Encrypted Handshake Message" packet while Firefox and Chrome had only 1 (the client cert).

**Comment by dengert** [comment]
Client/user certificates are signed by a CA that the server trusts. The server trusts the CA because the server has the CA certificate in its trusted CA store. 

If your client certificate is self signed, it is in effect acting as its own CA.  Depending on how the server code is written, it may or may not accept a self signed certificate. It may reject it immediately  or look for the certificate in its trusted CA store. And it may only add CA certificates (with CA attributes) to the CA trusted store.  

Using self signed certificates does not scale well if every one had to be added to the server's trusted CA store. 

In other words, using self signed certificates for web based servers is a  bad idea, and some servers will never support it. 

If you are trying to use self signed certificates for some testing, I would suggest that you  convert to using certificates signed by a CA.  Active Directory is one way, another is to use some open source CA. OpenSSL CA.pl  https://www.openssl.org/docs/manmaster/man1/CA.pl.html  (I sill use the older OpenSSL CA.sh for internal testing.) 

You can then create user and server "requests" then sign them with the demo CA. You then install the CA certificate in the server's trusted CA store.  If you have signed server certificates  install the CA certificate in the user's trusted CA store (or on the machine's trusted CA store)

**Comment by dengert** [comment]
> I also check with WireShark. Postman had 2 certificates in "Certificate, Client Key Exchange, Certificate Verify, Change Cipher Spec, Encrypted Handshake Message" packet while Firefox and Chrome had only 1 (the client cert).

IIRC With TLS The server will send its certificate, or the subject to the client, to verify the "HTTPS".
