### ISSUE TITLE
unable to select MF: File not found

### ISSUE THREAD

**Issue by luzik** [OpenSC/OpenSC#1962]
### Problem Description

Can't run opensc-explorer, nor read most listed certs stored on smart card

```
OpenSC Explorer version 0.20.0
P:7457; T:0x139699154344064 15:48:14.687 [opensc-explorer] ctx.c:852:sc_context_create: ===================================
P:7457; T:0x139699154344064 15:48:14.687 [opensc-explorer] ctx.c:853:sc_context_create: opensc version: 0.20.0
P:7457; T:0x139699154344064 15:48:14.687 [opensc-explorer] reader-pcsc.c:886:pcsc_init: PC/SC options: connect_exclusive=0 disconnect_action=0 transaction_end_action=0 reconnect_action=0 enable_pinpad=1 enable_pace=1
P:7457; T:0x139699154344064 15:48:14.687 [opensc-explorer] reader-pcsc.c:1368:pcsc_detect_readers: called
P:7457; T:0x139699154344064 15:48:14.687 [opensc-explorer] reader-pcsc.c:1381:pcsc_detect_readers: Probing PC/SC readers
P:7457; T:0x139699154344064 15:48:14.687 [opensc-explorer] reader-pcsc.c:1432:pcsc_detect_readers: Establish PC/SC context
P:7457; T:0x139699154344064 15:48:14.688 [opensc-explorer] reader-pcsc.c:1317:pcsc_add_reader: Adding new PC/SC reader 'OMNIKEY AG 3121 USB 00 00'
[..]
P:7457; T:0x139699154344064 15:48:15.301 [opensc-explorer] card.c:385:sc_connect_card: card info name:'Personal Identity Verification Card', type:14001, flags:0x0, max_send/recv_size:255/256
P:7457; T:0x139699154344064 15:48:15.301 [opensc-explorer] card.c:1521:sc_card_sm_check: called
P:7457; T:0x139699154344064 15:48:15.301 [opensc-explorer] card.c:1526:sc_card_sm_check: returning with: 0 (Success)
P:7457; T:0x139699154344064 15:48:15.301 [opensc-explorer] card.c:397:sc_connect_card: returning with: 0 (Success)
P:7457; T:0x139699154344064 15:48:15.301 [opensc-explorer] card.c:473:sc_lock: called
P:7457; T:0x139699154344064 15:48:15.301 [opensc-explorer] reader-pcsc.c:678:pcsc_lock: called
P:7457; T:0x139699154344064 15:48:15.301 [opensc-explorer] card-piv.c:3701:piv_card_reader_lock_obtained: called
P:7457; T:0x139699154344064 15:48:15.301 [opensc-explorer] card-piv.c:2696:piv_find_discovery: called
P:7457; T:0x139699154344064 15:48:15.301 [opensc-explorer] card-piv.c:878:piv_get_data: called
P:7457; T:0x139699154344064 15:48:15.301 [opensc-explorer] card-piv.c:879:piv_get_data: #10
P:7457; T:0x139699154344064 15:48:15.301 [opensc-explorer] card.c:473:sc_lock: called
P:7457; T:0x139699154344064 15:48:15.301 [opensc-explorer] card.c:513:sc_lock: returning with: 0 (Success)
P:7457; T:0x139699154344064 15:48:15.301 [opensc-explorer] card-piv.c:925:piv_get_data: buffer for #10 *buf=0x0x7ffe3ed5b180 len=256
P:7457; T:0x139699154344064 15:48:15.301 [opensc-explorer] card-piv.c:525:piv_general_io: called
P:7457; T:0x139699154344064 15:48:15.302 [opensc-explorer] card.c:473:sc_lock: called
P:7457; T:0x139699154344064 15:48:15.302 [opensc-explorer] card.c:513:sc_lock: returning with: 0 (Success)
P:7457; T:0x139699154344064 15:48:15.302 [opensc-explorer] apdu.c:546:sc_transmit_apdu: called
P:7457; T:0x139699154344064 15:48:15.302 [opensc-explorer] card.c:473:sc_lock: called
P:7457; T:0x139699154344064 15:48:15.302 [opensc-explorer] card.c:513:sc_lock: returning with: 0 (Success)
P:7457; T:0x139699154344064 15:48:15.302 [opensc-explorer] apdu.c:513:sc_transmit: called
P:7457; T:0x139699154344064 15:48:15.302 [opensc-explorer] apdu.c:363:sc_single_transmit: called
P:7457; T:0x139699154344064 15:48:15.302 [opensc-explorer] apdu.c:370:sc_single_transmit: CLA:0, INS:CB, P1:3F, P2:FF, data(3) 0x7ffe3ed5b118
P:7457; T:0x139699154344064 15:48:15.302 [opensc-explorer] reader-pcsc.c:316:pcsc_transmit: reader 'OMNIKEY AG 3121 USB 00 00'
P:7457; T:0x139699154344064 15:48:15.302 [opensc-explorer] reader-pcsc.c:317:pcsc_transmit: 
Outgoing APDU (9 bytes):
00 CB 3F FF 03 5C 01 7E 00 ..?..\.~.
P:7457; T:0x139699154344064 15:48:15.302 [opensc-explorer] reader-pcsc.c:235:pcsc_internal_transmit: called
P:7457; T:0x139699154344064 15:48:15.361 [opensc-explorer] reader-pcsc.c:326:pcsc_transmit: 
Incoming APDU (22 bytes):
7E 12 4F 0B A0 00 00 03 08 00 00 10 00 01 00 5F ~.O............_
2F 02 40 00 90 00                               /.@...
P:7457; T:0x139699154344064 15:48:15.362 [opensc-explorer] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:7457; T:0x139699154344064 15:48:15.362 [opensc-explorer] apdu.c:535:sc_transmit: returning with: 0 (Success)
P:7457; T:0x139699154344064 15:48:15.362 [opensc-explorer] card.c:523:sc_unlock: called
P:7457; T:0x139699154344064 15:48:15.362 [opensc-explorer] card.c:523:sc_unlock: called
P:7457; T:0x139699154344064 15:48:15.362 [opensc-explorer] card-piv.c:567:piv_general_io: returning with: 20
P:7457; T:0x139699154344064 15:48:15.362 [opensc-explorer] card.c:523:sc_unlock: called
P:7457; T:0x139699154344064 15:48:15.362 [opensc-explorer] card-piv.c:941:piv_get_data: returning with: 20
P:7457; T:0x139699154344064 15:48:15.362 [opensc-explorer] card-piv.c:2556:piv_parse_discovery: Discovery 0x60 0x1e 0x7ffe3ed5b182:18
P:7457; T:0x139699154344064 15:48:15.362 [opensc-explorer] card-piv.c:2581:piv_parse_discovery: returning with: 0 (Success)
P:7457; T:0x139699154344064 15:48:15.362 [opensc-explorer] card-piv.c:2715:piv_find_discovery: returning with: 0 (Success)
P:7457; T:0x139699154344064 15:48:15.362 [opensc-explorer] card-piv.c:3742:piv_card_reader_lock_obtained: returning with: 0 (Success)
P:7457; T:0x139699154344064 15:48:15.362 [opensc-explorer] card.c:513:sc_lock: returning with: 0 (Success)
P:7457; T:0x139699154344064 15:48:15.363 [opensc-explorer] card.c:817:sc_select_file: called; type=2, path=3f00
P:7457; T:0x139699154344064 15:48:15.363 [opensc-explorer] card-piv.c:2457:piv_select_file: called
P:7457; T:0x139699154344064 15:48:15.363 [opensc-explorer] card-piv.c:457:piv_find_obj_by_containerid: called
P:7457; T:0x139699154344064 15:48:15.363 [opensc-explorer] card-piv.c:458:piv_find_obj_by_containerid: str=0x3F00
P:7457; T:0x139699154344064 15:48:15.363 [opensc-explorer] card-piv.c:465:piv_find_obj_by_containerid: returning with: -1 (Unknown error)
P:7457; T:0x139699154344064 15:48:15.363 [opensc-explorer] card-piv.c:2481:piv_select_file: returning with: -1201 (File not found)
P:7457; T:0x139699154344064 15:48:15.363 [opensc-explorer] card.c:839:sc_select_file: 'SELECT' error: -1201 (File not found)
P:7457; T:0x139699154344064 15:48:15.363 [opensc-explorer] card.c:523:sc_unlock: called
P:7457; T:0x139699154344064 15:48:15.363 [opensc-explorer] reader-pcsc.c:730:pcsc_unlock: called
unable to select MF: File not found
```

**Comment by dengert** [comment]
It looks like you have a PIV card. You can not use opensc-explorer. PIV does not store its data in files, but rather in objects.  PIV is not a PKCS\#15 card, but emulates one internally.  The certs are actually stored in objects with other data and may be zipped.  

This script may help. [pivdump.sh.txt](https://github.com/OpenSC/OpenSC/files/4256759/pivdump.sh.txt)  You need to change the paths.

It uses pkcs11-tool and  pkcs15-tool to dump every thing to files in the current directory, included certificates that maybe stored offline and accessible via the PIV History object.

If all you want is the 4 certificates, you can use  `pkcs15-tool -r 01 | openssl x509 -text -noout`
where 01 can be replaced with 02, 03, 04

**Comment by dengert** [comment]
It also calls another program piv-history which is not included. If you really need this or need to see the image or decode the chuid, let me know.

**Comment by luzik** [comment]
Thanks for script. Your script is using old '-r' version, now --read-certificate. I also got those errors

```
pkcs11-tool --slot 0 --module /opt/smartcard/lib/opensc-pkcs11.so -r -y data --application-id 2.16.840.1.101.3.7.2.1.0
warning: PKCS11 function C_GetAttributeValue(VALUE) failed: rv = CKR_GENERAL_ERROR (0x5)

error: get CKA_VALUE failed

```
same for 2.16.840.1.101.3.7.2.1.2, 2.16.840.1.101.3.7.2.5.0

But there is some good things - with this git version I can see my cert for first time :) And I was able to use it with openconnect ! Thanks for your suggestions. Maybe there should be some error message about mixing PIV with opensc-explorer ?

**Comment by dengert** [comment]
I have not used the script in years.   

The PIV specifications are from  [NIST sp800-73-4](https://csrc.nist.gov/publications/detail/sp/800-73/4/final) It is used by the US federal government and others including NATO for ID cards for physical access (doors etc.) and logical access (computers and internet). Cards must pass a set of tests to be officially approved.  OpenSC can access all the objects, like Iris image, fingerprint and  photo, but does not use them. A calling PKCS11 application could use them. OpenSC really only uses the certificates and keys for logical access. PIV was designed to be an ID card (not a token) issued by government agencies after passing a security vetting process.  

The PIV spces do not include a PKCS15 file structure which is what opensc-explorer is trying to find. Other cards supported by OpenSC also to not have a PKCS15  file structure either. 

The specifications define a number of required and optional objects. They each have an OID. 
These can be found in sp800-73-4 Table 3.  2.16.840.1.101.3.7.2.1.0 , 2.16.840.1.101.3.7.2.1.2 and 2.16.840.1.101.3.7.2.5.0 are X.509 Certificate for Digital Signature, X.509 Certificate for Key Management and X.509 Certificate for Card Authentication respectively. 

So your one certificate (and matching key) must be the mandatory X.509 Certificate for PIV Authentication with OID 2.16.840.1.101.3.7.2.1.1. The certificate object contain more then the certificate. The PIV driver extracts the certificate from the object unzips it if needed, extracts the public key from the certificate and presents via PKCS15 and PKCS11 the certificate, public key and private key.  

Only the X.509 Certificate for Digital Signature and its key enforce the "PIN Always" policy so in your case #1966 is not an issue. It could be if you add that certificate and key. 

Other card vendors and open source developers have found the PIV attractive partly because Windows has a builtin PIV driver, thus they do not need additional software on Windows and partly because the specifications are well written. So these vendors have written their own PIV applets  installed on token and/or cards and written additional  applications to let the user administer the devices.  These are not officially approved devices, have minor differences from the specs and missing mandatory objects, additional features and some bugs too.  OpenSC tries to accommodate these devices as best it can.

**Comment by luzik** [comment]
Those information are not easy to find. Thank you very much for clarification.
