### ISSUE TITLE
Opensc 0.20.1.4 and FF ver. 74

### ISSUE THREAD

**Issue by Counter178** [OpenSC/OpenSC#2032]
Not sure if related to https://github.com/OpenSC/OpenSC/issues/1999 or not. Symptoms are a little bit different. 

The testing was made with the new latest OpenSC 0.20.1.4 and FF 74. 
- Firefox "not responding" but didn't close itself
- Every tab, what is being made brings up "not responding" response

Some things, what we're noticed:
1. Delay because of the smart card?
```
Outgoing APDU (4 bytes):
00 A4 00 0C ....
P:2124; T:2460 2020-05-08 16:05:34.100 [onepin-opensc-pkcs11] reader-pcsc.c:242:pcsc_internal_transmit: called
```
2. Interesting error codes

`P:2124; T:2460 2020-05-08 16:05:29.600 [onepin-opensc-pkcs11] OMNIKEY CardMan 1021 0:SCardTransmit/Control failed: 0x0000045d`

```
ERROR_IO_DEVICE
1117 (0x45D)
The request could not be performed because of an I/O device error.
```

3. Problem is starting near:

```
P:2124; T:2460 2020-05-08 15:55:52.950 [onepin-opensc-pkcs11] reader-pcsc.c:324:pcsc_transmit: 
Outgoing APDU (4 bytes):
00 A4 00 0C ....
P:2124; T:2460 2020-05-08 15:55:52.950 [onepin-opensc-pkcs11] reader-pcsc.c:242:pcsc_internal_transmit: called
P:2124; T:2460 2020-05-08 15:55:57.059 [onepin-opensc-pkcs11] OMNIKEY CardMan 1021 0:SCardTransmit/Control failed: 0x0000045d
```
Added log file in attachment. Hope something comes up.

[opensc-debug.txt](https://github.com/OpenSC/OpenSC/files/4608904/opensc-debug.txt)

**Comment by dengert** [comment]
The dump shows 2 readers, and 3 applications running.  P:2124 looks like Firefox, not sure what P:8366 is
```
$ grep "^P:" opensc-debug-2032.txt | sort | uniq -w 15 -c
   1249 P:2124; T:11140 2020-05-08 15:59:43.249 [onepin-opensc-pkcs11] C_GetSlotList(token=0, plug-n-play)
     30 P:2124; T:11308 2020-05-08 16:04:36.034 [onepin-opensc-pkcs11] C_GetSlotList(token=0, plug-n-play)
     30 P:2124; T:11856 2020-05-08 16:03:27.783 [onepin-opensc-pkcs11] C_GetSlotList(token=0, plug-n-play)
    277 P:2124; T:11960 2020-05-08 16:02:48.861 [onepin-opensc-pkcs11] C_GetSlotList(token=0, plug-n-play)
     68 P:2124; T:11976 2020-05-08 16:01:47.298 [onepin-opensc-pkcs11] C_GetSlotList(token=0, plug-n-play)
    387 P:2124; T:12008 2020-05-08 16:03:27.549 [onepin-opensc-pkcs11] C_GetSlotList(token=0, plug-n-play)
    374 P:2124; T:12188 2020-05-08 16:02:23.501 [onepin-opensc-pkcs11] C_GetSlotList(token=0, plug-n-play)
     90 P:2124; T:12808 2020-05-08 16:05:15.663 [onepin-opensc-pkcs11] C_GetSlotList(token=0, plug-n-play)
     30 P:2124; T:12820 2020-05-08 16:05:15.881 [onepin-opensc-pkcs11] C_GetSlotList(token=0, plug-n-play)
   5036 P:2124; T:2460 2020-05-08 15:54:57.981 [onepin-opensc-pkcs11] Alcor Micro USB Smart Card Reader 0: Detecting smart card
     30 P:2124; T:2692 2020-05-08 16:04:36.096 [onepin-opensc-pkcs11] C_GetSlotList(token=0, plug-n-play)
   2909 P:2124; T:2720 2020-05-08 15:54:54.559 [onepin-opensc-pkcs11] ===================================
   4257 P:2124; T:5172 2020-05-08 15:55:01.731 [onepin-opensc-pkcs11] Alcor Micro USB Smart Card Reader 0 check
     45 P:2124; T:6708 2020-05-08 15:55:02.402 [onepin-opensc-pkcs11] C_GetSessionInfo(hSession:0xd0c73c20)
     45 P:2124; T:8200 2020-05-08 15:55:01.121 [onepin-opensc-pkcs11] card.c:473:sc_lock: called
     30 P:2124; T:8548 2020-05-08 15:58:54.639 [onepin-opensc-pkcs11] C_GetSlotList(token=0, plug-n-play)
    360 P:2124; T:9352 2020-05-08 15:54:58.449 [onepin-opensc-pkcs11] C_GetSlotList(token=0, plug-n-play)
    593 P:2124; T:9688 2020-05-08 15:54:59.996 [onepin-opensc-pkcs11] C_GetSlotList(token=0, plug-n-play)
    270 P:2124; T:9692 2020-05-08 15:55:00.152 [onepin-opensc-pkcs11] C_GetSlotList(token=0, plug-n-play)
    417 P:2124; T:9696 2020-05-08 15:55:00.231 [onepin-opensc-pkcs11] C_GetSlotList(token=0, plug-n-play)
      1 P:2124; T:9696P:2124; T:2720 2020-05-08 15:55:00.559 2020-05-08 15:55:00.559 [ [onepin-opensc-pkcs11onepin-opensc-pkcs11] ] Alcor Micro USB Smart Card Reader 0 checkC_Initialize(): Cryptoki already initialized
     30 P:2124; T:9708 2020-05-08 15:55:00.481 [onepin-opensc-pkcs11] C_GetSlotList(token=0, plug-n-play)
    345 P:7036; T:7680 2020-05-08 15:53:37.080 [opensc-notify] ===================================
    882 P:8336; T:8328 2020-05-08 15:53:36.424 [opensc-pkcs11] ===================================
```
Without Firefox running, does this card work with `pkcs11-tool --test --login` This maybe a real card error. 

What OS are you running on?

Where did you get OpenSC 0.20.1.4? 

 It looks like two threads from process p:2124 T:9696 and T:2720 are both in C_Initialize. Although, locking is setup by C_Initialize, so this maybe OK, because one treaded returns Cryptoki already initialized.

P:2124; T:9696P:2124; T:2720 2020-05-08 15:55:00.559 2020-05-08 15:55:00.559 [ [onepin-opensc-pkcs11onepin-opensc-pkcs11] ] Alcor Micro USB Smart Card Reader 0 checkC_Initialize(): Cryptoki already initialized

**Comment by Counter178** [comment]
The "pkcs11-tool --test --login" works just fine on Windows 10. 
OpenSC 0.20.1.4 : 
797414be05220fa371972606d7a6c2e94dd6d8db from master + version number change + Franks log addition: https://ci.appveyor.com/project/metsma/opensc/builds/32708408/job/h2u1gs1qf72xvyie/artifacts

**Comment by frankmorgner** [comment]
FYI: The error is no SCARD-Error, but maybe
[ERROR_IO_DEVICE: "The request could not be performed because of an I/O device error."](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--1000-1299-)

**Comment by SQ-SEN** [comment]
I just tried to check that but I'm unable to add the onepin module to Firefox 76.0.1 (Windows 10). The regular works but I can't use that as I will get flooded with PIN requests. Did you do something special to add the module? I'm using OpenSC 0.20.0.

**Comment by frankmorgner** [comment]
Firefox blocks the library due to too many errors. We need a new version with fixes...

**Comment by Jakuje** [comment]
> Firefox blocks the library due to too many errors. We need a new version with fixes...

Do you have some reference where Firefox blocks the OpenSC library? I did not find any.

**Comment by metsma** [comment]
https://github.com/mozilla/gecko-dev/commit/4d14cf5024c65ab3b9d3c20fe80531244d0d25ad

**Comment by Jakuje** [comment]
Thank you for clarification. So it is strictly related to Firefox on Windows.

**Comment by dengert** [comment]
Is it also only related to a specific card? i.e. card-esteid2018.c?

Could be a FF error (or something new)  which exposes a locking error. The following looks like two or more threads are actively trying to use the same PCSC session C_Initialize?
line 3334:
P:2124; T:2720 2020-05-08 15:54:57.527 [onepin-opensc-pkcs11] C_Initialize() = CKR_OK

lines 4246-4248
P:2124; T:9696P:2124; T:2720 2020-05-08 15:55:00.559 2020-05-08 15:55:00.559 [ [onepin-opensc-pkcs11onepin-opensc-pkcs11] ] Alcor Micro USB Smart Card Reader 0 checkC_Initialize(): Cryptoki already initialized

P:2124; T:2720 2020-05-08 15:55:00.559 [onepin-opensc-pkcs11] C_Initialize(): Cryptoki already initialized

**Comment by metsma** [comment]
> Is it also only related to a specific card? i.e. card-esteid2018.c

and card-mcrd.c

**Comment by dengert** [comment]
First of two comments:

From the one debug log, it looks like FireFox is calling  C_Initialize from two seperate threads in same process. That appears to be strange, and maybe something new in FireFox. I know they switched from providing the 
CK_C_INITIALIZE_ARGS fields CreateMutex, DestroyMutex, LockMutex, UnlockMutex pointing at routines provided by FireFox, to having these set to NULL, and flag CKF_OS_LOCKING_OK. 

PKCS\#11 2.40 Does not say the C_Initialize should not be called from two different threads, but does talk
about it being called from different processes. 

Here is what could be happening. I would hope other developers could have a look at this too.

- pkcs11-global.c: C_Initialize is called and does:
- if (context != NULL) { 
            sc_log(context... 
             return CKR_CRYPTOKI_ALREADY_INITIALIZED;
  } 
- `sc_pkcs11_init_lock` sets up locking. 
- sc_context_create 
- load_pkcs11_parameters
- card_detect_all

`sc_pkcs11_init_lock` does: `if (global_lock)    return CKR_OK;` 

But the above **does not use the locks**, and so two threads could get into creating a context, 
or further.  `sc_context_create` does a lot of stuff before doing `*ctx_out = ctx;` at the end and does
not expect 2 threads could be active in this code at the same time, and could overwrite one context
with another while `card_detect_all` is active. 

So this could be a source of the reader list changing size, because the reader list is in the context, that
could be replaced. 

I am not very good with locking, mutex, semaphore and critical sections but this does not look correct. 
Maybe a static mutex or Windows  critical section?

Comments or suggestions?

---------------------------------------------------------------------
Second comment:

Is there any reason to believe other cards are affected? 

For example, does everyone in Estonia has one of these cards and is required to use it for some government website and must uses FireFox? So we would see failures with these cards more than others? 

On Windows, can they use EDGE with minidriver to get to the same sites? 

I believe I have only seen one debug log, the one above. Are there others available?

**Comment by metsma** [comment]
> Second comment:

> Is there any reason to believe other cards are affected?

From user comments, some cannot use Firefox when module is enabled. It does not matter if card is inserted or not.
It crashes or hangs when they start the browser.
We suspected that there are also integrated 3g/4g modems with sim cards. #1847

> For example, does everyone in Estonia has one of these cards and is required to use it for some government website and must uses FireFox? So we would see failures with these cards more than others?

Everyone in Estonia has such card and many public and private services use EID cards. There is no requirement for Firefox but we have big install base (roughly 1m installs and 95% are windows)

> On Windows, can they use EDGE with minidriver to get to the same sites?

Yes, Edge/Chrome/IE uses minidriver with same sites

> I believe I have only seen one debug log, the one above. Are there others available?

It's hard to reproduce and even harder to get logs from user. We can see crash reports at Mozilla bugzilla.

**Comment by dengert** [comment]
@metsma  Are you still seeing this problem? Latest Firefox version is 83.0 The failure was with 74.0

**Comment by metsma** [comment]
Seems to be fixed. There are still some crashesh but they have not update still module.
https://crash-stats.mozilla.org/search/?signature=~onepin&date=%3E%3D2020-11-26T18%3A50%3A00.000Z&date=%3C2020-12-03T18%3A50%3A00.000Z&_facets=signature&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature
