### ISSUE TITLE
Private Token Object access policy

### ISSUE THREAD

**Issue by johughes99** [OpenSC/OpenSC#2119]
I have been comprehensively testing a wide range of PKCS#11 USB tokens over the last 12 months - and have come across something strange about the handling of private token objects - which I don't quite understand.  This seems to impact two OpenSC based devices - including NitroKey HSM2.

The processing is as follows

- Logon as a user
- populate the token with a range of different private token objects. In this case two EC key pairs, two RSA key pairs and two data objects.  For each object CKA_TOKEN is set as true and CKA_PRIVATE is set as true (hence they are all "private token" objects). The key pairs are generated by C_GenerateKeyPair
- Logout as user - hence no authenticated user now exists
- using C_FindObject* attempt to find different object types for private tokens, public tokens, private sessions, public sessions.  A separate call to C_FindObject* is made for each combination

In all the other devices I have tested no objects should be found - as I have created private tokens.  You need to be logged on to find them.

But in the case of OpenSC it finds the EC and RSA public keys (at least it didn't find the private keys!).  However, it didn't find the private token data objects.

When it does find the private token public keys - it reports them as being public token objects.

Is this a design feature - in that when you create a private token public key OpenSC overides this and makes them a public token object?

I have attached two log files

the first is the output from my tool so you can get an overview of the processing and the calls made to PKCS#11

the second is the opensc.log with level=9. The key lines are:

- C_Login called at line 3
- C_generatekeyPair for the first EC key pair is on lines 8 to 26
- C_Logout occurs on line 3563
- C_FIndObject* find 4 matching objects around line 3965 when looking for public token public keys

[2020-09-23-List Objects.log](https://github.com/OpenSC/OpenSC/files/5281900/2020-09-23-List.Objects.log)
[opensc.log](https://github.com/OpenSC/OpenSC/files/5281902/opensc.log)

**Comment by dengert** [comment]
"Is this a design feature - in that when you create a private token public key OpenSC overides this and makes them a public token object?"  This may not be a design feature, but an oversite, or not supported by the token. Are you also intending to have certificates that will be marked CKA_PRIVATE?   99.9% of the time certificates are public, and also contain the public key, and on some cards the public key is not store on the token as separate object, but recovered from the certificate.  

It may also depend on the token. The token has access rules, which are then mapped to pkcs\#15 flags, that
are then mapped to PKCS\#11 flags. It may be the token is assuming public keys are not private. So the CKA_PRIVATE may get lost because the token does not store it directly. 

PKCS\#11 v2.40 says: "CKA_PRIVATE - CK_BOOL  -  CK_TRUE  if object is a private object; CK_FALSE if object is a public object. Default value is token-specific, and may depend on the values of other attributes of the object. 

So this maybe token-specific, or was never implemented for public keys.


Suggest you look at framework-pkcs15.c, and also look at how the key is generated.

**Comment by johughes99** [comment]
I will have a look at framework-pkcs15.c and get back on what I find

I understand about default values - but I was explicit in defining the value of CKA_PRIVATE in the template for both the private and public key.

And to re-interate this occurs in two of the OpenSC tokens I'm testing.  I also have a 3rd OpenSc based token - but that doesn't support loading of keys via PKCS#11.

**Comment by frankmorgner** [comment]
I think SC-HSM (which is behind NitroKey HSM2) [populates the flag CKA_PRIVATE as SC_PKCS15_CO_FLAG_PRIVATE to card objects](https://github.com/OpenSC/OpenSC/blob/b577531720cf1ec1e82c44cbae6d7fc23866e269/src/pkcs15init/pkcs15-sc-hsm.c#L392-L417), but not to public key objects. That's why, when read out again, the public key will be public, but the card object will be protected.

I'm pretty sure sc-hsm would be able to protect the public key from reading without authentication, but that's just not implemented in OpenSC. (By the way, this is really the kind of protection you want. This should not be done by the PKCS#11 module on its own.)

However, you're not reinitializing the library, which means that the PKCS#11 layer should still contain the CKA_PRIVATE flag for the public key...

@CardContact , would you mind to comment?

**Comment by frankmorgner** [comment]
public keys, CA certificates and user certificates are stored in an object range that is *always readable* (first byte of FID is `0xCA` or `oxCE`). So call it "token specific" behavior, but SC-HSM cannot protect public key objects with user authentication.

Theoretically it would be possible to store those objects in an object range that is *PIN protected* (first byte of FID would be `0xCD`). However, that would require modifications at multiple layers of OpenSC and the resulting profile would not be compatible anymore with sc-hsm-embedded (https://github.com/CardContact/sc-hsm-embedded) and the vendor supplied SmartCard-HSM SDK.

**Comment by frankmorgner** [comment]
In general, it is very well possible in OpenSC to generate a key pair and marking the public key as private, but it depends it on the actual card driver if this feature has been implemented (or, as seen above, if it is possible to be implemented at all).
