### ISSUE TITLE
Creating RSA Private Keys with C_CreateObject

### ISSUE THREAD

**Issue by johughes99** [OpenSC/OpenSC#2128]
I have a number of tests using C_CreateObject to create many different types of objects -ie data, private/public RSA, public/private EC keys for different object types

I have an issue when trying to create a RSA private key - i get a CKR_TEMPLATE_INCOMPLETE error - and this occurs on 2 different devices I'm testing.  Attached is the debug output log extracted for when the call is made

Drilling into the source I can see framework-pkcs15.c. (if I'm reading the code correctly) expects that parameters p and q are also required to be supplied.  Although in 2.40 of PKCS#11 only n, e and d are mandatory. 

All the other devices I have tested don't require p and q. 

Is this the expected behavior?  And is there anyway of changing opensc so you don't have to supply p and q?

[temp.log](https://github.com/OpenSC/OpenSC/files/5323526/temp.log)

**Comment by dengert** [comment]
Yes it can be changed. Even pkcs\#11 V2.20 says "Tokens vary in what they actually store for RSA private keys. Some tokens store all of the above attributes, which can assist in performing rapid RSA computations. Other tokens might store only the CKA_MODULUS and CKA_PRIVATE_EXPONENT values." 

PKCS\#15 v1.1  6.3.2 Private RSA key objects shows the ASN.1 and all are optional. and has similar comments on the minimum requirements,  

The framework-pkcs15.c should require only CKA_MODULUS and CKA_PRIVATE_EXPONENT, and treat the others as optional.  

The line numbers in you log do not match what is in master. 
But you could look at  framework-pkcs15.c line 2225, yours says line 2238
                 if (!rsa->modulus.len || !rsa->exponent.len || !rsa->d.len || !rsa->p.len || !rsa->q.len) {
and change to:
                 if (!rsa->modulus.len || !rsa->exponent.len || !rsa->d.len) {

Then lower levels  starting with pkcs15init/pkcs15-lib.c  sc_pkcs15init_store_private_key which calls
calls prkey_fixup_rsa which also tests for !rsa->p.len || !rsa->q.len. 

This is where you will need to add extra code as it tries to create all the missing attributes  because some card drivers need them. So you need to look at which cards you are using, and maybe add a  switch(card->type) 
or add a flag  to card that says it does not need p and q, so it can skip the fixup. 

Note any change you make can affect other card drivers.

**Comment by johughes99** [comment]
i understand all that - although I'm more use to version 2.40 (and some bits of 3.0)

My current plan is to test lots of different PKCS#11 devices - including softHSM - to find out if there are any weaknesses/faults.  Currently I have 12 devices from different vendors - but only 2 are using OpenSC.   I just came across this "issue" recently so I thought I would raise it - in case anyone else does.  None of the other tokens I'm testing that support RSA had this problem

as my focus is testing devices - I'm not inclined to have a go to try and fix this:-) - although I think it would be useful to add

I was using version 0.20.0 - i haven't download anything later than this (as yet)

**Comment by dengert** [comment]
My point about version 2.20 was the issue of different tokens was know back in 2004. 

Using PKCS\#11 to test what attributes a token really needs, does not account for PKCS\#11 and card drivers filling in missing attributes. So you are not testing the token, but the combination of the middleware and hardware. 

The OpenSC "prkey_fixup_rsa" tries to fill in missing attributes. This also applies to OpenSC as well as any vendor's PKCS\#11.  You could look at what attributes are sent to the token by looking in vendor documentation, 
or the OpenSC card drivers, as I would suspect the attributes sent are needed by the card.  

I am not interested in making any changes in this area. You could add this as wish list item.




 Someone else might, or it can be added to wishlist.

**Comment by johughes99** [comment]
I total understand I'm testing the middleware - and the hardware - and that's the point.

So if I find that both my OpenSC devices have the same issue - it sort of points to a middleware issue (although not necessarily 100%). And assuming its not covered in the OpenSC documentations - then, if you don't mind, i will raise it in this forum. (then at least its in the "corporate memory")

It would be rare if something as detailed as this would be covered in the vendor's documentation (assuming any specific PKCS#11 documentation exists!)
