### ISSUE TITLE
Implement Windows CNG KSP

### ISSUE THREAD

**Issue by elipsion** [OpenSC/OpenSC#2147]
As a user, I would like to leverage the expanded capabilities of a full KSP, instead of the Minidriver subset.

The documentation for writing a KSP can be found on Microsoft's [CNG Portal](https://docs.microsoft.com/en-us/windows/win32/seccng/cng-portal).

**Comment by elipsion** [comment]
The features that I'm personally interested in are:
* Exposing the `exportable` flag
* Listing existing keys

My end goal is having a plug-and-play experience for [MS ADCS CA](https://docs.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/server-certs/install-the-certification-authority), which I think would be a huge milestone for the community.

**Comment by frankmorgner** [comment]
We are happy about every contribution...

**Comment by dengert** [comment]
Be aware that some internal Microsoft code has not supported the the full KSP when used with smart  cards. For example:
https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps

This long discussion might help: https://github.com/OpenSC/OpenSC/issues/1763
 says:  "I see that it is very much possible ADCS will never work using SC-HSM or with OpenSC in general because of reasons only Microsoft can tell us."

[install-the-certification-authority](https://docs.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/server-certs/install-the-certification-authority)  says:

"On the Cryptography for CA page, keep the default settings for CSP (RSA#Microsoft Software Key Storage Provider) and hash algorithm (SHA2), and determine the best key character length for your deployment. Large key character lengths provide optimal security; however, they can impact server performance and might not be compatible with legacy applications. It is recommended that you keep the default setting of 2048."

**Comment by elipsion** [comment]
> Be aware that some internal Microsoft code has not supported the the full KSP when used with smart cards. For example:
> https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps

That's only partially true. There is a, in my opinion, bug in the MS Smart Card KSP where the key export options are not passed down to the minidriver, but instead rejected if set to something other than `XCN_NCRYPT_ALLOW_EXPORT_NONE`, see [#2088](https://github.com/OpenSC/OpenSC/issues/2088#issuecomment-670534742)

> This long discussion might help: #1763
> says: "I see that it is very much possible ADCS will never work using SC-HSM or with OpenSC in general because of reasons only Microsoft can tell us."

I have successfully, but with a non-user friendly amount of hassle, initialized and issued certificates from ADCS backed by SC-HSM. The method does however not support the use of `CAPolicy.inf`, so it has limited practical use.

> [install-the-certification-authority](https://docs.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/server-certs/install-the-certification-authority) says:
> "On the Cryptography for CA page, keep the default settings for CSP (RSA#Microsoft Software Key Storage Provider) and hash algorithm (SHA2), and determine the best key character length for your deployment. Large key character lengths provide optimal security; however, they can impact server performance and might not be compatible with legacy applications. It is recommended that you keep the default setting of 2048."

That documentation is specifically for deployment of 802.1X. Do instead have a look at the docs for [ADCS CA](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/hh831574(v=ws.11)) and [Install-AdcsCertificationAuthority](https://docs.microsoft.com/en-us/powershell/module/adcsdeployment/install-adcscertificationauthority?view=win10-ps#description)

**Comment by martonsz85** [comment]
> I have successfully, but with a non-user friendly amount of hassle, initialized and issued certificates from ADCS backed by SC-HSM. 
How did you manage to set up ADCS to use SC-HSM? I’ve been struggling with it for a few months now, but I can’t seem to figure it out.

**Comment by elipsion** [comment]
> How did you manage to set up ADCS to use SC-HSM? I’ve been struggling with it for a few months now, but I can’t seem to figure it out.

I used `New-SelfSignedCertificate -KeyExportPolicy NonExportable -Reader $cardreader` along with whatever options was desired to create a self-signed certificate for the CA root, which was then installed using `Install-AdcsCertificationAuthority -CertificateID $selfsigned.Serial`.

In the end we settled on using XCA on Windows for the Root and Policy CA, and ADCS without SC-HSM for the Issuing CA.

For us this was the sweet spot between security and convenience; we don't have to keep any SC hardware attached in our datacenter, and we don't need to lug around a 20 year old Windows instance for the aging Root. In the event of a security breach of our Issuing CA we can bring the Policy CA online to revoke the possibly stolen keys without too much hassle.
