### ISSUE TITLE
pkcs11-tool '--login' option always tries to create a read/write session

### ISSUE THREAD

**Issue by smuehlst** [OpenSC/OpenSC#2182]
### Problem Description

When the `--login` option is specified for `pkcs11-tool`, it always sets the the flag `CKF_RW_SESSION` in the `flags` parameter for the `C_OpenSession` call:

https://github.com/OpenSC/OpenSC/blob/f8af905574a55036f7c8e079188992be10ceb73e/src/tools/pkcs11-tool.c#L731-L734
https://github.com/OpenSC/OpenSC/blob/f8af905574a55036f7c8e079188992be10ceb73e/src/tools/pkcs11-tool.c#L1076-L1085

Because of this behavior it is impossible to login into a write-protected token. The concrete use case is to list all objects on a write-protected token including PKCS#11 private objects (having attribute `CKA_PRIVATE` set to `CK_TRUE`), which are visible only after authenticating to the token.

### Proposed Resolution

The presence of the `--login` option on the command line of `pkcs11-tool` should not automatically trigger the creation of a read/write session. A PKCS#11 session is needed but a read-write session isn't required per se. For example signing and listing of objects is allowed in read-only sessions.

### Steps to reproduce

```
$ pkcs11-tool --module <path to PKCS#11 library> -O --login
Using slot 0 with a present token (0x3e8)
error: PKCS11 function C_OpenSession failed: rv = CKR_TOKEN_WRITE_PROTECTED (0xe2)
Aborting.
```

**Comment by dengert** [comment]
PKCS11 v2.40 says: "If the token is write-protected (as indicated in the CK_TOKEN_INFO structure), then only read-only sessions may be opened with it."

Many if not all of the command line options to pkcs11-tool  will set `need_session` to `NEED_SESSION_RW` or `NEED_SESSION_RO` It looks like  line 732 should be `if (need_session & NEED_SESSION_RO)` and maybe around line 1079, pkcs11-tool could also look at the  `CK_TOKEN_INFO` for `CKF_WRITE_PROTECTED` and do one of these:
1. produce error,
2. let pkcs11 module return an error
3.  use `CKF_RW_SESSION` if token is not `CKF_WRITE_PROTECTED` 

line 732 has been that way since 2002-12-17,  If we go with 2.  we will need a review of the options to make sure `need_session` is set correctly. 

Are you testing using the OpenSC module or some other module(s)?

Do you want to create a Pull Request?

**Comment by smuehlst** [comment]
> PKCS11 v2.40 says: "If the token is write-protected (as indicated in the CK_TOKEN_INFO structure), then only read-only sessions may be opened with it."
> 
> Many if not all of the command line options to pkcs11-tool will set `need_session` to `NEED_SESSION_RW` or `NEED_SESSION_RO` It looks like line 732 should be `if (need_session & NEED_SESSION_RO)` and maybe around line 1079, pkcs11-tool could also look at the `CK_TOKEN_INFO` for `CKF_WRITE_PROTECTED` and do one of these:
> 
> 1. produce error,
> 2. let pkcs11 module return an error
> 3. use `CKF_RW_SESSION` if token is not `CKF_WRITE_PROTECTED`
> 
> line 732 has been that way since 2002-12-17, If we go with 2. we will need a review of the options to make sure `need_session` is set correctly.

I think line 732 should be

```
need_session |= NEED_SESSION_RO;
```

What also looks suspicious is the option for signing:

https://github.com/OpenSC/OpenSC/blob/f8af905574a55036f7c8e079188992be10ceb73e/src/tools/pkcs11-tool.c#L767-L769

Signing does not require a PKCS#11 read/write session.
  
> Are you testing using the OpenSC module or some other module(s)?

I came across this when I tested with a D-TRUST signature card with a PKCS#11 module from the Nexus Personal software.

> Do you want to create a Pull Request?

Yes, I can create a pull request.

**Comment by dengert** [comment]
https://github.com/OpenSC/OpenSC/blob/f8af905574a55036f7c8e079188992be10ceb73e/src/tools/pkcs11-tool.c#L778 for C_Decrypt also looks wrong. 

But pkcs1-tool may stop working for some existing modules. We should add a --session {RW|RO} option so a user can force the session to be RO or RW.

**Comment by mouse07410** [comment]
I see no benefit in adding "read-only" session.

In any case, it should be only enabled by an explicit flag (maybe `--session=RO`).

**Comment by smuehlst** [comment]
> I see no benefit in adding "read-only" session.

The benefit is that it would be possible to login into write-protected tokens with pkcs11-tool.

**Comment by mouse07410** [comment]
> The benefit is that it would be possible to login into write-protected tokens with `pkcs11-tool`.

What is a "write-protected token"? Could you name a few, and tell who issues them?

I have govt-issued tokens that I certainly can't write to, that work perfectly well with `pkcs11-tool`...

Regardless, I do not mind adding this - but would object against making it the default.

**Comment by dengert** [comment]
I would call a gov issued token "write protected" as the users who use OpenSC don't have the the keys or documentation on how to write to the token. or to say it in another way, its write protected because OpenSC pkcs11 does not have the code to allow updates by its opensc-pkcs11 module.

**Comment by smuehlst** [comment]
> What is a "write-protected token"? Could you name a few, and tell who issues them?

A write-protected token according to the PKCS#11 spec indicates this status via the flag `CKF_WRITE_PROTECTED` in the `flags` member of the `CK_TOKEN_INFO` structure:

http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/errata01/os/pkcs11-base-v2.40-errata01-os-complete.html#_Toc441755750

```
Table 6, Token Information Flags
...
CKF_WRITE_PROTECTED ... True if the token is write-protected (see below)
...
Exactly what the CKF_WRITE_PROTECTED flag means is not specified in Cryptoki.  An application may be unable to perform certain actions on a write-protected token; these actions can include any of the following, among others:

·         Creating/modifying/deleting any object on the token.
·         Creating/modifying/deleting a token object on the token.
·         Changing the SO’s PIN.
·         Changing the normal user’s PIN."
```

At the moment I can name only one token, a "D-TRUST multicard 100 3.0 qualifed" signature card from the German Bundesdruckerei. This is the one where I did run into this problem recently.

This is the PKCS#11 spy output when I try to call `pkcs11-tool ... -O --login` for this card:

```
*************** OpenSC PKCS#11 spy *****************
Loaded: "/Applications/Personal.app/Contents/PlugIns/CSPBundleNexus.bundle/Contents/Frameworks/tokenapi.framework/Versions/A/tokenapi"

0: C_GetFunctionList
2020-12-11 09:01:42.450
Returned:  0 CKR_OK

1: C_Initialize
2020-12-11 09:01:42.451
[in] pInitArgs = 0x0
Returned:  0 CKR_OK

2: C_GetInfo
2020-12-11 09:01:42.458
[out] pInfo: 
      cryptokiVersion:         2.20
      manufacturerID:         'Nexus                           '
      flags:                   0
      libraryDescription:     'Personal NG PKCS 11             '
      libraryVersion:          1.1
Returned:  0 CKR_OK

3: C_GetSlotList
2020-12-11 09:01:42.458
[in] tokenPresent = 0x0
[out] pSlotList: 
Count is 3
[out] *pulCount = 0x3
Returned:  0 CKR_OK

4: C_GetSlotList
2020-12-11 09:01:43.229
[in] tokenPresent = 0x0
[out] pSlotList: 
Slot 1000
Slot 0
Slot 1
[out] *pulCount = 0x3
Returned:  0 CKR_OK

5: C_GetSlotInfo
2020-12-11 09:01:43.229
[in] slotID = 0x3e8
[out] pInfo: 
      slotDescription:        'Crypto Token Reader             '
                              '                                '
      manufacturerID:         'Technology Nexus AB             '
      hardwareVersion:         4.0
      firmwareVersion:         4.0
      flags:                   1
        CKF_TOKEN_PRESENT                
Returned:  0 CKR_OK

6: C_OpenSession
2020-12-11 09:01:43.229
[in] slotID = 0x3e8
[in] flags = 0x6
pApplication=0x0
Notify=0x0
[out] *phSession = 0x1
Returned:  226 CKR_TOKEN_WRITE_PROTECTED

7: C_Finalize
2020-12-11 09:01:43.229
Returned:  0 CKR_OK
```

**Comment by frankmorgner** [comment]
We could make `--login` more flexible requesting the least protected session. This would mean that we would have to determine whether a RW or an RO session is required depending on the command line flags. This would be an acceptable solution, however, I'm not sure whether someone finds time to implement this.

An simpler alternative solution would be to add a new commandline switch (e.g. `--list-private-objects`), which *automatically* loggs into a RO session without `--login`.

**Comment by dengert** [comment]
The code  already does try and set NEED_SESSION_RW or NEED_SESSION_RO for every command switch, but:
--login sets `need_session |= NEED_SESSION_RW;` It has been there sine 2002
--pin sets `need_session |= NEED_SESSION_RW;` 
--sign sets `need_session |= NEED_SESSION_RW;`
--decrypt sets `need_session |= NEED_SESSION_RW;`

This discussion brings up a subtle problem we may have in pkcs11-tool and in OpenSC Pkcs11 module.

Pkcs11-tool does not support  CKS_RO_USER_FUNCTIONS.  These are R/O sessions where the user has logged in.

Reading between the lines in PKCS11 docs,  some crypto operations C_Sign, C_Decrypt can return CKR_USER_NOT_LOGGED_IN but never return  CKR_SESSION_READ_ONLY. i.e. They do not modify the token and can use a RO session, so don't need to return 
CKR_SESSION_READ_ONLY

C_DeriveKey and C_GenerateKey can return CKR_SESSION_READ_ONLY and/or CKR_USER_NOT_LOGGED_IN because the derived or generated key may be stored on the token. i.e. CKA_TOKEN = CK_FALSE if object is a session object.  "Only session objects can be created during a read-only session. Only public objects can be created unless the normal user is logged in."

Possible solution:
We could set the four lines above to  need_session |= NEED_SESSION_RO; 
and add a `--session-rw` to force NEED_SESSION_RW  just incase we missed something. This would also allow for testing any pkcs11 module to see if they behave correctly. 

Also `opt_login` is only set with --login, --pin, or do_sign || do_decrypt and CKF_LOGIN_REQUIRED. So these are forcing NEED_SESSION_RW.

**Comment by ulrichb** [comment]
(Continuation of the discussion of #2576.)

I have exactly the same issue with our (not yet published) [SignPath](https://about.signpath.io/) PKCS#11 implementation. This is also a "write-protected token" (`C_OpenSession()` immediately returns `CKR_TOKEN_WRITE_PROTECTED` in case of `CKF_RW_SESSION`) because the PKCS#11 interface basically only allows signing, all management (modifications) happens within the "back  end".

Still we require an authenticated session (`C_Login()`), and this is where the `NEED_SESSION_RW` for `--login` bites us.

I've prepared a PR for this ...
