### ISSUE TITLE
EF.ATR ASN1 parsing error/2F01

### ISSUE THREAD

**Issue by vjardin** [OpenSC/OpenSC#2220]
### Problem Description

When the EF.ATR object is:
```
    OpenSC [3F00]> cat 2F01
    00000000: 80 43 01 B8 46 04 04 B0 EC C1 47 03 94 01 80 4F .C..F.....G....O
    00000010: 08 80 25 00 00 01 FF 01 00 E0 10 02 02 01 04 02 ..%.............
    00000020: 02 01 04 02 02 01 00 02 02 01 00 78 08 06 06 2B ...........x...+
    00000030: 81 22 F8 78 02 82 02 90 00                      .".x.....
```

it is not properly parsed because sc_asn1_find_tag() from sc_parse_ef_atr_content() seems to assume that 0x43 is not a tag (ISO7816_TAG_II_CARD_SERVICE).

### Proposed Resolution

pre-Pad 1 byte

### Steps to reproduce

ASN1-parse the provided EF.ATR object.

**Comment by frankmorgner** [comment]
I've again read ISO 7816-4 carefully with regard to EF.ATR.

>12.2.2 EF.ATR/INFO
This EF indicates operating characteristics of the card. It contains a set of interindustry DOs which cannot be
nested in EF.DIR, either because not relevant to application selection, or because there is no EF.DIR.


>12.1.1.2 Structure and COMPACT - TLV data objects
The first historical byte is the “category indicator byte”. If the category indicator byte is set to '00' or '8X', then
Table 114 summarizes the format of the historical bytes. Any other value indicates a proprietary format.
If the first historical byte is set to:
 '00' the remaining historical bytes shall consist of optional consecutive COMPACT - TLV data objects followed
by a mandatory status indicator (see 12.1.1.11).
 '80' the remaining historical bytes shall consist of optional consecutive COMPACT - TLV data objects; the last
one may carry a status indicator in COMPACT - TLV format (see 12.1.1.11).
Any interindustry DO consisting of a tag field set to '4X', a length field set to '0Y' and a value field of Y bytes
can be converted into a COMPACT - TLV data object consisting of a byte set to 'XY' called “compact header” and
a value field of Y bytes.
Any interindustry data element defined hereafter (see 12.1.1.3 to 12.1.1.10) may be present in EF.ATR/INFO
(see 12.2.2). If present in EF.ATR/INFO, it shall appear in a DO, i.e. a tag field set to '4X', a length field set to
'0Y' and a value field of Y bytes.

Hence, the category indicator (`08`) should only be part of the card's ATR, but it should not be part of EF.ATR. I think that the issuer of your card doesn't respect the standard in this regard.

To work around this, I would suggest you do the following:
- In opensc-explorer specify an offset of 1 when parsing 2F01, i.e. `asn1 2F01 1`
- change ef-atr.c to support an optional category indicator before parsing the data as ASN.1. Please add a comment why you add this exception. Please also have in mind that there also might be an optional indicator at the end!

**Comment by vjardin** [comment]
Thanks @frankmorgner for the analysis. I hope I applied properly your guidelines. Your feedbacks are welcomed.

**Comment by frankmorgner** [comment]
I've made an inline comment.

ideally, you avoid modifying opensc-explorer.c. have you tried the suggested command `asn1 2F01 1`?

**Comment by vjardin** [comment]
Yes, we can avoid patching `opensc-explorer.c` in order to get the following:
```
./opensc-explorer -r 0
OpenSC Explorer version 0.21.0
OpenSC [3F00]> asn1 2F01 1
43 Application 3  (1 byte): decode error: B8 .
46 Application 6  (4 bytes): decode error: 04 B0 EC C1 ....
47 Application 7  (3 bytes): 94 01 80 ...
4F Application 15 (8 bytes): 80 25 00 00 01 FF 01 00 .%......
E0 Private 0  (16 bytes)
   02 INTEGER (2 bytes): 260
   02 INTEGER (2 bytes): 260
   02 INTEGER (2 bytes): 256
   02 INTEGER (2 bytes): 256
78 Application 24 (8 bytes)
   06 OBJECT IDENTIFIER (6 bytes):  1.3.162.15480.2
82 Context 2  (2 bytes): 36864: 90 00 ..
```
but I am concern about a user that would not be aware of the need to skip the first byte `0x80`. I do not have a long history with OpenSC. I thought it would be a better option to make it easy for users, but from your feedbacks, if you believe we should avoid any specific workaround within `opensc-explorer.c`, I'll be fine with dropping this patch in order to use `asn1 2F01 1`. I do not know if my concerns is valid.

**Comment by frankmorgner** [comment]
all tools are not meant to be for end users. we can assume some context knowledge from someone who wants to parse 2F01...

**Comment by vjardin** [comment]
Based on @frankmorgner 's comments, the commit 064746c includes both: a support for both legacy users that do not provide any offset and a support for the advance users that supply an offset.

**Comment by vjardin** [comment]
merged => closed.
