### ISSUE TITLE
Can't generate new key on Yubikey 4

### ISSUE THREAD

**Issue by nickrbogdanov** [OpenSC/OpenSC#2236]
With opensc 0.20.0-3:

```
# pkcs11-tool --keygen --id 02
Using slot 0 with a present token (0x0)
error: PKCS11 function C_GenerateKey failed: rv = CKR_FUNCTION_NOT_SUPPORTED (0x54)
Aborting.
```

Works fine with `yubico-piv-tool -a generate` but then I have to have my own logic map the PIV slot number to the OpenSC ID.

**Comment by Jakuje** [comment]
The PIV standard does not define the key generation and writing objects and it is left up to the vendors. This is the reason why opensc says CKR_FUNCTION_NOT_SUPPORTED. But given we have already several tweaks for yubikey, we can detect them quite reliably and we might consider implementing this inside of opensc. This would allow users to drop one more dependency when working with yubikeys or some other cards with PIV applet. I was made aware that there are couple of more similars out there, but the shipment did not arrive yet.

**Comment by dengert** [comment]
As stated above, NIST  left it up to vendors to provision PIV cards. And the cards are not expected to be provisioned by users but by organizations with a certificate management system. PIV is very popular because Microsoft provides a built in windows driver. 

So use your vendor's tool. 

The OpenSC piv-tool can do some provisioning but was designed to be used during development, not a a general tool. It and most other cards require some 3DES or AES key to be used to authenticate to the card. 

"But given we have already several tweaks for yubikey" more like many non-compliant issues/bugs.
