### ISSUE TITLE
Problems when p11-kit loads both opensc-pkcs11.so and onepin-opensc-pkcs11.so in p11-kit 

### ISSUE THREAD

**Issue by dengert** [OpenSC/OpenSC#2307]
### Problem Description
Problems when p11-kit loads both  opensc-pkcs11.so and onepin-opensc-pkcs11.so see:
https://github.com/OpenSC/libp11/issues/399

### Proposed Resolutions

- Obviously Don't load both.
- Build these as "modules" t make sure they are self contained. 
OpenSSL uses  loader options: -Wl,-z,defs -Wl,-znodelete -shared -Wl,-Bsymbolic
OpenSC does not do anything special for "modules" 

- If they can tell there is more then one loaded, they could take advantage of this. 
OpenSC can handle only one applet on a card at at time. If p11-kit or the modules can tell there are multiple OpenSC modules  loaded by P11-kit, each could handle one type of applet. for example PIV and CAC on same card, or PIV and OpenPGP on on another. 
 
### Steps to reproduce

See: https://github.com/OpenSC/libp11/issues/399
### Logs

See: https://github.com/OpenSC/libp11/issues/399

**Comment by frankmorgner** [comment]
On Windows and macOS, where the system doesn't provide us usable libraries, we're linking everything statically. On Linux and other Unixes the whole system typically uses the same version of OpenSSL so that name clashes should not be a problem.

Maybe I didn't read that other thread carefully enough, but what exactly is the problem you're seeing that should not be there. If I understand it correctly, then only the object identification wasn't clear, because that same object was provided by both versions of OpenSC. I think that's an expected behavior if we're using deterministic names. Beyond that, I don't see any conflicts between both modules, do you?

**Comment by dengert** [comment]
The problem I see is too many slot numbers, unless p11-kit's  `p11-kit-trust.so` takes up 16 slots. The following are for the two OpenSC modules.   
[17] Alcor Micro AU9540 00 00   login             (Siemens Corporate ID Card (V8))
[18] Alcor Micro AU9540 00 00   login             (Siemens Corpor... (Extra PIN #1))
[19] Alcor Micro AU9540 00 00   login             (Siemens Corpor... (Extra PIN #0))
[20] Alcor Micro AU9540 00 00   login             (Siemens Corporate ID Card (V8))

The sc-pkcs11.h defines   `extern struct sc_context *context` I am not sure if this is shared or each module has it own version. It may depend on the linker options.  

With OpenSSL 3.0.0 in alpha testing, it won't be long before it is released. I don't think we should depend on all modules or applications using the same version of OpenSSL. 

 p11-kit and PAM use modules, and many years ago I ran in to a module problem with Kerberos, and the solution there was to use `-Bsymbolic` and other options. OpenSSL-3.0.0  links all its shared libs, and engine modules like this:
`cc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O0 -g -g -L. -Wl,-znodelete -shared -Wl,-Bsymbolic  -Wl,--enable-new-dtags,-rpath=/opt/o     ssl-3.0.0/lib -Wl,-soname=libssl.so.3 \
        -o libssl.so.3 -Wl,--version-script=libssl.ld \
` followed by the object files.  This is system dependent, but it should help avoid issues. 

I marked this as a wish list. If someone is interested in looking into it.

**Comment by frankmorgner** [comment]
>[17] Alcor Micro AU9540 00 00 login (Siemens Corporate ID Card (V8))
[18] Alcor Micro AU9540 00 00 login (Siemens Corpor... (Extra PIN #1))
[19] Alcor Micro AU9540 00 00 login (Siemens Corpor... (Extra PIN #0))
[20] Alcor Micro AU9540 00 00 login (Siemens Corporate ID Card (V8))

It looks like the first 3 slots (17-19) are coming from `opensc-pkcs11.so`, the last one (20) is coming from `onepin-opensc-pkcs11.so` and the rest is truncated due to some internal limit to the maximum number of slots in libp11. This is supported by the fact that `pkcs11-tool` lists exactly the said 3 slots when fed with only `opensc-pkcs11.so`. You could argue that the limit in libp11 should be raised, but that's beyond our PKCS#11 module.

>The sc-pkcs11.h defines extern struct sc_context *context I am not sure if this is shared or each module has it own version. It may depend on the linker options.

since this symbol is not listed in `pkcs11.exports`, it will not be exported.

>p11-kit and PAM use modules, and many years ago I ran in to a module problem with Kerberos, and the solution there was to use -Bsymbolic and other options

As said above, I fully agree, that this may be a problem in few situations. The standard case is, however, to have one single version of OpenSSL on the system, that's used in every program or library on the system.

A distribution may choose to provide different flags for OpenSSL and the other dependencies to avoid potential clashes. Unfortunately, this means that OpenSC will have to be recompiled when there is an update of the said dependency. It's up to the distribution to decide how they want to compile OpenSC and which trade-off they want to make.

Additionally, you could argue that it is possible to have two different version of OpenSC with two different libopensc.so libraries, which may clash at runtime. This, too, is not a problem, because we're providing versioning information (`-version-info`) along with every symbol of the library so that multiple versions of libopensc can be loaded at runtime.

**Comment by henning-schild** [comment]
This reminds me of https://github.com/OpenSC/OpenSC/issues/2060

If the two modules must not be loaded at the same time, they should mutually exclude each other and issue a warning on double-load. Configuration errors where both get loaded can not be prevented so they need to be dealt with, ideally in a way that is just a warning.

Configuration can be coming in snippets out of packages, in the nss-browser case it can be coming from the autoconfig magic (pkcs11-register), legacy manual configuration or https://fedoraproject.org/wiki/Changes/NSSLoadP11KitModules

So i think duplicate and conflict detection should be a central feature of opensc. You can hardly align users, application maintainers and distro maintainers to prevent them.

**Comment by frankmorgner** [comment]
> So i think duplicate and conflict detection should be a central feature of opensc. You can hardly align users, application maintainers and distro maintainers to prevent them.

Sounds like a good feature. Any ideas on implementing that?

**Comment by frankmorgner** [comment]
@dengert , any further comments on the problems you see? [From my point of view](https://github.com/OpenSC/OpenSC/issues/2307#issuecomment-825562411), we have a) a limitation of libp11 and b) two opensc modules which work happily even though being loaded by a single process...

**Comment by dengert** [comment]
The "limitation of libp11" was new, commit [85a91f4502](https://github.com/OpenSC/libp11/commit/85a91f4502d48371df0d392d19cecfbced2388c0) solved a different problem, of un under specified URI for a key or cert. 

it looks like opensc-pkcs11.so and onepin-opensc-pkcs11.so will produce the same set of attributes supported by  [rfc7512](https://tools.ietf.org/html/rfc7512) except for slot-id, but the slot-id is assigned by p11-kit and may change depending on what readers and cards are inserted, making it unpredictable it be used in a URI. 

The three attributes in RFS 7512:
```
 pk11-lib-manuf       = "library-manufacturer" "=" *pk11-pchar
 pk11-lib-desc        = "library-description" "=" *pk11-pchar
 pk11-lib-ver         = "library-version" "=" 1*DIGIT [ "." 1*DIGIT ]
```
produce the same strings:
```
Manufacturer    OpenSC Project
Library               OpenSC smartcard framework (ver 0.22)
```
for opensc-pkcs11.so and onepin-opensc-pkcs11.so

The argument could be made that they should be different. One could also argue that p11-kit should also spot that two modules have the same Manufacturer and Library and version. I suspect it checks the name of the module for duplicates. I don't know of any other PKCS11 that might have this problem. 

We could add "onepin" into one of the attributes but this may cause some people problems with the attributes changing in scripts.   

Mozilla NSS might have a similar problem if both are loaded. 

The user closed the https://github.com/OpenSC/libp11/issues/399 once they looked at the modules loaded. 
So this may not be a big problem.

I don't know how the two modules could tell that that a second copy is also loaded or they are loaded via p11-kit. And it might depend on the OS.   

I line in the man page to say don't used both may be needed.

**Comment by henning-schild** [comment]
> Sounds like a good feature. Any ideas on implementing that?

dlopen has " __attribute__((constructor))" and also "__attribute__((destructor))" that can potentially be used to allocate some ressource that is uniqe to the two opensc libs, where the second one would maybe refuse to dlopen or open as a dummy

if they had the same symbols, you maybe could not load both, or the last loaded would always win ... do not know all that dlopen stuff by heart or how that is used by opensc

Not sure whether having both loaded is ever meaningful ... having both loaded in a browser leads to many PIN requests ... last time i checked.

Maybe a more fundamental question ... do we need two or can opensc just go to one module that does it all, maybe with a config file or an ENV variable to control the difference in the two modules ... per application loading it .

**Comment by henning-schild** [comment]
I never understood what the diff is between the two. Maybe they can be stacked ... so that loading "onepin" pulls in "normal" and just assign a global variable "opensc_onepin = 1" or something along those lines ... again only of having both at a time is for sure not something anyone would want

**Comment by vjardin** [comment]
+1: why can't it be a runtime (setenv(), config file, etc.) option ?

**Comment by frankmorgner** [comment]
the split into two modules is due to some applications that cannot properly handle multiple PINs (i.e. Firefox being the most prominent example). We can already configure this via opensc.conf. For this to be configured at runtime, we would have to detect those applications reliably on all platforms... However, even if we were able to eliminate the onepin module, OpenSC may still be loaded multiple times by the same process.

OK, we are circling around one problem: One loads OpenSC multiple times, one sees the slots multiple times. From the functional point of view everything is working correctly in these modules. Do you see any other problems?

**Comment by dengert** [comment]
Yes, the problem was introduced by OpenSC to solve a problem with FireFox. In so doing we introduced the problem of the user **accidentally** loading the same module under 2 different names. 
But now p11-kit can also **accidentally** load both modules. And libp11 now flags this as an error. 

This was also discussed e-mail thread from @Jakuje in 2016:
http://opensc.1086184.n5.nabble.com/OpenSC-onepin-td15850.html

So for now I would say it is a user error to configure any pkcs11 application to use both libraries at the same time and close the issue but leave on wishlist at low priority.

**Comment by Jakuje** [comment]
I second that this is a user error. We already added check into the modutil in RHEL/Fedora to warn users from adding modules directly there. Adding them to p11-kit is much easier and recommended, but they were adding stuff to modutil for years so it can be still found in some outdated guides. In p11-kit, we would need some runtime check to drop one of "duplicate" modules, which might cause some issues or unexpected behavior (which one would be dropped?). But it might be worth filling at least an issue in the p11-kit ...

**Comment by henning-schild** [comment]
I see no reason to close this and make it a user-problem. Exactly these problems are bound to happen and they do happen in practice. So again a "central" detection would be nice and can most likely be implemented in some way.

One module loads and allocs a central ressource, a symbol name, a pid-file, a global variable ... the second one detects that and loads-as-dummy-doing-nothing, takes over, warns ... or even fails to load.

**Comment by henning-schild** [comment]
just found this in my thunderbird `pkcs11.txt`

```
library=/usr/lib64/pkcs11/onepin-opensc-pkcs11.so
name=OpenSC smartcard framework (0.21)
library=/usr/lib64/opensc-pkcs11.so
name=OpenSC smartcard framework (0.22)
```

`pkcs11-register` is seriously broken! Since i am failing to get that solved here i will push for removal in gentoo linux again, sad that upstream does not care. I think fedora has it patched out as well.

**Comment by Jakuje** [comment]
> just found this in my thunderbird `pkcs11.txt`
> 
> ```
> library=/usr/lib64/pkcs11/onepin-opensc-pkcs11.so
> name=OpenSC smartcard framework (0.21)
> library=/usr/lib64/opensc-pkcs11.so
> name=OpenSC smartcard framework (0.22)
> ```
> 
> `pkcs11-register` is seriously broken! Since i am failing to get that solved here i will push for removal in gentoo linux again, sad that upstream does not care. I think fedora has it patched out as well.

If this is was caused by `pkcs11-register`, please open a new issue describing how that happens so we can handle this. This issue is related, but not about the `pkcs11-register`. If the `pkcs11-register` creates such pkcs11.txt files, its certainly something to fix, but we can probably not fix when the application will try to load opensc twice.

Also, the OS integration is the package maintainer responsibility. We can not handle builds and integration in all different operating systems and linux distros. If you believe the gentoo should not use the `pkcs11-register` or use `p11-kit`, please, open an issue in the gentoo issue tracker. We do not have any influence whats gets pulled in there and how is it integrated in the operating system and how it is tested.

**Comment by henning-schild** [comment]
`pkcs11-register` is broken by design. It writes files it is clearly not allowed to, the only tools allowed are the browsers or `modutil`. It writes them at the worst point in time ... on every session start. Say you install ubuntu, a browser and later opensc ... now you use that browser to load `onepin-opensc-pkcs11.so` because the magic did not yet happen. Your next reboot will have a nice surprise coming your way.
No duplicate detection because of symlinks #2060 no conflict detection between `onepin-opensc-pkcs11.so` and `opensc-pkcs11.so` (there is an issue but i am too lazy).

After that reboot/session restart you will be spammed with pin entry dialogues popping up all over the place. And you probably would not assume that some magic tried to mess with your config behind your back ... so you will not even look at those `pkcs11.txt` files .. likely you will not know they even exist and could be the problem. Because all you did was configure your thunderbird, firefox and chrome for opensc ... in the session you had when you set things up. And only days/weeks later you will reboot for any reason and nothing will work as it was before.

Now we could ask distros to stop shipping the magic, like many already do. Or we could ask them to put a "sudo reboot" into postinst. Or we could stop the magic and find a proper solution, happening at the right time, using the right tools.

redhat/fedora have that already. A snippet in a .d folder in etc https://github.com/OpenSC/OpenSC/issues/2060#issuecomment-723252416. Others do not have that yet, including i.e. gentoo. But i doubt opensc inventing hacks can help.

`pkcs11-register` deserves being removed from the codebase or off by default, any distro needing autoloading should use whatever redhat uses, or something similar ... the library magically loading/configuring itself is very wrong ... at least in my book

**Comment by henning-schild** [comment]
I will address all that in gentoo again, and am kind of confident gentoo will patch it out ... like redhat does since forever. But i would rather like to see it solved upstream, to reduce maint load on those distros and benefit distros who did not yet see the issues coming from their user-base and might eventually also end up patching.

**Comment by frankmorgner** [comment]
Regarding pkcs11-register, I've created #2212 . But technically speaking, I don't see the problem of this issue.

what exactly is the confusion with pkcs11-opensc and pkcs11-opensc-onepin being loaded at the same time? obviously, it lists tokens certs and keys twice. over at https://github.com/OpenSC/libp11/issues/399 it has been said that libp11 errors when finding the same key twice... this is something that could be improved by libp11, but it doesn't show any sign of the two opensc modules clashing.

Also it has been said that a PIN doesn't need to be verified in one module if it has been verified in the other module. This is also expected; we are providing the `atomic` option to avoid this. It is disabled by default, because we don't consider this to be easily exploitable.

It has been said that there is a problem with some context shared between both modules, what exactly is meant with this?

What other problems do you see?

**Comment by henning-schild** [comment]
It has been a long time since i opened this so i do not remember and simply have avoided adding both. Issues i remember from the past are "having to enter the PIN multiple times" or higher level applications like firefox, thunderbird, or chrome getting confused after all.

**Comment by frankmorgner** [comment]
Thanks for the feedback, will close this issue when #2681 is merged
