### ISSUE TITLE
Problems with Alcor Micro 9560 external usb reader and chip cards

### ISSUE THREAD

**Issue by iandstanley** [OpenSC/OpenSC#2336]
### Problem Description

Problems recognising either reader or card correctly.

I am assuming that either opensc isn't talking to the reader properly or it doesn't recognise the card / isn't compatible with the card (Yarongtech - smart card type SLE4442)

### Steps to reproduce
Plug in 

1. Plugin AU9560 external usb reader
2. insert Yarongtech smart card 
3. opensc-tool --serial

OUTPUT = 

$ **opensc-tool --serial
Using reader with a card: Alcor Micro AU9560 00 00
Failed to connect to card: Unresponsive card (correctly inserted?)**

This seems to be the response irrespective of which way card is inserted or 

$ **lsusb**
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 045e:00cb Microsoft Corp. Basic Optical Mouse v2.0
Bus 001 Device 003: ID 045e:07f8 Microsoft Corp. Wired Keyboard 600 (model 1576)
**Bus 001 Device 012: ID 058f:9540 Alcor Micro Corp. AU9540 Smartcard Reader**

### Logs

Full debug log @level 3 for --list-readers and --serial commands :

 [https://gist.github.com/iandstanley/a9bfaea421cd33e99b4c34acbde72d21](https://gist.github.com/iandstanley/a9bfaea421cd33e99b4c34acbde72d21)

**Comment by popovec** [comment]
SLE4442 seems to be a  EEPROM card, out of OpenSC scope. This card does not appear to be sending a normal ATR. Without information from the ATR, the card reader really declare this card as unresponsive.

**Comment by iandstanley** [comment]
what types of inexpensive cards should I be looking for 

I'm trying to program an X.509 cert into them for use with https://github.com/joyent/pivy#zfs-encryption which takes a single PIV slot (slot 9e if memory serves me right) .... so a full blown PIV card maybe over the top and probably a lot more expensive .

**Comment by popovec** [comment]
https://github.com/OpenSC/OpenSC/wiki/Frequently-Asked-Questions#where-can-i-buy-smart-cards-

inexpensive, but you need make it:
https://nx3d.org/gnuk-st-link-v2/
or look at OsEID card (based on AVR128DA32 MCU) ..

**Comment by dengert** [comment]
And as pointed out this is out of scope for OpenSC. None of this used OpenSC.  

The https://github.com/joyent/pivy suggests:
"PIV cards" notably includes Yubico Yubikey devices such as the NEO and Yubikey4, which can store up to 24 keys by using the "retired key" slots (which this agent supports)."

They have a simplified PIV tool and it looks like the ZFS will only work with a PIV like card.  OpenSC is not involved as best I can tell. 

Keep in mind that if you are going to encrypt you file system, make sure you have a backup copy of the encryption key some where else.

Looks like thy chose the 9E key, because on PIV it does not require the use of a PIN, as its intent is for the card to authenticate itself to devices like a door lock. So if anyone gets their hands on the PIV card, they have the key to you file system and maybe its backups.
