### ISSUE TITLE
Unable to Read File

### ISSUE THREAD

**Issue by sbouter-idsoftware** [OpenSC/OpenSC#2338]
### Problem Description
When issuing the following command:
piv-tool -A A:9B:08 -O 3000 -i file.dat

I receive this error message:
unable to read file C:\Users\Administrator\Downloads\chuid.dat

This only happens occasionally, and breaking it down there is a card uuid provided, which in this example is "17c81a9157db42bdb40d6bd1b4f90582", and when changing just that to another functional card, e.g. "455e0a85e1da4570a05a7237c49f6d0c" I have no problem.

### Proposed Resolution
Provide more details as what "unable to read file" means, and if there's a way to detect if certain data is not acceptable by your tool.
[file.zip](https://github.com/OpenSC/OpenSC/files/6468990/file.zip)

### Steps to reproduce
Using the 0.20 tools (required by security) and issuing the command in the description.

**Comment by dengert** [comment]
piv-tool.c when run on windows needs "rb" for fopen to avoid Windows changing line ending characters. 
Your bad uuid has "0d" which appears to be changed to two characters, and thus what is read does not match the expected length in outer TLV. (piv-tool is not used much and very rarely on Windows. The bug has been there since 2005.) 

#2339 has a fix. when the test builds are done you can find windows MSI  files for testing by clicking on "Show All Tests" then in "continuous-integration/appveyor/pr" line click on "Details". For this run this would lead to  

 https://ci.appveyor.com/project/LudovicRousseau/opensc/builds/39140543

This should show 8 jobs. by clicking on one of them, then on "artifacts" you can find MSI files.

**Comment by sbouter-idsoftware** [comment]
Thanks very much for the quick response. I’ll take a look in the morning! -Sam
________________________________
