### ISSUE TITLE
Some certs not imported from smartcard

### ISSUE THREAD

**Issue by silvermangb** [OpenSC/OpenSC#2365]
With OpenSC on Windows 10, some cert are not imported from a smart card.

1. Using PIVKEY smartcard, see pivkey.zendesk.com and taglio.com. Have OpenSC installed.
2. Inserted PIVKEY in card reader. The test cert that comes with the PIVKEY is imported to Firefox cert store.
3. Used this command to load a pfx file on the smartcard, certutil -v -csp "Microsoft Base Smart Card Crypto Provider" -p <password> -importpfx <pfx file>
4. Verified both certs are imported the Windows 10 certificate store with the Windows 10 MMC snap-in. Also, verified that both certs are in the Edge & Chrome cert stores.
5. Verified that only one certificate, the default that came with the card, was loaded into Firefox.

**Comment by dengert** [comment]
Writing to the smartcard is not supported via certutil, with the OpenSC minidriver, at least not for PIV cards. 
The NIST PIV standards leave it up to the card vendor on how to manage the keys, certs and objects on the card.
OpenSC piv-tool only supports a small subset of possible ways to do this. 

By default, the OpenSC minidriver is not enabled for PIV cards, because every PIV vendor provides a minidriver, or uses the Windows minidriver which treats the PIV card as read only. 

Your smartcard vendor says: https://pivkey.zendesk.com/hc/en-us/articles/204519385-Loading-a-certificate-and-keys-using-Certutil

Which says: "Important: The PIVKey minidriver must be installed to load or delete certificates from the PIVKey. (without the PIVKey minidriver, the PIVKey will be read-only).'

Also see:
https://pivkey.zendesk.com/hc/en-us/articles/203126729-PIVKey-Deployment-Overview
https://pivkey.zendesk.com/hc/en-us/articles/203129059-PIVKey-User-Installer
And the zip file with minidriver

Use regedit to see what smartcard derivers are installed:

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards\`
The ATR of the card is matched to one of these entries. Note that you may have to uninstall the certificates in the Microsoft certificate store. Ask your vendor if you have problems.

**Comment by frankmorgner** [comment]
As far as I can see, this is a problem of MS's implementation of a PIV driver, if not, please re-open this issue.
