### ISSUE TITLE
Italian CNS (aka TNS) ST2021: CKR_GENERAL_ERROR

### ISSUE THREAD

**Issue by gdeber** [OpenSC/OpenSC#2370]
### Problem Description

My brand new Italian service card ST2021 is not working as authentication mechanism. pkcs11-tool fails with CKR_GENERAL_ERROR.
pkcs11-tool fails with unsupported CLA byte in APDU.

### Steps to reproduce

1. insert card into gemalto USB reader
2. run pkcs11-tools -l -t 
3. insert pin

### Logs
```
/ # OPENSC_DEBUG=6 pkcs11-tool -l -t
...
P:22; T:0x140253314501960 07:33:48.998 [opensc-pkcs11] iso7816.c:128:iso7816_check_sw: Class not supported
P:22; T:0x140253314501960 07:33:48.998 [opensc-pkcs11] card.c:523:sc_unlock: called
P:22; T:0x140253314501960 07:33:48.998 [opensc-pkcs11] iso7816.c:1011:iso7816_decipher: APDU transmit failed: -1203 (Unsupported CLA byte in APDU)
P:22; T:0x140253314501960 07:33:48.998 [opensc-pkcs11] sec.c:47:sc_decipher: returning with: -1203 (Unsupported CLA byte in APDU)
P:22; T:0x140253314501960 07:33:48.998 [opensc-pkcs11] card.c:523:sc_unlock: called
P:22; T:0x140253314501960 07:33:48.998 [opensc-pkcs11] pkcs15-sec.c:285:sc_pkcs15_decipher: use_key() failed: -1203 (Unsupported CLA byte in APDU)
P:22; T:0x140253314501960 07:33:48.998 [opensc-pkcs11] pkcs15-sec.c:620:sc_pkcs15_compute_signature: returning with: -1203 (Unsupported CLA byte in APDU)
...
```

Thankyou all.

**Comment by dengert** [comment]
As you say: "brand new Italian service card ST2021" they may have changed something, like new card or version of the applet on the card or even gone to requiring some type of Secure Messaging to protect the response of the deciphered response. `(iso7816.c:1011:iso7816_decipher: APDU transmit failed: -1203 (Unsupported CLA byte in APDU)` 

Does the card work with the government supplied software? 

We need to see more of the debug log.  (but not your pin) This should include the card matching which ends with a line like: `card.c:XXX:sc_connect_card: matched: XXXXXXX`
and at least outgoing APDU and the response.

**Comment by gdeber** [comment]
Hi dengert.
It's a "brand new" for me because my last one expired. I don't know when this type of card was introduced.
anyway...

this is the output using gov. library (no DEBUG output at all):

```
#> OPENSC_DEBUG=6 pkcs11-tool --module ./libstpkcs11.so -l -t
Using slot 0 with a present token (0x1)
Logging in to "CNS".
Please enter User PIN: 
C_SeedRandom() and C_GenerateRandom():
  seems to be OK
Digests: not implemented
Signatures (currently only for RSA)
  testing key 0 (CNS0) 
warning: PKCS11 function C_GetAttributeValue(ALWAYS_AUTHENTICATE) failed: rv = CKR_ATTRIBUTE_TYPE_INVALID (0x12)

warning: PKCS11 function C_GetAttributeValue(ALWAYS_AUTHENTICATE) failed: rv = CKR_ATTRIBUTE_TYPE_INVALID (0x12)

  all 4 signature functions seem to work
warning: PKCS11 function C_GetAttributeValue(ALWAYS_AUTHENTICATE) failed: rv = CKR_ATTRIBUTE_TYPE_INVALID (0x12)

  testing signature mechanisms:
warning: PKCS11 function C_GetAttributeValue(ALWAYS_AUTHENTICATE) failed: rv = CKR_ATTRIBUTE_TYPE_INVALID (0x12)

error: PKCS11 function C_Sign failed: rv = CKR_DATA_LEN_RANGE (0x21)
Aborting.
    RSA-X-509:
```

please see attached debug file edited to remove personal information. Let me know if I edited soo much. 

Thankyou.
[debug.edited.log](https://github.com/OpenSC/OpenSC/files/6891876/debug.edited.log)

**Comment by dengert** [comment]
Your card appears to support a 2048 bit RSA key:
`framework-pkcs15.c:4069:pkcs15_prkey_sign: Selected flags 1. Now computing signature for 256 bytes. 1024 bytes reserved.`

The card driver only supports 1024 byte keys:   https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-itacns.c#L222 and does not set the 
SC_CARD_CAP_APDU_EXT to indicate card can support  extended APDU, so OpenSC tries to use command chaining. 

From the debug log, the APDU `10 2A 80 86 FF ...` is sending  command chaining - 0x10  and sending the first 255 bytes 0xFF but card does not support, command chaining. The reader can support extended APDUs and since the card does not support command chaining so it must support extended APDUs.

So the card driver needs to be updated for these newer cards. I do not have such a card, so some developer who does needs to get involved. That could be YOU https://github.com/gdeber if you want to get involved and submit a PR. 

There may be other changes that are also needed. 

About the pkcs11-tool warnings/error:
The gov libstpkcs11.so does not understand the ALWAYS_AUTHENTICATE, as it does not need to support keys that require it. These warnings can be ignored. 

Not sure about: `error: PKCS11 function C_Sign failed: rv = CKR_DATA_LEN_RANGE (0x21)` It could be libstpkcs11.so does not like siglen being set to 1024, which should be large enough. PKCS11 says the  buffer can be any size if large enough to contain the signature. The module will then return actual length in siglen.  
https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L5253-L5257

So this is a protocol bug in libstpkcs11.so. 

pkcs11-tool could be modified to catch this and set the size to match expected response.

**Comment by dengert** [comment]
This may be a possible fix. As I said I don't have a way to test it.
[untested-card-itacns.c-issue-2370.txt](https://github.com/OpenSC/OpenSC/files/6893762/untested-card-itacns.c-issue-2370.txt)

**Comment by gdeber** [comment]
> That could be YOU https://github.com/gdeber if you want to get involved and submit a PR.
Starting from your patch, I tried to fix key an modulus length in both card-itacns.c and pkcs15-itacns.c. 
pkcs11-tool returns no error (I tried also with my previous cns card). Is this enough to submit a PR? Should I do some other tests?

**Comment by dengert** [comment]
If you got it to work with old and new card submit a PR so others can look at your changes.

**Comment by mouse07410** [comment]
One important point that Doug's making is: do not kill the old card by adding support for the new one. Make sure both work.

**Comment by dengert** [comment]
Also see if you can find newer documentation. Both card-itacns.c and pkcs15-itacns.c have URLs for some older documentation. See if you can find newer versions that match the version 1.1. With out these we do not know what else there is in version 1.1. It may even support RSA > 2048 bit keys and/or EC keys. 

Compare your new and old cards by running `pkcs11-tool -O --login`, `pkcs15-tool --dump` with other options and any other tools. This might help identify differences.

**Comment by gdeber** [comment]
> One important point that Doug's making is: do not kill the old card by adding support for the new one. Make sure both work.

That's why I tried with my new one (ST2021) and my old one (AC 2014).
You can find  APDU spec here -> https://www.agid.gov.it/it/piattaforme/carta-nazionale-servizi

PR: #2371

**Comment by sacarde** [comment]
here on kubuntu-18.04  (card chip ST2021) with:

opensc                            0.17.0-3
opensc-pkcs11:amd64   0.17.0-3

when I run: pkcs11-tool -t -l

error: PKCS11 function C_SignFinal failed: rv = CKR_GENERAL_ERROR (0x5)

is there a solution?

**Comment by Jakuje** [comment]
can you try with the current opensc master. 0.17.0 is almost 5 years old.

**Comment by sacarde** [comment]
it is simpler to compile it on ubuntu-18.04 or to install in a system where it is newer


thanks

**Comment by Jakuje** [comment]
The fix from #2371 is not yet in any released version so I would suggest to rebuild opensc yourself. There are steps in wiki:

https://github.com/OpenSC/OpenSC/wiki/Compiling-and-Installing-on-Unix-flavors

Just use the git clone instead of building from tarballs.

**Comment by sacarde** [comment]
ok, thanks a lot

**Comment by resoli** [comment]
Tested as well and working. For the details see (italian) https://www.freelists.org/post/linuxtrent/nuova-Tessera-Sanitaria-aiuto,31
