### ISSUE TITLE
Support packaging as a MacOS/iOS Framework

### ISSUE THREAD

**Issue by minfrin** [OpenSC/OpenSC#2437]
### Problem Description

OpenSC is packaged for MacOS as a DMG, containing a package.

Ideally the DMG also needs OpenSC packaged as a MacOS/iOS framework in order to be used easily in MacOS and iOS apps.

### Proposed Resolution

Modify the MacOSX/build-package.in script to package the library as a framework.

It appears that the following command should in theory package the library and headers, although I am not sure which library should be used.

```
xcodebuild -create-xcframework
```

**Comment by frankmorgner** [comment]
Other projects can easily integrate the C code or the libraries directly, as done in [OpenSCToken](https://github.com/frankmorgner/OpenSCToken), for example.

If I understand correctly, this eases integration for an developers. Since none of the maintainers uses this type of interface, it should be hard to maintain in the long run. That's why, for apps and programs, I would use the standard APIs PKCS#11, CryptoAPI and CTK to use cryptographic tokens supported by OpenSC.
