### ISSUE TITLE
pkcs11-register: Honour Firefox's integration of OS client certificates

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#2446]
### Problem Description

Firefox added integration of OS specific client certificates in version [72](https://www.mozilla.org/en-US/firefox/72.0/releasenotes/)/[75](https://www.mozilla.org/en-US/firefox/75.0/releasenotes/). This feature [was enabled by default](https://blog.mozilla.org/security/2021/07/28/making-client-certificates-available-by-default-in-firefox-90/) in version [90](https://www.mozilla.org/en-US/firefox/90.0/releasenotes/). Mozilla obviously [noticed OpenSC's `pkcs11-register`](https://blog.mozilla.org/security/2020/04/14/expanding-client-certificates-in-firefox-75/) and still seems to recommend it for Linux.

Since pkcs11-register is executed by default on Windows/macOS startup it may be possible to see an OpenSC token twice in Firefox, i.e. via registering onepin-opensc-pkcs11 and via minidriver/CTK through osclientcerts. The tool should detect [osclientcerts](https://github.com/mozkeeler/osclientcerts/) and avoid this behavior.

There are some open questions:
- Will Linux be supported by libosclientcerts?
- How does osclientcerts deals with tokens that have multiple PINs (historically, Fireofox' support has been bad, which is why we only expose authentication keys/certificates in the onepin module)?
- How should osclientcerts be detected?

Maybe @mozkeeler or @staktrace could share some thoughts...

**Comment by staktrace** [comment]
Sorry my knowledge of this is very limited. My involvement in the client certs stuff was limited to one small patch to fix a specific issue.

**Comment by frankmorgner** [comment]
> Sorry my knowledge of this is very limited. My involvement in the client certs stuff was limited to one small patch to fix a specific issue.

Thanks for the feedback

**Comment by mozkeeler** [comment]
> - Will Linux be supported by libosclientcerts?

Eventually I want some sort of "automatic" solution for Firefox to be able to use client certificates on Linux, but it's not clear what that will be yet.

> - How does osclientcerts deals with tokens that have multiple PINs (historically, Fireofox' support has been bad, which is why we only expose authentication keys/certificates in the onepin module)?

osclientcerts leaves all the details of PINs to the OS (that is, if the OS decides the user needs to enter a PIN or otherwise authorize an operation, the OS transparently does whatever it needs to to make that happen).

> - How should osclientcerts be detected?

My goal is to make osclientcerts work well enough that other PKCS#11 modules won't be needed, so I think it's less of an issue of OpenSC detecting osclientcerts and more a situation of Firefox not needing to load other modules.

**Comment by dengert** [comment]
@mozkeeler

I see  https://blog.mozilla.org/security/2020/04/14/expanding-client-certificates-in-firefox-75/  
 says: "To enable it, set the "about:config" preference “security.osclientcerts.autoload” to true." and also says:
"For users running various flavors of Linux, the OpenSC project (https://github.com/OpenSC/OpenSC/wiki) can provide similar functionality."

On my Windows 10  FireFox 94.01  security.osclientcerts.autoload=true and has two devices that load "osclientcerts.dll"  You say security.osclientcerts.autoload  default was changed in version 90 

 Are you a representative of Mozilla, or just an independent developer who has forked a version of osclientcerts? 

Some of issues people see are caused by NSS doing polling  rather then event driven changes in card status and the fact that PKCS11 does not support multiple PINS very well.  "osclientcerts is a PKCS#11 module"  so how will it handle the polling issues from NSS or has that chaged too.

On Windows, OpenSC also installs minidriver (CNG modules) so OpenSC might still be called via osclientcerts using Windows CNG.

If we were to change `pkcs11-registery` would `security.osclientcerts.autoload` be the thing to test.

**Comment by mozkeeler** [comment]
I work for Mozilla.

Again, osclientcerts leaves all the details of PINs to the OS. So multiple PINs shouldn't be a problem.

The polling issues haven't changed.

> On Windows, OpenSC also installs minidriver (CNG modules) so OpenSC might still be called via osclientcerts using Windows CNG.

Ok. Again, the aim of osclientcerts is to make it so no other PKCS#11 modules need to be loaded by Firefox to be able to access smart cards.

> If we were to change `pkcs11-registery` would `security.osclientcerts.autoload` be the thing to test.

I don't know what `pkcs11-registry` is, but this sounds correct.

**Comment by frankmorgner** [comment]
Thanks for the update.

For a program written in C, what's the best way to test `security.osclientcerts.autoload` for `true`?

Is libosclientcerts also used in other Mozilla products, e.g. Thunderbird?

**Comment by mozkeeler** [comment]
> For a program written in C, what's the best way to test `security.osclientcerts.autoload` for `true`?

I don't know that there is a way. It's not actually clear to me that it's OpenSC's responsibility to check if Firefox has osclientcerts enabled. Like I said, if osclientcerts is enabled, Firefox shouldn't need to look for client certificates on other PKCS#11 modules, so eventually it may be the case that those modules won't get loaded, which as far as I understand, means there isn't a problem here. Am I missing something?

> Is libosclientcerts also used in other Mozilla products, e.g. Thunderbird?

Not by default at the moment.

**Comment by dengert** [comment]
OpenSC has been working with FireFox for more then 10 years and other smartcard vendors provide PKCS11 modules too.

IMHO if osclientcerts wants insert itself before any other PKCS11 modules and you work for Mozilla, Mozilla needs to solve the problem, not the individual PKCS11 module providers. (And it should be a user choice to use the old or new way.)   

Google for: mozilla NSS PKCS11 loaded
leads to https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/PKCS11/Module_Installation
and then to:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/pkcs11/isModuleInstalled

So there is a way to see if a specific PKCS11 module is installed and then not install another. 
Its not C but could be used. "Module Name" looks like it is the name made up by the user, rather then "Module Filename"  

I believe NSS loads all the modules at startup. And will query all of them to find certificates if a website wants user authentication. It will then find a certificate from the list. I don't think it stops when it finds the first, 
But I will leave that up to someone who is having a problem with osclientcerts and OpenSC to test. 

Mozilla NSS has a number of debugging  tools. 
Google for: mozilla NSS PKCS11 debugging 

Mozilla has the NSS_DEBUG_PKCS11_MODULE env to debug one PKCS11 module. 

OpenSC provides additional debugging, and an opensc-spy module that can debug any PKCS11 but only one at a time because of the PKCS11SPY env variable to point to the module. 

Does osclientcerts have any additional debugging?

**Comment by metsma** [comment]
I think the main point is here that osclientcerts will use minidriver and ctk on macos. Therefore you cannot compare if card is handled by PKCS11. For us (Estonia) it is good news and we do not have to mess with firefox modules and extensions and it will work out of box. Same way like in chrome and edge

**Comment by dengert** [comment]
With Estonian card If not using OpenSC PKCS11 with fireFox:
Are you using the OpenSC minidrivers? 
Or a minidriver provided by a vendor"?
Or are these supported by Microsoft drivers? 

What ever happened to the NSS CAPI module?

Also found  https://github.com/janhf/mozilla-capi

**Comment by metsma** [comment]
Previously was in-house built minidriver, MS certified and distributed via MS Windows update (https://github.com/open-eid/minidriver).
Now with idemia cards have vendor minidriver.

**Comment by mozkeeler** [comment]
> IMHO if osclientcerts wants insert itself before any other PKCS11 modules and you work for Mozilla, Mozilla needs to solve the problem, not the individual PKCS11 module providers.

I guess I don't really understand what problem you're concerned about.

**Comment by mouse07410** [comment]
One problem I'm having with Firefox: it "sees" certificates on a smart card multiple times, so when is time to use the cert and the PIN is entered - the token remains locked, because the part that promoted for the PIN is not the same that's trying to use the key.

In theory it probably would work because it's the same Unix process, in practice, since several different shared libraries are involved - user is prompted ad nauseum for the PIN, and is stuck there, operation does not happen.

**Comment by mozkeeler** [comment]
Are you on macOS/Windows? If not, that's not an issue with osclientcerts and you should file a bug: https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Security%3A%20PSM
Please include as many specifics as you can, such as what platform you're on and what PKCS#11 modules you have loaded.

**Comment by mouse07410** [comment]
MacOS (updated above).

**Comment by mozkeeler** [comment]
What happens if you don't load opensc-pkcs11.so?

**Comment by mouse07410** [comment]
If I remove PKCS11 module opensc-pkcs11.so v0.19 that Firefox insists on loading without asking me, and remove opensc-pkcs11.so that I built from master, situation improves.

**Comment by mozkeeler** [comment]
Firefox doesn't load any opensc PKCS#11 modules automatically. Do you have an add-on or something that loads it for you?

**Comment by mouse07410** [comment]
Long time ago, I added Security Device to load OpenSC module that I built - and it worked wonderfully for several years (I kept updating the module and re-read loading it). 

Recently I had to remove it, to address the above problem. 

I don't know who load v0.19 - either Firefox or our local IT (in which case I'll have a talk with them).

**Comment by frankmorgner** [comment]
pkcs11-register modifies firefox's `pkcs11.txt` to add some PKCS#11 module (OpenSC's module by default). It is launched when the user logs into her account.

#2459 changes this behavior to now skip this process on Windows and macOS
