### ISSUE TITLE
github actions build-mingw and build-build-mingw32 are failing

### ISSUE THREAD

**Issue by dengert** [OpenSC/OpenSC#2456]
### Problem Description
github actions build-mingw and build-build-mingw32 started failing with several  PR checks. 

> The following packages have unmet dependencies:
>  wine32:i386 : Depends: libwine:i386 (= 5.0-3ubuntu1) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
> Error: Process completed with exit code 100.
> The following packages have unmet dependencies:
>  wine32:i386 : Depends: libwine:i386 (= 5.0-3ubuntu1) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
> Error: Process completed with exit code 100.

On my XUbuntu-20.4, synaptic has a dependencies "Breaks:wine32" which may be a clue.
(The OS was upgraded over the years.) 

Could the "held broken packages" be caused by doing upgrades of the actions? 

https://wiki.debian.org/Wine
lists a different set of packages to install. 

https://github.com/OpenSC/OpenSC/blob/master/.github/setup-linux.sh#L28

These might help in figuring out what to do:
https://askubuntu.com/questions/1204823/wine32i386-depends-libwinei386-3-0-1ubuntu1-but-it-is-not-going-to-be-i
which points at:
https://wiki.winehq.org/Ubuntu

### Proposed Resolution
none

**Comment by Jakuje** [comment]
I tried to look into this last week, but without any success so far. I tried to run the same scripts in podman container and all worked fine (the same as it worked until last week in github actions) so I assume the github/azure mirror is somehow broken, providing broken dependencies, but I am not expert on debian packaging.

I also tried to get some more debug logs from apt, but it was not much helpful so far:

https://github.com/Jakuje/OpenSC/runs/4351244711?check_suite_focus=true
https://github.com/Jakuje/OpenSC/commit/d090ba6ed18ff63c85c822d1dc3cdf0e771f3525

Suggestions/patches/ideas how to solve this are welcomed.

**Comment by Jakuje** [comment]
For the record, I tried a lot of stuff, but there is something badly broken in the github images.

It changed between https://github.com/OpenSC/OpenSC/runs/4316990114?check_suite_focus=true (good) and https://github.com/OpenSC/OpenSC/runs/4325865048?check_suite_focus=true (bad), which updated image:

    13 Version: 20211114.1                      |   13 Version: 20211122.1 

~~The new image from today should show up in couple of days, hopefully fixing this issue.~~ Probably not

This brought me to the issue https://github.com/actions/virtual-environments/issues/4589 which proposes a workaround (yeah! Fix all the existing CI scripts because we installed some conflicting package and we do not support multiarch).

**Comment by dengert** [comment]
I have been trying a lot of stuff too. Glad you found a workaround  until gihhub fixes it correctly, and asked them to reopen it. https://github.com/actions/virtual-environments/issues/4589#issuecomment-981924126
