### ISSUE TITLE
macOS Monterey ( Version 12.3.1 (21E258))- Could not add card "/usr/local/lib/opensc-pkcs11.so": agent refused operation

### ISSUE THREAD

**Issue by amarsrms** [OpenSC/OpenSC#2560]
### Problem Description
mac lib % ssh-add -s /usr/local/lib/opensc-pkcs11.so
Enter passphrase for PKCS#11: 
Could not add card "/usr/local/lib/opensc-pkcs11.so": agent refused operation

**Comment by Jakuje** [comment]
Please, provide more debug information from opensc or from openssh as described in the issue template. With such a common error message, there is nothing we can do for you. https://github.com/OpenSC/OpenSC/blob/master/.github/ISSUE_TEMPLATE.md?plain=1

**Comment by jasonlyle88** [comment]
I am having this same issue on MacOS Monterey 12.4
```
> sw_vers
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79
```

I realize this is a different version than the title, and this is not my issue. If you would prefer I create a separate issue, I can do that. But since it seemed very similar, I thought I would post here first.

I am using the latest OpenSC Version
```
> opensc-tool --version
OpenSC-0.22.0-rc1-74-gc902e199, rev: c902e199, commit-time: 2021-08-10 11:09:03 +0200
```

and the following OpenSSH version
```
> ssh -V
OpenSSH_8.6p1, LibreSSL 3.3.6
```

With a yubikey
```
> opensc-tool --name
Using reader with a card: Yubico YubiKey OTP+FIDO+CCID
Personal Identity Verification Card
```

When trying to add my yubikey to my ssh agent, I receive the following
```
> OPENSC_DEBUG=9 ssh-add -vvv -s /usr/local/lib/opensc-pkcs11.so
Enter passphrase for PKCS#11:
Could not add card "/usr/local/lib/opensc-pkcs11.so": agent refused operation
```

As you can see, I am specifying to use OPENSC_DEBUG with a value of 9, using three "v" parameters for the most verbosity on the ssh-add output, and still not receiving any additional output. If there is another way to get additional logs for you to help with this issue, please let me know and I will be happy to help.

One thing to note is that adding the yubikey to the ssh agent does work the first time I attempt this after restarting my mac. However, if I clear my agent (`ssh-add -D`) after it has been successfully added and try to add it again, I get the above message.

For some context, I am using this yubikey to gain access to a box to create an SSH tunnel. When I do not have the yubikey added to my ssh agent, it works perfectly and just asks for the yubikey pin twice. However, If I have the yubikey added to the agent, it fails to authenticate. I realize this may be a separate issue... but I wanted to provide this information here in case it has any bearing on this issue.

Additionally, on the [macOS quick start guide](https://github.com/OpenSC/OpenSC/wiki/macOS-Quick-Start), you mention that I could test tokend support with Keychain Access and the app should list my smart card in the Keychains pane. On the left pane, I have a group for "Default Keychains" that contains a "login" keychain and an "iCloud" keychain, along with a "System Keychains" group that contains a "System" keychain and a "System Roots" keychain. Nothing there about a smart card or yubikey or anything of the sort. Again, this may be a separate issue... but I wanted to provide this information here in case it has any bearing on this issue.

**Comment by Jakuje** [comment]
I do not think there is any outstanding issue. If there will be some problem, open a new issue, or let us know.
