### ISSUE TITLE
Use OpenPGP Get Data command to retrieve PIN tries for Yubikey

### ISSUE THREAD

**Issue by MkfsSion** [OpenSC/OpenSC#2565]
### Problem Description

Yubikey 5 NFC and 5C NFC (Firmware version: 5.4.3) returns 6A 80 for Verify command without data instead of 63CX.

### Proposed Resolution
We may need to use Get Data command to get DO C4 for querying PIN tries like what GnuPG do currently.

### Steps to reproduce
1. configure opensc to use openpgp driver for the token.
2. OPENSC_DEBUG=9 pkcs11-tool --login --list-objects

### Logs
```
...
P:3779; T:0x140372872375168 19:28:51.385 [opensc-pkcs11] sec.c:203:sc_pin_cmd: called
P:3779; T:0x140372872375168 19:28:51.385 [opensc-pkcs11] card-openpgp.c:1999:pgp_pin_cmd: called
P:3779; T:0x140372872375168 19:28:51.385 [opensc-pkcs11] apdu.c:550:sc_transmit_apdu: called
P:3779; T:0x140372872375168 19:28:51.385 [opensc-pkcs11] card.c:473:sc_lock: called
P:3779; T:0x140372872375168 19:28:51.385 [opensc-pkcs11] card.c:522:sc_lock: returning with: 0 (Success)
P:3779; T:0x140372872375168 19:28:51.385 [opensc-pkcs11] apdu.c:515:sc_transmit: called
P:3779; T:0x140372872375168 19:28:51.385 [opensc-pkcs11] apdu.c:363:sc_single_transmit: called
P:3779; T:0x140372872375168 19:28:51.385 [opensc-pkcs11] apdu.c:367:sc_single_transmit: CLA:0, INS:20, P1:0, P2:82, data(0) 0x7ffd9d95bb40
P:3779; T:0x140372872375168 19:28:51.386 [opensc-pkcs11] reader-pcsc.c:325:pcsc_transmit: reader 'Yubico YubiKey OTP+FIDO+CCID 00 00'
P:3779; T:0x140372872375168 19:28:51.386 [opensc-pkcs11] reader-pcsc.c:326:pcsc_transmit: 
Outgoing APDU (4 bytes):
00 20 00 82 . ..

P:3779; T:0x140372872375168 19:28:51.386 [opensc-pkcs11] reader-pcsc.c:244:pcsc_internal_transmit: called
P:3779; T:0x140372872375168 19:28:51.386 [opensc-pkcs11] reader-pcsc.c:335:pcsc_transmit: 
Incoming APDU (2 bytes):
6A 80 j.

P:3779; T:0x140372872375168 19:28:51.386 [opensc-pkcs11] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:3779; T:0x140372872375168 19:28:51.386 [opensc-pkcs11] apdu.c:539:sc_transmit: returning with: 0 (Success)
P:3779; T:0x140372872375168 19:28:51.386 [opensc-pkcs11] card.c:532:sc_unlock: called
P:3779; T:0x140372872375168 19:28:51.386 [opensc-pkcs11] iso7816.c:128:iso7816_check_sw: Incorrect parameters in the data field
P:3779; T:0x140372872375168 19:28:51.386 [opensc-pkcs11] card-openpgp.c:2089:pgp_pin_cmd: returning with: -1205 (Incorrect parameters in APDU)
P:3779; T:0x140372872375168 19:28:51.386 [opensc-pkcs11] sec.c:259:sc_pin_cmd: returning with: -1205 (Incorrect parameters in APDU)
P:3779; T:0x140372872375168 19:28:51.387 [opensc-pkcs11] card.c:532:sc_unlock: called
P:3779; T:0x140372872375168 19:28:51.387 [opensc-pkcs11] reader-pcsc.c:740:pcsc_unlock: called
P:3779; T:0x140372872375168 19:28:51.387 [opensc-pkcs11] pkcs15-pin.c:742:sc_pkcs15_get_pin_info: returning with: -1205 (Incorrect parameters in APDU)
P:3779; T:0x140372872375168 19:28:51.387 [opensc-pkcs11] framework-pkcs15.c:617:C_GetTokenInfo: C_GetTokenInfo(0) returns CKR_OK
Logging in to "OpenPGP card (User PIN)".
```

**Comment by MkfsSion** [comment]
> * You're talking about the PGP application of the Yubikey, right?
Yes
> * Could you post an example for using `DO C4`?
Here is scdaemon log
```
2022-06-11 21:31:12 scdaemon[6771] DBG: send apdu: c=00 i=CA p1=00 p2=C4 lc=-1 le=256 em=0
2022-06-11 21:31:12 scdaemon[6771] DBG:  raw apdu: 00 CA 00 C4 00
2022-06-11 21:31:12 scdaemon[6771] DBG:  response: sw=9000  datalen=7
2022-06-11 21:31:12 scdaemon[6771] DBG:       dump:  00 7F 7F 7F 03 03 03
2022-06-11 21:31:12 scdaemon[6771] DBG: chan_7 -> S CHV-STATUS +0+127+127+127+3+3+3
```
> * We need to check the docs if implementation of verify to get the pin status is mandatory...
Yes, it's mandatory but Yubikey firmware didn't implement it properly.
> * the PIV card driver alredy detects different type of yubikeys and their limitations. maybe we need to copy some of this to the pgp driver to work around this issue

**Comment by dengert** [comment]
You are correct. The ISO 7816-4 verify command should also return 63 CX for an incorrect pin.

The YubiKey 5 NFC says it implements PGP version 3.4.
```
./openpgp-tool -C
Using reader with a card: Yubico YubiKey OTP+FIDO+CCID 00 00
AID:             d2:76:00:01:24:01:03:04:00:06:13:41:22:87:00:00
Version:         3.4
Manufacturer:    Yubico
Serial number:   13412287
```

https://gnupg.org/ftp/specs/OpenPGP-smart-card-application-3.4.0.pdf (2019)
says: "If the command is called with P1 = 00 and no data (Lc empty), then the actual access status of the addressed password in P2 is returned. If the password is still verified the cards answers with normal status bytes (SW1-SW2 = 9000). If the password is not checked and the verification is required, then the card answers with the status bytes 63CX, where 'X' encodes the number of further allowed retries."

The above was introduced in Jan 2016: https://gnupg.org/ftp/specs/OpenPGP-smart-card-application-3.1.pdf 

To test if the command even tests the login state I tries this:

Here is a test to show what the verify command can do. The 82 pin is 123456.

- send get data to see retry counts
- send incorrect pin. ISO 7816-4 verify would have returned 63C2. saying only 2 retries left.
- send get data to see retry counts, and pin  82  now only has only 2 retries
- send correct pin
- send get data to see if retry count are reset and they are
- send verify without Lc which fails.  
- 
```
OPENSC_DRIVER=openpgp ./opensc-tool -s "00 CA 00 C4 00" -s "00 20 00 82 06 31 32 33 34 35 39" -s "00 CA 00 C4 00" -s "00 20 00 82 06 31 32 33 34 35 36"  -s "00 CA 00 C4 00" -s "00 20 00 82"
Using reader with a card: Yubico YubiKey OTP+FIDO+CCID 00 00
Sending: 00 CA 00 C4 00 
Received (SW1=0x90, SW2=0x00):
FF 7F 7F 7F 03 00 03 .......
Sending: 00 20 00 82 06 31 32 33 34 35 39 
Received (SW1=0x69, SW2=0x82)
Sending: 00 CA 00 C4 00 
Received (SW1=0x90, SW2=0x00):
FF 7F 7F 7F 02 00 03 .......
Sending: 00 20 00 82 06 31 32 33 34 35 36 
Received (SW1=0x90, SW2=0x00)
Sending: 00 CA 00 C4 00 
Received (SW1=0x90, SW2=0x00):
FF 7F 7F 7F 03 00 03 .......
Sending: 00 20 00 82 
Received (SW1=0x6A, SW2=0x80)
```

PIV was designed to retain the login state as long as no other applet on the card  is selected. And this could be tested by using the  00 20 00 81 (in PIV case) to see if some other application has logged out or selected some other applet on the card and caused the login state to be lost. 

PGP appears to have been designed to have only have a single application access the card, (scdaemon) and it would use PC/SC exclusive access, so no other application on the system could access the card, so the extra features of verify were not needed. 

And Yubico did not even implement the required features that have been in PGP specs since version 3.1, 6 years ago even when they offer a card that can have both PIV and PGP applets!

So the question is: Can the actual login state of the applet be tested so as to avoid having to ask the user to enter the PIN?  The get data 00 CA 00 C4 00 just shows the retry counts, it does not show the login state. 

It might be possible to test the state, by trying to read some object that need PIN authentication. But it looks like using verify is not the way to do it.

**Comment by dengert** [comment]
V3.4.1 says verify can check status. V2.sometbing does not.
