### ISSUE TITLE
Giesecke & Devrient GmbH StarSign CUT S Unsupported card. Any chance to get it working in a next release ?

### ISSUE THREAD

**Issue by marozsas** [OpenSC/OpenSC#2580]
### Problem Description
```
kimera:~ # opensc-tool --list-readers --verbose
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             Giesecke & Devrient GmbH StarSign CUT S [.] (03211015001257) 00 00
     3b:f9:96:00:00:81:31:fe:45:53:43:45:37:20:0e:00:20:20:28 Unsupported card 
kimera:~ # opensc-tool --serial
Using reader with a card: Giesecke & Devrient GmbH StarSign CUT S [.] (03211015001257) 00 00
sc_card_ctl(*, SC_CARDCTL_GET_SERIALNR, *) failed
kimera:~ # opensc-tool -n 
Using reader with a card: Giesecke & Devrient GmbH StarSign CUT S [.] (03211015001257) 00 00
Unsupported card
kimera:~ # opensc-tool -i  
OpenSC 0.22.0 [gcc  12.1.0]
Enabled features: locking zlib readline openssl pcsc(libpcsclite.so.1)
kimera:~ # opensc-tool --atr
Using reader with a card: Giesecke & Devrient GmbH StarSign CUT S [.] (03211015001257) 00 00
3b:f9:96:00:00:81:31:fe:45:53:43:45:37:20:0e:00:20:20:28
kimera:~ # pkcs15-tool --list-info
Using reader with a card: Giesecke & Devrient GmbH StarSign CUT S [.] (03211015001257) 00 00
Failed to connect to card: Card is invalid or cannot be handled
```

And this [site](https://smartcard-atr.apdu.fr/parse?ATR=3b:f9:96:00:00:81:31:fe:45:53:43:45:37:20:0e:00:20:20:28
)  correctly identify the usb token based on atr command above
I appreciate any help.

### Proposed Resolution

none 

### Logs

```
Jul 23 10:02:05 kimera kernel: usb 1-1.4.4: new full-speed USB device number 10 using ehci-pci
Jul 23 10:02:05 kimera kernel: usb 1-1.4.4: New USB device found, idVendor=1059, idProduct=0019, bcdDevice= 1.00
Jul 23 10:02:05 kimera kernel: usb 1-1.4.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jul 23 10:02:05 kimera kernel: usb 1-1.4.4: Product: StarSign CUT S
Jul 23 10:02:05 kimera kernel: usb 1-1.4.4: Manufacturer: Giesecke & Devrient GmbH
Jul 23 10:02:05 kimera kernel: usb 1-1.4.4: SerialNumber: 03211015001257
```

**Comment by dengert** [comment]
Looks like a proprietary token But it looks like drivers for windows and linux are available. 

Google for: SAFESIGN Starsign CUT

and Google for: StarSign CUT S "linux"


https://certificaat.kpn.com/files/drivers/SafeSign/SafeSign%20IC%20Standard%20Version%203.6%20for%20Linux%20Release%20Document.pdf

**Comment by marozsas** [comment]
Yeah, I've tried already. 
For Windows 7&10 it works out of box, no need of install anything.

The link to the RPM CentOS package is broken, couldn't find other.
For ubuntu I found a obsolete package  for ubuntu 18.04. Besides it is 4 years old now, I use a RPM based distro (opensuse), can't manage to use it.
I even tried on a VM with usb-pass-through enabled, but no luck either. I don ´t have another bare-metal machine to install Ubuntu 18 to test, but even if I had, it makes no sense. I want to use it on my daily machine to sign legal documents and access governamental sites that requires a strong authentication method.

**Comment by dengert** [comment]
Writing a smartcard driver requires good documentation about the card and access to a working card. You say there is a Ubuntu 18.04 package. Is the source code publicly available? From what I was able to find this morning it looks like this is a proprietary token. So the only other option is use some PCSC traces to see what is sent and received from the card. 

So have a look at these:

https://github.com/OpenSC/OpenSC/wiki/Getting-involved-in-OpenSC-development

https://github.com/OpenSC/OpenSC/wiki/Adding-a-new-card-driver

**Comment by marozsas** [comment]
Thanks for the explanation.
I don't have the documentation neither the skills to develop a driver of my
own.
However, I have the option to buy my own certificate in a PKS file. It is
less secure but it works in Linux without any fuss.

Thank you,


Em sáb., 23 de jul. de 2022 13:02, Doug Engert ***@***.***>
escreveu:

**Comment by murder** [comment]
I have the card, I also don't understand how this is unsupported, I remember back 4 years ago people mentioning this card here..
This is everything I found about it https://github.com/murder/startsigncuts_pub
Tons of Linux packages and PDFs

I've been digging with it using pkcs11admin to try exporting my private key, by changing some attributes, no success

**Comment by frankmorgner** [comment]
@murder , the repository you are mentioning contains a proprietary software driver and its documentation. if you want to write such a driver for yourself (e.g. by integrating in OpenSC), you need the hardeware's documentation (i.e. the APDU interface).

@marozsas if it is possible to obtain a private key + certificate, you can use that to personalize a token of your choice. A yubikey or nitrokey would be a popular choice, for example.

**Comment by murder** [comment]
@frankmorgner @dengert I'm currrently interested in 'donating' my time and my card + my certificate/private key in order to make it work with OpenSC.
The idea in the future is to be able to export as a bundle and import in Yubi or similars.

How can I proceed?
And how can I guarantee I do a 'full hardware backup' of my current card before doing anything?
It's been 3 times I lost my certificate trying to do that - luckily the guys never suspected I was trying to rev. eng. the card but rather suspected the cards were bad.

Thanks

**Comment by popovec** [comment]
In principle, there is no possibility to back up a "safe" token/card. If the card/token works really securely, the private key can never leave the token/card. 

Some of the tokens/cards provide a key wrapping operation, which makes it possible to relatively safely export the private key from the card/token and import it into another card/token, but  there may be a security risk that the key wrapped in this way will be unwrapped in another non-secure token/card, or only in the software simulation of the card/token, and thus the private key will be exposed.

Without accurate documentation for your card/token, it is impossible to determine whether the card/token enables this operation. In addition, if this operation also exists, the key on the card/token may have such attributes that it cannot be exported from the card/token even in this way.

**Comment by dengert** [comment]
Where were the keys created? On card or off card?
Who created the card? By you or some organization that issued a card to you. 

As @popovec points out if on card they should not be extractable. If they where that defeats the point in using a smartcard. Some hacked or infected machine could copy your keys.

If off card by you, you could reload them and any other data needed to create a duplicate card.

If off card by some organization, they could issue you a new card, but they may have different rules depending on what happened to old card. 

For legal regulations, an organization may escroll encryption keys, and may always issue a new signing key.

If issued by some organization, and you manage to copy them, that is a very bad  breach of security.

**Comment by murder** [comment]
> Where were the keys created? On card or off card? Who created the card? By you or some organization that issued a card to you.
> 
> As @popovec points out if on card they should not be extractable. If they where that defeats the point in using a smartcard. Some hacked or infected machine could copy your keys.
> 
> If off card by you, you could reload them and any other data needed to create a duplicate card.
> 
> If off card by some organization, they could issue you a new card, but they may have different rules depending on what happened to old card.
> 

I bought the certificate online, they did the validation through webcam etc.
After that, I received an email wih a java application, I opened that java application and it asked for an ORDER #.
I did input the ORDER # followed by a password that came with an email from them.
The application then asked me to insert the USB Token/SC in the USB slot and started writing the contents.
Afterwards, it tested and that's it.

If I try the same procedure again now, it simply says `the certificate has already been installed, if necessary contact the company support`

**Comment by murder** [comment]
What about these options?
![image](https://user-images.githubusercontent.com/437087/203105606-46e185ab-6d73-432c-a1d3-704b1a0d2a4f.png)

**Comment by dengert** [comment]
So it looks like some organization issued you a certificate and you followed their rules. 
Have you "contacted their support? 

A certificate contains the public key that matches a private key and is signed by a CA. 

It is still not clear if the private key and certificate where created ahead of time and they sent you a certificate to be loaded on the card and the private key..  

Or the java application did the following normal PKI process to issue a certificate:

- Create key pair on the card with the private key staying on the card and public key being read from card.
- Create a CSR which has some info and  public key. The CSR is signed by the card. The proves possession of the private key
- Sends the CSR back to the CA
- The CA creates a certificate with the public key and other info and the CA signs it with the CA private key.
- The certificate is then sent back to the java application that  writes the certificate to the card.

In the above case the organization does not have a copy of the private key as it is only on the card. 
I suspect  the above. 

In normal PKI if a card is lost, stolen or broken a new certificate and new public and private key will be created and the old certificate  marked revoked, so any application which checks for revocation via a CRL or OSCP will not accept the old certificate, but will accept the new certificate.  

Also see https://en.wikipedia.org/wiki/Certificate_signing_request

**Comment by murder** [comment]
> So it looks like some organization issued you a certificate and you followed their rules. Have you "contacted their support?
> 

Yes, I did - exactly. But I haven't contacted their support, because all I wanted is to have the certificate in my Yubikey and they say Yubikey is not yet accepted by the country's whitelisting of token devices.

> A certificate contains the public key that matches a private key and is signed by a CA.
> 
> It is still not clear if the private key and certificate where created ahead of time and they sent you a certificate to be loaded on the card and the private key..
> 
> Or the java application did the following normal PKI process to issue a certificate:
> 
> * Create key pair on the card with the private key staying on the card and public key being read from card.
> * Create a CSR which has some info and  public key. The CSR is signed by the card. The proves possession of the private key
> * Sends the CSR back to the CA
> * The CA creates a certificate with the public key and other info and the CA signs it with the CA private key.
> * The certificate is then sent back to the java application that  writes the certificate to the card.
> 
> In the above case the organization does not have a copy of the private key as it is only on the card. I suspect the above.
> 
> In normal PKI if a card is lost, stolen or broken a new certificate and new public and private key will be created and the old certificate marked revoked, so any application which checks for revocation via a CRL or OSCP will not accept the old certificate, but will accept the new certificate.
> 
> Also see https://en.wikipedia.org/wiki/Certificate_signing_request

It probably followed that, yes.
Once I had a problem with an old certificate and they imediately told me to send a revocation request.
In fact, I own the revogation code right now just in case I have to proceed with that.


The only thing I want is that this card is supported enough so I can take my own certificate out of it and put it somewhere else, that's all.

**Comment by murder** [comment]
I've ran PKCS11Admin from @Jariq and I got the following (#### means there's data but I'm not exposing here)
A silly question, is there something that might sound obvious in the following content that I could in some way extract my private key out of it?

```

================================================================================
Dumping all objects of type "Private key"
================================================================================


CKA_PRIVATE: TRUE
CKA_LABEL: 
    ""
CKA_KEY_TYPE: CKK_RSA
CKA_SUBJECT: 
        
CKA_ID: 
###XXX
CKA_SENSITIVE: TRUE
CKA_DECRYPT: TRUE
CKA_UNWRAP: TRUE
CKA_SIGN: TRUE
CKA_SIGN_RECOVER: TRUE
CKA_DERIVE: FALSE
CKA_START_DATE:     -  -  
CKA_END_DATE:     -  -  
CKA_MODULUS: 
####
CKA_PUBLIC_EXPONENT: 
     01 00 01                                           ...
CKA_EXTRACTABLE: TRUE
CKA_LOCAL: FALSE
CKA_NEVER_EXTRACTABLE: FALSE
CKA_ALWAYS_SENSITIVE: FALSE
CKA_KEY_GEN_MECHANISM: FFFFFFFF (-1) CKM_UNAVAILABLE
CKA_MODIFIABLE: TRUE

```

**Comment by dengert** [comment]
> The only thing I want is that this card is supported enough so I can take my own certificate out of it and put it somewhere else, that's all.

You can take the certificate out of you card and put it anywhere. But the the certificate is useless to anyone unless you can prove you hold the private key. That's what is done with HTTPS:, login, ssh, signed documents etc. 

The point of using a smart card is it will never let you read the private key.  You can ask the card to do signature or decryption operations with the key, but the card never return the actual private key.

You talk about:  "country's whitelisting of token devices". They are never going to whitelist a token that will return the private key.

**Comment by murder** [comment]
> You talk about: "country's whitelisting of token devices". They are never going to whitelist a token that will return the private key.

Yubikey is flawed like that?

**Comment by mouse07410** [comment]
> > You talk about: "country's whitelisting of token devices". They are never going to whitelist a token that will return the private key.
> 
> 
> 
> Yubikey is flawed like that?

Is it a troll question? No reputable manufacturer would do suck a stupid thing, and Yubico is no exception. Private keys are not extractable/"returnable".

@dengert 's point is - it doesn't make sense to copy your certificate from that idiotic proprietary token to Yubikey, because you won't be able to extract and put into Yubikey your _private_ key (unless that proprietary token is even more idiotic than I think). And without that private key, your certificate alone is useless.

**Comment by murder** [comment]
Guys,

I understand your point now. I wasn't trolling at all.
It makes total sense.
I just thought that if it is my token and I am the solely proprietary of it I could somehow extract it with some kind of identification, but I understood that the token is not worth being called token if I can extract the private key, even if it is my own (owner) decision.

And let's wait for Brazil to allow Yubikey to be used as a token.

**Comment by shantanubindhani** [comment]
got any progress so far??? i am facing the same kinda issue with a smart card, i want to be able to sign pdf with digital signature using the cert stored inside.....(ps : new to all this )

**Comment by popovec** [comment]
I don't understand what you are dealing with. If someone has provided you with a proprietary solution for a particular proprietary application, use that solution and don't expect that proprietary solution to ever have support in the open source world. If you "force" this proprietary solution on any other operation (even just signing a random pdf), don't expect it to work. You will sign the document, but no one will be able to verify who the signature belongs to - thanks to the ownership of your token that signed it (and this is primarily not a problem of the token, but of the entire solution from which this token comes)

I watch with amazement an attempt to use a token issued by, for example, a state (in the form of an ID card) for the purpose of, for example, logging into a remote computer using ssh. Do you realize the impact that instead of logging in with ssh, you can sign a document that deprives you of your property?

Precisely for this reason, I do not consider it good to add even only "read only" drivers of proprietary solutions to OpenSC, which an unknowing user can very easily "unfortunately" use for what he did not actually want to do.

**Comment by shantanubindhani** [comment]
> I don't understand what you are dealing with. If someone has provided you with a proprietary solution for a particular proprietary application, use that solution and don't expect that proprietary solution to ever have support in the open source world. If you "force" this proprietary solution on any other operation (even just signing a random pdf), don't expect it to work. You will sign the document, but no one will be able to verify who the signature belongs to - thanks to the ownership of your token that signed it (and this is primarily not a problem of the token, but of the entire solution from which this token comes)
> 
> I watch with amazement an attempt to use a token issued by, for example, a state (in the form of an ID card) for the purpose of, for example, logging into a remote computer using ssh. Do you realize the impact that instead of logging in with ssh, you can sign a document that deprives you of your property?
> 
> Precisely for this reason, I do not consider it good to add even only "read only" drivers of proprietary solutions to OpenSC, which an unknowing user can very easily "unfortunately" use for what he did not actually want to do.


the proprietary haven't provided us with their own implementation of pkcs11 that is able to interact with their card, so the only place to look for that is open source, if that's not how it's gonna work then can you please suggest me some other ways to make this work??

**Comment by popovec** [comment]
For the purposes of your organization (country, government institution), you also received a token with software application. In addition to document signing, this application also provides certificate management (CSR generation, installation of certificates in tokens, etc.).  Is there a reason to bypass this app when communicating with your organization? Need to use this token against other entities? (outside your organization or country)?

If for some reason you absolutely need to use the given token in the open source world, there is only one possible way... reverse engineering the software that was provided to you for this token. 

Consider whether this is even possible (it is possible that when you installed this proprietary solution you confirmed a license for your token that does not allow you to attempt reverse engineering).

If you managed to make an open source pkcs11 module for this token (or integrate this token into OpenSC), it is questionable whether it makes sense at all. You may be able to sign the PDF, but without the ability to verify who created the signature, it's useless. This signature verification happens outside of pkcs11 or outside of OpenSC - it depends on who issues certificates, provides revocation lists, etc.

Next, you will have to add an open source application to the pkcs11 module, which allows you to generate CSRs, manage revocations, etc. Is this really your goal?

**Comment by shantanubindhani** [comment]
Our goal is to be able to integrate our token (which is PKCS11 and PKCS7 compliant) with OpenSC. Can you help understand how we can achieve this? We will be getting the certificates from third party certificate vendors. We want to be able to enable all PKCS11 "APIs" to our partners who will work on downloading the certificate on our token. 

Our token should be able to sign documents (of all kinds: PDFs, documents, text files etc) and also be able to encrypt such documents. I understand that this may out of scope of OpenSC but if we can expose the PKCS11 and PKCS7 functionalities of our token using the OpenSC as a middleware that will be a good start for us. The application layer  on top of the middleware wil be developed by thirdparties

Hope this clarifies where we are coming from.

**Comment by popovec** [comment]
I assume that you either have documentation for your token or you will perform reverse engineering of the software that was delivered to the token. In both cases, you can start implementing a new driver into OpenSC.. how to start: https://github.com/OpenSC/OpenSC/wiki/Adding-a-new-card-driver

**Comment by nshah2588** [comment]
Thank you for your response. 

How do we get the token integrated into the PKCS11 middleware that OpenSC has provided for other token vendors? What information will be needed to do that? We have the smart card commands to do various things that PKCS11 expects from the token and we want to be able to use the OpenSC middleware with our token and in a way customise it to work with our token.

Is the link you provided in the earlier post still the best way to proceed?

**Comment by mouse07410** [comment]
@popovec I don't understand your concern regarding PKI at all. For many, open source software to handle CSR, cert issuance, etc. is OpenSSL - and it works. 
If the organization issues certs within their proprietary PKI - the user can share their root CA cert with the intended verifiers of signed PDFs. In other words, all that appears truly trivial. 

The only real problem is writing PKCS#11 module for OpenSC, to make the card accessible by OpenSSL (and Adobe Acrobat, etc.). Here you're correct, and I for one don't know how to figure out the specs of that proprietary token. Perhaps, tracing with OPENSC_SPY might help...?

To conclude, @nshah2588 your organization would've been much better off if they selected PIV-compliant token instead, as there's plenty of both PIV cards and open source code that support it. Maybe it's not too late to switch yet.

**Comment by nshah2588** [comment]
@mouse07410 Looks like we are talking about two different things. Hence you may not understand my request. Let me try to go over what I am thinking in a different way.

We have a token which supports all PKCS11 functions. The people who are going to use the token only understand the functions mentioned in the PKCS11 specifications. So we need to expose the functions that PKCS11 has specified on this link:

http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959729

Looks like the same have been integrated within OpenSC within files like:

https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c

We are not looking to generate/build our own CSR or anything. But we want to be able to provide a middleware for our PKCS11 based token to such companies who can use the PKCS11 commands to integrate their tools with our token.

Our research suggested that we want to be able to integrate our token with something like this:

https://github.com/OpenSC/pkcs11-helper

https://github.com/OpenSC/libp11

So that we can expose our PKCS11 functionality to people using OpenSSL as a middleware (essentially like a .so, .dylib as well as .dll)

Does this help understand where we are coming from?

**Comment by popovec** [comment]
> @popovec I don't understand your concern regarding PKI at all. For many, open source software to handle CSR, cert issuance, etc. is OpenSSL - and it works. If the organization issues certs within their proprietary PKI - the user can share their root CA cert with the intended verifiers of signed PDFs. In other words, all that appears truly trivial.

In principle, you are right, but I will state, for example, a situation that concerns me (skeid). Even though support in OpenSC already exists, I can't actually use my ID card with OpenSC at all. If I need to sign a document, I have to use the application provided by our government. (only due to compliance with the appropriate format of the documents that I sign). And then there is the other side of the matter, I have no way of verifying the identity of the documents that have reached me signed... OpenSC cannot do this for me, but the application that my government supplied me knows.

Another example, the employer issues "employee ID cards", I don't have the possibility to add a key to them. I can use this card only for actions defined by the employer. If I wanted to use this card to log in with SSH or to authenticate to openVPN, it would be possible, but there is a problem here that there is one key and the card is not really safe to use .. in relation to a third-party application.

**Comment by popovec** [comment]
@nshah2588 
> We have a token which supports all PKCS11 functions."

OpenSC is "software" that creates a pkcs#11 interface over the card/token.. as I understood from your posts,  you already have such a solution in a proprietary form..

**Comment by popovec** [comment]
@nshah2588 I'll try to say it another way... The "OpenSC" driver, on the one hand, provides the application with standard pkcs#11 calls and transforms them into an APDU that sends a token (card). The response from the card (in the form of an APDU) is then transformed into a response for a pkcs#11 call. 

Or I can think of another definition.. OpenSC ensures the transformation between pkcs#11 and ISO7816-4 (ISO7816-8, etc.) (but this is not a rule, there may be a token that doesn't conform to ISO7816 at all, but OpenSC implements all the necessary pkcs#11 calls on top of that token).

If there is a pkcs#11 library for your token, this library can be called from libp11 or from ssh or as an engine/provider for openssl, etc.

If your proprietary library does not suit you for any reason, you can try to rewrite this library in OpenSC..

**Comment by popovec** [comment]
How to start:
Publish your token documentation (detailed description of all APDUs) somewhere... 

then read ... 
https://github.com/OpenSC/OpenSC/wiki/Adding-a-new-card-driver

Try to compile this skeleton and gradually supplement it with the following functions:

1. try to write a procedure that identifies your card/token based on ATR or based on the selection of some AID... (match_card())
2. see how the init and finish functions are implemented for other cards - implement both so that they work with your token.
3. If the card supports ISO7816-4, and has pkcs#15 functions, use the default implementations from iso_ops->get_response, select_file etc.
4. You will probably have to write your own functions for create_file and process_fci
5. Write functions for verification and initialization of PINs
6. write the functions for MSE, for the signature, and if you have available wrap/unwrap operations or a symmetric cipher, write the corresponding functions for these operations.

It is ideal if you will carry out the development somewhere on github, the possible consultation will be much easier.

**Comment by nshah2588** [comment]
Dear @popovec 

Thank you for the guidance. I have created a new private repo (due to the confidentiality of the matter at hand) and added yourself as well as @mouse07410 to it.

Looking forward to collaborating

**Comment by popovec** [comment]
If it is to be an open source project, there is no reason to work in a private repo. And of course, until publicly available and high-quality documentation for the token is available, it makes no sense to look for open source developers for such a project. 

Try to look at the documentation for example  the MyEID card, (https://github.com/OpenSC/OpenSC/wiki/Aventra-MyEID-PKI-card reference manual)... publish a similar reference manual and you can expect your token to be well supported in the open source world.

**Comment by nshah2588** [comment]
Dear @popovec 

I understand where you are coming from. The only reason to make the repo private was that the APDUs that we have received from our vendor are under an NDA so we cannot expose them in the public domain. If there is another way to work this out please do advice.

**Comment by popovec** [comment]
In case the vendor forces me to solve something under NDA, it is an excellent moment to turn to another vendor. 

(If there is any closed proprietary software for the token, it is not a problem to capture the relevant APDUs, even at the USB level, and write an open source module based on them, the only problem is how many "unfortunate" workarounds will be created this way..)

**Comment by frankmorgner** [comment]
> How to start: Publish your token documentation (detailed description of all APDUs) somewhere...
> 
> then read ... https://github.com/OpenSC/OpenSC/wiki/Adding-a-new-card-driver
> 
> Try to compile this skeleton and gradually supplement it with the following functions:
> 
>     1. try to write a procedure that identifies your card/token based on ATR or based on the selection of some AID... (match_card())
> 
>     2. see how the init and finish functions are implemented for other cards - implement both so that they work with your token.
> 
>     3. If the card supports ISO7816-4, and has pkcs#15 functions, use the default implementations from iso_ops->get_response, select_file etc.
> 
>     4. You will probably have to write your own functions for create_file and process_fci
> 
>     5. Write functions for verification and initialization of PINs
> 
>     6. write the functions for MSE, for the signature, and if you have available wrap/unwrap operations or a symmetric cipher, write the corresponding functions for these operations.
> 
> 
> It is ideal if you will carry out the development somewhere on github, the possible consultation will be much easier.

Yes, this is the best way to start. If I understand correctly, then @nshah2588 and @shantanubindhani are even talking about yet another token. Anyway, since we have little to no information about the token to be added, we cannot do anything to support it in OpenSC.

If you have already done some efforts that you want to get reviewed, the best way to get feedback is to open a (publicly visible) pull request.

**Comment by DiegoRibeirodeSouza** [comment]
For anyone still watching this: the exact card reported here (`Giesecke & Devrient GmbH StarSign CUT S`, ATR `3b:f9:96:00:00:81:31:fe:45:53:43:45:37:20:0e:00:20:20:28`) is now supported. Opened a native driver (`card-starsign.c`) as PR #3764, currently under review — reverse-engineering notes and background are in the linked companion repo in the PR description.
