### ISSUE TITLE
OpenSC causes Firefox on Windows 11 to crash

### ISSUE THREAD

**Issue by xam-ps** [OpenSC/OpenSC#2603]
### Problem Description

OpenSC causes Firefox on Windows 11 to crash.

### Proposed Resolution

🤷‍♂️

### Steps to reproduce

I upgraded from Windows 10 to Windows 11. I had the same problems already month ago, which made me roll back to Windows 10. I was hoping the problem is solved by now...seems to be not.

I was using v0.20.0, but also after updating to v0.22.0 Firefox kept crashing.

https://bugzilla.mozilla.org/show_bug.cgi?id=1790233

I now completely uninstalled OpenSC and the crashes are gone.

### Logs

https://crash-stats.mozilla.org/report/index/4ce528d9-ce6a-498d-a019-0f31d0220911

**Comment by dengert** [comment]
Where you using a smart card at the time?
What card was it?

Can you try the build of https://github.com/OpenSC/OpenSC/pull/2600

The MSI files can be found by doing this:
- near the bottom of  https://github.com/OpenSC/OpenSC/pull/2600 go to "Some checks were not successful"
- scroll down to: "continuous-integration/appveyor/pr" 
- Click on details
- You will see a list of 8 jobs 
- Click on one of the 2017 jobs. (5th in for "Configuration: Release; Platform: x64" 4th job is for x86) 
- Click on "Artifacts"
- You will find two files. In this case:   https://ci.appveyor.com/api/buildjobs/cxo0ag2c5n08y0xq/artifacts/OpenSC-0.22.0_win64-Debug.zip and  https://ci.appveyor.com/api/buildjobs/cxo0ag2c5n08y0xq/artifacts/OpenSC-0.22.0_win64.msi


I am not very good with windows debug tools, but the zip files have the info to show routine names in an dump that you get.

What may be going on, is Windows 11 is treating any TPM or other crypto device as a smart card. 

Can you try some of the OpenSC tools to look at what readers/slots  are seen: `opensc-tool -l` or  `pkcs11-tool -L`

To produce a an OpenSC debug log see:
https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC
https://github.com/OpenSC/OpenSC/blob/master/etc/opensc.conf.example.in
C:\Program Files\OpenSC Project\OpenSC\opensc.conf
C:\Program Files (x86)\OpenSC Project\opensc.conf

**Comment by dengert** [comment]
> I was hoping the problem is solved by now...seems to be not.
Although you may have reported it to Mozilla AFAIK no one reported it to OpenSC.

I now have Windows 11 on ASUS TUF Z690-PLUS with I5-12600k with Firefox 104.0.2 and OpenSC from PR #2600
So far it appears to be working. 

To help identify the failure, can you give some details about when a failure occured?
- using a site that requests certificates?
- Was a a smart card in a reader? 
- inserting/removing a smart card?
- What type of card?
- doing nothing, it just crashes on its own?

On Firefox can you go to settings-> Privacy & Security -> Certificates -> Security Devices and look at OpenSC entries.

**Comment by frankmorgner** [comment]
It would be great if someone could expand the crash report given here
https://crash-stats.mozilla.org/report/index/4ce528d9-ce6a-498d-a019-0f31d0220911

with our debug symbols from here 
https://github.com/OpenSC/OpenSC/releases/download/0.22.0/OpenSC-0.22.0_win64-Debug.zip
https://github.com/OpenSC/OpenSC/releases/download/0.22.0/OpenSC-0.22.0_win32-Debug.zip

That would allow us to see where a possible problem may be

**Comment by dengert** [comment]
I could do it,  but how do you do it?  

https://github.com/xam-ps was the crash dump with 0.20.0 or 0.22.0?

**Comment by xam-ps** [comment]
The crashes occurred without a cardreader (and smartcard) being connected to the machine.

@dengert 
Regarding the version, I'm super sorry but I'm not sure anymore. I upgraded vom 0.20.0 -> 0.22.0 sometime on sunday (2022-09-11) morning. Some of the reports could not be sent right after the crash, that's also why they have the same timestamp.

https://crash-stats.mozilla.org/report/index/2410f0e3-bdfe-4eef-99d4-36e780220911
https://crash-stats.mozilla.org/report/index/d8e68452-bc32-4cb1-ad48-ba4b30220911
https://crash-stats.mozilla.org/report/index/870a576a-bf17-41db-afc2-7c9f80220911

They all came from my machine.

**Comment by dengert** [comment]
The three Crash reports under "Modules" all show 0.20.0.0:

<html>
<body>


onepin-opensc-pkcs11.dll | 0.20.0.0 | 77CA4D84E55C45CBB2AB63D77906CA6E1 | onepin-opensc-pkcs11.pdb
-- | -- | -- | --


<br class="Apple-interchange-newline">
</body>
</html>
On the "Crash Anotations" the "CrashTime" are all different and "InstallTime" are all the same.

On the 'Raw Data and Minidumps": "minidump-stackwalk output" does not have enough info to match up the line numbers to  the OpenSC Debug pdb files. Mozilla will not allow us to see the actual dump See: [protected data access documentation](https://crash-stats.mozilla.org/documentation/protected_data_access/)

Do you have any of the crash dumps available? Are you willing to attach one of them to  this OpenSC issue?

We would really like to see a failure using 0.22.0, as 0.20.0 is 3 years old.

**Comment by xam-ps** [comment]
I just reinstalled 0.22.0 again. Let's see what's happening. When I uninstalled both because of the crashes, I could uninstall 0.20.0 but when I tried to uninstall 0.22.0 I got a notification that I have to close Firefox first. So I think 0.22.0. was used by Firefox in the end. Not sure though, if having installed both version could have had an effect on the new version.

**Comment by dengert** [comment]
You can only have one version of OpenSC at a time. All versions of OpenSC installs in the same directories.  64 bit in "Program Files" 32 bit in "Program Files(x86)".  I always uninstall OpenSC before installing an other version to avoid any problems. 

When OpensSC is installed and a Firefox profile can be found, OpenSC will add the security device i.e. the PKCS11 module.  You can see or edit these these by going to Settings->Privacy & Security-> Security Devices. If you OpenSC 32 bit and 64 bit you will see both. "Load is to add a new PKCS11 module, unload is to delete the entry in your profile. 

You can also look at your profile: https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data to find the pkcs11.txt file.  
On my machine that is: "C:\Users\doug\AppData\Roaming\Mozilla\Firefox\Profiles\mwik0yso.default-release\pkcs11.txt"
```
library=
name=NSS Internal PKCS #11 Module
parameters=configdir='sql:C:\\Users\\doug\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\mwik0yso.default-release' certPrefix='' keyPrefix='' secmod='secmod.db' flags=optimizeSpace updatedir='' updateCertPrefix='' updateKeyPrefix='' updateid='' updateTokenDescription='' 
NSS=Flags=internal,critical trustOrder=75 cipherOrder=100 slotParams=(1={slotFlags=[ECC,RSA,DSA,DH,RC2,RC4,DES,RANDOM,SHA1,MD5,MD2,SSL,TLS,AES,Camellia,SEED,SHA256,SHA512] askpw=any timeout=30})

library=C:\Program Files\OpenSC Project\OpenSC\pkcs11\onepin-opensc-pkcs11.dll
name=OpenSC smartcard framework (0.22)

library=C:\Program Files (x86)\OpenSC Project\OpenSC\pkcs11\onepin-opensc-pkcs11.dll
name=OpenSC smartcard framework (0.22)
```
 A reboot is required because OpenSC 0.22.0 adds a notification service.

But after the restart then entries in pkcs11.txt are not removed.
And FireFox will look for the module, but skip it if not found. 

You have not said if you have a smartcard you want to use with OpenSC without FireFox  or with FireFox and OpenSC. 
FireFox also has a "C:\Program Files\Mozilla Firefox\osclientcerts.dll"

This does not show up in the pkcs11.txt but does in the Security Devices" It uses the Windows smart card facilities.
https://docs.microsoft.com/en-us/windows/security/identity-protection/smart-cards/smart-card-architecture

OpenSC also installs a  "minidriver" that is called by the Windows smart card facilities. You can see this in registry:
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards`

So what we might be seeing is both PKCS11 and  Windows smartcard facilities are being called, and some interference. 

Windows also supports TPM and there is a way to use the TPM as a smartcard. Don't know if this is an issue or not. 

There was a lot of code added to OpenSC after 0.20.0 and in in 0.22.0 to deal with Firefox and slots. So if you do anything else
use OpenSC 0.22.0.

**Comment by xam-ps** [comment]
So what I did on Sunday:
- I did not remove 0.20.0
- I installed 0.22.0
- I did not reboot Windows, only restarted Firefox
- In the "Programs and Features" sections both versions did show up
- I was able to uninstall 0.20.0 while Firefox was running (for 0.22.0 uninstalling was now not possible anymore while running Firefox), that's why I though 0.22.0 is in use
- I remove 0.22.0 -> no crashes anymore

What I did now:
- Install 0.22.0 again
- Smartcard is working
- No crashes

So sorry for wasting everyone's time and thank you for the help!
Maybe for the future the installer could remove the old version before installing the new version? I think this is common with quite a lot of applications - just an idea ;)

**Comment by dengert** [comment]
Good to hear it works.
