### ISSUE TITLE
PKCS11Provider of OpenSC in ssh_config does not work when loaded in SSH agent

### ISSUE THREAD

**Issue by jasonlyle88** [OpenSC/OpenSC#2613]
### Problem Description
I have the following entries in my OpenSSH config

```
Host jumphost.instance-*
    User                    myuser
    PKCS11Provider          /usr/local/lib/opensc-pkcs11.so

Host targethost.instance-*
    User                    myuser
    PKCS11Provider          /usr/local/lib/opensc-pkcs11.so

Host my-tunnel
    HostName                targethost.instance-abc
    ProxyJump               jumphost.instance-abc,jumphost.instance-def
    LocalForward            *:1522 255.255.255.255:1522
    PKCS11Provider          /usr/local/lib/opensc-pkcs11.so
    ServerAliveInterval     180
    ExitOnForwardFailure    yes
    ControlMaster           auto
    ControlPath             ~/.ssh/tunnels/%C
```

And this works just fine. I have to enter my pin for each of the hosts (3 times total in this case: 2x for jump hosts and 1x for the target host).

The problem starts when I add my YubiKey to my ssh agent. If I add my YubiKey to my ssh-agent (`ssh-add -s /usr/local/lib/opensc-pkcs11.so`) and try to connect, the connection fails.

If I keep my YubiKey loaded in my SSH agent and comment out the `PKCS11Provider` line in the 3 host specifications above, then the connection works just fine.

### Proposed Resolution
I would have expected to be able to leave the PKCS11Provider in the OpenSSH config file and have it automatically go through the SSH agent first. If that fails, I would then expect it to go directly to the hardware token.

### Steps to reproduce
See above

### Logs
This dropbox link points to a log file taken at log level 3. I was unsure about what was considered sensitive information, so I replaced anything that could be sensitive with `[**~REDACTED~**]`. Happy to provide more detailed logs or more information if needed.

https://www.dropbox.com/s/nyl21vozxcpemp6/opensc_output_debug_3.log?dl=0

**Comment by Jakuje** [comment]
The pkcs11 module accessed from ssh process resets login state in the ssh-agent process, which causes the failures, I think. It would be nice if it would work like you describe, but the OpenSSH reads the keys in its process before consulting the agent and regardless the agent has the requested keys so only one of the ways is valid (card in agent or in configuration file). Additionally, the agent is stupid enough that it can not ask for the pin when this happens nor it can not cache the pin. I wrote a patch for openssh to solve this 4 years ago, but it is still not merged: https://bugzilla.mindrot.org/show_bug.cgi?id=2890

If this is an issue for you, please, urge the OpenSSH developers to get the patch merged or solve it somehow else. The issue is annoying not only for you, but for many others, but there is nothing OpenSC could do to improve here, as far as I know.

**Comment by jasonlyle88** [comment]
Thanks so much for the quick reply. Not the first time I've come across this OpenSSH bug posting. I've added a comment to the bug to start... might get a little more annoying about it in the future depending on how/if the OpenSSH team responds.

Thanks for your work!

As I don't see there being anything you feel you can do here, I will go ahead and close this issue.
