### ISSUE TITLE
pkcs11-tool: list_objects not passing in object class template?

### ISSUE THREAD

**Issue by dlegaultbbry** [OpenSC/OpenSC#2627]
### Problem Description

Is there a reason pkcs11-tool list_objects doesn't pass in a template with the object class directly rather than getting all objects and then checking if the class matches? Seems like this is what the API intended all along.

https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L4613

Related to this, it seems impossible to list a reduced item set matching other criteria. Would it be desirable to take input parameters such as label, id, type, etc. and assemble a proper template to pass for the search and allow listing objects matching the sub-criteria?

**Comment by Jakuje** [comment]
I assume this is because the list_objects was introduced to list all objects and functionality to filter by the type was introduced only later and without giving a though that there might be a better way to do that. I think allowing the filtering by other parameters would be also helpful. Contributions are welcomed.

**Comment by dlegaultbbry** [comment]
Sounds good, I'll check into adding this functionality.
