### ISSUE TITLE
Missing `opensc-notify` during OpenSCToken build in OSX workflow

### ISSUE THREAD

**Issue by xhanulik** [OpenSC/OpenSC#2632]
### Problem Description
Currently, OSX CI fails on the build of OpenSCToken because of missing `opensc-notify`. Building of `opensc-notify` when dependencies are missing was removed in #2617.

When building OpenSCToken
https://github.com/OpenSC/OpenSC/blob/7eb0ec34c87fee640d977fdc396feca3bbb30217/MacOSX/build-package.in#L197-L200

In OpenSCToken, notify is [disabled with `--disable-notify`](https://github.com/frankmorgner/OpenSCToken/blob/4d6e2bba9fcec9701d0cc2dc9918a0dcb0505f0d/bootstrap#L53) and therefore `opensc-notify` is not built.

### Proposed Resolution
Removing `opensc-notify` references from OpenSCToken, but I'm not that familiar with OpenSCToken.

**Comment by Jakuje** [comment]
or removing the `--disable-notify` from the OpenSCToken build script. What do you think @frankmorgner ? Should and do the Mac builds have the notify support or not?

**Comment by frankmorgner** [comment]
It is not about opensc-notify, it is about the code that doesn't get compiled in https://github.com/OpenSC/OpenSC/blob/7eb0ec34c87fee640d977fdc396feca3bbb30217/src/ui/notify.c. This hinders the CTK App Extension from *sending* notification, even though `opensc-notify` is actually running, because it was built (and installed) based on [a different configuration](https://github.com/OpenSC/OpenSC/blob/7eb0ec34c87fee640d977fdc396feca3bbb30217/MacOSX/build-package.in#L81-L92) that does *not* disable notifications.

Could you clearify on which CI fails? I think building and running the macos software should work just fine. The only problem should be that no notification will be shown.

In any case, I think just removing --disable-notify from the `bootstrap` script in OpenSCToken should be done.

**Comment by Jakuje** [comment]
> It is not about opensc-notify, it is about the code that doesn't get compiled in https://github.com/OpenSC/OpenSC/blob/7eb0ec34c87fee640d977fdc396feca3bbb30217/src/ui/notify.c. This hinders the CTK App Extension from _sending_ notification, even though `opensc-notify` is actually running, because it was built (and installed) based on [a different configuration](https://github.com/OpenSC/OpenSC/blob/7eb0ec34c87fee640d977fdc396feca3bbb30217/MacOSX/build-package.in#L81-L92) that does _not_ disable notifications.
> 
> Could you clearify on which CI fails? I think building and running the macos software should work just fine. The only problem should be that no notification will be shown.

In github actions on master right now: https://github.com/OpenSC/OpenSC/commit/7eb0ec34c87fee640d977fdc396feca3bbb30217
https://github.com/OpenSC/OpenSC/actions/runs/3360389358/jobs/5569524582

> In any case, I think just removing --disable-notify from the `bootstrap` script in OpenSCToken should be done.

Can you push the changes and rerun the above pipeline?

**Comment by frankmorgner** [comment]
I see, that's due to opensc-notify being hard coded in the OpenSCToken's project file. Removing --disable-notify will make this work again.
