### ISSUE TITLE
`opensc-tool --serial` fails with SC-HSM v4.0 card

### ISSUE THREAD

**Issue by ojo2000** [OpenSC/OpenSC#2648]
### Problem Description

Reading a _SmartCard-HSM v4.0_ serial number via `opensc-tool` returns an error.

### Steps to reproduce

```
$ opensc-tool --serial --verbose
Using reader with a card: REINER SCT cyberJack RFID komfort (<ELIDED>) 00 00
Connecting to card in reader REINER SCT cyberJack RFID komfort (<ELIDED>) 00 00...
Using card driver SmartCard-HSM.
Card serial number:sc_card_ctl(*, SC_CARDCTL_GET_SERIALNR, *) failed
```

### System

* Ubuntu 22.04
* `opensc` package version: 0.22.0-1ubuntu2
* card reader: Reiner SCT cyberJack komfort
* driver package version: `libifd-cyberjack6` 3.99.5final.sp14-2
* smart card type:
```
$ opensc-tool --name
Using reader with a card: REINER SCT cyberJack RFID komfort (<ELIDED>) 00 00
SmartCard-HSM version 4.0
```

**Comment by frankmorgner** [comment]
@CardContact ?

**Comment by CardContact** [comment]
The SmartCard-HSM driver does not support SC_CARDCTL_GET_SERIALNR, simply because a SmartCard-HSM does not have a serial number.

Instead each device has a Device Certificate as per TR-03110, which contains in the CHR field an unique identifier (Unique in the context of the issuing Device Issuer CA).

The CHR is reported with

    asc@caprese:~$ pkcs11-tool -L
    Available slots:
    Slot 1 (0x4): Identiv uTrust 3512 SAM slot Token [CCID Interface] (55511822...
      token label        : SmartCard-HSM (UserPIN)
      token manufacturer : www.CardContact.de
      token model        : PKCS#15 emulated
      token flags        : login required, rng, token initialized, PIN initialized
      hardware version   : 24.13
      firmware version   : 4.0
      serial num         : UTCC0100790
      pin min/max        : 6/15

or

    asc@caprese:~$ pkcs15-tool --list-info
    Using reader with a card: Identiv uTrust 3512 SAM slot Token [CCID Interface] (55511822604216) 00 00
    PKCS#15 Card [SmartCard-HSM]:
           Version        : 0
           Serial number  : UTCC0100790
           Manufacturer ID: www.CardContact.de
           Flags          :

**Comment by CardContact** [comment]
Little precision here: The driver supports SC_CARDCTL_GET_SERIALNR, but only after the PKCS#15 layer has been initialized, the device certificate was read and parsed to obtain the CHR.

The opensc-tool does not initialize the PKCS#15 layer, which is why the serial number is not set in the low-level driver.

**Comment by ojo2000** [comment]
No problem with the serial number not being available with those cards per that command.  Just saying that seeing a message that looks like the result of an assertion is irritating for end users.
