### ISSUE TITLE
T1 is slower than T0 with opensc-pkcs11.dll

### ISSUE THREAD

**Issue by Muzosh** [OpenSC/OpenSC#2673]
### Problem Description

Hi, I have been doing some research with [PivApplet](https://github.com/arekinath/PivApplet) via OpenSC PKCS#11 library and YubiKey YKCS#11 library (PivApplet is compatible with Yubi-defined PIV extensions for card management).

There was one curiosity: with `opensc-pkcs.dll`, the T1 card is slower than T0 card. This is not the case with other p11 library, where T1 is faster, which is expected. 

Here are the results:
| (all times are in [ms])       	| opensc-pkcs11 	| ykcs11  	|
|-----------------------------	|---------------	|---------	|
| **T0** card with 1 cert loaded  	| 1057.82       	| 5451.78 	|
| **T0** card with 4 certs loaded 	| 1446.06       	| 7310.35 	|
| **T1** card with 1 cert loaded  	| 1102.34       	| 3292.79 	|
| **T1** card with 4 certs loaded 	| 1715.84       	| 4567.97 	|

As you can see, via openSC library, the operations (see Logs) are still faster when compared to ykcs11 (mainly because there is no overhead with the YUBI defined functions, just pure PIV commands), however the T0 times are faster than T1 times in the second column. This is strange and is the reason I'm writing this issue.

### Logs
For clarity, here are the operations in sequence in my test:

| Operation                                                                                                	|
|----------------------------------------------------------------------------------------------------------	|
| Library unloading (C_Finalize)                                                                           	|
| Library loading (C_GetFunctionList, C_Initialize)                                                        	|
| Getting slot (2x C_GetSlotList, Xx C_GetSlotInfo)                                                        	|
| Getting token (C_GetTokenInfo)                                                                           	|
| Obtain session (C_OpenSession)                                                                           	|
| List all certificates (C_FindObjectsInit, 1x/4x C_FindObjects, C_FindObjectsFinal)                       	|
| Get right certificate (2x/8x C_GetAttributeValue)                                                        	|
| Log in (C_Login)                                                                                         	|
| Obtain private key handle (2x C_GetAttributeValue, C_FindObjectsInit, C_FindObjects, C_FindObjectsFinal) 	|
| Create digital signature (2x C_GetAttributeValue, C_SignInit, 2x C_Sign)                                 	|
| Log out and close session (C_Logout, C_CloseSession)                                                     	|

Here are the log files:
[PIV_OPENSC.module.T0.log](https://github.com/OpenSC/OpenSC/files/10344875/PIV_OPENSC.module.T0.log)
[PIV_OPENSC.pkcs11spy.T0.log](https://github.com/OpenSC/OpenSC/files/10344877/PIV_OPENSC.pkcs11spy.T0.log)

[PIV_OPENSC.module.T1.log](https://github.com/OpenSC/OpenSC/files/10344876/PIV_OPENSC.module.T1.log)
[PIV_OPENSC.pkcs11spy.T1.log](https://github.com/OpenSC/OpenSC/files/10344873/PIV_OPENSC.pkcs11spy.T1.log)

Or gist with mentioned log files: https://gist.github.com/Muzosh/1ffefea6d5015723f7b6ae6d730cba8f

**Comment by dengert** [comment]
PIV uses GET DATA commands where the size of the data to be read is contained in the TLV in the first few bytes.
ISO has two GET DATA commands  with odd and even numbers where 
PIV GET DATA  uses CB (odd) where the response is "BER-TLV tag of the data object to be retrieved. See Table 3, Part 1.)

The OpenSC internals for APDU processing assume the caller will provide a buffer big enough to handle the response, but PIV object could be as large as 16K, So the current PIV driver reads the first few bytes, to get the size needed,  allocates the buffer and starts the read over. In some cases this will cause the reader of card to read 256 bytes or more to get the size.

What should happen, is the OpenSC internals for APDU should support the reading of objects with dynamic allocation of the buffer for the GET DATA odd number (There are a few other commands that could use dynamic allocaion of the buffer too.) At the time the PIV driver was first written no other card needed dynamic buffer allocation, so I never pushed to have this feature in apdu.c and  reader.c and possibly pcsc. 

[PIV Secure Messaging as defined in NIST 800-73-4](https://github.com/OpenSC/OpenSC/pull/2053) include many changes of which on it to have PIV driver allocate a large buffer to avoid having to read any of the data twice. 

So if you want to see the difference please try #2053

(If you questioning the YubiKey times, It is not an OpenSC issue.)

**Comment by frankmorgner** [comment]
I've looked at the data and cannot confirm your observation that T=1 is slower than T=0 as a general statement.

First of all, your initial report misses the first call to C_Initialize. It should have looked something like this: 

| Operation                                                                                                	|
|----------------------------------------------------------------------------------------------------------	|
| **Library loading (C_Initialize) (was missing initially)**                                                                        	|
| **Library unloading (C_Finalize)**                                                                          	|
| Library loading (C_GetFunctionList, C_Initialize)                                                        	|
| Getting slot (2x C_GetSlotList, Xx C_GetSlotInfo)                                                        	|
| Getting token (C_GetTokenInfo)                                                                           	|
| Obtain session (C_OpenSession)                                                                           	|
| List all certificates (C_FindObjectsInit, 1x/4x C_FindObjects, C_FindObjectsFinal)                       	|
| Get right certificate (2x/8x C_GetAttributeValue)                                                        	|
| Log in (C_Login)                                                                                         	|
| Obtain private key handle (2x C_GetAttributeValue, C_FindObjectsInit, C_FindObjects, C_FindObjectsFinal) 	|
| Create digital signature (2x C_GetAttributeValue, C_SignInit, 2x C_Sign)                                 	|
| Log out and close session (C_Logout, C_CloseSession)                                                     	|

Then, looking into the spy logs, we can see that only the first two calls (above in **bold**)  T=0 is faster than T=1. In all other cases, and specifically in the chain of calls you actually wanted to test, T=1 is faster. It seems that in the first run the delay is actually caused by the GET DATA commands that retrieve the certificates from the card, for example.

AFAICS, the OpenSC module doesnt carry any cache from the first run to the second. However, the card is not reset after C_Finalize. This would allow the **card** (or applet) to preserve some cache from the first run to the second. Or, of course, it could simply be caused by some hardware problem (e.g. bad coupling with a contact-less card).

**Comment by frankmorgner** [comment]
[t0.t1.ods](https://github.com/OpenSC/OpenSC/files/10451250/t0.t1.ods)

**Comment by dengert** [comment]
I would also like to point out  card-piv.c reads all 4 certificates when card is first seen while `opensc-pkcs11` is loaded, or during C_Initialize (This is to get the public keys from the certificates which have the key type and size or curve.) So any timing calculations made based on PKCS11 calls do not include any time for loading the certificates. 

A better comparison would be of similar times in logs to read the certificates.  

- [T0](https://github.com/OpenSC/OpenSC/files/10344875/PIV_OPENSC.module.T0.log) case:
line  180 P:14924; T:20388 2023-01-04 14:48:46.701 [opensc-pkcs11] reader-pcsc.c:324:pcsc_transmit:
Outgoing APDU (10 bytes):
00 CB 3F FF 05 5C 03 5F C1 05   (T0 with no Le)
Incomming status 61FF  
Get Response then reads 256 bytes, at line 204. 
line 2668 P:14924; T:20388 2023-01-04 14:48:52.241 [opensc-pkcs11] All tokens created
**This is 5.54 seconds.**
and 2,488 lines in log


- [T1](https://github.com/OpenSC/OpenSC/files/10344876/PIV_OPENSC.module.T1.log) case:
Line 633  P:3340; T:5092 2023-01-04 14:56:19.927 [opensc-pkcs11] reader-pcsc.c:324:pcsc_transmit:
Outgoing APDU (11 bytes):
00 CB 3F FF 05 5C 03 5F C1 05 08   (he is for 8 bytes to get length of object.) 
incomming
53 82 03 1F 70 82 03 16 61 FF      (First 8 bytes: T=53 L=2 V=031F so length total length is 031F+2.status 61 FF to say there is more. 
line 3046 P:3340; T:5092 2023-01-04 14:56:25.632 [opensc-pkcs11] All tokens created
**This is 5.705 seconds**
and 2,413 lines in log. 

These are wall clock times, so other factors may be in play. 

As I said before, If you want this to run faster, have you looked at https://github.com/OpenSC/OpenSC/pull/2053
