### ISSUE TITLE
Unable to reset user-pin with so-pin if user-pin is locked

### ISSUE THREAD

**Issue by anchpop** [OpenSC/OpenSC#2737]
### Problem Description

After mis-entering my user PIN one too many times, my pin appears to be locked:

```
❯ pkcs11-tool --list-slots
Available slots:
Slot 0 (0x0): Nitrokey Nitrokey HSM
  token label        : SmartCard-HSM (UserPIN)
  token manufacturer : www.CardContact.de
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized, user PIN locked
  hardware version   : 24.13
  firmware version   : 3.4
  serial num         : DENK0105461
  pin min/max        : 6/15
``` 

I found #686, where someone had a similar problem, and @CardContact suggested this command, but it doesn't work for me:

```
❯ pkcs11-tool --login --login-type so --so-pin=**************** --init-pin --new-pin=648219   
Using slot 0 with a present token (0x0)
error: PKCS11 function C_InitPIN failed: rv = CKR_PIN_LOCKED (0xa4)
Aborting.
```

I'm pretty sure that my so-pin is correct, but I can't test it with the `--test` command due to a `CKR_SESSION_HANDLE_INVALID` error:

```
❯ pkcs11-tool --login --login-type so --so-pin=*************** --test                     
Using slot 0 with a present token (0x0)
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
error: PKCS11 function C_OpenSession failed: rv = CKR_SESSION_HANDLE_INVALID (0xb3)
Aborting.
```

I thought `--init-pin` didn't seem like the right command, so I tried `--change-pin`, which `pkcs11-tool --help` claims can be used to change the user pin. However, it seems to be changing the so-pin, since it complains about `CKR_PIN_LEN_RANGE`.

```
❯ pkcs11-tool --login --login-type so --so-pin=**************** --change-pin --new-pin=******          
Using slot 0 with a present token (0x0)
error: PKCS11 function C_SetPIN failed: rv = CKR_PIN_LEN_RANGE (0xa2)
Aborting.
```

### Steps to reproduce

Get a `Nitrokey Nitrokey HSM`, lock yourself out of your pin, then try to reset it.

**Comment by frankmorgner** [comment]
@CardContact ?

**Comment by spfendtner** [comment]
I have a similar problem but by SO-PIN is not locked: 
`pkcs11-tool --login --login-type so --so-pin=3537363231383830 --init-pin --new-pin=648210`
`Using slot 0 with a present token (0x0)`
`error: PKCS11 function C_InitPIN failed: rv = CKR_TOKEN_NOT_RECOGNIZED (0xe1)`
`Aborting.`

I compared this with a new token with the same firmware (4.0). It does work for the standard usage. But it does not work for my token which was initialized with smartcard shell and DKEK shares to load backuped p12 files.

sc-hsm-tool looks like this:
`sc-hsm-tool `
`Using reader with a card: Identiv uTrust 3512 SAM slot Token [CCID Interface] (xxxx) 00 00`
`Version              : 4.0`
`Config options       :`
`  User PIN reset with SO-PIN enabled`
`SO-PIN tries left    : 13`
`User PIN locked`
`DKEK shares          : 1`
`DKEK key check value : xxxx`

Debugging the APDUs show that the token responds with 6A 81 instead of 90 00 for the InitPin call:
`APDU: 00 2C 00 81 0E 35 37 36 32 31 38 38 30 36 34 38 32 31 30`
`SW: 6A 81`

Looks like the selected option "User PIN reset with SO-PIN enabled" is not working inside the token!

**Comment by frankmorgner** [comment]
please contact the vendor directly
