### ISSUE TITLE
New release 0.24.0

### ISSUE THREAD

**Issue by kloczek** [OpenSC/OpenSC#2792]
https://github.com/OpenSC/OpenSC/compare/0.23.0...master shows +250 commits since last release. Amongst those commits are some critical fixes.

Do you have any plans to release new version soon? 🤔

**Comment by Jakuje** [comment]
I was hoping to have one later this summer. I think we can not make it more frequently than once a year.

I created https://github.com/OpenSC/OpenSC/projects/12 last week that can collect what we would like to include or not.

Can you point out the critical fixes?

**Comment by kloczek** [comment]
Thank you 👍 
Looking on current rate of commits I think that best would be good to have one minor release per 3-4 months .. just to flush set of already committed fixes/improvements/updates.

**Comment by xhanulik** [comment]
This is a draft of release notes for 0.24.0, summarising new changes from the last release. Please, feel free to fix or propose other changes which should be included.

---

## General improvements
* Fix compatibility of EAC with OpenSSL 3.0 (https://github.com/OpenSC/OpenSC/pull/2674)
* Enable `use_file_cache` by default (https://github.com/OpenSC/OpenSC/pull/2501)
* Use custom libctx with OpenSSL >= 3.0 (https://github.com/OpenSC/OpenSC/pull/2712, https://github.com/OpenSC/OpenSC/pull/2715)
* Fix record-based files (https://github.com/OpenSC/OpenSC/pull/2604)
* Fix several race conditions (https://github.com/OpenSC/OpenSC/pull/2735)
* Run tests under Valgrind (https://github.com/OpenSC/OpenSC/pull/2756)
* Test signing of data bigger than 512 bytes (https://github.com/OpenSC/OpenSC/pull/2789)
* Update to OpenPACE 1.1.3 (https://github.com/OpenSC/OpenSC/pull/2796)
* Fixed various issues reported by OSS-Fuzz and Coverity regarding card drivers, PKCS#11 and PKCS#15 init

## PKCS#11
* Check card presence state in `C_GetSessionInfo` (https://github.com/OpenSC/OpenSC/pull/2740)

## PKCS#15
* Fix PIN authentication bypass when card in authenticated state (https://github.com/OpenSC/OpenSC/pull/2806)

## pkcs11-tool
* Fix RSA key import with OpenSSL 3.0 (https://github.com/OpenSC/OpenSC/pull/2656)
* Add support for attribute filtering when listing objects (https://github.com/OpenSC/OpenSC/pull/2687)
* Add support for `--private` flag when writing certificates (https://github.com/OpenSC/OpenSC/pull/2768)

## westcos-tool
* Generate 2k RSA keys by default (https://github.com/OpenSC/OpenSC/commit/b53fc5cdb326d2a3f101980be2a0ae3537617037)

## pkcs11-register
* Disable autostart on Linux by default (https://github.com/OpenSC/OpenSC/pull/2680)

## IDPrime
* Add support for IDPrime MD 830, 930 and 940 (https://github.com/OpenSC/OpenSC/pull/2666)
* Add support for SafeNet eToken 5110 token (https://github.com/OpenSC/OpenSC/pull/2812)

## EPass2003
* Change of PIN requires verification of the PIN (https://github.com/OpenSC/OpenSC/pull/2759)
* Use true random number for mutual authentication for SM (https://github.com/OpenSC/OpenSC/pull/2766)
* Add verification of data coming from the token in the secure messaging mode (https://github.com/OpenSC/OpenSC/pull/2772)

## OpenPGP
* Fix select data command (https://github.com/OpenSC/OpenSC/pull/2753, issue https://github.com/OpenSC/OpenSC/issues/2752)

## eOI
* Add support for Slovenian eID card (eOI) (https://github.com/OpenSC/OpenSC/pull/2646)

## Italian CNS
* Add support for IDEMIA (Oberthur) tokens (https://github.com/OpenSC/OpenSC/pull/2483)

## PIV
* Add support for Swissbit iShield FIDO2 Authenticator (https://github.com/OpenSC/OpenSC/pull/2671)

## SkeID
* Add support for Slovak eID cards (https://github.com/OpenSC/OpenSC/pull/2672)

## isoApplet 
* Support ECDSA with off-card hashing (https://github.com/OpenSC/OpenSC/pull/2642)

## MyEID
* Fix WRAP operation when using T0 (https://github.com/OpenSC/OpenSC/pull/2695)
* Identify changes on the card and enable `use_file_cache` (https://github.com/OpenSC/OpenSC/pull/2798)

## SC-HSM
* Add support for `opensc-tool --serial` (https://github.com/OpenSC/OpenSC/pull/2675)
* Fix unwrapping of 4096 keys with handling reader limits (https://github.com/OpenSC/OpenSC/pull/2682)

**Comment by kloczek** [comment]
LGTM 👍

**Comment by frankmorgner** [comment]
I've updated https://github.com/OpenSC/OpenSC/projects/12 with the missing pieces.

We still have some things to do regarding the fixed security issues. @Jakuje, would it be possible for you to review and request possible CVEs with Red Hat's support (see the project's cards that are still *To Do*)? If needed, you may re-use some of the descriptive CVE text blocks for a possible security advisory in the wiki.

Unfortunately, we didn't make any progress regarding [signed OpenSC release packages](https://github.com/OpenSC/OpenSC/issues/1129). I don't think we be able will finish #2799 for this release. macOS binaries are signed by Tim Wilbrink, but we didn't set up notarizion. Signed source code packages make sense with its git integration, which is still planned to be reviewed by @Jakuje.

Thanks, @xhanulik , for providing a draft for the release notes. Please remember to synchronize this once project cards are *done* which are currently *in progress*.

**Comment by Jakuje** [comment]
Sorry for a delay. I can certainly put together some advisory drafts and ask for CVE numbers in coming week after I will go through the oss-fuzz issues and the auth bypass. 

Regarding to the #1129 my take would be just to provide a signature on the final tarball using one of our PGP keys. But given the mess in which PGP is I am not using it on daily/weekly basis I was setting it up already several times (on yubikey) and I am not sure if it works right now or if it did not expire. Last time I did [sign libcacard](https://gitlab.freedesktop.org/spice/libcacard/-/releases/v2.8.1). Would have to check.

**Comment by frankmorgner** [comment]
Is it correct that we don't have any outstanding coverity issues?! :rocket:

**Comment by Jakuje** [comment]
> Is it correct that we don't have any outstanding coverity issues?! rocket

The dashboard says 9. I squashed most of the outstanding in #2817. There are some low-priority and long standing ones though that I either skipped or ignored.

**Comment by frankmorgner** [comment]
I am also seeing the info on the dashboard, but in the "View Defects" the category "Issues: By Snapshot | Outstanding Issues" is totally empty...

**Comment by Jakuje** [comment]
I am attaching security advisories drafts. I would go ahead with two separate ones. One for the PIN bypass and the other for the oss-fuzz and coverity reported issues. Feel free to propose changes. I just went ahead to test that the zero-lenght pin are indeed not able to exploit the screen unlock on Linux (with fresh install + new yubikey 5) and I was not able to get in so I would propose to communicate it as it affects only the MacOS, though, keeping the CVSS score high.

--------

# Potential PIN bypass  (#2806, frankmorgner/OpenSCToken#50, #2807)

When the token/card was plugged into the computer and autenticated from one process, it could be used to provide cryptographic operations from different process when the empty, zero-length PIN. This is dangerous for OS logon/screen unlock and small tokens that are plugged permanently to the computer. The bypass was removed and OpenSC implemented explicit logout for most of the card drivers to prevent leaving unattended logged-in tokens.

The PoC is available for MacOS screen unlock bypass. Other tested applications (firefox, sssd, ...) seems to reject zero-length pin even before reaching out to the PKCS#11 module so they should not be affected.

CVSS:3.0/[AV:P/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:H](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:P/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:H&version=3.0) (7.3)


# Static and dynamic analyzers reports

This advisory summarizes automatically reported issues that are security relevant that were reported since the release of OpenSC 0.23.0. All of these require physical access to the computer running opensc and crafted USB device or smart card that would present the system with specially crafted answers so they are considered a high-complexity and low-severity.

## Security-related oss-fuzz issues

 * https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60971 Heap buffer overflow in the test code -- ignore
 * Stack buffer overflow in sc_pkcs15_get_lastupdate
   * https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60769 
   * https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60527
 * https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60672 Heap buffer overflow in setcos_create_key
 * https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60650 Heap buffer overflow in cosm_new_file
 * https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60616 Heap double free in sc_pkcs15_free_object_content
 * https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58932 Stack buffer overflow in cflex_delete_file
 * https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56213 Heap buffer overflow in sc_hsm_write_ef
 * Stack buffer overflow while parsing pkcs15 profile files
   * https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55998 
   * https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55851
 * https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54312 Stack buffer overflow in muscle driver
 * https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53927 Stack buffer overflow in cardos driver for pkcs15init

## High severity coverity issues

 * CID 382262: Memory leak. Fixed with 739fa81050989c3f85ca883ec76542b71cae7edc  Why this memory leak in SM is high? I would skip this one.
 * CID 380538: Out-of-bounds read in MyEID handling of encryption using symmetric keys. Fixed with f1993dc4e0b33050b8f72a3558ee88b24c4063b2

CVSS:3.0/[AV:P/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:P/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N&version=3.0) (3.1)

**Comment by frankmorgner** [comment]
>-  CID 382262: Memory leak. Fixed with https://github.com/OpenSC/OpenSC/commit/739fa81050989c3f85ca883ec76542b71cae7edc Why this memory leak in SM is high? I would skip this one.
>-  https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60971 Heap buffer overflow in the test code -- ignore

I agree to skip both of these issues.

As far as I can see, all of the issues from coverity and oss-fuzz can only be triggered by a specially crafted rogue smart card. Since this limits the attack vector for exploiting these problems, I think it is useful to mention this in the security advisory. (We could use some phrasing of one of our previous advisories on this kind of problems.)

**Comment by Jakuje** [comment]
Updated the previous comment:

 * removed the two unrelated issues
 * Clarified the wording of the issue. I tried to start from https://github.com/OpenSC/OpenSC/wiki/OpenSC-security-advisories but did not find any of them verbose and specific enough. What do you think about this wording (already part of of the previous comment):

> All of these require physical access to the computer running opensc and crafted USB device or smart card that would present the system with specially crafted responses to the APDUs so they are considered a high-complexity and low-severity.

**Comment by frankmorgner** [comment]
Yes, very good, thank you!

**Comment by manu0401** [comment]
As requested in [#2832](https://github.com/OpenSC/OpenSC/issues/2832), here is the p11 test output for Athena ASE III, which uses the asepcos driver:

[athena_ase_III.json.txt](https://github.com/OpenSC/OpenSC/files/12359717/athena_ase_III.json.txt)

**Comment by dlegaultbbry** [comment]
Feel free to add the latest round of pkcs11-tool fixes that cropped up recently if judged noteworthy enough.

**Comment by Jakuje** [comment]
The rc1 is out: https://github.com/OpenSC/OpenSC/releases/tag/0.24.0-rc1

The testing of the installers and different cards welcomed. Please, share the results as PR to the following wiki page:

https://github.com/OpenSC/Wiki/blob/master/Smart-Card-Release-Testing.md

**Comment by kloczek** [comment]
Please next time tag such releases not as `0.24.0-rc1` but as `0.24.rc1`.
When final `0.24.0` will be released it will be upgradeable and version string will be ascending (`0.24.rc1` is lover than `0.24.0`).
More info about reasons use of that convention you can find on https://discourse.gnome.org/t/new-gnome-versioning-scheme/4235

**Comment by frankmorgner** [comment]
> Please next time tag such releases not as `0.24.0-rc1` but as `0.24.rc1`.

Our naming scheme has been used for the past decades and we will not change this soon.

**Comment by kloczek** [comment]
> Our naming scheme has been used for the past decades and we will not change this soon.

Yes and that that naming scheme has home issue for packagers which many maintainers simple ignores.
Simple many package management software do not accept `-` in version string and `0.24.0-rc1` is not lower *as version string) than `0.24.0`.
Making something incorrectly very long time simple happens ..

PS. Latin "errare humanum est perseverare autem diabolicum".

**Comment by AlbertoAIG** [comment]
I have tried this version with macOS Sonoma and it doesn't work either after doing a clean installation, while in another version of macOS or on windows it works perfectly. Will it be fixed in the future?
Thanks

**Comment by frankmorgner** [comment]
Preferably, we should support Sonoma with this release as well. It seems that 0.23.0 has problems with Sonoma, too (https://github.com/OpenSC/OpenSC/issues/2887). My macbook air is too old, so I cannot reproduce this problem.

Maybe @metsma has more experience with Sonoma...

**Comment by below** [comment]
Maybe this helps, please let me know if this information is more helpful elsewhere

Like many people (apparently), I had big problems with OpenSC after upgrading to macOS Sonoma. I have noticed that the issues depend very much on hardware, so I tested a few readers. I don't know enough about all of this, I am a developer, but have no clue about this particular domain. I am using the SmartCard through Chrome to access Citrix and some VPN tunnel. Let me know how I can give you more info:

✓ Identiv SCR3500 C Contact Reader: **Working** apparently without issues Product 0x581d, Vendor ID 0x04e6
(✓) ACR39U ICC Reader, **Working partially** (seemingly only once per connection), Product 0xb100, Vendor 0x072f
⤫ EMV SmartCard Reader **Not working** Product 0x9540 Vendor 0x058f  	
⤫ SCR3310 SmartCard Reader **Not Working** Product 0x5116 Vendor 0x04e6

**Comment by Jakuje** [comment]
@below most of the people reported that the Sonoma issues got better after updating the CCID driver. See the issue #2887. The OpenSC does not implement any readers drivers and is using PCSC to do the talking with the HW so there is not much we can do from the OpenSC side.

**Comment by Jakuje** [comment]
Release is out:
https://github.com/OpenSC/OpenSC/releases/tag/0.24.0
Closing this issue.
