### ISSUE TITLE
error: Failed to load pkcs11 module

### ISSUE THREAD

**Issue by nshah2588** [OpenSC/OpenSC#2884]
Hello,

We tried to create the new OpenSC dll on Windows all fine.

Then we tried to run it on Windows and we got the error as below

`C:\Program Files\OpenSC Project\OpenSC\tools>pkcs11-tool --module "C:\xxxxx\xxxxxx\Downloads\opensc-pkcs11.dll" -L
sc_dlopen failed: LoadLibrary/GetProcAddress failed
error: Failed to load pkcs11 module
Aborting.
`

Furthermore,  when we built the OpenSC from within Cygwin and tried to run it from within Cygwin we got the proper response for the -L command

Also, we are not able to run the OPENSC_DEBUG=9 prompt to get the logs unfortunately

`C:\Program Files\OpenSC Project\OpenSC\tools>OPENSC_DEBUG=9 pkcs11-tool --module "C:\xxxxx\xxxxx\Downloads\opensc-pkcs11.dll" -L
'OPENSC_DEBUG' is not recognized as an internal or external command,
operable program or batch file.
`
Can you please advise what we are missing?

**Comment by dengert** [comment]
Building on windows or cross compiling are very tricky. 

> 'OPENSC_DEBUG' is not recognized as an internal or external command ...

Windows does not support setting environment variables on the command line. Use the "set" command. It looks like you are mixing a windows built pkcs11-tool with a cross compiled module. That may never work.


As I said in #2883  "submit your changes as a Pull Request, Windows MSI and MacOS DMG files are created automatically on github and your changes will be kept up to date."

Based on #2883 it looks like you are trying to make changes to `card-entersafe.c`  because that was the driver OpenSC matched or you forced that driver. Looking at your github account avatar of a token, it looks like some new token with both USB Type A and Type C with a button and maybe NFC? And you refer to yourself as "we" so I assume you are not doing this alone.  

So I would suggest that the best way to get support for this device using OpenSC code get it working on Linux, then submit your changes as a PR, let Github build the Windows MSI and MacOS DMG files and use them to test. 

When you get it working, your company can say the new device is supported by OpenSC like other smartcard venders do. 

If you goal is to copy OpenSC code and distribute your own version based on OpenSC, you may have license issues.

**Comment by dengert** [comment]
Do you have a member who has uses github before? 
If not  Start here: 
https://docs.github.com/en/get-started/quickstart/fork-a-repo

make your changes to your local  copy
push you to your forked version. 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

I am busy most of rest of day...

**Comment by nshah2588** [comment]
Thank you @dengert for your suggestion. We will get back on this shortly
