### ISSUE TITLE
Outlook not able to decrypt email - part 2

### ISSUE THREAD

**Issue by RufusJWB** [OpenSC/OpenSC#3076]
### Problem Description

When trying to decrypt an email in MS Outlook with OpenSC 0.25 I receive the following error message:

![image](https://github.com/OpenSC/OpenSC/assets/1633499/d967b430-3b35-452d-95b1-b473505e0f44)

This seems to be related to https://github.com/OpenSC/OpenSC/issues/2925

### Proposed Resolution

Email should be decrypted

### Steps to reproduce

Decrypting an email

### Logs

https://gist.github.com/RufusJWB/c2ec57352395e7c7508dd6375622fb60

**Comment by Jakuje** [comment]
The log now says we are getting 245 B of data from the PKCS#1.5 padded block instead of 16 we should have from my fast check of the data block.

> P:8528; T:13012 2024-03-18 16:06:18.797 [cardmod] decrypted data(245):

We changed in 0.25.0 the depadding function to be constant time, but it looks like it does not handle this case well. @xhanulik can you have a look if this is an issue of the depadding or of the way how the depadding is used in the minidriver?

It might be that the function is now more strict and we might need to inject the missing null byte to the beginning in the cardos driver.

**Comment by xhanulik** [comment]
The depadding function correctly returns the length of depadded message, but the minidriver uses the function argument to get the length, which is not set correctly. I will create PR with fix.

**Comment by RufusJWB** [comment]
> I will create PR with fix.

As soon as you have binaries, I'd love to test them.

**Comment by RufusJWB** [comment]
> We changed in 0.25.0 the depadding function to be constant time, but it looks like it does not handle this case well.

I re-tested with 0.24 and I can confirm, there it is still working.

**Comment by Jakuje** [comment]
@RufusJWB can you check the #3077?

**Comment by jozsefd** [comment]
See my report #3085 about CardRSADecrypt.
