### ISSUE TITLE
'hacked' mode

### ISSUE THREAD

**Issue by ROZOH** [OpenSC/OpenSC#356]
Hi,
I need to know more about "hacked" and onepin mode that is exist in opensc 12.0.2 and before, what is reason for removing it from opensc. I'm search about it very without any clear description.
Can anyone help to me?

**Comment by frankmorgner** [comment]
The onepin mode (and hacked mode, too, I think) exposed only one PIN to the application.
Have a look at d1cf65754b9326c09213f151b7ee2f19f4037730 for detailed information.
Onepin-mode returned in 8e13acf51ebd18d6fa4aeb4fb38c240c11595f3d for some reason.

**Comment by frankmorgner** [comment]
@viktorTarasov why was the onepin library added again after removing it?

**Comment by ROZOH** [comment]
In fact, I meet a problem with hack_enabled variable in opensc 0.12.2 farmework-pkcs15.c file:

948	if (hack_enabled)
949		auth_count = 1;

Sometimes, sc_pkcs15_get_objects function assigns 0 to auth_count, hack_enabled conditional statement changes it to 1 and next lines send access vliolation exception.   
I want to know this is logical that auth_count gets 0 suddenly after multiple successful assign? What things may be involved? Is this relative to system elements? 

I changed the code To handle this exception:

948	if (hack_enabled && auth_count)
949		auth_count = 1;

, but after multiple connect and disconnect card system hangs!
Is there any idea about it?

**Comment by martinpaljak** [comment]
@frankmorgner Because people depend on it for sensible operation. There's a prominent application - Firefox - that can't handle in default setup PKCS#11 modules with more than one slot sensibly. You get usage glitches like a PIN prompt for every slot *before* certificate selection, in default settings. The workaround (Friendly Certificates flag) doesn't stick through sessions. Firefox even did not know how to select the "right" certificate for web authentication, considering nonrepudiation certificates as "stronger and thus better" certificates for web authentication.

Having two separate modules by OpenSC is necessary because there are applications that are capable of working with multiple slots, in a sensible way. Quite often running at the same time as a browser. Because of the way modules are loaded, there can't be a configuration option "enable hack" and "disable hack", because that's just not usable.

The way the "hack" works is creating the "onepin" module, that exposes just a single slot with a token. It is far from being a "nice" implementation, as it assumes that the first key-certificate pair is the authentication one. It magically works for most eID schemes where there are dedicated keys at quite often fixed locations. Better implementation would be n "alt-opensc-pkcs11" with a configuration option, where the default would be exposing just a single slot with the "right" certs and pins.

The whole thing is a bit complicated from "traditional" PKCS#11 modules, where a single module usually serves a single token. The "hack" only works when you have a single inserted card. If you have more, and they are supported by OpenSC, things go crazy again.

So this is about instant usability for users rather than technically correct solution for a technical problem.

I gave up bugging Mozilla (did not really feel like re-building mozilla to try to fix it, when the other side is not interested in this getting fixed) and use Chrome instead. While also based on NSS, it can at least select the right certificate!

**Comment by viktorTarasov** [comment]
> @viktorTarasov why was the onepin library added again after removing it?

As for me the onepin version is excessive; there were introduced the opensc pkcs11-* configuration options that allow to pkcs11 module create only one slot, slot for every PIN (ex. PIN & SignPIN) or slot for every on-card PKCS15 application (used mostly with IAS/ECC card) .

Then there were <i>usability</i> reasons, that, as I vaguely remember, mostly stated that there is a need to use simultaneously two PKCS11 modules in two different configurations.

**Comment by frankmorgner** [comment]
So istead of creating a separate library a better fix would be to hardwire a specific configuration to certain applications...

**Comment by frankmorgner** [comment]
exporting OPENSC_CONF would help before starting firefox, but I understand that's not what the average user wants to do...

**Comment by martinpaljak** [comment]
If you find a way to detect the application (reliably, on 3 platforms) that loads a shared module, that would be an option.

**Comment by ROZOH** [comment]
No idea about my problem that i described in 6th previous comment?

**Comment by martinpaljak** [comment]
As always, do provide a full log that might give some insight.

**Comment by viktorTarasov** [comment]
> @ROZOH 
> No idea about my problem that i described in 6th previous comment?

Hardly anybody will be attentive to your problem with the ancient OpenSC version.

You should rather use the current OpenSC version with following configuration option in pkcs11 section of opensc.conf :
create_slots_for_pins = "user"

Note that  <i>onepin-opensc-pkcs11 module </i> is not the same as <i>opensc-pkcs11 module configurated with one slot</i>. 
The second one tries to discover the PIN's role. 
The first one simply takes the first parsed PIN, in the same manner as it was in the <i>hack-enabled</i> mode of the previous OpenSC versions .

**Comment by ROZOH** [comment]
Your descriptions about hack-enabled and onepin was very helpful for me. 

Thanks a lot.
