### ISSUE TITLE
ScardConnect Hangs in minidriver

### ISSUE THREAD

**Issue by MaryamSD** [OpenSC/OpenSC#361]
Hi, 
I had issued a problem about windows smart card logon reported in #287.
Now, we meet an another situation that is similar to it. Sometimes, If i insert a card in reader and then run an application uses of this card, it will hang until remove the card. Also we can stop ScardSvr service of windows in problem situation and application will run. By following opensc logs, we find "ScardConnect failed". 

I google it and meet this post that is ambiguous for me:
https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/99c23967-3925-40b7-a02c-3135c744ebd6/scardconnect-hangs?forum=windowssecurity   

Is it true that we shouldn't use SCardConnect in a minidriver implementation?
There are many "Scard... failed" in our opensc log while generally successful in practice.

**Comment by dengert** [comment]
On 1/22/2015 6:59 AM, MaryamSD wrote:
> Hi,
> I had issued a problem about windows smart card logon reported in #287 <https://github.com/OpenSC/OpenSC/issues/287>.
> Now, we meet an another situation that is similar to it. Sometimes, If i insert a card in reader and then run an application uses of this card, it will hang until remove the card. Also we can stop
> ScardSvr service of windows in problem situation and application will run. By following opensc logs, we find "ScardConnect failed".
>
> I google it and meet this post that is ambiguous for me:
> https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/99c23967-3925-40b7-a02c-3135c744ebd6/scardconnect-hangs?forum=windowssecurity

The article is saying the Windows passes a handle to the minidriver after windows does its own SCardConnect.
Outside the minidriver, OpenSC initiates the process to connect to the card, in the minidriver, windows passes the handle.
See check_reader_status(), associate_card() and disassociate_card() in minidriver.c that look for a change in handle.

In #287 you say you are developing your own token.

Are you modifying the minidriver code?

Do you have your own src/libopensc/card-*.c driver?

>
> Is it true that we shouldn't use SCardConnect in a minidriver implementation?

True, don't use SCardConnect. Use the handle passed in the CARD_DATA.

> There are many "Scard... failed" in our opensc log while generally successful in practice.

I you have not modified the OpenSC Minidriver, or OpenSC code, I would be interested in the trace,
because OpenSC should not be using SCardConnect when called from the minidriver.




>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/361>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
Hi,

Indeed, in associate_card there is a call to SCardConnect. It is used with the flag "do not share the card" to gather reader data, like if it supports a Pinpad.
The call fails (because the card is already opened), then it reuses the handle provided by the Base CSP to check the status again.

On my opinion, 
1) the ScardConnect noted in the logs has nothing to do with the problem 
2) the problem is related to the other application which is blocking the card with a transaction, and then, the Base CSP, which handles the minidriver, has to wait for the transaction to complete.
3) or you compiled the minidriver and forget to set in libopensc the flag ENABLE_MINIDRIVER (the code will compile, but the code related to the switch of the context will not be active)

To provide a solution, I'll recommend to launch a monitoring tool (like rohitab API monitor) to track SCardBeginTransaction and SCardEndTransaction / SCardDisconnect
You'll be able to see you started a transaction and didn't termine it.

regards,
Vincent Le Toux

**Comment by frankmorgner** [comment]
@MaryamSD please reopen if the hints above didn't solve the issue
