### ISSUE TITLE
OpenSC/MiniDriver Issue with 2 readers

### ISSUE THREAD

**Issue by rafikbo76** [OpenSC/OpenSC#384]
Hi,

I am stucking on an issue for more than a couple of week. The thing is when an empty card (without certificate) is inserted in the second reader and any other card in the first, CryptAcquireContext failed with error 0x00000002 (error_file_not_found). When the card is in the first reader or did contain a certificate, everything works fine. This error was reported when testing with our customer CAPI client application on Windows XP.

We can reproduce the bug with  the folowing config : 
- Windows 2003 CA (web enrol),
- Windows XP (Enroll Station),
- Gemalto Classic TPC (Gemalto CSP) or ACS ACOS5 (ACS CSP) in the first reader,
- Muscle Applet card with OpenSC 0.13 in the second reader,

First, we need to enroll the first card and than try to enrol the muscle card with the signature certificate of the first card. In this situation, we've got (0x8007007E specified module not found) error.

Another way to reproduce the bug is using certutil in Windows 7 (That's need a little change to card-muscle.c to allow Win7 enumerate Card certificate). 

I am attaching Mini Driver and OpenSC log files for ACS and muscle Applet test case (Win 2003 web enroll). 

Test Case :
- Win 2003 Web Enroll. 
- 2 smart card, 1 Muscle card with OpenSC, the Other from another CSP suppllier (in This case ACS ACOS5)
- md-reader-2.log : MiniDriver log file for Muscle Card in the second reader (bug),
- opensc-debug-reader-2.log : OpenSC log file for Muscle Card in the second reader (bug),
- md-reader-1.log : MiniDriver log file for Muscle Card in the first reader (works till pin request),
- opensc-debug-reader-1.log : OpenSC log file for Muscle Card in the first reader (works till pin request),

here is the link : https://drive.google.com/file/d/0B4ExQ5o6485FVGFodDZ2Tkp2V0U/view?usp=sharing

Another thing with Win7 test case : 
- Any smart card inserted in the first reader will reproduce the bug (0x2 error)
- When Muscle card contain a certificate certutil can read it without any problem

I didn't find any clue to debug Microsoft Base CSP because everythings seems fine to me in the log files.

I appreciate any help from you 
And thanks in Advance

**Comment by dengert** [comment]
I would suspect that this is a serial number problem with the muscle card,
which does not support a serial number. see:

  https://github.com/OpenSC/OpenSC/pull/368#issuecomment-73378116

Also look at the thread

http://opensc.1086184.n5.nabble.com/AT-SIGNATURE-and-AT-EXCHANGE-Problem-td15058.html

The muscle card on Windows was this issue.

Windows needs a unique identifier to match up certs in the cert store with
what card needs to be loaded.

The pkcs15-init --serial can be used when initializing a card to set the tokeninfo->serial_number
so each PKCS15 card is unique. Without this the minidriver might use "0000" as the default
or not work at all.



On 2/18/2015 4:34 AM, rafikbo76 wrote:
> Hi,
>
> I am stucking on an issue for more than a couple of week. The thing is when an empty card (without certificate) is inserted in the second reader and any other card in the first, CryptAcquireContext
> failed with error 0x00000002 (error_file_not_found). When the card is in the first reader or did contain a certificate, everything works fine. This error was reported when testing with our customer
> CAPI client application on Windows XP.
>
> We can reproduce the bug with the folowing config :
>
>   * Windows 2003 CA (web enrol),
>   * Windows XP (Enroll Station),
>   * Gemalto Classic TPC (Gemalto CSP) or ACS ACOS5 (ACS CSP) in the first reader,
>   * Muscle Applet card with OpenSC 0.13 in the second reader,
>
> First, we need to enroll the first card and than try to enrol the muscle card with the signature certificate of the first card. In this situation, we've got (0x8007007E specified module not found) error.
>
> Another way to reproduce the bug is using certutil in Windows 7 (That's need a little change to card-muscle.c to allow Win7 enumerate Card certificate).
>
> I am attaching Mini Driver and OpenSC log files for ACS and muscle Applet test case (Win 2003 web enroll).
>
> Test Case :
>
>   * Win 2003 Web Enroll.
>   * 2 smart card, 1 Muscle card with OpenSC, the Other from another CSP suppllier (in This case ACS ACOS5)
>   * md-reader-2.log : MiniDriver log file for Muscle Card in the second reader (bug),
>   * opensc-debug-reader-2.log : OpenSC log file for Muscle Card in the second reader (bug),
>   * md-reader-1.log : MiniDriver log file for Muscle Card in the first reader (works till pin request),
>   * opensc-debug-reader-1.log : OpenSC log file for Muscle Card in the first reader (works till pin request),
>
> here is the link : https://drive.google.com/file/d/0B4ExQ5o6485FVGFodDZ2Tkp2V0U/view?usp=sharing
>
> Another thing with Win7 test case :
>
>   * Any smart card inserted in the first reader will reproduce the bug (0x2 error)
>   * When Muscle card contain a certificate certutil can read it without any problem
>
> I didn't find any clue to debug Microsoft Base CSP because everythings seems fine to me in the log files.
>
> I appreciate any help from you
> And thanks in Advance
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/384>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by rafikbo76** [comment]
Thanks for ur answer,

That's what I meant with (a little change to card-muscle.c) in my comment. We also found for hierarchical enrollement (Card enroll for another card) that's the serial number should be specific to each card (obviously) and that's Windows use the Serial Number to calculate CardID file.

But our issue is empty card in the second reader and it is happening with any other card (even not pki card) in the first reader. With 2 Muscle card there is no problem.
I can provide any trace file that could help because I did a lot of test and nothing seemed abnormal to me.

**Comment by dengert** [comment]
The pin-pad readers might be a problem. Can you try with regular readers?

Differences with Windows vs Unix:
   The minidriver is passed the handle for the reader, cutting out a lot of the
   code in OpenSC to handle multiple readers.

   A Windows process may call the same DLL from multiple threads, passing in different readers
   each time.

   Minidriver.c calls check_reader_status on each reentry to watch for the reader handle changing.
   If it does it will output the message "HANDLES CHANGED from 0xxxxxxxxx 0xxxxxxxxx"

  then call
    disassociate_card(PCARD_DATA pCardData)
    associate_card(PCARD_DATA pCardData)
  There may be an issue here with pin pad readers...

Does the application crash, or just not respond?
The logs just appear to end, without any useful information.
Can you make sure the opensc.conf debug = N; is a least 9. some other messages may get logged at the end.

Make sure the md.log is writable by all users. When cards get inserted, the system takes a look at the card.
If on 64 bit machines, make sure both a 32 bit and 64 bit versions of OpenSC are installed,
and the registry entries for OpenSC are added to both. THe system may use 64 bit, your app may use 32.

The cardid still appears to be zero:

MD virtual file system: file 'cardid' added
cardid(16)
--- 028F1E70:16
  0000  00000000 00000000 00000000 00000000





On 2/18/2015 4:34 AM, rafikbo76 wrote:
> Hi,
>
> I am stucking on an issue for more than a couple of week. The thing is when an empty card (without certificate) is inserted in the second reader and any other card in the first, CryptAcquireContext
> failed with error 0x00000002 (error_file_not_found). When the card is in the first reader or did contain a certificate, everything works fine. This error was reported when testing with our customer
> CAPI client application on Windows XP.
>
> We can reproduce the bug with the folowing config :
>
>   * Windows 2003 CA (web enrol),
>   * Windows XP (Enroll Station),
>   * Gemalto Classic TPC (Gemalto CSP) or ACS ACOS5 (ACS CSP) in the first reader,
>   * Muscle Applet card with OpenSC 0.13 in the second reader,
>
> First, we need to enroll the first card and than try to enrol the muscle card with the signature certificate of the first card. In this situation, we've got (0x8007007E specified module not found) error.
>
> Another way to reproduce the bug is using certutil in Windows 7 (That's need a little change to card-muscle.c to allow Win7 enumerate Card certificate).
>
> I am attaching Mini Driver and OpenSC log files for ACS and muscle Applet test case (Win 2003 web enroll).
>
> Test Case :
>
>   * Win 2003 Web Enroll.
>   * 2 smart card, 1 Muscle card with OpenSC, the Other from another CSP suppllier (in This case ACS ACOS5)
>   * md-reader-2.log : MiniDriver log file for Muscle Card in the second reader (bug),
>   * opensc-debug-reader-2.log : OpenSC log file for Muscle Card in the second reader (bug),
>   * md-reader-1.log : MiniDriver log file for Muscle Card in the first reader (works till pin request),
>   * opensc-debug-reader-1.log : OpenSC log file for Muscle Card in the first reader (works till pin request),
>
> here is the link : https://drive.google.com/file/d/0B4ExQ5o6485FVGFodDZ2Tkp2V0U/view?usp=sharing
>
> Another thing with Win7 test case :
>
>   * Any smart card inserted in the first reader will reproduce the bug (0x2 error)
>   * When Muscle card contain a certificate certutil can read it without any problem
>
> I didn't find any clue to debug Microsoft Base CSP because everythings seems fine to me in the log files.
>
> I appreciate any help from you
> And thanks in Advance
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/384>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by rafikbo76** [comment]
In windows Xp test case (Web enroll), IExplorer respond with module not found error. In win 7 certutil and our customer app we got 0x2 error (file not found).
I will re run the tests and make sure of all your suggestions. Also I have to take a closer look to check_reader_status behavior. 

I will post log files next Sunday,  as I m not available for the next 2 days.

Thanks for your time Mr dengert.

**Comment by rafikbo76** [comment]
Hi again,

Here is the link of the test case new logs:

https://drive.google.com/file/d/0B4ExQ5o6485FNndNVUUzS0R2LXM/view?usp=sharing

As I told you before, this is Windows XP 32 bit enrollement station with Win2003 CA web enroll application.

About the cardid file, 
It's value is 0000  00000000 00000000 00000000 00000000 because the serial number attribute in Token-Info file was 0000 (as we initialized with pkcs15-init).
In our tests with 2 cards enrollement in WebEnroll app, we found that the second cards must have a serial number attribute differents of the first, otherwise WebEnroll failed to distinguish between the 2 cards. 

Microsoft claims 
"cardid : This value is assigned by Microsoft software to assure that a unique value is generated for the card. It is unrelated to the serial number that may or may not be assigned to the card during manufacture."

But the 2 cards enrollement wasn't succesful unless we changed Token-Info serial number of the second card and it was clear the cardid in the logs wasn't the same.

**Comment by dengert** [comment]
On 2/22/2015 5:09 AM, rafikbo76 wrote:
> Hi again,
>
> Here is the link of the test case new logs:
>
> https://drive.google.com/file/d/0B4ExQ5o6485FNndNVUUzS0R2LXM/view?usp=sharing
>
> As I told you before, this is Windows XP 32 bit enrollement station with Win2003 CA web enroll application.
>
> About the cardid file,
> It's value is 0000 00000000 00000000 00000000 00000000 because the serial number attribute in Token-Info file was 0000 (as we initialized with pkcs15-init).
> In our tests with 2 cards enrollement in WebEnroll app, we found that the second cards must have a serial number attribute differents of the first, otherwise WebEnroll failed to distinguish between
> the 2 cards.
>
> Microsoft claims
> "cardid : This value is assigned by Microsoft software to assure that a unique value is generated for the card. It is unrelated to the serial number that may or may not be assigned to the card during
> manufacture."

Yes that is true. Microsoft has/had some sort of card, and on those cards there is a cardid file.
The OpenSC minidriver is emulating one of those cards, as required by the Microsoft CNG.
There is no actual cardid file on any card supported by OpenSC, and many cards do not have
an unique data from the manufacture that is readable. What OpenSC calls a "seralnr" on many
cards is derived from data stored on the card, and if it has a pkcs15 appl, it will try and
use the PKCS#15 tokenInfo->serial_number if available then fall back and try and use some
other means based on the card, to get a serial number.

The value obtained to use for cardid must be the same each time the card is used. It must also
not be the same as another card used on the same system.

>
> But the 2 cards enrollement wasn't succesful unless we changed Token-Info serial number of the second card and it was clear the cardid in the logs wasn't the same.

Does this mean your problem is solved if you use pkcs15init --serial
to set the some unique value before doing the "webEenroll" app?

I have not looked at your trace yet, as it sound  pkcs15init --serial is the solution.

Are you looking for some other option?

If the Minidriver was to find that the results of trying to derive a unique number
to use in cardid results in zero, that it would:

  (1) Obtain a GUID from the local system, and try and write the tokenInfo->serial_number
  so it would be available for future use.

  (2) If that write failed it would cause an error to tell the user the card needs to be initialized.

I am not sure if this is possible, or if it would cause problems in existing cards
currently in use, and I have no way to test it.

Maybe (2) would be enough.



>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/384#issuecomment-75430367>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by rafikbo76** [comment]
The serial number was the solution to handle 2 muscle card on the same system. And we are using your first suggestion (Writing the serial number in Token Info file).

The problem we are facing now, is using Muscle card on the second reader and any other card on the first reader.
When the muscle card is empty (without certificate), CryptAcquireContext failed with error 0x2 (wabenroll failed with  0x8007007E error). 
If Muscle card did contain a certificate or is inserted in the first reader, everythings works fine.

I attached enrollement traces of Muscle card with ACOS5 card (ACS CSP) for both cases (Muscle in the first and than in the second reader). I also disabled any driver but the muscle card one.

Thanks for your help

**Comment by dengert** [comment]
I can't do much today. Will look tomorrow.

On 2/22/2015 7:42 AM, rafikbo76 wrote:
> The serial number was the solution to handle 2 muscle card on the same system. And we are using your first suggestion (Writing the serial number in Token Info file).
>
> The problem we are facing now, is using Muscle card on the second reader and any other card on the first reader.
> When the muscle card is empty (without certificate), CryptAcquireContext failed with error 0x2 (wabenroll failed with 0x8007007E error).
> If Muscle card did contain a certificate or is inserted in the first reader, everythings works fine.
>
> I attached enrollement traces of Muscle card with ACOS5 card (ACS CSP) for both cases (Muscle in the first and than in the second reader). I also disabled any driver but the muscle card one.
>
> Thanks for your help
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/384#issuecomment-75435909>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by rafikbo76** [comment]
I can't do much today. Will look tomorrow.
OK,
Sorry for make you working in the weekend

**Comment by dengert** [comment]
All the cardid values in the traces appear to be zero.

Can you run these commands against both cards one at a time
with only one reader on windows using the version of OpenSC
you have installed?

  opensc-tool --serial
  Note muscle card does not support this.
  pkcs15-tool --dump
Look for "Serial number  :" near the top.

What version of the minidriver are you using?

I ask because of this commit:
  https://github.com/OpenSC/OpenSC/commit/faaa11e091001f063dac46f29f0aad28c2494a18

  2015-01-08 to address changes in this area.

You can build it yourself, or use the latest master or a build from
a pull request. See here:

  https://opensc.fr/jenkins/view/OpenSC-master/

I would speculate that both cards are returning a cardid of zero.
Certificates/keys also have an ID, that is different for your two cards,
so windows can fine existing certificates on the right card, but
for a blank card, it is using cardid and always finding the first.



On 2/22/2015 7:42 AM, rafikbo76 wrote:
> The serial number was the solution to handle 2 muscle card on the same system. And we are using your first suggestion (Writing the serial number in Token Info file).
>
> The problem we are facing now, is using Muscle card on the second reader and any other card on the first reader.
> When the muscle card is empty (without certificate), CryptAcquireContext failed with error 0x2 (wabenroll failed with 0x8007007E error).
> If Muscle card did contain a certificate or is inserted in the first reader, everythings works fine.
>
> I attached enrollement traces of Muscle card with ACOS5 card (ACS CSP) for both cases (Muscle in the first and than in the second reader). I also disabled any driver but the muscle card one.
>
> Thanks for your help
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/384#issuecomment-75435909>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by rafikbo76** [comment]
- What version of the minidriver are you using?
We are using Opensc 0.13 and forcing the MiniDriver version to 6 because we don't support card padding yet. and also we implemented serialnr in cardctl (the commit you suggest is the right way of course).

The exact situation is CryptAcquireContext failed with the card in the 2 nd reader and Any other Card in the first reader.
To show the problem I took web enroll as test case. Web enroll doesn't accept 2 cards unless one enroll the other so I did it with ACOS5 card and ACS CSP.
OpenSC is only supporting the muscle card, any other driver is disabled for this test case.
Of course the cardid of the muscle card is still zero but I changed the serial number without succes.

**Comment by dengert** [comment]
What is "card padding"?

And you are not using OpenSC for the ACOS5 card?

What I was speculating is the card in the first reader, even if not using the OpenSC minidriver
for that card is setting cardid to zero, causing problems.

I don't have a good way to test any of this.

Can you try the the commit I suggested?

As a test to see if the cardid is the problem you could change minidriver.c md_set_cardid()
if (vs->p15card->tokeninfo && vs->p15card->tokeninfo->serial_number) {
to have an else clause that at least logs an error, and could set the cardid to something other then zero,
like 1, so see if the issue is the ACOS5 ACS CSP also has a problem with using zero for the cardid.


On 2/23/2015 8:49 AM, rafikbo76 wrote:
>   * What version of the minidriver are you using? We are using Opensc 0.13 and forcing the MiniDriver version to 6 because we don't support card padding yet. and also we implemented serialnr in
>     cardctl (the commit you suggest is the right way of course).
>
> The exact situation is CryptAcquireContext failed with the card in the 2 nd reader and Any other Card in the first reader.
> To show the problem I took web enroll as test case. Web enroll doesn't accept 2 cards unless one enroll the other so I did it with ACOS5 card and ACS CSP.
> OpenSC is only supporting the muscle card, any other driver is disabled for this test case.
> Of course the cardid of the muscle card is still zero but I changed the serial number without succes.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/384#issuecomment-75553872>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by rafikbo76** [comment]
What is "card padding"?
MiniDriver 7 new feature : Support for RSA Padding Removal Operations in the Smart Card
We should take more attention to PFN_CSP_UNPAD_DATA and CardRSADecrypt as suggested in MiniDriver 7 spec but we didn't. 
Win Logon failed in Windows 7 with Muscle Card because of Padding Removal in the smart card.

	And you are not using OpenSC for the ACOS5 card?
Yes for this test case we used ACOS card with ACS CSP

I will try to find an easiest test to illustrate the problem, in the mean time I will try your suggestion.

Thanks

**Comment by dengert** [comment]
On 2/23/2015 10:29 AM, rafikbo76 wrote:
> |What is "card padding"?
> |
>
> MiniDriver 7 new feature : Support for RSA Padding Removal Operations in the Smart Card
> We should take more attention to PFN_CSP_UNPAD_DATA and CardRSADecrypt as suggested in MiniDriver 7 spec but we didn't.

When you say "We" are you referring to OpenSC, or are you referring to your company trying to
write your own minidriver to use muscle cards?

AFAIK since the muscle card did not support a serial number, it never did work on Windows.

Minidriver.c has:
3015                         else if (pInfo->dwPaddingType == CARD_PADDING_OAEP)   {
3016                                 /* TODO: Handle OAEP padding if present - can call PFN_CSP_UNPAD_DATA */
3017                                 logprintf(pCardData, 2, "OAEP padding not implemented\n");
3018                                 return SCARD_F_INTERNAL_ERROR;
3019                         }

With Win7, do you specify in the registry specify both:
"Crypto Provider"="Microsoft Base Smart Card Crypto Provider"
"Smart Card Key Storage Provider"="Microsoft Smart Card Key Storage Provider"
in the minidriver source directory are some examples, some use both,
some don't. I believe both of these should be used for all cards, so the Microsoft code
will do most of the heavy lifting, like the OAEP padding.  It easy to try.

AFAIK, OpenSC does not support OAEP padding for any cards.


> Win Logon failed in Windows 7 with Muscle Card because of Padding Removal in the smart card.
>
> |And you are not using OpenSC for the ACOS5 card?
> |
>
> Yes for this test case we used ACOS card with ACS CSP
>
> I will try to find an easiest test to illustrate the problem, in the mean time I will try your suggestion.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/384#issuecomment-75576737>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by rafikbo76** [comment]
This issue can be closed.

We did some test on Windows 7 with MMC enroll. The card is detected without any problem. We also had the same issue with Gemalto GemSafeMD MiniDriver, So We suppose it is Client Side problem unrelated with OpenSC MiniDriver (as OpenSC traces show the card was detected).

Thanls for your help
