### ISSUE TITLE
Testing for new release 0.15.0 required

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#404]
In preparation of a new release (currently in the branch `opensc-0.15.0`) the @OpenSC/opensc-maintainers are currently testing existing cards and applications. We plan to add a matrix of what is supported (and what is untested).

Could you please add your test cases and cards here if possible?

@viktorTarasov @frankmorgner @marschap @martinpaljak @LudovicRousseau @hongquan @philipWendland @dengert @szikora @mbrossard @tc-anssi @metsma @poupas @resoli @ttaylor249 @germanblanco @mjrider @tkil @hean01 @Flameeyes @hiviah @cbancroft @sjoblomt @frankthater @dirkx @Ecordonnier-theobroma @puccia @hhonkanen @eighthave @henryk

**Comment by LudovicRousseau** [comment]
I do not use OpenSC these days.
I have no test cases to provide. Sorry.

**Comment by dirkx** [comment]
> In preparation of a new release (currently in the branch opensc-0.15.0) we are currently testing existing cards and applications. We plan to add a matrix of what is supported (and what is untested).
> Could you please add your test cases and cards here if possible.

Those on Yosemite - you may need the not yet incorperated

		https://github.com/dirkx/OpenSC/commit/1cd8d02449b2c1aeb0383b9c583aa59265ab1460

in order to build it.

Dw.

**Comment by dirkx** [comment]
> In preparation of a new release (currently in the branch opensc-0.15.0) we are currently testing existing cards and applications. We plan to add a matrix of what is supported (and what is untested).
> 
For Yosemite - had to massage in:

	https://github.com/dirkx/OpenSC/commit/1cd8d02449b2c1aeb0383b9c583aa59265ab1460

to make the OSX build work again. Not sure if that is specific to my setup ? I also noted that the version number in the build packages is still 0.14:

	config.log:PACKAGE_VERSION='0.14.0'

Besides that - works for the common test cases here (Yosemite, FreeBSD); except the ones that require the still pending 

	https://github.com/dirkx/OpenSC/commit/59d06ae43b1f8f57e9ca3cb7ad63ab0819982e7a

on readers with and without PIN pads (SPR532, HID, etc) against a range entersafe (feitian), aventra, aet, BE/PT/IT govt. cards, medical NL cards.

I do notice that opensc-tool/-explore now produce more sensible (albeit gargbled) output on PKCS15 cards or not yet initialized cards. E.g. stuff like

	[5015]	DF 32767	Name: ?\x00\x00\x00cPKCS-15 

	Using reader with a card: SCM Microsystems Inc. SPR 532
	`??V?

	Using reader with a card: SCM Microsystems Inc. SPR 532
	`R?T?

where previously things would error out. Do you have a wiki page with the embryonic matrix ? So we can fill out stuff we care about.

Dw

**Comment by CardContact** [comment]
Published test results for the SmartCard-HSM here

https://gist.github.com/CardContact/784e826ba5fe6d4626d2

Andreas

**Comment by hiviah** [comment]
Feitian ePass 2003 on Linux - tested the PKCS11 library with ssh and opensc-explorer. Seems to work fine.

**Comment by dengert** [comment]
PIV cards  work on Ubuntu 14.4 in virtualBox under W7.   Opensc-0.15.0, engine-opensc and libp11 compiled to use OpenSSL-1.0.2a . openssl req  command using the engine-opensc and libp11 can sign a certificate request.  piv-tool can generate keys and load objects, like CHUID and certificate. 
pkcs11-tool, and pkcs15-tool also work with PIV cards.
pkcs11-tool --derive with ECDH also works. 

FireFox on Ubuntu can use the new  opensc-pkcs11.so to read certificate.

**Comment by philipWendland** [comment]
IsoApplet, Arch Linux with 1.0.2.a-1, libp11 0.2.8-1, engine_pkcs11 0.1.8-3:
pkcs11-tool:
--show-info, list-objects, sign, change-pin, keypairgen, read-object, delete-object, write-object
Came up with #400 and #407. Other options not supported or not tested.

pkcs15-init:
--create-pkcs15, --generate-key/store-private-key (tested every supported EC curve except 384 bits + RSA either generated or imported), store-public-key, store-certificate, update-certificate, store-data, delete-object, change-attributes, update-last-update

pkcs15-tool:
--learn-card and file caching, --list-applications, --read-certificate, list-certificates, read-data-object, list-data-objects, list-pins, list-public-keys, read-public-key, read-ssh-key, dump, change-pin

Firefox:
Card recognized, "Change Password" working, self-signed certificate is recognized

Openssl:
* Openssl RSA encrypted data can be deciphered using pkcs15-crypt
* RSA signatures generated by openssl with engine_pkcs11 can be verified with the public key with Openssl.
* ECDSA signatures created by pkcs11-tool verifiable by openssl with every supported curve. However limited input data length due to the fact that the IsoApplet requires plain input data and no precalculated hashes due to limitations of the Java Card 2.2.2 API (this does not count for RSA).
* Can create self-signed RSA certificates with openssl using engine_pkcs11.

OpenSSH authentication is working using RSA.

I might update this post.

**Comment by tc-anssi** [comment]
Hi,

I did not have time to investigate further issue #353 (closed now).
However, without the workaround I proposed (removing the overwriting of `key_usage`), I cannot segregate key usage on IAS-ECC cards.

It would be great to have this fixed for the 0.15 release !

**Comment by dengert** [comment]
I would propose the removing of the overwriting of the key usage.

All the card can do is a crypto sign|encrypt operation on some data. The card can not determine what it is signing, or how it will be used. The verifier of the crypto operation, be it a web or login
authentication, a recipient of a signed e-mail or an encrypted symmetric key, will look at the key usage bits in the certificate to make the final decision if the key is being used correctly.

So any attempts by the middleware, like OpenSC, to provide the caller with key usage bits are only to assist the user to the select the correct key, that the verifier will accept.
Additional middle ware above OpenSC may also look at the key usage in the certificates from the card to assist the user to select the correct key.

A user could in effect make the same "(removing the overwriting of |key_usage|)" modification to their copy of OpenSC, or remove any future fix in this area, or use other middleware.

The point is the correct key usage is not determined by the card, the user or the user's middleware.

The trust in the key usage is determined by the verifier who trusts the card issuer and the CA that signed the certificate and the key usage extensions in the certificate.


On 3/31/2015 6:31 AM, Thomas Calderon wrote:
> Hi,
>
> I did not have time to investigate further issue #353 <https://github.com/OpenSC/OpenSC/issues/353> (closed now).
> However, without the workaround I proposed (removing the overwriting of |key_usage|), I cannot segregate key usage on IAS-ECC cards.
>
> It would be great to have this fixed for the 0.15 release !
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/404#issuecomment-88053875>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by hongquan** [comment]
OpenPGP card (CryptoStick) works with OpenSC 0.15. Tested:

 - Import key and certificate from p12 file.
- Use that key to authenticate in Firefox.

Test in Ubuntu 14.10

**Comment by viktorTarasov** [comment]
* Aventra MyEID 4:
 * (re-)init
 * import PKCS#12; generate RSA, EC (secp192r1, secp256r1)
 * sign, decrypt

* CardOS 4.3B, SetCOS
 * (re-)init
 * import PKCS#12, generate RSA (1024)
 * sign, decrypt

* Gemalto IAS/ECC
 * erase protected and generic application
 * import PKCS#12, generate RSA 2048 in protected and generic application
 * sign (protected), decrypt with tools
 * generate key and import cert. with PKCS#11, minidriver (generic)
 * authentication (generic)

**Comment by resoli** [comment]
itacns on Ubuntu 14.10 64bit

A preliminary note: pkcs15-tool --help output is messed from --rfc4716 on

$ pkcs15-tool
Usage: pkcs15-tool [OPTIONS]
Options:
[...]
      --rfc4716                 Test if the card needs a security update
  -T, --test-update             Update the card with a security update
  -U, --update                  Uses reader number <arg>
      --reader <arg>            Specify PIN
      --pin <arg>               Specify New PIN (when changing or
unblocking)
      --new-pin <arg>           Specify Unblock PIN
      --puk <arg>               Verify PIN after card binding (without
'auth-id' the first non-SO, non-Unblock PIN will be verified)
      --verify-pin              Outputs to file <arg>
  -o, --output <arg>            Disable card caching
      --no-cache                The auth ID of the PIN to use
  -a, --auth-id <arg>           Specify AID of the on-card PKCS#15
application to bind to (in hexadecimal form)
      --aid <arg>               Wait for card insertion
  -w, --wait                    Verbose operation. Use several times to
enable debug output.
  -v, --verbose                 Do not prompt the user; if no PINs
supplied, pinpad will be used.

===
$ opensc-tool -i
OpenSC 0.15.0 [gcc  4.9.1]
Enabled features: zlib readline openssl pcsc(libpcsclite.so.1)

===
$ pkcs11-tool --module /usr/lib/pkcs11/onepin-opensc-pkcs11.so -t -l
Using slot 1 with a present token (0x1)
Logging in to "ROBERTO RESOLI (PIN CNS0)".
Please enter User PIN:
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only RSA signatures)
  testing key 0 (CNS0)
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
Verify (currently only for RSA):
  testing key 0 (CNS0)
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
Unwrap: not implemented
Decryption (RSA)
  testing key 0 (CNS0)  -- can't be used to decrypt, skipping

==

Test of onepin-opensc-pkcs11.so on firefox 0.37 works as expected.

===

The newly[1] implemented "opensc-tool --serial" works as expected.

Since this makes CSP minidriver working under MS platforms, hope to have
the time to build and test there as well.

Bye,
rob

[1]https://github.com/OpenSC/OpenSC/pull/321#event-210096874

**Comment by dirkx** [comment]
> itacns on Ubuntu 14.10 64bit
> A preliminary note: pkcs15-tool --help output is messed from --rfc4716 on
> 
> $ pkcs15-tool
> 
> 
Against which commit/tag was this ? As I am having trouble to reproduce.

Dw

**Comment by resoli** [comment]
@dirkx, branch opensc-0.15.0, got via 
git clone -b opensc-0.15.0 --single-branch https://github.com/OpenSC/OpenSC.git
rob

**Comment by resoli** [comment]
Here the whole output:
>$ pkcs15-tool
>Usage: pkcs15-tool [OPTIONS]
>Options:
>  -L, --learn-card              Stores card info to cache
>      --list-applications       List the on-card PKCS#15 applications
>  -r, --read-certificate <arg>  Reads certificate with ID <arg>
>  -c, --list-certificates       Lists certificates
>  -R, --read-data-object <arg>  Reads data object with OID, applicationName or label <arg>
>  -C, --list-data-objects       Lists data objects
>      --list-pins               Lists PIN codes
>      --list-secret-keys        Lists secret keys
>  -D, --dump                    Dump card objects
>  -u, --unblock-pin             Unblock PIN code
>      --change-pin              Change PIN or PUK code
>  -k, --list-keys               Lists private keys
>      --list-public-keys        Lists public keys
>      --read-public-key <arg>   Reads public key with ID <arg>
>      --read-ssh-key <arg>      Reads public key with ID <arg>, outputs ssh format
>      --rfc4716                 Test if the card needs a security update
>  -T, --test-update             Update the card with a security update
>  -U, --update                  Uses reader number <arg>
>      --reader <arg>            Specify PIN
>      --pin <arg>               Specify New PIN (when changing or unblocking)
>      --new-pin <arg>           Specify Unblock PIN
>      --puk <arg>               Verify PIN after card binding (without 'auth-id' the first non-SO, non-Unblock PIN will be verified)
>      --verify-pin              Outputs to file <arg>
>  -o, --output <arg>            Disable card caching
>      --no-cache                The auth ID of the PIN to use
>  -a, --auth-id <arg>           Specify AID of the on-card PKCS#15 application to bind to (in hexadecimal form)
      --aid <arg>               Wait for card insertion
  -w, --wait                    Verbose operation. Use several times to enable debug output.
  -v, --verbose                 Do not prompt the user; if no PINs supplied, pinpad will be used.

**Comment by dirkx** [comment]
> On 07 Apr 2015, at 17:32, resoli <notifications@github.com> wrote:
> 
> @dirkx, branch opensc-0.15.0, got via 
> git clone -b opensc-0.15.0 --single-branch https://github.com/OpenSC/OpenSC.git
> 

Thanks - found it - something in the merge went wrong. Missing is 2c50151453a7785f9989ba65b9b8949c3157d3d5. / #430

Dw.

https://github.com/OpenSC/OpenSC/compare/master...dirkx:master
 5  src/tools/pkcs15-tool.c

@@ -21,6 +21,7 @@
 
 #include "config.h"
 #include <ctype.h>
+#include <assert.h>
 
 #ifdef ENABLE_OPENSSL
 #if defined(HAVE_INTTYPES_H)
@@ -140,6 +141,7 @@ static const char *option_help[] = {
 	"Reads public key with ID <arg>",
 #if defined(ENABLE_OPENSSL) && (defined(_WIN32) || defined(HAVE_INTTYPES_H))
 	"Reads public key with ID <arg>, outputs ssh format",
+	"Outputs the public keuy in RFC 4716 format (requires --read-ssh-key)",
 #endif
 	"Test if the card needs a security update",
 	"Update the card with a security update",
@@ -155,6 +157,7 @@ static const char *option_help[] = {
 	"Wait for card insertion",
 	"Verbose operation. Use several times to enable debug output.",
 	"Do not prompt the user; if no PINs supplied, pinpad will be used.",
+	NULL
 };
 
 static sc_context_t *ctx = NULL;
@@ -1856,6 +1859,8 @@ int main(int argc, char * const argv[])
 	int action_count = 0;
 	sc_context_param_t ctx_param;
 
+	assert(sizeof(option_help)/sizeof(char *)==sizeof(options)/sizeof(struct option));
+
 	c = OPT_PUK;
 
 	while (1) {

**Comment by dwmw2** [comment]
Seems to work here on a Feitian PKI eToken and Yubikey NEO (PIV). Except that it doesn't work at all in OpenVPN due to #333, of course. That wants fixing, and the test case for it that I filed in #464 should probably go into the 0.15.0 branch too. (We should probably actually fix pkcs11-helper not to do that, since it violates POSIX in certain circumstances, but I'm not holding my breath).

#468 also needs fixing (by reverting the offending commit if it's possible to do it some other way, or just going ahead and bumping the soname).

The comments I made on #229 probably want addressing. I can do that if we have a consensus on what we want to do.
