### ISSUE TITLE
pkcs11-tool: inconsistent ECDSA signature format 

### ISSUE THREAD

**Issue by philipWendland** [OpenSC/OpenSC#407]
When doing ECDSA signatures with the pkcs11-tool, it converts the sequence of R,S integers to an ASN1 sequence understood by OpenSSL (if OpenSC is compiled with OpenSSL format).
It is not done with ECDSA-SHA1.

See:
https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L1418

This should also be done with ECDSA-SHA1:
https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L4760

However, in pkcs15-crypt an option to chose this format was introduced:
https://github.com/OpenSC/OpenSC/commit/b08671fab5b500ed18e7fe189d8e6aadbaf22f4b

This could also be done for pkcs11-tool instead of just changinng [line 1423](https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L1423) to
```
 if (opt_mechanism == CKM_ECDSA || opt_mechanism == CKM_ECDSA_SHA1) {
```
Which solution is preferred?

**Comment by dengert** [comment]
I would say, By default pkcs11-tool should be outputting what PKCS#11 says is the signature
This is the tool to test PKCS#11...

I would suggest that we use the same options as in as pkcs15-crypt and use the same code
if possible to convert the signature to a different format.

The choice of what is the format of the signature output should not depend on if the code
was compiled with or without OpenSSL. It looks like this choice of format based
on how it was compiled was in opensc-0.13.0.

Since it was in opensc-0.13.0, the default should be what ever it did.

I think this needs to be fixed for 0.15.0
and should work for any ECDSA signature mechanism.



On 3/26/2015 8:47 AM, Philip Wendland wrote:
> When doing ECDSA signatures with the pkcs11-tool, it converts the sequence of R,S integers to an ASN1 sequence understood by OpenSSL (if OpenSC is compiled with OpenSSL format).
> It is not done with ECDSA-SHA1.
>
> See:
> https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L1418
>
> This should also be done with ECDSA-SHA1:
> https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L4760
>
> However, in pkcs15-crypt an option to chose this format was introduced:
> b08671f <https://github.com/OpenSC/OpenSC/commit/b08671fab5b500ed18e7fe189d8e6aadbaf22f4b>
>
> This could also be done for pkcs11-tool instead of just changinng line 1423 <https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L1423> to
>
> |  if (opt_mechanism == CKM_ECDSA || opt_mechanism == CKM_ECDSA_SHA1) {
> |
>
> Which solution is preferred?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/407>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by philipWendland** [comment]
The default since 13.0 seems to be `OpenSSL signatures for ECDSA with OpenSSL` and `R,S signatures for ECDSA-SHA1` and `R,S with ECDSA and without OpenSSL`. One could argue that R,S signatures should be used for ECDSA and ECDSA-SHA1 not dependent on OpenSSL support, but it could break for example existing regression tests.


Using the same code (`sc_asn1_sig_value_rs_to_sequence()`) for the conversion seems to be difficult, as pkcs11-tool does not have access to sc_context (ctx) (?).
Using OpenSSL methods leads to restrictions when not compiled with OpenSSL, another option would be to do a simple hack with memmove and byte manipulations.

**Comment by dengert** [comment]
One could argue that 0.13 was broken, and the default should be R,S as that is what PKCS#11 does, and this is the "PKCS11"-tool.
Adding a format parameter would mitigated the change. Now would be the time to doi this as ECC is just catching on.

pkcs11-tool does not have access to the OpenSC ctx. PKCS11-tool was designed to work with non-OpenSC pkcs11 modules too,
so it is limited. Note the #include statements. It does use some sc_ functions for OIDs, including sc_asn1_encode_object_id
that does not take a ctx parameter.  Both sc_asn1_encode_object_id and sc_asn1_sig_value_rs_to_sequence are in asn1.c

It appears that sc_asn1_sig_value_rs_to_sequence takes ctx, for the sole purpose to log debugging messages.
At the heart of all the debug messages is sc_do_log_va  and sc_hex_dump that do:

           assert(ctx != NULL);

           if (ctx->debug < level)
                  return;

We could change this to

  if (!ctx || ctx->debug < level)
           return;

in effect for deb using messages, if ctx == NULL is the same as debug == 0

(This is just an idea, we need to look at this closer.)



On 4/3/2015 7:00 AM, Philip Wendland wrote:
> The default since 13.0 seems to be |OpenSSL signatures for ECDSA with OpenSSL| and |R,S signatures for ECDSA-SHA1| and |R,S with ECDSA and without OpenSSL|. One could argue that R,S signatures should
> be used for ECDSA and ECDSA-SHA1 not dependent on OpenSSL support, but it could break for example existing regression tests.
>
> Using the same code (|sc_asn1_sig_value_rs_to_sequence()|) for the conversion seems to be difficult, as pkcs11-tool does not have access to sc_context (ctx) (?).
> Using OpenSSL methods leads to restrictions when not compiled with OpenSSL, another option would be to do a simple hack with memmove and byte manipulations.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/407#issuecomment-89267309>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by philipWendland** [comment]
I totally agree. The `assert(ctx != NULL)` was what I found as well. I will try and find out which consquences your proposed change to sc_do_log_va and sc_hex_dump might have later, have to run now.

**Comment by philipWendland** [comment]
I didn't find a convincing reason why not to do this change. One risk is that new code could occur in future which calls functions with ctx==NULL even if it is possible to obtain a reference to ctx.

I created a new PR #427, things can be changed/rebased there. Thanks for your help so far - let's continue there.

**Comment by kousu** [comment]
Hiya, how do I verify an rs or sequence style signature? The opensc wiki has taught me about `openssl dgst -$HASH -verify pubkey.pem -signature $SIG $FILE` but that only works with openssl-format output. Sorry to bump an old thread but I'm having a real hard time googling this; this bug report is the only reference to the format question I've found, and I'd appreciate any pointers to other tools you can give me! Do I need to write a C program to verify rs signatures?

**Comment by dengert** [comment]
You can convert the R,S format to the sequence format. OpenSC contains both  `sc_asn1_sig_value_sequence_to_rs` and `sc_asn1_sig_value_rs_to_sequence` to convert from to another. 
[PKCS11-curr-v2.40](http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/pkcs11-curr-v2.40.pdf) Section "2.3.1 EC Signatures" may alos help you understand what you may need to do.

**Comment by kousu** [comment]
Hi @dengert, thanks for chiming in!

1. My question is what tools support the 'rs' and 'sequence' formats? It seems that, in practice, I _must_ use 'openssl' because I don't know of any other tooling. Does libsodium support the rs format? What about the sequence format?
2. Who defined the rs and sequence formats?
3. It is confusing that `--signature-format` only applies to ECDSA; you can pass it when not using ECDSA, and it's just ignored, instead of giving an error. I spent a while this week wondering if I could use it to convince RSA mode to output DER vs PEM formats -- would both of those count as 'openssl' format? Why can't `-f` apply to all mechanisms?
4. In general, the output formats of `pkcs11-tool --sign` seem underdocumented; _is there a list of all the formats `pkcs11-tool` will sign with, and what tools can be used to verify each signature format?_ experimentally
  - `-m RSA-PKCS` produces a binary (PKCS#1.5-padded) RSA encryption of whatever is passed in
    - you can get it back out with `openssl rsautl -verify -inkey 9a.pub -pubin -raw -in "$FILE".sig`; if you replace `"$FILE".hash` with say, some text, you will see it come out again
  - `-m SHA1-RSA-PKCS` and its cousins (`SHA512-RSA-PKCS`, `SHA256-RSA-PKCS`...) produce a an a binary (PKCS#1.5-padded) RSA encryption of DER-encoded-ASN1 structure (omg so many formats!!) that is basically the tuple `('algorithm, hash)`
    - you can inspect it with `openssl rsautl -verify -inkey 9a.pub -pubin -in "$FILE".sig | openssl asn1parse -inform DER`

For any future travelers in this niche, here's a reference test run of what works for me and what doesn't.

I've got a [YubiKey 4](https://support.yubico.com/support/solutions/articles/15000006486-yubikey-4) and I'm using its PIV applet via OpenSC's [piv driver](https://github.com/OpenSC/OpenSC/wiki/US-PIV).

I have [`ykman`](https://github.com/Yubico/yubikey-manager) installed, along with opensc (which is the only supported Linux client, [according to YubiCo](https://developers.yubico.com/PIV/Introduction/Platform_support.html).

I can initialize an ECC key on the card in the [9a slot](https://developers.yubico.com/PIV/Introduction/Certificate_slots.html) like this:

```
ykman piv reset
ykman piv generate-key -a ECCP384 9a 9a.pub
ykman piv generate-certificate -s "ECC key test" 9a 9a.pub  # without this, `pkcs11-tool -O` nor `pkcs15-tool --list-keys` won't report the key being available
```

Then I can sign something with the card:

```
$ FILE=something.mp3
$
# NB: the hash step has to be done separately because pkcs11-tool only supports --mechanism ECDSA, not SHA512-ECDSA; it could also be done in software with `openssl dgst`
# YubiCo has written an alternate PKCS#11 implementation that pkcs11-tool can call which does suppose hash+sign all in one: https://developers.yubico.com/YubiHSM2/Usage_Guides/Using_OpenSC_pkcs11-tool.html, but that's annoying
$ pkcs11-tool --hash -m SHA384 --input-file "$FILE" --output-file "$FILE".hash
$ pkcs11-tool --id 01 --sign -m ECDSA --pin 123456 --input-file "$FILE".hash --output-file "$FILE".sig
```

But this signature doesn't verify, because _when using ECDSA signatures_, the output is in "rs" format:

```
[nguenthe@papyrus experiment]$ openssl dgst -sha384 -verify 9a.pub -signature "$FILE".sig "$FILE"
Error Verifying Data
139724480901632:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1129:
139724480901632:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:289:Type=ECDSA_SIG
```

I figured out what to do by digging futher into this bug and realizing that making that format optional was added in #427: `--signature-format openssl` fixes it:

```
$ pkcs11-tool --id 01 --sign -m ECDSA --signature-format openssl --pin 123456 --input-file "$FILE".hash --output-file "$FILE".sig
Using slot 0 with a present token (0x0)
Using signature algorithm ECDSA
$ openssl dgst -sha384 -verify 9a.pub -signature "$FILE".sig "$FILE"
Verified OK
```

**Comment by dengert** [comment]
The RS format is defined by PKCS11. So by default pkcs11-tool returns the
PKCS11 format.
