### ISSUE TITLE
Compilation without OpenSSL - guid computation issue

### ISSUE THREAD

**Issue by vletoux** [OpenSC/OpenSC#425]
There is an issue when OpenSC is compiled WITHOUT OpenSSL and if the serial number is less than 15 bytes.
This case is triggered when OpenSC is called from the minidriver, when it needs to have the GUID for each container (called from CardAcquireContext)

If OpenSSL is enabled, id.len is forced to the size of a SHA hash, else id.len = 1 when called from the minidriver
Check the #ifdef ENABLE_OPENSSL
![1](https://cloud.githubusercontent.com/assets/10632326/6980977/a8e67ebe-d9fa-11e4-9f2c-ab6984756dd8.png)

Then sc_pkcs15_serialize_guid is called and fails if id.len & serialnumber.len < 16.
In this case, it fails if serialnumber < 15 bytes because id.len = 1

![2](https://cloud.githubusercontent.com/assets/10632326/6981008/33fb5538-d9fb-11e4-8c96-e55712df1e7e.png)

My suggestion would be to remove the <16 check (if compiled with OpenSSL, this check is always satisfied) or to lower it, for example to 3 or 1.
Indeed, the function sc_pkcs15_serialize_guid is always called from sc_pkcs15_get_object_guid
In my tests, commenting the test do not produce any other impact.

(sorry I do not do a pull request - my last one  #414 is still not approved)

Vincent

**Comment by frankmorgner** [comment]
`in_size` is forced to have a certain size because `in` is accessed at these positions. You can check the value of `offs` at the end of `sc_pkcs15_serialize_guid`. There is no segmentation fault because `guid_bin` in `sc_pkcs15_get_object_guid` is always long enough.

However, if OpenSSL is deactivated then the length of the input data depends on the card's serial number in EF.TokenInfo + the length of the object's ID. Both length depend on the personalized values on the card itself (potentially hostile input from the library's point of view). So the length check is always needed.

**Comment by frankmorgner** [comment]
The "hostile input" as mentioned above can not cause a segmentation fault. But it causes the rest of `guid_bin` to be uninitialized (i.e. set to `0`). This may be a problem in case of collision with other cards. So iff we are willing to risk a collision (don't know if that's a problem) then we may expand the length passed to `sc_pkcs15_serialize_guid` to be 16 rather than omitting the length check in `sc_pkcs15_serialize_guid`.

**Comment by frankmorgner** [comment]
Thinking about it, leaving the `guid_bin` at `"id + serial + 0..0"` is as good as setting it to `"SHA1(id + serial)"` from an entropy point of view. Does Windows sometimes use only the last bytes of the GUID? If not, I'd go with passing 16 as input length from `sc_pkcs15_get_object_guid` to `sc_pkcs15_serialize_guid`.

**Comment by dengert** [comment]
Since this is for the minidriver, why not use the Microsoft

CryptCreateHash and CryptHashData to do the sha1

  https://msdn.microsoft.com/en-us/library/windows/desktop/aa379908(v=vs.85).aspx

(This is just an idea, I have not looked at it closely.)

There are cards in use today, that depend on the guid to remain the same,
because the Microsoft certificate store has cached information about the card
using the current method of generating the guid t iidentify the card. This need to keep working.
So the keep the SHA1.

Sha1 is not a security risk in this situation, but a uniqness problem that the minidriver needs
to return the same number for existing cards each time, and sha1 is still good for that.



On 4/3/2015 6:13 PM, Frank Morgner wrote:
> Thinking about it, leaving the |guid_bin| at |"id + serial + 0..0"| is as good as setting it to |"SHA1(id + serial)"| from an entropy point of view. Does Windows sometimes use only the last bytes of
> the GUID? If not, I'd go with passing 16 as input length from |sc_pkcs15_get_object_guid| to |sc_pkcs15_serialize_guid|.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/425#issuecomment-89447277>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
I know how to use the crypto api hash function but won't there are a cross compilation problem with minigw? (If built for Unix / built on Unix for windows)
If yes should the code be encapsulated in a define and if yes, which one ?
Vincent

**Comment by dengert** [comment]
On 4/4/2015 1:53 AM, vletoux wrote:
> I know how to use the crypto api hash function but won't there are a cross compilation problem with minigw? (If built for Unix / built on Unix for windows)

Good question. I don't know.  I would assume that the mingw has access to the header files from the Windows SDK.
and we are only taking about doing this is not built with OpenSSL, and the guid calculation is really only
done for the minidriver. The code could be moved to teh mindriver if its not already in the mindriver.


There are two other options.

Add a separate sha1 routine. (I thought that at one time OpenSC has a sha1 routine, but can not find
it right now.) It would only be used if not built with OpenSSL.

Live with the fact that the guid will be different if built with or without OpenSC.

The guid or values derived from the guid are stashed by windows in the Microsoft certificate store
so a card can be associated with cached certificate/key pair. This is on a machine by machine.
So in most cases we are talking about a hand full of cards that are ever used in a machine.

If the way OpenSC calculates the guid changes based on having or not having OpenSSL because of
the lack of SHA1 would only effect a machine that switches between versions of OpenSC that
use SHA1 and a version that does not. Such as a upgrade of the software. This can be very hard
on a user, as the code stops working for their existing cards.  (This may not be an issue
as most versions of OpenSC are built with OpenSC.)


> If yes should the code be encapsulated in a define and if yes, which one ?
> Vincent
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/425#issuecomment-89514213>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
If I'm correct, opensc builts are compiled with OpenSSL. Only a manual built without OpenSSL triggers the problem. The problem is seen on Windows only because the minidriver does not load the card (because the "id" is too short)
I may be the only one seeing that "bug".

Note: the certificate propagation service (which registered the certificate in the certificate store) recreates the entry.

Would a #ifdef WIN32 inside the #else solve the problem?
It will impact only windows built and building a code from source is pretty rare on the Windows platform.

Second option: force a 16 bytes Id on the minidriver side. In this case, all windows built is impacted because all the guid will be changed.

Vincent

**Comment by dengert** [comment]
@viktorTarasov 
Can you comment on this issue, especially on the use or SHA1 in the sc_pkcs15_get_object_guid
and what to do if OpenSSL is not used?
You have more of a stake in this code then I do. 

The card I am most interested does not use the sha1 code, but lets the card driver determine the guid. In sc_pkcs15_get_object_guid this is called:
  rv = p15card->ops.get_guid(p15card, obj, out, out_size);

**Comment by frankmorgner** [comment]
Minidriver is used exclusively on Windows, so a `#ifdef _WIN32` does not make much sense. The minidriver is deactivated when cross compiling in CI because it's already incompatible with MinGW. Today the MSI is built with Visual studio only so that you can simply ignore the corner cases and simply use `CryptHashObject` or whatever you prefer.

The correct (tm) way would be to add checks to configure.ac with your function testing compilation of a program with the sha1 implementation of your choice (`AC_CHECK_FUNCS`). This adds a define to config.h if it is found and you can test for #ifdef HAVE_FUNCTIONOFCHOICE. Next you need to define `HAVE_FUNCTIONOFCHOICE` in `winconfig.h.in` which is included when building with visual studio.

**Comment by viktorTarasov** [comment]
Without resolving with/without OpenSSL compiled consistency of GUID:
if one/three bytes of ID + serialNum is sufficient for you to get the unique GUID
then *sc_pkcs15_get_object_guid* can be called with at least 16 bytes of input data.
(https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/pkcs15.c#L2760)

So, this data will be the ID+Serial right padded with zeros
or padded with somewhat else, like CRC32(ID+Serial).
This last one is present in code without OpenSSL.

**Comment by vletoux** [comment]
Hi,

Here is my proposition:
I just extend the size to 16 bytes as suggested by Viktor

https://gist.github.com/vletoux/b445f6fb3bf54263ce2b

regards,
Vincent
