### ISSUE TITLE
Pinpad error handling improvement

### ISSUE THREAD

**Issue by vletoux** [OpenSC/OpenSC#439]
Hi,

I'd like to discuss about Pinpad error handling.
Indeed, the iso7816.c file doesn't handle it while ctbcs.c does handle a few messages.

The error code about PinPad firewalling (SW1=64 SW2=04) isn't known by OpenSC. I'm using a Gemalto Enzo Shield for my tests. As a consequence, the default error SC_ERROR_CARD_CMD_FAILED (-1200) is returned and the message shown by Windows isn't pretty (PIN invalid).

I'd like to fix it by:
- adding the error code SC_ERROR_KEYPAD_TIMEOUT, SC_ERROR_KEYPAD_CANCELLED, SC_ERROR_KEYPAD_PIN_MISMATCH, SC_ERROR_KEYPAD_MSG_TOO_LONG and labels in iso7816.c file
- add a new error code corresponding to the 6404 return code named SC_ERROR_KEYPAD_REQUIRED and its handling in ctbcs.c and iso7816.c
- handle it in the minidriver

I'm waiting for your feedback

regards,
Vincent

**Comment by frankmorgner** [comment]
The error codes you are referencing to are from PC/SC part 10 section 2.6.3 FEATURE_VERIFY_PIN_FINISH / FEATURE_MODIFY_PIN_FINISH. And actually they should be handled in the reader driver (i.e. in ctbcs.c or in https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/reader-pcsc.c#L1696-L1712). The error code from the reader should be propagated also by the 7816 card driver, see https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/iso7816.c#L1095.

I could imagine that at some point the specific error code (e.g. keypad timeout) gets replaced by a non specific error. You could try to find out where that happens to avoid the loss of information.

**Comment by frankmorgner** [comment]
actually I just checked with 7816-4 and it *does* specify 64XX error codes. but they are not related to a pinpad reader:
![pic](https://cloud.githubusercontent.com/assets/1266577/7158125/048473cc-e377-11e4-91e2-6b989b5b542e.png)
... which means that keypad errors *must* be handled by the reader driver instead of a card driver.

**Comment by martinpaljak** [comment]
AFAIK, right now the "firewalled" response code is not described anywhere and I *think* that only Gemalto does use it, instead of some generic "INS not supported" style SW:

http://www.pcscworkgroup.com/specifications/files/pcsc10_v2.02.09.pdf

Last time I heard, pcscworkgroup thought that this is none of their business to define those errors (which is strange):

http://ludovicrousseau.blogspot.com/2011/12/pcsc-workgroup-november-2011-meeting.html

Most of the more detailed error codes make sense when you have a way to inform the user with some sort of message and GUI, but don't make much sense when you need to adjust the code to speak some existing API, be it PKCS#11, minidriver or Tokend. None of them includes the *exact* status codes and translating "pinpad required" to some weird but semantically similar errors (like "not allowed") shall probably result in strange or unwanted behaviour in the UI, in the end.

So on one hand an API should be as exact and specific as possible, on the other hand we need to think on the context where most of the apps are using OpenSC: drivers. It doesn't make sense to "pollute" the OpenSC namespace with arbitrary errors, because errors need to be handled but I don't see who and where should handle it in OpenSC. So instead define clearly the expected outcomes from a PIN operation in the scope of existing API constructs and statuses.

**Comment by martinpaljak** [comment]
So yeah, pinpad issues need to be resolved in reader-pcsc.c and mapped to generic-yet-meaningful errors, if they arise.

**Comment by vletoux** [comment]
Should I propose a patch to include the new error code SC_ERROR_KEYPAD_REQUIRED and test 6404 in reader-pcsc.c ?
Should this modification include a test about the reader to limit it to the gemalto ones or should this behavior happen for all readers ?

Should a trace be added for all pinpad events in reader-pcsc.c ?
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/reader-pcsc.c#L1696-L1712

regards,
Vincent

**Comment by frankmorgner** [comment]
I just double checked: In PCSC pt 10 the defined error codes do *not* include `6404`, as Martin stated above. I would hesitate to include it in OpenSC.

What's the situation when you get this error? `SC_ERROR_KEYPAD_REQUIRED` would indicate to me that OpenSC should have used the PIN-Pad instead of sending a VERIFY. This should not happen in the default configuration: The use would have to specify `enable_pinpad = false;` in the configuration file. If so, I would suspect the user knows what he's doing and can deal with a cryptic error message.

**Comment by vletoux** [comment]
The problem is with the minidriver.
There are many cases where applications ask the PIN then pushes the PIN using CryptSetProvParam when the application can't display a GUI.
(for example the smart card logon from lsass.exe or runas /smartcard which forward it to the runas service).
I'm just trying to avoid the error message "your PIN was incorrect" if the problem is related to a PIN firewall.

Indeed, 6404 is not defined in PCSC pt10. I just saw Ludovic proposal about that.
If you think it is specific, it is possible to restrict the test to Gemalto readers until it is formalized.

Then if OpenSC is sending an error code about that, I can add a translation in the minidriver to change it to a pure windows error code (which doesn't have a pinpad firewall error code)

I now that the change i'm proposing can be debated, that's why I didn't yet propose a patch.

**Comment by frankmorgner** [comment]
Do you agree, that `6400`...`6403` are handled correctly by OpenSC?

Just for the record, if you're using a reader with firewall *and* you can't avoid Windows' PIN caching then you are screwed anyway (*even if* you can throw a meaningful error message).

I think `6404` should not be handled in a generic way (i.e. "for all ISO-cards" or "for all PCSC readers") in neither the core libraries nor in the minidriver because it can have a different meaning for different vendors.

I think this issue is related to #209 #307 #306 where we are essentially handling "special" behavior of a reader. We need a more generic way of handling these fixups, though previous approaches have not been very fruitful.

**Comment by vletoux** [comment]
Yes, I agree that the pcsc reader handle 6400 to 6403 and that I'm screwed with the firewall feature trying to logon to Windows.
I just wanted to fix the error reporting (as the title of this issue suggests it) to be better and not scare the user about an invalid PIN.

You can decide to not fix my particular issue, but I think the error code SC_ERROR_KEYPAD_REQUIRED should be at least defined for a future implementation.

If readers need fixes, why not implementing an "inherit feature" ?

**Comment by martinpaljak** [comment]
Being one of the persons who proposed the code in question, the logic behind my selection was:

  * it is anyway an artificial SW and not the best glue for signalling, whatever is chosen is still essentially piggypacking 
  * it is synthesized by the the reader, rather than a response from the card => should be a SW not *usually* returned by VERIFY and other interpreted commands
  * belongs to the "pin handling" and "secure pin entry" category of issues => makes sense to bundle it together with the other codes that deal with the issue and are generated by the reader, rather than card, that (suitable or not) happen to be 64XX in the PC/SC spec
  * take the first "free" code from that list => 6404

The reality is that the number of readers (or vendors) building readers with a firewall is (at least was, some time ago) probably countable with one, maximum two hands. Ludovic's list currently has 4.

Practicality beats purity, so when other PIN handling commands (due to code in readr-pcsc.c) can assume that the *reader* - not the card - return codes in the 64XX range, it is almost-valid for the "ISO" generic code in iso7816.c, if necessary.

Taking into account how the pinpad specification was created (called "teletrust" originally) it maks sense if we try to stick to some endorsements rather than implement this as an exception. Or the next firewalled reader that gets implemented/tested with free software might again use some other random SW for such errors.

**Comment by dengert** [comment]
https://support.microsoft.com/en-us/kb/2589130

implies there is a registry setting for turning off the pin caching. May not apply to all windows systems.

I don't see this in my registry on W7 Pro.



On 4/16/2015 11:41 AM, Frank Morgner wrote:
> Do you agree, that |6400|...|6403| are handled correctly by OpenSC?
>
> Just for the record, if you're using a reader with firewall /and/ you can't avoid Windows' PIN caching then you are screwed anyway (/even if/ you can throw a meaningful error message).
>
> I think |6404| should not be handled in a generic way (i.e. "for all ISO-cards" or "for all PCSC readers") in neither the core libraries nor in the minidriver because it can have a different meaning
> for different vendors.
>
> I think this issue is related to #209 <https://github.com/OpenSC/OpenSC/pull/209> #307 <https://github.com/OpenSC/OpenSC/issues/307> #306 <https://github.com/OpenSC/OpenSC/issues/306> where we are
> essentially handling "special" behavior of a reader. We need a more generic way of handling these fixups, though previous approaches have not been very fruitful.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/439#issuecomment-93780984>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
About the minidriver, if a PIN is submitted and refused by the reader (SC_ERROR_KEYPAD_REQUIRED), I can modify it to request it on the pinpad by submitting a null PIN.

I see one problem with this approach: as is, displaying a UI is actually required to use a PINPAD (to ask the user if he really wants to enter the pin using the pinpad - action which can be cancelled).
I may need to add a configuration parameter (no set by default) to not display this dialog is the flag "no UI" (CRYPT_SILENT) is set.

In this case, OpenSC should be able to be used on smart card logon with a Pinpad firewall.
Example:
at the logon screen, enter any PIN (or a blank one)
The pinpad rejects it and the minidriver relaunch a pinpad authentication
The user is logged on.

Requirements:
- an official error code about pinpad firewall
- some function which returns this code
- the configuration parameter to ask the pin on a pinpad without a UI is active

**Comment by martinpaljak** [comment]
The other option is to have custom PIN dialog for the pinpad.

**Comment by vletoux** [comment]
I don't understand what you say. What do you mean by a custom dialog ?

When CRYPT_SILENT is set (for example from lsass.exe when a smart card logon attempt is set), the authentication is denied.
See : https://github.com/OpenSC/OpenSC/blob/master/src/minidriver/minidriver.c#L3315-3316

When the minidriver is allowed to create dialog, a simple messagebox is shown.
See : https://github.com/OpenSC/OpenSC/blob/master/src/minidriver/minidriver.c#L3342-3359

As a consequence, Windows smart card logon with a pinpad can work only if a pin is submitted (and not firewalled). Pinpad smart card logon doesn't work.

**Comment by frankmorgner** [comment]
@vletoux if I understand correctly, you want to satisfy Windows by honouring the PIN-Dialog with a NULL-PIN but you will ask for the PIN on the PIN-Pad nontheless. I agree, that will work for the Login. However, you will get most likely some unexpected side effects since Windows believes the NULL PIN is the correct one and will provide this PIN to a number of subprocesses.

I'm sure it's a hell you don't want to go through ;-). I think it's best to simply not support this use case and instead give a good error message. I had the same issue in a different project where we ended up modifying the Firmware of the PIN-Pad reader. Now, its firewall has some very specific rule when to allow a preconfigured PIN.

**Comment by martinpaljak** [comment]
On Fri, Apr 17, 2015 at 12:11 PM, Frank Morgner <notifications@github.com>
wrote:

> Now, its firewall has some very specific rule when to allow a
> preconfigured PIN.


Interesting, could you share this ?

--
Martin
+372 515 6495

**Comment by frankmorgner** [comment]
@martinpaljak sorry, can't share the details

**Comment by vletoux** [comment]
@frankmorgner I do not know what is your Windows knowledge but a NULL pin means no PIN cache on Windows (pin=null => no PIN ; pin="" => empty PIN). Moreover pushing a NULL pin force to clean the cache (cf CryptSetProvParam documentation).
I'm pretty confident about what be done with Windows because I closely looked at the Windows Smart card logon implementation while implementing the security package used in EIDAuthenticate.

When you connect with a smart card, the PIN is collected from a credential provider and package in a structure. This structure is then pushed to lsass.exe (via LsaLogonUser) which gets forwarded to a security package. Lsa then call the login function of the security package (LsaApLogonUserEx2). In the case of kerberos, it does some cryptographic operations then ask via CryptoAPI to compute a signature / decypher a challenge  (depends on the type of mapping - explicit or UPN) to verify the PIN. That"s CryptoAPI via the BaseCSP which asks the minidriver to do it. Any caching on the PIN is done in cryptoAPI. There is no resilience in lsass.exe.

If you push an empty PIN when authenticating, the minidriver will be called with the PIN="" (!=NULL). OpenSC send it to the PINPAD reader which is firewalling it. Then if the minidriver resent the NULL PIN to OpenSC, OpenSC force the use of the PINPAD.
So on my opinion, there is no side effect.

**Comment by frankmorgner** [comment]
@vletoux thanks for clearifying, I didn't know the details. But isn't it true that especially for Windows 8 a number of other processes would require user authentication directly after logging in (i.e. the user would have to insert the PIN at the pin pad mulitple times after logging in)?

**Comment by vletoux** [comment]
@frankmorgner i do not know what you mean. Once the Kerberos ticket is generated and added to the token , there is no more authentication to perform. Have you an example of application ?

**Comment by dengert** [comment]
With Kerberos and smart card, The client machine is using PKINIT to the AD DC acting as teh KDC. Part of the protocol is  the KDC returns a nounce, which is  encrypted by the card and returned to  the KDC. Tthe KDC then returns the Kerberos TGT. With  smart card login, the PIN is only needed once.

https://msdn.microsoft.com/en-us/library/cc238455.aspx

https://tools.ietf.org/html/rfc4556

Later some other applications may need to sign e-mail, encrypt e-mail or do web authentication using TLS. This may require additional uses of the card and may require the PIN.

**Comment by frankmorgner** [comment]
If so, then nevermind. Sorry for the noise.

**Comment by vletoux** [comment]
Ok I've proposed a fix for windows login. Handling pin firewall error code doesn't help.

At the login prompt, windows recognizes card with external pin and call cardauthenticatex. The windows asking for the pin is shown. Once the pin is entered at the pin pad,windows reuse the session pin created by this function in further calls to CardAuthenticateEx.

Creating a dummy session pin which triggers pin pad prompt fixes the windows login. However the pin is asked several times (I counted 5 times)

To avoid multiple pin prompt is there something in ISO 7684 which can ask as a session pin and which is implemented in driver ?  Something returned after a pin authentication and not firewalled ? Get challenge ? 
I suppose that the card should also provide a deauthentication function to avoid reset and lost the session pin.

Vincent

**Comment by frankmorgner** [comment]
As written in https://github.com/OpenSC/OpenSC/issues/439#issuecomment-93949305, I encountered your problem earlier. As far as I know, there is no easy fix to this issue. What we could do is implement a session PIN in software i.e. a (temporary) magic PIN that always verifies to 0x9000 without prompting the card (or the reader). But that's a lot of work and may have some corner cases. I don't know any real card that implements a session PIN.

Each card driver should do deauthentication in the card's finish function. It is called whan the OpeSC's card handle is freed. Additionally the card is "reset" in the reader on the PC/SC level (reset/poweroff/leave can be configured in opensc.conf).

**Comment by vletoux** [comment]
yes and no.
Your special solution worked because the card was not deauthenticated between calls. I wrote a ticket about that because on my opinion this is a security vulnerability #434 
=> sorry if I broke your pinpad firmware fix by triggering a reset of the card

As a consequence, I think that implementing a fake pin doesn't work because the card is now reseted (and the user unauthenticated) by the Base CSP when the context is disposed.

One card i know is working is the Gemalto Idprime. This card provides indeed:
- an deauthentication function (which is provided into the minidriver and do not make a reset on the card)
- an session pin which can be generated after a successful VERIFY and can be used to establish the security context again until the card has been reseted.

If software adjustment can be done in drivers, does any cards have this functionalities ?
I see in iso7816 for deauthentication:
VERIFY : if P1 = FF => set verification status to “not verified”, see last paragraph of this clause
for session pin:
Internal authenticate

**Comment by frankmorgner** [comment]
*Deauthentication*: If it is in the standard we can implement it for iso7816.c's verify. But this may not work for the other cards (either because they overwrite the verify command or because the card does not support it). We could work around the card's limitation by manually resetting the card in the deauthentication function (which should also fix #434 while allowing efficient deauthentication without reset). think of a new call back function in the card driver that allows deauthentication and which is NULL by default. If the callback is not implemented by the driver then manually reset the card if deauthentication is triggered.

*Multiple PIN-Pad prompts*: That's the "told you so" I was referring to and that is what we solved by allowing the PIN to be passed to the reader in certain situations. And yes, I think it can also be solved by implementing a state machine for the session PIN in software.

**Comment by vletoux** [comment]
Deauthentication: yes, I can propose a patch using a new callback.

For the moment, I've on hold a lot of changes in the "minidriver branch" and some waiting in #443 (I do not know what's the problem with the compilation or if I should do something). Moreover I checked with git and there is no fast forward merge from the "minidriver branch" to the main one.
I do not want to make proposition that won't be accepted.
Should I request some commit about the whole change I made ?

Since most of the minidriver changes I've planned have been done, I'd like to work on the setup.
Mostly on the minidriver registration.
(FYI, I made a test in my repository to change the background from the default red from wix to a nice one - see https://github.com/vletoux/OpenSC/commit/7a7f8fb27471719a32f0cdcf819170771589791b)

About multiple pinpad prompt: my understanding is that smart card logon with pinpad wasn't working because no session pin were handled (after I fixed the deauthentication bug). Maybe I'm wrong. But with the last commit I made in my pull request, smart card logon is now working. Indeed, with multiple pinpad prompt.
Making a "non safe" patch is easy to limit pinprompts:
1) do it only if GetModuleName == "lsass.exe" && OS >= Vista
2) do not call for a deauthentication in CardDeauthenticate(Ex)
3) call for a deauthentication in CardDeleteContext
The risk is limited because system smart card calls are isolated from session ones since Vista.
With this, you'll get only 2 pinpad prompt (in winlogon.exe and in lsass.exe)

**Comment by dengert** [comment]
One of the issues early with the minidriver, was that Windows would call the minidriver with the same pCardData but different handles
and the check_reader_status() was added to call disassociate_card() and associate_card() if the handle changed.

In the linux version this is not a problem because OpenSC has a list of readers in clode that is not used by the minidriver.
Maybe the minidriver needs code more like the linux version and keeps a list of active handles so upon seeing the handle change it can switch
between them rather calling disassociate_card() and associate_card(). Maybe there needs to be something like queue_handle and resume_handle
that does not reset the card (Could uses channels or multisession to the card if the card supports it?)

The pCardData appears to be shared among processes/threads that can access the same card without having to re-authenticate.



On 4/21/2015 3:27 AM, vletoux wrote:
> yes and no.
> Your special solution worked because the card was not deauthenticated between calls. I wrote a ticket about that because on my opinion this is a security vulnerability #434
> <https://github.com/OpenSC/OpenSC/issues/434>
> => sorry if I broke your pinpad firmware fix by triggering a reset of the card
>
> As a consequence, I think that implementing a fake pin doesn't work because the card is now reseted (and the user unauthenticated) by the Base CSP when the context is disposed.
>
> One card i know is working is the Gemalto Idprime. This card provides indeed:
>
>   * an deauthentication function (which is provided into the minidriver and do not make a reset on the card)
>   * an session pin which can be generated after a successful VERIFY and can be used to establish the security context again until the card has been reseted.
>
> If software adjustment can be done in drivers, does any cards have this functionalities ?
> I see in iso7816 for deauthentication:
> VERIFY : if P1 = FF => set verification status to “not verified”, see last paragraph of this clause
> for session pin:
> Internal authenticate
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/439#issuecomment-94700867>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
What I think is that the minidriver does not change handles except when it receives the error scard_e_system_cancelled when calling ScardBeginTransaction. This error is triggered when there is a switch to the secure desktop (aka winlogon) to not mix smart card communication made inside the session with the logon session.

The minidriver handles can be shared by threads (the CryptoAPI context HPROV are shared too) but not among different processes. A smart card handle is just a memory address inside a process.

For me, you have a clear pattern:
one base csp object <-> one minidriver pcarddata
When you called CryptReleaseContext, CardDeleteContext is called, everytimes.
[Note: You can check some kerberos code leaked when part of Windows 2000/NT4 was published to see CryptoAPI calls.]
So : end of logon operation -> end of kerberos code -> cleaning for CryptoAPI calls -> cryptreleasecontext -> carddeletecontext   and no handle change (because it is a system call) nor smart card reset except the one made in CardDeauthenticate(Ex).

I'm not a smart card specialist, but I practiced Windows smart card a lot. If you need some CryptoAPI test code, I'll be happy to release it ;-)

by the way, I found why my #443 built wasn't working : I forget to declare IDC_STATIC in the .rc file. I'm gonna fix this.

**Comment by dengert** [comment]
On 4/21/2015 9:07 AM, vletoux wrote:
> What I think is that the minidriver does not change handles except when it receives the error scard_e_system_cancelled when calling ScardBeginTransaction. This error is triggered when there is a
> switch to the secure desktop (aka winlogon) to not mix smart card communication made inside the session with the logon session.

That was were I had see it too.

>
> The minidriver handles can be shared by threads (the CryptoAPI context HPROV are shared too) but not among different processes. A smart card handle is just a memory address inside a process.
>
> For me, you have a clear pattern:
> one base csp object <-> one minidriver pcarddata
> When you called CryptReleaseContext, CardDeleteContext is called, everytimes.
> [Note: You can check some kerberos code leaked when part of Windows 2000/NT4 was published to see CryptoAPI calls.]
> So : end of logon operation -> end of kerberos code -> cleaning for CryptoAPI calls -> cryptreleasecontext -> carddeletecontext and no handle change (because it is a system call) nor smart card reset
> except the one made in CardDeauthenticate(Ex).

Just thought I would bring the check_reader_status to your attention, as it maybe doing something it should not.

>
> I'm not a smart card specialist, but I practiced Windows smart card a lot. If you need some CryptoAPI test code, I'll be happy to release it ;-)

I am retired now, but used to do a lot with Kerberos, PKINIT, AD, Linux Kerberos login to AD as well as IETF krb-wg chair and even Shibboleth smart card authentication.
I don't want to setup AD or even a KDC at home to do any minidriver testing, but still keep up on OpenSC, as it is easy to test.

Someone else on this list might find the CryptoAPI test code useful.

>
> by the way, I found why my #443 <https://github.com/OpenSC/OpenSC/pull/443> built wasn't working : I forget to declare IDC_STATIC in the .rc file. I'm gonna fix this.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/439#issuecomment-94807911>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
All your changes on the dedicated branch look good and, I think, they can easily be integrated in master. It still needs some testing with some other cards/readers, however.

I think @viktorTarasov created the dedicated branch because you announced a big chunk of changes that seemed hard to review. Separating it in smaller chunks that get integrated in a dedicated branch makes review a bit easier.
