### ISSUE TITLE
TLS with openssl pkcs11 engine 

### ISSUE THREAD

**Issue by flyingmouse** [OpenSC/OpenSC#481]
I am trying to establish a TLS connection using the credentials stored in a cryptographic token (Gemalto IDPrimeMD in my case and I have its pkcs11 module).  Perhaps openssl pkcs11 engine is a possible solution. The [tuto](http://blog.fkraiem.org/2013/03/13/linux-smart-card-authentication-openssl/) I find only permits to generate certificates using the keys stored in the token. But I have no idea if openssl pkcs11 engine can do the TLS connection I mentioned above. Does anyone have any ideas? Thanks in advance.

**Comment by dengert** [comment]
You did not say if the TLS is one way (server has cert and key) or two way (both have their own cert and key).
The OpenSSL s_client and s_server programs both have a -engine option, so they should work.

Google for: openssl s_client engine

For web, the servers private key could be on a smart card or HSM but usually is not because the key needs to be used on every TLS connection
and smart cards are to slow to use on a server.

For uses with a browser FireFox, chrome, IE all support the use of smart card
for authentication of the user to the server.

Google for: firefox pkcs11

Sounds like you first need to get a key and a certificate on the card. Does your card already have
a key and certificate?

Can you use the vendor's libs? sounds like you could:
http://www.gemalto.com/Products/idgo_800_generic/index.html


The first half of the example is how to setup using the opensc engine_pkcs11. The second half is how to use a EnterSafe
card and generate a certificate request using openssl req  with the engine and an existing key on the card.

Have a look at the OpenSC wiki:

   https://github.com/OpenSC/OpenSC/wiki

On 6/15/2015 4:04 AM, Haoming Wang wrote:
> I am trying to establish a TLS connection using the credentials stored in a cryptographic token (Gemalto IDPrime in my case). Perhaps openssl pkcs11 engine is a possible solution. The tuto
> <http://blog.fkraiem.org/2013/03/13/linux-smart-card-authentication-openssl/> I find only permits to generate certificates using the keys stored in the token. But I have no idea if openssl pkcs11
> engine can do the TLS connection I mentioned above. Does anyone have any ideas? Thanks in advance.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/481>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by flyingmouse** [comment]
Thank you very much for your detailed reply. TLS I'm doing is two-way, both the server and the client have key and cert staff.  The ultimate goal is to authenticate the client to the server using the key and certificate stored in the smart card as if they are stored locally without the smart card.

I've installed the  IDGo 800 PKCS#11 libraries for the IDPrimeMD card and I replaced **opensc-pkcs11.so** by **/usr/lib/libidprimepkcs11.so**. It works well. I can generate a certificate request using openssl req  with the engine and an existing key on the card.

To do TLS without smartcard is very simple, I am coding in Node.js and by specifying key, cert and ca in **options** of module TLS in Nodejs can do it. I am just wondering if we could do the same thing with openssl  pkcs11 engine. Thanks to google, I found [this](http://www.gnutls.org/manual/html_node/Using-a-PKCS11-token-with-TLS.html), I am not sure if this would solve my problem. So any suggestions from your part is appreciated.

**Comment by dengert** [comment]
On 6/15/2015 7:59 AM, Haoming Wang wrote:
> Thank you very much for your detailed reply. TLS I'm doing is two-way, both the server and the client have key and cert staff. The ultimate goal is to authenticate the client to the server using the
> key and certificate stored in the smart card as if they are stored locally without the smart card.
>
> I've installed the IDGo 800 PKCS#11 libraries for the IDPrimeMD card and I replaced *opensc-pkcs11.so* by */usr/lib/libidprimepkcs11.so*. It works well. I can generate a certificate request using
> openssl req with the engine and an existing key on the card.
>
> To do TLS without smartcard is very simple, I am coding in Node.js and by specifying key, cert and ca in *options* of module TLS in Nodejs can do it. I am just wondering if we could do the same thing
> with openssl pkcs11 engine. Thanks to google, I found this <http://www.gnutls.org/manual/html_node/Using-a-PKCS11-token-with-TLS.html>, I am not sure if this would solve my problem. So any suggestions
> from your part is appreciated.

GnuTLS was written to be a replacement for OpenSSL using a GNU license. Sounds like GnuTLS has builtin PKCS#11 support,
currently OpenSSL does not and that was why OpenSC engine_pkcs11 was written many years ago.

There is some suggestions that OpenSSL should have PKCS#11 support. See the following that has some comments to that effect.

http://openssl.6102.n7.nabble.com/openssl-dev-Using-openssl-with-a-remote-private-key-tt57014.html#none

>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/481#issuecomment-112060231>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by flyingmouse** [comment]
@dengert I'd like to thank you because I followed your advice and tested openssl s_client engine option, it turned out that s_client is capable to load pkcs#11 engine and use the private key stored in smart card to do the TLS without moving it out.
