### ISSUE TITLE
OpenSC does not support PSS which is defined in PKCS#11 v2.20

### ISSUE THREAD

**Issue by NWilson** [OpenSC/OpenSC#529]
PKCS#11 describes the CKM_RSA_PKCS_PSS mechanism, which produces RSA signatures with PSS padding. The underlying smartcard functions generally do raw RSA operations, so OpenSC should in theory support PSS padding just as easily as PKCS padding.

I would use PSS signatures if they were available, and I think it would be nice to implement them, given that EMC recommends a gradual transition from PKCS#1 v1.5 padding.

**Comment by dengert** [comment]
On 8/21/2015 12:24 PM, Nicholas Wilson wrote:
> PKCS#11 describes the CKM_RSA_PKCS_PSS mechanism, which produces RSA signatures with PSS padding. The underlying smartcard functions generally do raw RSA operations, so OpenSC should in theory support
> PSS padding just as easily as PKCS padding.
>
> I would use PSS signatures if they were available, and I think it would be nice to implement them, given that EMC recommends a gradual transition from PKCS#1 v1.5 padding.

Mods are always welcome.

>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/529>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by NWilson** [comment]
That's true, I'd be willing to do it, and maybe I will if I have time (I'd have to do it at home, it would be hard to justify in work time). I've implemented PSS before for another crypto library, but that was much easier because there's no messy logic for dealing with the underlying device's capabilities.

**Comment by CardContact** [comment]
The current SmartCard-HSM 1.2 version supports PSS with internal hash and the new 2.0 release does support PSS padding internally with the hash provided externally.

I'd be very interested to review the patch.

**Comment by NWilson** [comment]
For any devices offering raw RSA as well (many or most smartcards?) the
padding can be done in software, so I'd be able to test that on a couple of
those devices. I have to say, letting the driver do the padding does seem
like a pretty dangerous feature for a card, but that's maybe just the way
it is!

**Comment by CardContact** [comment]
That's why in the next release you can disable raw RSA for a key and therefore force PSS padding inside the card. This is a requirements in most electronic signature schemes.

**Comment by NWilson** [comment]
@CardContact, do you know if any cards do onboard hashing of the entire message for signatures? Suppose you have a 1MB document you want to sign, obviously it's going to be hashed first. Are there any cards which perform that hash on the card, or are the cards happy to do the padding and signature themselves? I'm thinking here of EDCSA (and GOSTR!?!) as well as RSA.

I can easily believe that there are cards which insist on performing PKCS#1 v1.5 padding themselves, or have an onboard SHA256 implementation for doing the PSS padding, but I don't believe that anyone would make a card that insists on doing the message hashing on the card, since that would place a nasty limit on the size of the message that could be signed.

OpenSC has a bit of a mess of code that deals with hashing the signature values, and at the moment a card is able to declare that it supports "ECDSA+SHA256", but my guess is that this is bogus, and the hash is applied by the driver not the card. Or, no drivers at all use those flags!

**Comment by philipWendland** [comment]
Sadly, Java Card versions prior to 3.0.4 only supported ECDSA with SHA-1 done on the card. So some Java Card applets (without additional card-specific APIs), like the IsoApplet can only support this. I can not understand what was the reason for this limitation in Java Card.
However, 3.0.4 cards start to show up so this can be implemented in the future. (The same for PSS and OAEP padding on-card.)

For RSA I think it is unlikely that the hash is performed on the card.

Should we also look at OAEP padding as well for decryption? (See PKCS#1 v2.0 and above)

**Comment by CardContact** [comment]
Actually yes: This is used for signing small information items like certificates or OCSP responses.

Most electronic signature cards support on-card and external hashing, typically using PSO HASH to transmit either the plain value, the hash value or an intermediate value (hash last round done in the card). And because of CC certification, they do no allow raw RSA operation with the key.

I see the following variants

a) Hashing, padding, RSA operation all done in the card
b) Partial external hashing, internal hash-last-round, padding, RSA operation
c) External hashing, internal padding and RSA operation
d) External hashing, padding and internal RSA operation

But I'm happy if we start with c).

**Comment by NWilson** [comment]
OK, I've got some code up and running. It supports PSS signatures for cards that declare support in their card driver, or through software hashing if the card supports raw RSA. It's fairly complete, but I've only done some basic testing to begin with.

NWilson@42f3199e66796db6f003668e77315203d07f1038

I'm new to the OpenSC codebase, so I'm sure I'm not doing everything in the most idiomatic way, but some of the code does seem a bit confusing and inconsistent!

If anyone wants to comment, go ahead, or I could make a PR if you think it's ready.

**Comment by dengert** [comment]
On 8/25/2015 7:56 AM, Nicholas Wilson wrote:
> @CardContact <https://github.com/CardContact>, do you know if any cards do onboard hashing of the entire message for signatures? Suppose you have a 1MB document you want to sign, obviously it's going
> to be hashed first. Are there any cards which perform that hash on the card, or are the cards happy to do the padding and signature themselves? I'm thinking here of EDCSA (and GOSTR!?!) as well as RSA.

I don't know of any, but it is possible. It could be possible that the final round of a digest could be done on the card.
Also the term "card" implies a ID badge with a slow processor. PKCS#11, and support more powerful crypto devices that could do the Digest on the card.

>
> I can easily believe that there are cards which insist on performing PKCS#1 v1.5 padding themselves, or have an onboard SHA256 implementation for doing the PSS padding, but I don't believe that anyone
> would make a card that insists on doing the message hashing on the card, since that would place a nasty limit on the size of the message that could be signed.

There are cards that insist on doing the RSA padding on the card. Any card that does not support RAW RSA i.e. CKM_RSA_X_509 but does support CKM_RSA_PKCS, CKM_RSA_PKCS_OAEP or CKM_RSA_PKCS_PSS
is doing the padding on the card. (Although there are some tricks with RSA that allow a Decrypt to be used as a RAW operation. OpenSC will try and use this too, if the card does not
enforce key usage on the card.)

They could do digest on the "card" as the PKCS#11 routines for digest, signing, decrypt etc have a C_XXXInit, C_XXXUpdate C_XXXFinal that allow for multi-part operations.

PKCS#11 allows all of the above, but OpenSC tends to only implement code when there is a "card" that can support it.

>
> OpenSC has a bit of a mess of code that deals with hashing the signature values, and at the moment a card is able to declare that it supports "ECDSA+SHA256", but my guess is that this is bogus, and
> the hash is applied by the driver not the card. Or, no drivers at all use those flags!

I would call it complicated, not a mess. The card driver should be declaring what can be done on the card. OpenSC then defines PKCS#11 mechanisms that can be built on top of the what the card can do, 
and what OpenSC can do in software.

It is a common mistake for new developers to try and define in the card driver everything they expect to be able to do, even if the card and PKCS#11 don't allow it.

Even PKCS#11 2.40 still only defines CKM_ECDSA_SHA1 there are no other hashes defined for ECDSA. (DSA does have CKM_DSA_SHA* 1,224,256,384,512)

OpenSC can do hashing in software if built with OpenSSL.  A call to  C_GetMechanismInfo returns a
CK_MECHANISM_INFO and OpenSC will set CKF_HW flag if all of the operations of the mechanism are done by the card.

>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/529#issuecomment-134577150>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by dengert** [comment]
With regard to OAEP see:

https://github.com/OpenSC/OpenSC/issues/386

**Comment by dengert** [comment]
Looking at the code in framework-pkcs15.c, line 6435:
/*
 * Mechanism handling
 * FIXME: We should consult the card's algorithm list to
 * find out what operations it supports
*/
And line 4656:
/* That practise definitely conflicts with CKF_HW -- andre 2010-11- 28 */

The CKF_HW is being set for some of the padding mechanisms, even though the
padding will be done in software....

**Comment by martinpaljak** [comment]
Well, I think this is acceptable, as the important parts (private information, key material) is indeed in HW.

**Comment by martinpaljak** [comment]
I mean, more important than trying to figure out which of the ambiguous interpretations of PKCS#11 might have been considered by the authors, is to stick one holistic interpretation/view/vision and stick to it.

**Comment by dengert** [comment]
Well OpenSC has not stuck to one holistic interpretation/view/vision. 

One of the interperations would be CKF_HW is TRUE if all the operations needed for a mechanism are done on the device. PKCS#11 2.01 and 2.40 both say: "True if the mechanism is performed by the device; false if the mechanism is performed in software". 

Its ambiguous if a mechanism requires multiple opertions, part on the device and part in the software. For example the PIV that only does RSA RAW on the card pkcs11-tool -M reports among other mechanisms:

  RSA-X-509, keySize={1024,3072}, hw, decrypt, sign, verify
  RSA-PKCS, keySize={1024,3072}, hw, decrypt, sign, verify
  SHA1-RSA-PKCS, keySize={1024,3072}, sign, verify

RSA_PKCS could be  RAW RSA on card with software  or hardware  padding.   I would assume CHF_HW would be set only if both RSA and padding was in hardware. 

I would favor "True if the full mechanism is performed by the device; false if any part is done in software."

OpenSC already does not set CKF_HW for any mechanism that includes hashing.  Its the mechanisms that include padding that are inconsistent.  

An application wanting to do RSA padding and hashing, could quere for CKM_RSA_X_509, CKM_RSA_PKCS, and CKM_SHA1_RSA_PKCS, and get back TRUE, TRUE, FALSE
which would indicate RSA and PADDING are done on card, but not hashing.

If it got back TRUE, FALSE, FALSE it would indicate the padding and hashing are in software. 
But OpenSC  still return TRUE, TRUE, FALSE even if padding was in sofware. 

If  CKM_RSA_X_509 was not a valid mechanism  would indicate the card does not do RAW over the interface. If a query for CKM_RSA_PKCS returned TRUE, means the card does the padding and the RSA on the card.  (It could not return FALSE, because CKM_RSA_PKCS  can not be supported in sofware if CKM_RSA_X_509 is not supported on the card.)

The CKM_HW is minor, because the only way the application can be sure the device is trully hardware, it to use a train of trust back to a trusted CA that only only signs certificates were the key is on a hardware device.
 




But  the OpenSC response  



 








For example
CKM_RSA_X_509  is just RAW RSA. 
CKM_RSA_PKCS   is pkcs1 padding followed by RAW RSA, or RAW RSA folloed by de-padding.

**Comment by frankmorgner** [comment]
@CardContact did you find time to review NWilson@42f3199 ?

**Comment by CardContact** [comment]
Still on my list.

On 11/01/2015 09:41 PM, Frank Morgner wrote:
> @CardContact did you find time to review NWilson@42f3199 ?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/OpenSC/OpenSC/issues/529#issuecomment-152861721
> 


-- 

    ---------    CardContact Software & System Consulting
   |.##> <##.|   Andreas Schwier
   |#       #|   Schülerweg 38
   |#       #|   32429 Minden, Germany
   |'##> <##'|   Phone +49 571 56149
    ---------    http://www.cardcontact.de
                 http://www.tscons.de
                 http://www.openscdp.org
                 http://www.smartcard-hsm.com

**Comment by CardContact** [comment]
I've tried to integrate the PSS code, but it still fails in PSS verification.

There seems to be a problem in the PSS padding that creates EMs which are larger than the modulus.

@NWilson How did you test your code ?

**Comment by NWilson** [comment]
Hi, thank you very much for looking at the code. Good question, I have an application that uses PKCS#11, and it uses the PSS padding if it's available. So, to test the signing functions I just ran my application, and exercised the code and sent off the signatures to our web service which checks them; I know the web service is good because it happily checks signatures generated in the normal way using OpenSSL (rather than on a hardware token).

To be honest, I'm not sure I tested the PSS verification very thoroughly (probably a once-off run of the code as a basic sanity check). Is there anyone who actually has a need to verify signatures via PKCS#11? I would expect most applications just use OpenSSL (or whatever), since you gain nothing doing the verification on the device (and OpenSC doesn't even do that).

If the verification doesn't work, I'd be happy just to drop that entirely, I'm only really interested in signing.

**Comment by mouse07410** [comment]
> If the verification doesn't work, I'd be happy just to drop that entirely,
> I'm only really interested in signing.

Perhaps I'm being too naive - but who cares for signatures that cannot be verified?!

**Comment by dengert** [comment]
I am trying to understand your modifications in https://github.com/NWilson/OpenSC/commit/42f3199
You have made a lot of changes to SC_ALGORiTH_* flags, and its not clear what you are doiing. 
As I said above, this is a area of the code that is not well understood, and making masive changes may work for you but break other cards. You have to convince others that the base code will still work for these cards.  A good place for the explaination is in the Commit message.

I see changes to  ECDSA, ECDH and GOST flags. Have you tested the changes with these?
You have to at least point out changes that you can not test. 

Some may build OpenSS without OpenSSL. (I think you have this covered, but you should try compiling without OpenSSL even if  PSS requires OpenSSL and will thus not function.)

Please rebase your changes  to the OpenSC master.

**Comment by frankmorgner** [comment]
@CardContact and @NWilson is there any work being done on this issue?

**Comment by Jakuje** [comment]
Can we reopen this issue to continue discussion here, rather than on the commit https://github.com/NWilson/OpenSC/commit/42f3199e66796db6f003668e77315203d07f1038 ?

It looks like there was no update from @NWilson since 2015. I pulled the changes (on top of #1404), modified them to work with PIV cards and basic workflow with default values worked for me from signatures to verification. What I did not investigate yet was the PSS parameters passing, which is in this case implemented by extending the pkcs15 objects with `init_params`. If this is an acceptable solution, I can try to put the code into shape for merging and verify the functionality with the cards I have around.

The testing I used so far is documented in the wiki: https://github.com/OpenSC/OpenSC/wiki/Using-pkcs11-tool-and-OpenSSL#sha1-rsa-pkcs-pss

**Comment by NWilson** [comment]
Yes, I've just not had time to come back to this - and after 2 years I'm afraid I can't really come back it. I don't use OpenSC myself, and don't have the incentive to return to the work I started.

Please use the code if any of you would like PSS support, and if it's of any use towards that.

I'm sorry for starting something and not having the time to follow it through the test/review process.

**Comment by Jakuje** [comment]
Thank you for coming back. I will try to follow up on this, either with your patch or at least with testing, if the complete patch will not be proposed by @CardContact in #1404.
I do not want to propose conflicting pull requests so lets wait for the first one.

I already have working, but hairy version using `PKCS1_MGF1()`, rather than doing the `mgf_rounds` manually. I would rather use the whole `RSA_padding_add_PKCS1_PSS_mgf1()`, but it would involve either faking RSA key structure or pulling at least public key for the private key operation. I will have a better look during next week.
