### ISSUE TITLE
Certificate not listed at PKCS#11 interface but with pkcs15-tool -D

### ISSUE THREAD

**Issue by CardContact** [OpenSC/OpenSC#561]
For a card with EC Private Key and X.509 certificate, pkcs15-tool -D shows the certificate object:
```
c:\Program Files (x86)\OpenSC Project\OpenSC\tools>pkcs15-tool.exe -c -k
Using reader with a card: Gemplus USB SmartCard Reader 0
X.509 Certificate [f8654afe-c4c4-4680-a574-9e86228234a0]
        Object Flags   : [0x0]
        Authority      : no
        Path           : ce01
        ID             : 66383635346166652d633463342d343638302d613537342d396538363232383233346130

Private EC Key [f8654afe-c4c4-4680-a574-9e86228234a0]
        Object Flags   : [0x3], private, modifiable
        Usage          : [0xE], decrypt, sign, signRecover
        Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
        FieldLength    : 192
        Key ref        : 1 (0x1)
        Native         : yes
        Path           : e82b0601040181c31f0201::
        Auth ID        : 01
        ID             : 66383635346166652d633463342d343638302d613537342d396538363232383233346130
        MD:guid        : {15621088-310b-4657-538f-843268ec641c}
          :cmap flags  : 0x0
          :sign        : 0
          :key-exchange: 0

With pkcs11-tool the certificate is not shown:

c:\Program Files (x86)\OpenSC Project\OpenSC\tools>pkcs11-tool.exe --module opensc-pkcs11 -O --slot 1 --login

Logging in to "SmartCard-HSM (UserPIN)".

Please enter User PIN: 2015-09-22 17:44:44.103 cannot lock memory, 
sensitive data may be paged to disk

Private Key Object; EC
  label:      f8654afe-c4c4-4680-a574-9e86228234a0
  ID:         66383635346166652d633463342d343638302d613537342d396538363232383233346130
  Usage:      decrypt, sign

The log reveals, that the code has an issue with the curve, but the same code is used by pkcs15-tool.

2015-09-23 08:44:45.149 [opensc-pkcs11] pkcs15-pubkey.c:1463:sc_pkcs15_fix_ec_parameters: Unsupported named curve: -1408 (Not supported)
2015-09-23 08:44:45.149 [opensc-pkcs11] pkcs15-pubkey.c:1331:sc_pkcs15_pubkey_from_spki_fields: failed to fix EC parameters: -1408 (Not supported)
2015-09-23 08:44:45.149 decoding of ASN.1 object 'subjectPublicKeyInfo' failed: Not supported
2015-09-23 08:44:45.149 decoding of ASN.1 object 'tbsCertificate' failed: Not supported
2015-09-23 08:44:45.149 [opensc-pkcs11] pkcs15-cert.c:109:parse_x509_cert: ASN.1 parsing of certificate failed: -1408 (Not supported)
2015-09-23 08:44:45.149 [opensc-pkcs11] pkcs15-cert.c:198:sc_pkcs15_read_certificate: returning with: -1401 (Invalid ASN.1 object)
2015-09-23 08:44:45.149 Found 0 data objects
2015-09-23 08:44:45.149 Looking for objects related to object 0
2015-09-23 08:44:45.149 Object is a private key and has id 66383635346166652d633463342d343638302d613537342d396538363232383233346130
2015-09-23 08:44:45.149 found 1 FW objects
2015-09-23 08:44:45.149 Found 1 FW objects objects
2015-09-23 08:44:45.149 Found 2 authentication objects
2015-09-23 08:44:45.149 Found authentication object 'UserPIN'
2015-09-23 08:44:45.149 Create slot (p11card 00A0B608, fw_data 00A17A68, auth 00A17FB0, app_info 00000000)
2015-09-23 08:44:45.149 Allocated slot 0x1 for card in reader Gemplus USB SmartCard Reader 0
2015-09-23 08:44:45.149 Initialized token 'SmartCard-HSM (UserPIN)' in slot 0x1
2015-09-23 08:44:45.149 Add objects related to PIN('UserPIN',ID:01)
2015-09-23 08:44:45.149 ObjID(00A137A8,f8654afe-c4c4-4680-a574-9e86228234a0,104):01
2015-09-23 08:44:45.149 Slot:00A16540, obj:00A137A8  Adding private key 0 to PIN 'UserPIN'
2015-09-23 08:44:45.149 Slot:1 Setting object handle of 0x0 to 0xa137a8
2015-09-23 08:44:45.149 Set first slot: 00A16540
2015-09-23 08:44:45.149 Add public objects to slot 00A16540
2015-09-23 08:44:45.149 1 public objects to process
2015-09-23 08:44:45.149 All tokens created
```
The code worked in 0.14, so the bug was introduced on the way to 0.15

**Comment by dengert** [comment]
Using a build from yesterday, I don't see a problem using a PIV card with EC keys. Can you show more of the log or the certificate?
What is the curveName?

**Comment by dengert** [comment]
See if this may have caused a problem. It is from April:

https://github.com/OpenSC/OpenSC/commit/ee23d286547d730dc82011857b318186140b31f5

Is the curve size a multiple of 8 bits?

**Comment by jariq** [comment]
Further investigation revealed that problem is caused by the SubjectPublicKeyInfo part of certificate. When SubjectPublicKeyInfo refers to curve by its OID then everything works as expected. Dump of such structure follows:

<pre>$ openssl asn1parse -inform DER -in spki1.der -dump
    0:d=0  hl=2 l=  73 cons: SEQUENCE
    2:d=1  hl=2 l=  19 cons: SEQUENCE
    4:d=2  hl=2 l=   7 prim: OBJECT            :id-ecPublicKey
   13:d=2  hl=2 l=   8 prim: OBJECT            :prime192v1
   23:d=1  hl=2 l=  50 prim: BIT STRING
      0000 - 00 04 39 6c b2 df ab d5-d6 26 83 77 0e b5 63 25   ..9l.....&.w..c%
      0010 - 12 6b 5d ac 74 7b 38 bf-ca ee 0a f1 dc cc f6 b3   .k].t{8.........
      0020 - 3c 3e 99 43 2e bc bb 00-e7 c9 f8 a6 b4 48 68 57   <>.C.........HhW
      0030 - dd 11                                             ..</pre>

Example of full certificate:

<pre>-----BEGIN CERTIFICATE-----
MIICAjCB66ADAgECAgECMA0GCSqGSIb3DQEBCwUAMBExDzANBgNVBAMTBlRFU1RD
QTAeFw0xNTA5MjMwMDAwMDBaFw0yNTA5MjIyMzU5NTlaMBYxFDASBgNVBAMMC1RF
U1RDTElFTlQxMEkwEwYHKoZIzj0CAQYIKoZIzj0DAQEDMgAEOWyy36vV1iaDdw61
YyUSa12sdHs4v8ruCvHczPazPD6ZQy68uwDnyfimtEhoV90RozwwOjAMBgNVHRMB
Af8EAjAAMB0GA1UdDgQWBBS41tFHE1l5S4Hwmrz9pnBbpG6LyDALBgNVHQ8EBAMC
B4AwDQYJKoZIhvcNAQELBQADggEBANxp8UvPhO8e1PcD1IZFSEs+Y+No4oGLfQrC
e+q9YS8BZRsX9HGcY9voOFSE+7vktGHTT5JGmvDMswVosYx8+UsY+t09ETnFDZca
9TsFsTD9N8Oa+NatQcFnnuT8bsUVLjBWybO4Y2pAC3iJ5n9cxQgNJSH7lZVeAqmd
kwIl+dZWWTgRxX228y23jY6kiCWkc4NWW0ORk3O+UA5/FXzFRTeGqQGMcZRRRhL3
44cLjVHeK2NY6gmhw4DX2DqrYGujo9uen9KFACLCU7xlAVw54Ghlyn/DRab51mKP
n/tYmqiTZneOj+ZUO1T/u7b3auWvF/yrjbG3OHv07vvNpEYXjq0=
-----END CERTIFICATE-----</pre>

However when SubjectPublicKeyInfo refers to curve using its explicit domain parameters then failure discussed in this issue occurs. Dump of such structure follows:

<pre>$ openssl asn1parse -inform DER -in spki2.der -dump
    0:d=0  hl=3 l= 242 cons: SEQUENCE
    3:d=1  hl=3 l= 187 cons: SEQUENCE
    6:d=2  hl=2 l=   7 prim: OBJECT            :id-ecPublicKey
   15:d=2  hl=3 l= 175 cons: SEQUENCE
   18:d=3  hl=2 l=   1 prim: INTEGER           :01
   21:d=3  hl=2 l=  36 cons: SEQUENCE
   23:d=4  hl=2 l=   7 prim: OBJECT            :prime-field
   32:d=4  hl=2 l=  25 prim: INTEGER           :FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFF
   59:d=3  hl=2 l=  75 cons: SEQUENCE
   61:d=4  hl=2 l=  24 prim: OCTET STRING
      0000 - ff ff ff ff ff ff ff ff-ff ff ff ff ff ff ff fe   ................
      0010 - ff ff ff ff ff ff ff fc-                          ........
   87:d=4  hl=2 l=  24 prim: OCTET STRING
      0000 - 64 21 05 19 e5 9c 80 e7-0f a7 e9 ab 72 24 30 49   d!..........r$0I
      0010 - fe b8 de ec c1 46 b9 b1-                          .....F..
  113:d=4  hl=2 l=  21 prim: BIT STRING
      0000 - 00 30 45 ae 6f c8 42 2f-64 ed 57 95 28 d3 81 20   .0E.o.B/d.W.(..
      0010 - ea e1 21 96 d5                                    ..!..
  136:d=3  hl=2 l=  25 prim: OCTET STRING
      0000 - 03 18 8d a8 0e b0 30 90-f6 7c bf 20 eb 43 a1 88   ......0..|. .C..
      0010 - 00 f4 ff 0a fd 82 ff 10-12                        .........
  163:d=3  hl=2 l=  25 prim: INTEGER           :FFFFFFFFFFFFFFFFFFFFFFFF99DEF836146BC9B1B4D22831
  190:d=3  hl=2 l=   1 prim: INTEGER           :01
  193:d=1  hl=2 l=  50 prim: BIT STRING
      0000 - 00 04 57 f0 55 84 7a 1d-64 56 bf 37 34 43 30 74   ..W.U.z.dV.74C0t
      0010 - df 54 b2 79 88 1b 03 23-be 17 78 0a 70 6f d0 c9   .T.y...#..x.po..
      0020 - cc 84 68 22 70 08 71 4a-12 32 d2 a3 2d fe a4 13   ..h"p.qJ.2..-...
      0030 - 4d 40                                             M@</pre>

Example of full certificate:

<pre>-----BEGIN CERTIFICATE-----
MIICqjCCAZKgAwIBAgIBAzANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDDAZURVNUQ0EwHhcNMTUw
OTI0MDkxMzIwWhcNMTYwOTI0MDkxMzIwWjAWMRQwEgYDVQQDDAtURVNUQ0xJRU5UMjCB8jCBuwYH
KoZIzj0CATCBrwIBATAkBgcqhkjOPQEBAhkA/////////////////////v//////////MEsEGP//
//////////////////7//////////AQYZCEFGeWcgOcPp+mrciQwSf643uzBRrmxAxUAMEWub8hC
L2TtV5Uo04Eg6uEhltUEGQMYjagOsDCQ9ny/IOtDoYgA9P8K/YL/EBICGQD///////////////+Z
3vg2FGvJsbTSKDECAQEDMgAEV/BVhHodZFa/NzRDMHTfVLJ5iBsDI74XeApwb9DJzIRoInAIcUoS
MtKjLf6kE01AozkwNzAJBgNVHRMEAjAAMB0GA1UdDgQWBBTyq1kF6jtZrYR2u0zZyDX/tVcT/jAL
BgNVHQ8EBAMCB4AwDQYJKoZIhvcNAQELBQADggEBADwMOKKcmonRd09yZr6cRJDq8ngcjeioymIO
7dV5Wdxy34gfjhKBLNb+R/HTuGTdSkOopd+2Q8wCY1fQ6zo3gSYoaDA426TdT+iCO3ozqTxuI4I0
/BjnX+LD1lr6NnK85Q0ZXmIU0aTys1AtHE09Zs9cNnYtb3ZtN7sKBELjdZzxnGTl8XZAEALmATRQ
nruDfx+XA8qc+7perCPvgqychdSbmEM/gn5DarC9zCtIeg4qMph4WYE+qY8RP+6Mab/01tw+Z62j
JwjH5Cx2oLXg52/StF2ckhnws0BxPnVDnsXFsF3/HZQWN5K5LNaWApMlXkWw99QOnbHXtqcRHbVb
moM=
-----END CERTIFICATE-----</pre>

Both certificates refer to secp192r1 curve (1.2.840.10045.3.1.1) but it seems that certificate parsing code used in OpenSC PKCS#11 library works only when curve is referenced by its OID. Question is whether it should also support/recognize known curves referenced by their explicit domain parameters.

**Comment by dengert** [comment]
See:
https://tools.ietf.org/html/rfc5480

2.1.1.  Unrestricted Algorithm Identifier and Parameters
o specifiedCurve, which is of type SpecifiedECDomain type (defined
        in [X9.62]), allows all of the elliptic curve domain parameters
        to be explicitly specified.  This choice MUST NOT be used.  See
        Section 5, "ASN.1 Considerations".

It looks like over the years, in an attempt to simplify EC and for interoperability issues, only named cureves are allowed these days in certificates.

If you feel that any curve, or at least known curves be support, code could be added.
See pkcs15-pubkey.c line 1461 /* TODO: support of explicit EC parameters form */

An example of adding new curves (brainpool curves)  is:
https://tools.ietf.org/html/rfc7027
This referencs 5480.

**Comment by frankmorgner** [comment]
I think parsing the parsing of the SubjectPublicKeyInfo is located in `sc_pkcs15_pubkey_from_spki_fields` of `pkcs15-pubkey.c`. Could you, @jariq @CardContact, have a look at this?

**Comment by frankmorgner** [comment]
I think `sc_pkcs15_fix_ec_parameters`, as suggested by @dengert, is only relevant for encoding, not for decoding. But having a look here, too, doesn't hurt...

**Comment by dengert** [comment]
sc_pkcs15_pubkey_from_spki_fields   does the parse, but does not parse the ASN.1 for the ec parameters. It passes the der encoded to parameters sc_pkcs15_fix_ec_parameters:

1328                         memcpy(pubkey->u.ec.params.der.value, ecp->der.value, ecp->der.len);
1329                         pubkey->u.ec.params.der.len = ecp->der.len;
1330                         r = sc_pkcs15_fix_ec_parameters(ctx, &pubkey->u.ec.params);
1331                         LOG_TEST_RET(ctx, r, "failed to fix EC parameters");

The named curves are OID, the explicit curve is a sequence. As stated above:

See pkcs15-pubkey.c line 1461 /* TODO: support of explicit EC parameters form */
It could also just accept that there are explicit parameteres without parsing them

Additional ASN.1 parse code could be added to  sc_pkcs15_pubkey_from_spki_fields  to decode the the CHOICE of namedCurve or explicit parameters.  sc_pkcs15_pubkey_from_spki_fields  lines 1316-1319  is expecting sc_pkcs15_fix_ec_parameters to set the field_length.

**Comment by frankmorgner** [comment]
If someone is willing to fix this, please re-open or make a pull request
