### ISSUE TITLE
Add support for public key authentication and n-of-m threshold scheme

### ISSUE THREAD

**Issue by CardContact** [OpenSC/OpenSC#594]
The newly released 2.0 version of the SmartCard-HSM (named "EA+" for extended authentication) supports public key authentication with a n-of-m threshold scheme.

The mechanism allows shared control over keys on a SmartCard-HSM, which is in particular useful for CA, sensitive SSH or code signing keys. It replaces the user PIN with a public key authentication scheme using ECDSA and a challenge-response protocol. The threshold scheme is defined during initialization and defines the total number of authentication keys and the quota required for a successful authentication.

As PKCS#11 does not support such an authentication mechanism directly, I would like to start a discussion how an integration with OpenSC could be accomplished.

**Comment by dengert** [comment]
On 10/29/2015 8:33 AM, CardContact Software & System Consulting wrote:
> The newly released 2.0 version of the SmartCard-HSM (named "EA+" for extended authentication) supports public key authentication with a n-of-m threshold scheme.
>
> The mechanism allows shared control over keys on a SmartCard-HSM, which is in particular useful for CA, sensitive SSH or code signing keys. It replaces the user PIN with a public key authentication
> scheme using ECDSA and a challenge-response protocol. The threshold scheme is defined during initialization and defines the total number of authentication keys and the quota required for a successful
> authentication.
>
> As PKCS#11 does not support such an authentication mechanism directly, I would like to start a discussion how an integration with OpenSC could be accomplished.

PKCS#11 does support CKF_PROTECTED_AUTHENTICATION_PATH flag in CK_TOKEN_INFO which could be used to indicate that this feature might be supported.
and C_Login with a NULL password indicates to use some other authentication path. This is usually taken to be a pin pad reader.

PKCS#11 allows for *_VENDOR_DEFINED Objcts, Hardware Features, Certificate, Attributes, Mechanisms, Return values:
CKO_VENDOR_DEFINED, CKH_VENDOR_DEFINED, CHC_VENDOR_DEFINED, CKA_VENDOR_DEFINED,  CKM_VENDOR_DEFINED, CKR_VENDOR_DEFINED.
Netscape and now  NSS has used some of these mostly for indicating trust.

One way would be to define a vendor_defined object or vendor_defined mechanisum. to pass out and in parameters needed to the authentication.

Then to do the the ECDSA, C_Sign pointing at a special ECDSA key or keys one for each party.




(In any case VENDOR_DEFINED values should all start with 2 bytes that would not conflict with some
other vendors use of these. (OpenSC does use
  #define CKA_OPENSC_NON_REPUDIATION      (CKA_VENDOR_DEFINED | 1UL)
which is 0x8000000001, which could cause conflicts Starting with something like 0x80EA would be fairly unique.






>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/594>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by CardContact** [comment]
CKF_PROTECTED_AUTHENTICATION_PATH is what I had in mind as well.

I guess the problem to solve is how to plug public key authentication into C_Login.

One way I could think of is to implement a RAMoverHTTP client that would allow an external component to perform the authentication steps. That way the pkcs#11 module in C_Login would connect to an authentication server and hand-over APDU access to the device. On the server the necessary authentication steps could be performed by key custodians logged into the server. Once authentication completes, the server terminates the connection and the module returns from C_Login.

**Comment by dengert** [comment]
On 10/29/2015 1:23 PM, CardContact Software & System Consulting wrote:
> CKF_PROTECTED_AUTHENTICATION_PATH is what I had in mind as well.
>
> I guess the problem to solve is how to plug public key authentication into C_Login.
>
> One way I could think of is to implement a RAMoverHTTP client that would allow an external component to perform the authentication steps. That way the pkcs#11 module in C_Login would connect to an
> authentication server and hand-over APDU access to the device. On the server the necessary authentication steps could be performed by key custodians logged into the server. Once authentication
> completes, the server terminates the connection and the module returns from C_Login.

This is an N-of-M authentication. Does the card know the public keys of the M possible keys?
Does it then generate M challenges one for each of the M keys?


Application asks for attributes for a N-of-M vendor defined object, that returns the value of N, M and M challenges
possibly along with the M public keys as attributes Or query the token for one attribute that has all this.
This causes card to expect the responses.

Application then uses other means (Maybe pkcs11 to access N cards) to have each of the challenges signed.
Once application has N of the M challenges signed, it uses PKCS#11 calls to create another vendor-defined object,
with attributes for each of the N challenges. This is stored in PKCS#11 application (or on card).

When C_Login is then called without PIN, the above data is then presented to card, or card is told to verify the
signed challanges and card returns 9000 if it has worked.

So all the authentication is done over one PKCS#11 session.

Another way:

Define one vendor define attribute for the token.
If card does not support this it returns CKR_ATTRIBUTE_TYPE_INVALID.
If it does it returns a structure with all N, M and M challenges.
This also signals PKCS#11 implementation that next C_Login with NULL pin is not for a pinPAD reader,
but for the N of M authentication.

A call to C_Login with NULL PIN starts the process.
This also signals PKCS#11 implementation that this type of login has started.

Application then gets N of the M challenges signed, and presents
each response using C_Login with userType set to CKU_CONTEXT_SPECIFIC and the signed
challenge as the pin. (the PIN should be character, so may need to be base64)


Only after N calls to  C_Logins with userType set to CKU_CONTEXT_SPECIFIC is the
PKCS#11 session considered R/W. and complete.





>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/594#issuecomment-152274472>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by CardContact** [comment]
> This is an N-of-M authentication. Does the card know the public keys of the M possible keys?
> Does it then generate M challenges one for each of the M keys?
Yes, M public keys are registered during device initialization. This is
done outside of PKCS#11. A challenge is generated for each of the N
authentication keys.

I guess the individual authentication steps could be implemented using
C_GenerateRandom() to get the challenge and C_Login() with a structure
containing the key identifier and the signed challenge encoded in
Base64. The n-of-m state information (M, N and number of currently
authenticated keys) could be made available in a vendor defined object.

However this approach requires a modification of the application to
perform n-of-m. With CKF_PROTECTED_AUTHENTICATION_PATH changes are
higher that an application will work without modification, if the
authentication part is taken out of the equation.

Maybe we need both.

**Comment by dengert** [comment]
On 10/30/2015 4:09 AM, CardContact Software & System Consulting wrote:
>  > This is an N-of-M authentication. Does the card know the public keys of the M possible keys?
>  > Does it then generate M challenges one for each of the M keys?
> Yes, M public keys are registered during device initialization. This is
> done outside of PKCS#11. A challenge is generated for each of the N
> authentication keys.
>
> I guess the individual authentication steps could be implemented using
> C_GenerateRandom() to get the challenge and C_Login() with a structure
> containing the key identifier and the signed challenge encoded in
> Base64. The n-of-m state information (M, N and number of currently
> authenticated keys) could be made available in a vendor defined object.
>
> However this approach requires a modification of the application to
> perform n-of-m. With CKF_PROTECTED_AUTHENTICATION_PATH changes are
> higher that an application will work without modification, if the
> authentication part is taken out of the equation.
>
> Maybe we need both.

OK, I can see how it could be very important to not change the application.


Has anyone implemented PKI authentication for C_Login? i.e. a 1 of 1 version?
If they have, could the same approach be used, but require N of M calls.

>

An example of a vendor using the  VENDOR_DEFINED features:
https://wiki.ca.com/display/AA80/PKCS+11+Module

Something similar that required multiple PINs was deprecated:
http://www.cryptsoft.com/pkcs11doc/STANDARD/pkcs-11v2-11r1.pdf

   6.7 Secondary authentication (Deprecated)
   6.7.4 Secondary authentication PIN collection mechanisms
In 2.20 This was replaced with CKU_CONTEXT_SPECIFIC



>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/594#issuecomment-152465912>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by CardContact** [comment]
A [blog post](http://www.smartcard-hsm.com/2015/10/10/Shared_Control_over_Key_Usage.html) explains the motivation and gives more background information.

**Comment by dengert** [comment]
Cool. The presentation show it nicely.

On 10/30/2015 9:23 AM, CardContact Software & System Consulting wrote:
> A blog post <http://www.smartcard-hsm.com/2015/10/10/Shared_Control_over_Key_Usage.html> explains the motivation and gives more background information.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/594#issuecomment-152539596>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by CardContact** [comment]
Addressed in #1711

**Comment by Viajaz** [comment]
#2301

**Comment by CardContact** [comment]
We now have added [Public Key Authentication via PKCS#11](https://www.smartcard-hsm.com/2026/08/24/pka-with-pkcs11.html) in the native SmartCard-HSM PKCS#11 provider.

If there is demand, we could port that to OpenSC as well, even though this is a very SmartCard-HSM specific mechanism.

**Comment by Viajaz** [comment]
For what it's worth, I'm still very interested.

SmartCard-HSM is unique in its price category in supporting this combination of mechanisms, making it particularly well suited to various organisational and compliance models where trust needs to be distributed across multiple people rather than held by a single custodian.

Broader OpenSC support would make this capability easier to integrate into existing workflows, and would help more organisations apply separation of duties, dual control, key ceremonies, and other multi-party trust models without requiring enterprise-class HSM infrastructure or significant developer support.

I still have a stack of these devices I'd love to use for such projects.

**Comment by lrascao** [comment]
Adding a demand signal, since #3246 suggested minimal demand was the deciding factor.

**Use case:** offline root CA for a private PKI. The root stays disconnected and
comes out every few years to sign intermediates. n-of-m public key authentication
is precisely the control I'd want around that ceremony — but it has to work from a
scriptable command line, air-gapped, with no network service in the authentication
path.

**What already works through OpenSC:** initialization. Tested against a Pico HSM
(a SmartCard-HSM 6.4-compatible reimplementation — flagging that explicitly in case
it's relevant):

    $ sc-hsm-tool --initialize --so-pin <...> --pin <...> -K 5 -n 3
    $ sc-hsm-tool --public-key-auth-status
    Number of public keys:     5
    Missing public keys:       5
    Required pubkeys for auth: 3
    Authenticated public keys: 0

The card enforces the scheme correctly: with 0 of 3 authenticated, `C_GenerateKeyPair`
returns `CKR_USER_NOT_LOGGED_IN` even after a successful `C_Login`, and the user PIN
retry counter stays at 3 — so the PIN is accepted and the quorum is genuinely what
blocks key access. The only missing piece on this path is the client-side
challenge-response.

**A question worth settling before any porting effort:** does the new PKCS#11 PKA
implementation support a purely local configuration — custodian cards on the same
host, no `PKCS11_LOGIN_URL` / RAMOverHTTP to a remote service? If authentication
necessarily routes through a trust-center or management-server instance, it won't
serve an air-gapped root regardless of which library implements it.

Happy to test a port against Pico HSM hardware if that's useful.

**Comment by saper** [comment]
@lrascao I have prepared a scripted setup for my customers  doing this kind of offline ceremony. 

The main reasons:

* I want to keep a single session to the HSM while doing all this
* https://github.com/OpenSC/OpenSC/issues/2432
* Our case is more involved, for example we are wrapping and unwrapping keys from another HSM environment

This was all done in the Rhino JavaScript as provided by the smartcard shell with some additional Java class to convert RSA private key formats.

sc-hsm-tool would need to get some kind of batch interface, similar to what [Mozilla Network Security Services (NSS) `certutil -B` option is doing](https://www.devdoc.net/web/developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Reference/NSS_tools_%3A_certutil.html)

We got a much nicer UI on top for the ceremony participants to enter their shares instead :)

**Comment by lrascao** [comment]
@saper — that matches what I ended up measuring, and #2432 is the root cause;
you'd identified it years before I ran into it. On a SmartCard-HSM-compatible
card I can see the applet SELECT clear `isUserAuthenticated`, the pending
challenge, and the selected public key all at once, so any design where
authentication and use are separate invocations is dead on arrival regardless
of who implements it. Your batch-interface suggestion is the only shape left,
and it matches what @frankmorgner and @istr concluded on that issue.

For what it's worth the protocol side is settled. Driving it directly over
PC/SC, the exchange is:

```
MSE SET           00 22 81 A4  Lc | 83 <len> <CHR>
GET CHALLENGE     00 84 00 00  <Le>          also zeroes puk_status
EXTERNAL AUTH     00 82 00 00  Lc | <r||s>   raw, not DER
signed data       SHA-256( dev_name || challenge )
```

with `dev_name` the CHR of EF.C_DevAut. One challenge, then one MSE +
EXTERNAL AUTHENTICATE per custodian, all on one connection. I have this
working against a 3-of-5 scheme, so whatever a port targets, the wire protocol
is not the uncertain part — only where the code lives.

Two firmware bugs turned up on the way, which is probably why nobody had
exercised this path: EC domain parameters were resolved by walking to a
self-signed CVC, which fails for every key OpenSC generates because
`pkcs15init` stamps a fixed `UTCA00001` CAR that no certificate matches; and
`HSM_OPT_COMBINED_AUTH` (bit 0x10, what `--require-pka-and-pin` sets) was
stored and reported back as enforced while nothing enforced it. Both are fixed
and measured; neither is an OpenSC issue.

@CardContact — the question from my earlier comment is still open, and it
decides whether a port would help this use case at all: does the PKCS#11 PKA
implementation support a purely local configuration, custodian cards on the
same host, with no `PKCS11_LOGIN_URL` / RAMOverHTTP to a remote service? For an
air-gapped root CA a network hop in the authentication path is disqualifying
regardless of which library performs it.

**Comment by saper** [comment]
Great write up! There is one thing I don't fully follow:

> EC domain parameters were resolved by walking to a self-signed CVC, which fails for every key OpenSC generates because pkcs15init stamps a fixed UTCA00001 CAR that no certificate matches

Probably related to changes https://github.com/OpenSC/OpenSC/pull/3786 but I am not sure!

> HSM_OPT_COMBINED_AUTH (bit 0x10, what --require-pka-and-pin sets) 

What does it do? Makes schsm to requires PKA only? PIN only?

**Comment by CardContact** [comment]
Yes, it does. Public Key Authentication is a session based authentication mechanism in the SmartCard-HSM. A session starts with the SELECT(AID) APDU and is active until you power-down the chip, do a reset or issue a SELECT(AID) APDU.

That is why this can never work with command line tools, as each tool opens a new session. It can only work, if you keep the session open.

PKCS#11 does not provide a mechanism that could implement PKA. Consequently PKCS#11 aware applications done have support for this. The only mechanism in PKCS#11 is CKF_PROTECTED_AUTHENTICATION_PATH, which basically tells the PKCS#11 aware application not to prompt the user for a PIN entry, but call C_Login() without arguments. It is then left to the PKCS#11 module to perform authentication. It could, for example, then prompt for PIN entry on a PIN-PAD reader or - in our case - connect to an authentication service in order to perform PKA.

You could of course hack into the communication between a PKCS#11 module and the SmartCard-HSM with a shared PCSC connection. The first application opens the session and a separate application share the PCSC session to perform PKA.

But that is really a hack and will probably not work reliably in any case (We see PCSC sharing as a major problem when we use secure messaging between the SmartCard-HSM and the PKI-as-a-Service Portal. There are often other middleware components (like GPG) that open shared PCSC connections to the device and break the secure messaging channel).

BTW. the [SmartCard-HSM Cloud Service](https://github.com/CardContact/sc-hsm-cloud-service) can of course be deployed locally. No need to put that somewhere in the cloud, a simple Docker container would be sufficient.

What others are using is a key management script for the Smart Card Shell that interfaces with the Key Manager. You use the Key Manager to access the SmartCard-HSM, perform PKA and run a script to perform PKI operations. You could also write your own Key Manager plug-in to add functionality.

**Comment by lrascao** [comment]
@CardContact — thank you, that answers it. A locally deployed container is a
very different proposition from a hosted service, and it means the remote-login
path isn't disqualified for an offline root after all. Noted also on shared
PCSC connections; what I have does everything on one connection in one process
precisely to avoid that.

@saper — on the first point, it isn't #3786. `UTCA00001` goes back to 72786abe.
What changed the picture is f9cd1fc4:

```c
-	strcpy(cvc.car, "UTCA00001");
-	strcpy(cvc.chr, "UTTM00001");
+	strlcpy(cvc.car, "UTCA00001", sizeof cvc.car);
 	if (priv->serialno)
 		strlcpy(cvc.chr, priv->serialno, sizeof cvc.chr);
```

Both CAR and CHR used to be placeholders. The CHR now carries the real device
serial while the CAR stays fictional, so a generated key names an issuer no
certificate matches. TR-03110 resolves EC domain parameters by walking until
CAR == CHR, so that walk cannot terminate.

I originally patched the firmware to read a certificate's own parameters
instead; polhenarejos pushed back that the walk is what the spec prescribes and
the real bug is the unresolvable CAR, and he's right -- I closed that PR. The
same certificate with CAR rewritten to equal its CHR authenticates on
*unmodified* firmware, which is the evidence for his reading rather than mine.

Whether the fix here is to derive the CAR from the same serial, or to omit the
tag and let the card fall back to its own device name, I don't know well enough
to say -- the card does the latter when no CAR is supplied. I'll open something
separately rather than derail this thread.

On your second question: per #3786 the default is "PIN or PKA", and
`--require-pka-and-pin` sets bit 0x10 to demand both. On the implementation I
tested, that bit was stored and reported back as enforced while nothing acted
on it -- access was granted on the quorum alone, with no PIN. That's fixed and
merged there. Worth adding that the same implementation also treats the default
as PKA-only rather than "PIN or PKA": with a scheme configured and no keys yet
registered, a correct PIN leaves C_GenerateKeyPair returning
CKR_USER_NOT_LOGGED_IN with the retry counter untouched. Both are third-party
deviations, not OpenSC's.
