### ISSUE TITLE
Commit 5ed3df90248146f4cc5b46809bd3169acf21633d breakes signing...

### ISSUE THREAD

**Issue by llogar** [OpenSC/OpenSC#631]
Hi, at least on smartcard-hsm the above mentioned commit breakes signing:

`$ pkcs11-tool  --module /usr/lib/pkcs11/opensc-pkcs11.so --sign --input-file test.bin`
`Using slot 1 with a present token (0x1)`
`Logging in to "test (UserPIN)"`
`Please enter User PIN: *****`
`Using signature algorithm ECDSA`
`error: PKCS11 function C_SignFinal failed: rv = CKR_USER_NOT_LOGGED_IN (0x101)`

Kind regards
Luka

**Comment by CardContact** [comment]
I can confirm the bug. It's apparently caused by a re-select of the applet, which clears the authentication state. This will probably affect other cards as well.

@frankmorgner Why is the new select required ?

I'd recommend to revert the patch for further investigation on the cause.

**Comment by dengert** [comment]
It appears that some cards react differently to a select AID, then others. 
Sounds like if the HSM is reselected it loese the login state. 
The PIV can be reselected, the state does not change. The selection of a different AID 
of a valid appliet on the PIV card, will cause the PIV applet to loose its login state. (i.e. CAC cards or OpenPG on a NEO.)

The root of all the discussion of atomic operations or check_state  is that PCSC 
can only notify an application if the card is removed, or the card is reset. It does not
return that some other prcess may accessed the card and reset the AID, or changed the SM 
session, did  an unverify or changed files on the card. 

This is further complicated by user_conset restrictions a card my enforce.

I contend that much of the logic to detect the sitution (and possible revovery) needs to be done at the card driver level, with assistance from sc_* and sc_pkcs15_* functions. 

#624 is a start at adding the check_state.

But to further assist it, I would propose 4 lock count variables be added to the sc_card structure.
They would be incremented when sc_lock, sc_unlock, card->reader->ops->lock(card->reader)
and card->reader->ops->unlock(card->reader) were called. 

A card driver could then save in its own private data, the values of these variables, and when the card driver is next called, gain it could see if the card is still in the same state. in particular if the PCSC lock 
has not been releases and reestablished between calls. As long as the PCSC lock is exclusive
and has not been released and reestablished, the card has not been aceesed by some other process
and the card state should not have been changed. 



  











When to do a select of the applet, needs to be controlled by the card driver.

**Comment by frankmorgner** [comment]
I assumed I only refactored what was already present (e.g. selecting the key's aid). @CardContact could you point out the code that *re-selects* the Applet?

**Comment by CardContact** [comment]
The issue seems to be, that select_key_file() is called after PIN validation. As the path contains the AID, the applet is re-selected and clears the authentication state.

This is related to the changes introduced in #563, which had to be done to support de-authentication in minidriver (minidriver resets the card to de-authenticate and as such the applet needs to be selected after reset and before the PIN is verified).

I also don't like automatic PIN caching, as it leaves the PIN somewhere in memory. I support Dougs proposal to handle the card state at the card driver layer. If a card wants to support PIN caching, it should do it there. If it detects a broken SM channel it should re-establish it there. If it detects a deselected applet it should select it there.

And we should develop a clear understanding of what a PKCS#11 session is and what this means for the PKCS#15 layer. The minidriver approach to de-authentication is a good example that our understanding of a session (e.g. sc_pkcs15_bind() to sc_pkcs15_unbind()) is not accurate.

**Comment by CardContact** [comment]
@frankmorgner What is causing the problem is that the sequence of sc_select_key_file(), sc_pkcs15_pincache_revalidate() and sc_compute_signature() has changed. sc_select_key_file() is now done after sc_pkcs15_pincache_revalidate() which resets the just archives authentication state.

But as written before, the problem is much more general and relates to our common understanding of what a session in OpenSC is supposed to be.

**Comment by frankmorgner** [comment]
Please compare https://github.com/OpenSC/OpenSC/blob/33841136168f1c2fd9787e205c8b5b3e4c3c4fc5/src/libopensc/pkcs15-sec.c#L482-L488 (before 5ed3df90248146f4cc5b46809bd3169acf21633d) with https://github.com/OpenSC/OpenSC/blob/5ed3df90248146f4cc5b46809bd3169acf21633d/src/libopensc/pkcs15-sec.c#L500-L505, it is identical. The AID is and always has been selected before a signature operation (if the AID was encoded in the PKCS#15 structure). I don't see the *additional* select...

Yes, we could do a lot of refactoring, improving a lot of code, talk a lot how things should work. But very few are actively developing OpenSC. And even fewer people (none?) are working on making structural improvements. I've done my best to at least fix most of the critical errors reported by Coverity https://scan.coverity.com/projects/4026. And even those security fixes have been regarded very critically. So please do not use the wording *we should ...*, instead *go ahead* and propose changes, write documentation, build up test cases and so on!

**Comment by frankmorgner** [comment]
I think I now understand the issue with SC HSM. The problem is that DNIe requires the re-validation of the PIN to be *before* `select_key_file()`, see https://github.com/OpenSC/OpenSC/issues/596#issuecomment-152719169.

I have to re-read ISO-7816-15, but to be honest, I think the currently implemented logic is correct. My understanding of the standard is that it's a global picture of the card. Instead, OpenSC sc-hsm driver only has a local picture. That's why sc-hsm should translate between the global picture (OpenSC's PKCS#15 framework) and the card driver's local view. I'd rather like to see SC-HSM strip the SC-HSM aid from incoming select commands, because the card driver *always* expects the SC-HSM applet to be selected.

One solution would be to not use the while loop but to instead re-validate the PIN if needed per function. An other (great structural) improvement that would solve the problem, would be to use file path caching in sc-hsm as done here https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-starcos.c#L646-L658

**Comment by frankmorgner** [comment]
File caching is also identically used in some other card drivers.

**Comment by frankmorgner** [comment]
Another solution would be to drop the path specification of the private key in sc-hsm. Since the key is always in the local applet specifying this AID doesn't even make sense because this leaves the local context.

**Comment by CardContact** [comment]
The path specification for the private key was introduced to allow de-authentication in minidriver. I could easily remove that, but then minidriver de-authentication fails, because the applet is not automatically selected after card reset.

That's my point, with the session: minidriver has a different view on sessions as it does not call sc_pkcs15_bind after the card has been reset. Instead the code assumes that after a reset the PIN verification makes sure the card is in the proper state again. That would be OK, if the card had a chance to figure out what happened.

Maybe it is as simple as adding a call to pkcs15_logout() in minidriver/Deauthenticate() ?

@vletoux: Would that be a better alternative to 6aaf9d4 ? This way Windows would not just reset the card to de-authenticate, but would call the logout() method in the card driver that could either use it's own de-authenticate or force a card reset. Any applet selection context would be untouched in that case.

**Comment by vletoux** [comment]
yes, while developping the GIDS card, I discovered the logout function defined here:
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/opensc.h#L551

**The sc-hsm card doesn't implement it now,** but it can be easily be fixed by adding this function & inside, selecting the applet (again).
then call sc_logout from the minidriver and if not successful, trigger a reset of the card by returning an error (like SCARD_E_UNSUPPORTED_FEATURE).
Approx 10 cards implement this logout function.
So yes, pkcs15_logout seems fine.

vincent

**Comment by vletoux** [comment]
I've made a quick pull request to add the sc_logout function (pkcs15_logout cannot be called because it requires a P11 structure).
#633
=> I didn't test it because i do not have a card that supports it

**Comment by CardContact** [comment]
Created a PR to remove path automatically added by sc_pkcs15_decode_prkdf_entry() and to add logout().

@vletoux Can you check if that works with minidriver ?

**Comment by vletoux** [comment]
not possible within the next days ;-(

**Comment by vletoux** [comment]
I integrated Andrea's fix into PR #633 => integration builds can be used for tests
