### ISSUE TITLE
Permission on pkcs15-tool.exe -D command to hide it from unknown persons

### ISSUE THREAD

**Issue by scottthomas007** [OpenSC/OpenSC#689]
pkcs15-tool.exe -D shown card dump. Anyone whether he is a bad guy gets the card can see the dump easily. 
Can we set a permission so that the dump command only works to the authorized persons only ?

**Comment by frankmorgner** [comment]
You could use Windows policies to disallow certain programs for certain users, but this only hides the problem.

It's an intrinsic problem is that you need to get the certificates (that may hold some private user data, e.g. Name/mail address) in order to do something with them. Most cards simply sacrificed privacy for usability by making all PKCS#15 data freely available. Just look at your NFC powered credit card, it shouts out your creditcard number and name to everyone who asks for it (there are several demo apps on the android store).

The German ID card solved this by protecting the PKCS#15 data with an additional secret. There are several other ways to solve the problem, but all of them require modifications of the card.

**Comment by LudovicRousseau** [comment]
Even if you modify ``pkcs15-tool.exe -D`` to _not_ dump some information, anybody can use a modified version of ``pkcs15-tool.exe`` to revert its behaviour and dump every thing again.

As explained @frankmorgner above, the check must be done inside the card or it is useless.

You should complain to the card applications designers, not to OpenSC.

**Comment by dengert** [comment]
Yes, but its useless.

The security of the card is within the card itself. Some cards require the PIN to read some of the data.
These access rules applies to the dump command too. Much of the data is mean to be readable without the PIN such as certificates.
Many applications depend on reading certificates before requesting the PIN.

OpenSC is open source, the bad guys can get it, modify it or write their own code to bypass anything we add to OpenSC.
They don't have to use OpenSC at all.

Depending on your card, you could change what data is readable only with the PIN or with keys known only by the card administrator.


On 2/25/2016 10:11 PM, Scott Thomas wrote:
> pkcs15-tool.exe -D shown card dump. Anyone whether he is a bad guy gets the card can see the dump easily.
> Can we set a permission so that the dump command only works to the authorized persons only ?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/689>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by martinpaljak** [comment]
Dup of #690 in spirit
