### ISSUE TITLE
Multiple ePass2003 error

### ISSUE THREAD

**Issue by velter** [OpenSC/OpenSC#720]
### Expected behaviour

Use serveral ePass2003 on the same machine sould be possible
### Actual behaviour

When two ePass2003 are plugged in a machine, only the second slot is usable. As soon as you try to login in the first slot a C_Login failed with error CKR_DATA_INVALID is raised.
### Steps to reproduce
1. Plug two ePass2003
2. pkcs15-init --reader 0 -E
3. pkcs15-init --reader 1 -E
4. pkcs15-init --reader 0 -C --use-default-transport-keys --profile pkcs15+onepin --pin 123456 --puk 123456
5. pkcs15-init --reader 1 -C --use-default-transport-keys --profile pkcs15+onepin --pin 123456 --puk 123456
6. pkcs11-tool --slot 5 -t -l -p 123456 return OK
7. pkcs11-tool --slot 1 -t -l -p 123456 return the following error :

"error: PKCS11 function C_Login failed: rv = CKR_DATA_INVALID (0x20)"
### Logs

[opensc-debug.txt](https://github.com/OpenSC/OpenSC/files/186022/opensc-debug.txt)

I tried to analyze this. What happen is while
1. OpenSc init first token
2. OpenSc init second token
3. OpenSc try to login to second token

Return OK
1. OpenSc init first token
2. OpenSc init second token
3. OpenSc try to login to first token

Fail

This seem to show that the second token init mess up something for the first one.

Looking at card-epass2003.c there is a lot of static variable (including encryption key) for example on line 97

static unsigned char g_sk_enc[16] = { 0 };  /\* encrypt session key _/
static unsigned char g_sk_mac[16] = { 0 };  /_ mac session key _/
static unsigned char g_icv_mac[16] = { 0 }; /_ instruction counter vector(for sm) */

which should be card dependant, not global. any ideas what's the best way to fix this ?

Thanks for your help

**Comment by FeitianSmartcardReader** [comment]
Hi Velter

This is Ben, from FEITIAN tech team.
We will take a look this issue, should back to you tomorrow, thanks

**Comment by velter** [comment]
Hi Ben,

Nice thanks.

it looks like card-epass2003.c should use card->sm_ctx.info.session.gp_keyset.enc/mac/kek ...instead of static global vars.

I found another sm related issue. This time with a single token but with two shells. Steps to reproduce are (with an already initialized token) :

Shell 1 : pkcs11-tool -t -l (Do NOT enter pin at this time)
Shell 2 : pkcs11-tool -t -l
Shell 2 : Enter Pin
Shell 2 : Test succeed
Shell 1 : Enter Pin
Shell 1 : "error: PKCS11 function C_Login failed: rv = CKR_DATA_INVALID (0x20)"

Here are the relevant logs

[opensc-debug.txt](https://github.com/OpenSC/OpenSC/files/186521/opensc-debug.txt)

This seem to also be a sm related problem where the keys setup by the first call are destroyed by the second. This is an issued a described in #558 for which I found a workaround but would be nice to properly fix.

**Comment by FeitianSmartcardReader** [comment]
@velter We just solve the problem and submit pull request, more information, please check https://github.com/OpenSC/OpenSC/pull/730 

This issue can close now. Thanks for your time.

**Comment by velter** [comment]
@FeitianSmartcardReader thanks. I juste gave your patch a try and I get a crash for pkcs11-tool -O -l (with a single token inserted). See logs :

[opensc-debug-crash.txt](https://github.com/OpenSC/OpenSC/files/214634/opensc-debug-crash.txt)

I have some questions about your patch. If I understand it correctly, you reinit everything when the specific error is raised. But :
* I still think storing mutual auth datas somewhere in the card structure instead of global vars would be much better in some cases. Imagine two or more tokens accessed from a single process which use them alternatively. Keeping global var will need a reinit at each use while using the card structure does not need any reinit.
* Why is epass2003_init needed in epass2003_pin_cmd ? Shouldn't this be catched by sc_transmit_apdu_t ?
* There is a potential infinite recursion because epass2003_init call get_data which call sc_transmit_apdu_t (even if g_sm=SM_PLAIN) which can call epass2003_init again. Storing g_smtype in the card struct will solve this as this is invariant for a token and sc_transmit_apdu_t will only need to call epass2003_refresh

What do you think ?

**Comment by FeitianSmartcardReader** [comment]
Hi Velter

Let me check and give back to you later, thanks for your test. 
 


Best Regard 
 
Ben |Technical Specialist (GLBAL SUPPORT) | 国际部 王红宾
Skype: Hooben@FEITIAN | Tel: +86 (10) 62304466 ext. 575
Feitian, Inc. Floor 17th, Tower B, Huizhi Mansion, No.9 Xueqing Road, Haidian District Beijing 100085, P.R China
Smartcard Readers->http://www.ftsafe.com/product/Smart_Reader
Online Shop->http://www.ftsafe.com/product/reader_shop
 
This email message (including any attachments) is for the sole use of the intended recipient and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution of this information is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy the original message and all of its copies.
 
From: velter
Date: 2016-04-12 17:17
To: OpenSC/OpenSC
CC: Feitian Technologies
Subject: Re: [OpenSC/OpenSC] Multiple ePass2003 error (#720)
@FeitianSmartcardReader thanks. I juste gave your patch a try and I get a crash for pkcs11-tool -O -l (with a single token inserted). See logs :
opensc-debug-crash.txt
I have some questions about your patch. If I understand it correctly, you reinit everything when the specific error is raised. But :
I still think storing mutual auth datas somewhere in the card structure instead of global vars would be much better in some cases. Imagine two or more tokens accessed from a single process which use them alternatively. Keeping global var will need a reinit at each use while using the card structure does not need any reinit.
Why is epass2003_init needed in epass2003_pin_cmd ? Shouldn't this be catched by sc_transmit_apdu_t ?
There is a potential infinite recursion because epass2003_init call get_data which call sc_transmit_apdu_t (even if g_sm=SM_PLAIN) which can call epass2003_init again. Storing g_smtype in the card struct will solve this as this is invariant for a token and sc_transmit_apdu_t will only need to call epass2003_refresh
What do you think ?

**Comment by velter** [comment]
@FeitianSmartcardReader  I have made another patch #731 based on yours and a cleaner implementation of the first one. It solves both problems. Can you have a look ? Thanks.

**Comment by FeitianSmartcardReader** [comment]
@velter Let me check and make a test, should back to you tomorrow, thanks for your time.

**Comment by FeitianSmartcardReader** [comment]
Already check Velter code and approval for these changes.
