### ISSUE TITLE
CardOS 5.0 cards not supported by OpenSC driver

### ISSUE THREAD

**Issue by DDvO** [OpenSC/OpenSC#744]
When using a Card OS 4.2 card, everything seems to work fine, but not with v5.0 cards.
As promised, here is some diagnostic data on using OpenSC with my CardOS 5.0 card.

`cardos-tool -i` seems fine; it says
> 3b:d2:18:00:81:31:fe:58:c9:01:14
> Info : CardOS V5.0, 2012
> Serial number: 02 02 36 cd 00 07 27 4c
> OS Version: 201.1 (that's CardOS V5.0)
> Current life cycle: 16 (operational)
> Security Status of current DF:
> Free memory : 579
> ATR Status: 0x0 ROM-ATR
> Packages installed:
> E1 0B 53 06 03 04 13 02 C9 01 8F 01 01 ..S..........
> Ram size: 7, Eeprom size: 96, cpu type: 78, chip config: 63, chip manufacturer: 5
> Free eeprom memory: 74096
> Current Maximum Data Field Length: 640
> Complete chip production data:
> CC 78 33 3A 01 00 01 00 0E 00 00 01 0B 02 02 36 .x3:...........6
> CD 00 07 00 27 00 4C 61 75 37 37 FF FF FF FF 78 ....'.Lau77....x
> 01 51 40 78 05 16 07 00 00 83 12 05 E7 55 21 02 .Q@x.........U!.
> 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
> 00 00 00 00 00 00 00 00 00 00 00 00             ............
> System keys: PackageLoadKey (version 0x00, retries 10)
> System keys: StartKey (version 0x00, retries 10)
> Path to current DF:
> 50 15 50 75 4B 07 P.PuK.

This output is also attached:[cardos-tool_-i_output.txt](https://github.com/OpenSC/OpenSC/files/234374/cardos-tool_-i_output.txt) and comes with debug trace [cardos-tool_-i_debug.txt](https://github.com/OpenSC/OpenSC/files/234375/cardos-tool_-i_debug.txt)

`pkcs11-tool -I` seems fine; it says
> Cryptoki version 2.20
> Manufacturer     OpenSC (www.opensc-project.org)
> Library          Smart card PKCS#11 API (ver 0.0)

with debug trace [pkcs11-tool_-I_debug.txt](https://github.com/OpenSC/OpenSC/files/234463/pkcs11-tool_-I_debug.txt) and spy trace [pkcs11-tool_-I_spy.txt](https://github.com/OpenSC/OpenSC/files/234464/pkcs11-tool_-I_spy.txt)

`pkcs11-tool -L` gives strange output:
> Available slots:
> Slot 0 (0xffffffff): Virtual hotplug slot
>   (empty)
> Slot 1 (0x1): O2Micro CCID SC Reader 0
>   token label        : (null)
>   token manufacturer :
>   token model        : PKCS#15
>   token flags        : token initialized
>   hardware version   : 0.0
>   firmware version   : 0.0
>   serial num         :

with debug trace [pkcs11-tool_-L_debug.txt](https://github.com/OpenSC/OpenSC/files/234469/pkcs11-tool_-L_debug.txt) and spy trace [pkcs11-tool_-L_spy.txt](https://github.com/OpenSC/OpenSC/files/234471/pkcs11-tool_-L_spy.txt)

`pkcs11-tool -O` does not find any objects (empty output),
with debug trace [pkcs11-tool_-O_debug.txt](https://github.com/OpenSC/OpenSC/files/234475/pkcs11-tool_-O_debug.txt) and spy trace [pkcs11-tool_-O_spy.txt](https://github.com/OpenSC/OpenSC/files/234476/pkcs11-tool_-O_spy.txt)

Upon request I can provide further debug data.

**Comment by dengert** [comment]
Any OpenSC developer willing to look at CardOS V5 issues?

OK, this is more helpful.

pkcs11-tool_-L_debug.txt shows two things:
Line1: Unable to open "/usr/local/etc/opensc.conf"
This may not be a problem, but you should check why it is missing.
If you have it you can set:
    debug = 9;
    debug_file = /path/to/some/file;


It  looks like you may have compiled the code based on /usr/local/etc/opensc.conf
and the OpenSC version is 0.15.0.

Can you try the opensc-0.16.0 from git? There may be many CardOS V5 fixes.

The debug output also showed opensc found it was a CardOS V5  i.e. type 1009 based on ATR.
Line 91 card.c:307:sc_connect_card: card info name:'CardOS M4', type:1009, flags:0x0, max_send/recv_size:634/638
The string is wrong, saying 'CardOS M4'.

But after that OpenSC can not find any PKCS#15 files on the card. I am not familiar with CardOS some other developer
who is should be look at this.

In regards to pkcs11-tool, it could use the Official CardOS module add the --module option and point to the lib.

In regards to use SPY. SPY can be used with libp11 and with any PKCS#11 module, not just OpenSC.
running libp11 with SPY and the CardOS module might show what the official CardOS module is returning.





On 4/25/2016 7:20 AM, David von Oheimb wrote:
> When using a Card OS 4.2 card, everything seems to work fine, but not with v5.0 cards.
> As promised, here is some diagnostic data on using OpenSC with my CardOS 5.0 card.
>
> |cardos-tool -i| seems fine; it says
>
>     3b:d2:18:00:81:31:fe:58:c9:01:14
>     Info : CardOS V5.0, 2012
>     Serial number: 02 02 36 cd 00 07 27 4c
>     OS Version: 201.1 (that's CardOS V5.0)
>     Current life cycle: 16 (operational)
>     Security Status of current DF:
>     Free memory : 579
>     ATR Status: 0x0 ROM-ATR
>     Packages installed:
>     E1 0B 53 06 03 04 13 02 C9 01 8F 01 01 ..S..........
>     Ram size: 7, Eeprom size: 96, cpu type: 78, chip config: 63, chip manufacturer: 5
>     Free eeprom memory: 74096
>     Current Maximum Data Field Length: 640
>     Complete chip production data:
>     CC 78 33 3A 01 00 01 00 0E 00 00 01 0B 02 02 36 .x3:...........6
>     CD 00 07 00 27 00 4C 61 75 37 37 FF FF FF FF 78 ....'.Lau77....x
>     01 51 40 78 05 16 07 00 00 83 12 05 E7 55 21 02 .Q@x.........U <mailto:.Q@x.........U>!.
>     01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
>     00 00 00 00 00 00 00 00 00 00 00 00 ............
>     System keys: PackageLoadKey (version 0x00, retries 10)
>     System keys: StartKey (version 0x00, retries 10)
>     Path to current DF:
>     50 15 50 75 4B 07 P.PuK.
>
> This output is also attached:cardos-tool_-i_output.txt <https://github.com/OpenSC/OpenSC/files/234374/cardos-tool_-i_output.txt> and comes with debug trace cardos-tool_-i_debug.txt
> <https://github.com/OpenSC/OpenSC/files/234375/cardos-tool_-i_debug.txt>
>
> |pkcs11-tool -I| seems fine; it says
>
>     Cryptoki version 2.20
>     Manufacturer OpenSC (www.opensc-project.org <http://www.opensc-project.org>)
>     Library Smart card PKCS#11 API (ver 0.0)
>
> with debug trace pkcs11-tool_-I_debug.txt <https://github.com/OpenSC/OpenSC/files/234463/pkcs11-tool_-I_debug.txt> and spy trace pkcs11-tool_-I_spy.txt
> <https://github.com/OpenSC/OpenSC/files/234464/pkcs11-tool_-I_spy.txt>
>
> |pkcs11-tool -L| gives strange output:
>
>     Available slots:
>     Slot 0 (0xffffffff): Virtual hotplug slot
>     (empty)
>     Slot 1 (0x1): O2Micro CCID SC Reader 0
>     token label : (null)
>     token manufacturer :
>     token model : PKCS#15
>     token flags : token initialized
>     hardware version : 0.0
>     firmware version : 0.0
>     serial num :
>
> with debug trace pkcs11-tool_-L_debug.txt <https://github.com/OpenSC/OpenSC/files/234469/pkcs11-tool_-L_debug.txt> and spy trace pkcs11-tool_-L_spy.txt
> <https://github.com/OpenSC/OpenSC/files/234471/pkcs11-tool_-L_spy.txt>
>
> |pkcs11-tool -O| does not find any objects (empty output),
> with debug trace pkcs11-tool_-O_debug.txt <https://github.com/OpenSC/OpenSC/files/234475/pkcs11-tool_-O_debug.txt> and spy trace pkcs11-tool_-O_spy.txt
> <https://github.com/OpenSC/OpenSC/files/234476/pkcs11-tool_-O_spy.txt>
>
> Upon request I can provide further debug data.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/744>
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by dengert** [comment]
One more thing, the debug.txt says the reader is an "O2Micro CCID SC Reader 0"
This may not be a supported reader. See:
  https://pcsclite.alioth.debian.org/ccid/section.html
Have you tried one of the "supported" readers?

Also see:

https://github.com/OpenSC/OpenSC/issues/735

Was your card issued by some government organization?
Or are you trying to initialize and populate the card with your own certs and keys?

if yes, what tools have you used to do this?

Just because the card says it is CardOS, does not say how the data on the card is organized.


On 4/25/2016 7:20 AM, David von Oheimb wrote:
> When using a Card OS 4.2 card, everything seems to work fine, but not with v5.0 cards.
> As promised, here is some diagnostic data on using OpenSC with my CardOS 5.0 card.
>
> |cardos-tool -i| seems fine; it says
>
>     3b:d2:18:00:81:31:fe:58:c9:01:14
>     Info : CardOS V5.0, 2012
>     Serial number: 02 02 36 cd 00 07 27 4c
>     OS Version: 201.1 (that's CardOS V5.0)
>     Current life cycle: 16 (operational)
>     Security Status of current DF:
>     Free memory : 579
>     ATR Status: 0x0 ROM-ATR
>     Packages installed:
>     E1 0B 53 06 03 04 13 02 C9 01 8F 01 01 ..S..........
>     Ram size: 7, Eeprom size: 96, cpu type: 78, chip config: 63, chip manufacturer: 5
>     Free eeprom memory: 74096
>     Current Maximum Data Field Length: 640
>     Complete chip production data:
>     CC 78 33 3A 01 00 01 00 0E 00 00 01 0B 02 02 36 .x3:...........6
>     CD 00 07 00 27 00 4C 61 75 37 37 FF FF FF FF 78 ....'.Lau77....x
>     01 51 40 78 05 16 07 00 00 83 12 05 E7 55 21 02 .Q@x.........U <mailto:.Q@x.........U>!.
>     01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
>     00 00 00 00 00 00 00 00 00 00 00 00 ............
>     System keys: PackageLoadKey (version 0x00, retries 10)
>     System keys: StartKey (version 0x00, retries 10)
>     Path to current DF:
>     50 15 50 75 4B 07 P.PuK.
>
> This output is also attached:cardos-tool_-i_output.txt <https://github.com/OpenSC/OpenSC/files/234374/cardos-tool_-i_output.txt> and comes with debug trace cardos-tool_-i_debug.txt
> <https://github.com/OpenSC/OpenSC/files/234375/cardos-tool_-i_debug.txt>
>
> |pkcs11-tool -I| seems fine; it says
>
>     Cryptoki version 2.20
>     Manufacturer OpenSC (www.opensc-project.org <http://www.opensc-project.org>)
>     Library Smart card PKCS#11 API (ver 0.0)
>
> with debug trace pkcs11-tool_-I_debug.txt <https://github.com/OpenSC/OpenSC/files/234463/pkcs11-tool_-I_debug.txt> and spy trace pkcs11-tool_-I_spy.txt
> <https://github.com/OpenSC/OpenSC/files/234464/pkcs11-tool_-I_spy.txt>
>
> |pkcs11-tool -L| gives strange output:
>
>     Available slots:
>     Slot 0 (0xffffffff): Virtual hotplug slot
>     (empty)
>     Slot 1 (0x1): O2Micro CCID SC Reader 0
>     token label : (null)
>     token manufacturer :
>     token model : PKCS#15
>     token flags : token initialized
>     hardware version : 0.0
>     firmware version : 0.0
>     serial num :
>
> with debug trace pkcs11-tool_-L_debug.txt <https://github.com/OpenSC/OpenSC/files/234469/pkcs11-tool_-L_debug.txt> and spy trace pkcs11-tool_-L_spy.txt
> <https://github.com/OpenSC/OpenSC/files/234471/pkcs11-tool_-L_spy.txt>
>
> |pkcs11-tool -O| does not find any objects (empty output),
> with debug trace pkcs11-tool_-O_debug.txt <https://github.com/OpenSC/OpenSC/files/234475/pkcs11-tool_-O_debug.txt> and spy trace pkcs11-tool_-O_spy.txt
> <https://github.com/OpenSC/OpenSC/files/234476/pkcs11-tool_-O_spy.txt>
>
> Upon request I can provide further debug data.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/744>
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by DDvO** [comment]
Thanks @dengert  for your hints and questions.

Since my company unfortunately favors Windows, I use Cygwin for developing and testing. 
'make' worked fine, but 'make install' had some trouble, but I can manually copy `opensc.conf` to `/usr/local/etc` and then it gets used as you wrote for debug options etc.

I've meanwhile tried also the latest version from the git master HEAD, but (non-)support CardOS 5.0 is the same there.

Indeed the card label printed ("CardOS M4") seems wrong: it is the same for type 1009 as it is for my CardOS 4.2 card with type 1006. 

I never had issues with the brand/type of card reader. I also have a "Gemplus USB Smart Card Reader", which seems officially supported. I've just tried it, with the same results.

The CardOS 5.0 cards I use for testing are evaluation samples directly form the Atos CardOS team, thus not pre-formatted/filled. I initialize them with the CardOS cardview.exe tool which works fine. I fill the card mostly using and enhanced version of pkcs11-tool: #747 and occasionally with XCA. All these work (mostly) fine using the official cardos11.dll module.

**Comment by dengert** [comment]
Any CardOS OpenSC developers what to look at these problems?

So you have:
  samples cards from Atos CardOS team

  using CardOS cardview.exe to initialize

  using official cardos11.dll for PKCS#11

  using modified pkcs11-tool to initialize the cards.


What you might be seeing as compared to OpenSC implementation of CardOS V5 code could be:

Samples cards from Atos CardOS team may are initialized differently then what OpenSC has been seen in the past.
Files may have different paths for example. Thus OpenSC can not find any objects on the card, because it is looking
in the wrong place. The CardOS cardview.exe and official cardos11.dll may do thing differently.

Much of the OpenSC code has been developed to support ID cards issued European or US government organizations.
In most cases there is some documentation at the card edge/APDU level documenting how to access the cards
and listing paths to files. This may not match what the Atos CardOS team is doing.

The ATR of your cad is listed in OpenSC, it maybe one of these government ID cards uses the same card, but
may have info located in different places.


In many cases the government issued cards may do things differently then what the card manufacturer does.

Thus to see what is going on, one really needs to see the documentation.

There are several levels of debugging that can help. There is the OPENSC_SPY that can work with any pkcs11 module,
and should work with the official cardos11.dll under windows.

There is the OpenSC lib level debug that shows opensc internal tracing and APDU commands and responses but it only
works with OpenSC.

The APDU commands and responses can be obtained in other ways. (I use an Ubuntu Unix system run in a virtual machine
using Oracle VirtualBox runing on a 64bit Windows 10 running on a I5 computer.) In this environment, the Ubuntu
pcscd system process can show all APDU commands and responses sent to the card. This would only work for you if
Atos has a unix version cardview.exe and a cardos11.so  library.

Looks like they do:
http://atos.net/content/dam/global/we-do/atos-cardos-api-data-sheet.pdf

On windows there are trace programs to look at the USB traffic that can show the APDU commands and responses.
You can ask on this list for more info, I don't have it.

What I am getting at is all smart cards are not the same, even from the same manufacture. They can be used differently
when initialized. Most OpenSC developers only have 1 or two types of cards, so there may only be one developer that
can assist you with the CardOS differences you may be seeing with your cards and what is in OpenSC.

I am going to ask you again for a SPY trace of accessing the EC keys on you card using the cardos11.dll. This should
what attributes are requested and what is returned. Either start with the pkcs11-tool, libp11, or even cardview.exe
if it uses PKCS11 which i doubt.

If your company plans on using a lot of these cards, ask the Atos sales reps for more internal documentation
on card edge interface, and PKCS#15 file layouts, cardview and cardos11 PKCS#11 or what ever they will give you.
Ask if it is publicly available or NDA only.

It appears that you want to use libp11 and don't really need OpenSC's module, so any  PKCS#11  documentation from Atos
would help you.

And Oh, did I mention a OPENSC SPY trace of calls to cardos11.dll could be your best debugging tool?



On 4/27/2016 5:28 AM, David von Oheimb wrote:
> Thanks @dengert <https://github.com/dengert> for your hints and questions.
>
> Since my company unfortunately favors Windows, I use Cygwin for developing and testing.
> 'make' worked fine, but 'make install' had some trouble, but I can manually copy |opensc.conf| to |/usr/local/etc| and then it gets used as you wrote for debug options etc.
>
> I've meanwhile tried also the latest version from the git master HEAD, but (non-)support CardOS 5.0 is the same there.
>
> Indeed the card label printed ("CardOS M4") seems wrong: it is the same for type 1009 as it is for my CardOS 4.2 card with type 1006.
>
> I never had issues with the brand/type of card reader. I also have a "Gemplus USB Smart Card Reader", which seems officially supported. I've just tried it, with the same results.
>
> The CardOS 5.0 cards I use for testing are evaluation samples directly form the Atos CardOS team, thus not pre-formatted/filled. I initialize them with the CardOS cardview.exe tool which works fine. I
> fill the card mostly using and enhanced version of pkcs11-tool: #747 <https://github.com/OpenSC/OpenSC/pull/747> and occasionally with XCA. All these work (mostly) fine using the official cardos11.dll
> module.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/744#issuecomment-215042815>
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
CardOS 5.0 was integrated here https://github.com/OpenSC/OpenSC/pull/283. The pull request was withdrawn due to licensing issues.

**Comment by DDvO** [comment]
That's a pity.
I can ask the Atos CardOS team for their support here.

**Comment by martelletto** [comment]
Hi @DDvO, that would be greatly appreciated. It is indeed an unfortunate situation. The driver is mostly complete, yet can't be integrated due to licensing issues.

**Comment by DDvO** [comment]
Meanwhile I got a first response from them: Gabriele Preis wrote (translated):

> Via CardOS API we offer our own smartcard middleware, including the full functionality for supporting CardOS smartcards on current OSes over standard interfaces. For which projects or use cases do you see the necessity to use OpenSC?

I'm about to answer that I do not have specific reason to use an OpenSC driver, but that an OSS driver gives more chance to flexibly deal with any bugs and specific requirements that may emerge. Also for reference and debugging purposes it may be good to have a second implementation at hand, and in this case it would be a waste if the already existing one just is not allowed to get published.

Do you have anything which you suggest to add or change to this tentative statement?

**Comment by martelletto** [comment]
Hi,

It has been a couple of years, and my memory is a bit fuzzy.

If I recall correctly, CardOS 5 smartcards come out of the factory in a
"initialization" state. The key needed to proceed with the
initialization and activate the cards is proprietary, and therefore
absent from the pull request in question.

Perhaps it would be important to point this out to them, as they would
still have exclusive control over a card's activation process. In other
words, only cards previously activated, or activated by people in
possession of CardOS 5's start key will work with OpenSC's CardOS 5
driver.

Otherwise, I believe your statement is fine as it is. Thank you very
much for taking this initiative.

-p.

**Comment by findler** [comment]
The reason why I would like to have a working OpenSCs CardOS5 driver is that I am using other cards (in addition to CardOS cards) which are supported by OpenSC but are not supported by Atos CardOS middleware....

**Comment by debrouxl** [comment]
Besides the other posters' additional comments, another valid use case for a working OpenSC CardOS 5 driver is using the corporate SC to sign messages, encrypt messages, or contain a private key usable for SSH authentication on Linux servers, for corporate purposes, on corporate PCs which do not run the standard Atos Windows image.
Essentially, using the Atos SC for the same purposes as a YubiKey (see https://github.com/lfit/ssh-gpg-smartcard-config/blob/master/YubiKey_NEO.rst ) or Nitrokey, both of which do not require a SC reader.
