### ISSUE TITLE
About src/libcardnpa

### ISSUE THREAD

**Issue by viktorTarasov** [OpenSC/OpenSC#820]
Recent commits have introduced the card specific sources on the level where it has no place.

My questions:
- why ?
- have you looked for the other ways to compile your own 'purified' module? Like, for ex. a new compile object in 'libopensc'?

Question of codding style of a newly introduced sources I leave for a moment aside.

**Comment by frankmorgner** [comment]
libcardnpa.dll is an external card driver, that's why it is compiled and created separately. Other users have asked about how to use the external card driver since a reference was missing and OpenSC only comes with internal card drivers. The new card driver can be used as one example how to do that.

**Comment by viktorTarasov** [comment]
For me it's not the reason to put card specific staff on this level.

You can do dedicated make target in libopensc, create folder dedicated to external modules (probably inside libopensc).

**Comment by frankmorgner** [comment]
So you're suggesting to move the folder libcardnpa into libopensc?

**Comment by viktorTarasov** [comment]
_master_ rebased without _npa_ merge.

Let's start new discussion to include the _npa_ support.
